using System;
using System.Collections.Generic;
using FOC.Domain.Characters;
using FOC.Domain.Cities;
using FOC.Domain.Common;

namespace FOC.Domain.Economy
{
    public enum TradeGoodCategory{Food,RawMaterial,Processed,Luxury,Military}
    public enum DemandSourceKind{Population,Institution,ProductionInput,Trade,ArmyFuture,EventFuture,LuxuryFuture}
    public enum MarketAvailability{Unavailable,Shortage,Available}
    public enum PriceAdjustmentSource{StockScarcity,Demand,ProductionCost,Transport,Security,TaxCustoms,Season,War,CityWealth,Competition,Diplomacy}
    public enum EconomicOwnerKind{Character,House,Organization}
    public enum CaravanLifecycle{Active,Completed,Lost,Retired}
    public enum CaravanLocationStage{AtOrigin,InTransit,AtDestination}
    public enum RouteRiskSource{Banditry,War,EnemyControl,PoorRoads,Weather,LocalSecurity,PoliticalHostility}

    public readonly struct GoodsQuantity:IEquatable<GoodsQuantity>{public GoodsQuantity(long value){if(value<0)throw new ArgumentOutOfRangeException(nameof(value));Value=value;}public long Value{get;}public bool Equals(GoodsQuantity other)=>Value==other.Value;public override bool Equals(object? obj)=>obj is GoodsQuantity other&&Equals(other);public override int GetHashCode()=>Value.GetHashCode();}
    public readonly struct MoneyAmount:IEquatable<MoneyAmount>{public MoneyAmount(long value){if(value<0)throw new ArgumentOutOfRangeException(nameof(value));Value=value;}public long Value{get;}public bool Equals(MoneyAmount other)=>Value==other.Value;public override bool Equals(object? obj)=>obj is MoneyAmount other&&Equals(other);public override int GetHashCode()=>Value.GetHashCode();}

    public sealed class TradeGoodDefinition
    {
        public TradeGoodDefinition(TradeGoodId id,string name,TradeGoodCategory category,long unitWeight,bool isFood=false,bool isMilitaryGood=false,bool isLuxury=false,long? referenceUnitValue=null){if(!id.IsValid)throw new ArgumentException("TradeGoodId is invalid.",nameof(id));if(string.IsNullOrWhiteSpace(name))throw new ArgumentException("Name is required.",nameof(name));if(!Enum.IsDefined(typeof(TradeGoodCategory),category))throw new ArgumentOutOfRangeException(nameof(category));if(unitWeight<=0)throw new ArgumentOutOfRangeException(nameof(unitWeight));if(referenceUnitValue.HasValue&&referenceUnitValue.Value<=0)throw new ArgumentOutOfRangeException(nameof(referenceUnitValue));if(isFood!=(category==TradeGoodCategory.Food)||isMilitaryGood!=(category==TradeGoodCategory.Military)||isLuxury!=(category==TradeGoodCategory.Luxury))throw new InvalidOperationException("Trade Good flags must match its category.");Id=id;Name=name;Category=category;UnitWeight=unitWeight;IsFood=isFood;IsMilitaryGood=isMilitaryGood;IsLuxury=isLuxury;ReferenceUnitValue=referenceUnitValue;}
        public TradeGoodId Id{get;}public string Name{get;}public TradeGoodCategory Category{get;}public long UnitWeight{get;}public bool IsFood{get;}public bool IsMilitaryGood{get;}public bool IsLuxury{get;}public long? ReferenceUnitValue{get;}
    }
    public sealed class TradeGoodRegistry
    {
        private readonly SortedDictionary<TradeGoodId,TradeGoodDefinition> _items=new SortedDictionary<TradeGoodId,TradeGoodDefinition>();public IReadOnlyCollection<TradeGoodDefinition> OrderedGoods=>_items.Values;public int Count=>_items.Count;public void Add(TradeGoodDefinition item){if(item==null)throw new ArgumentNullException(nameof(item));if(_items.ContainsKey(item.Id))throw new InvalidOperationException("Duplicate TradeGoodId.");_items.Add(item.Id,item);}public TradeGoodDefinition GetRequired(TradeGoodId id){if(!_items.TryGetValue(id,out var item))throw new KeyNotFoundException("Trade Good was not found.");return item;}
    }
    public sealed class TradeGoodStock{public TradeGoodStock(TradeGoodId goodId,long quantity){if(!goodId.IsValid)throw new ArgumentException("TradeGoodId is invalid.",nameof(goodId));if(quantity<0)throw new ArgumentOutOfRangeException(nameof(quantity));GoodId=goodId;Quantity=new GoodsQuantity(quantity);}public TradeGoodId GoodId{get;}public GoodsQuantity Quantity{get;internal set;}}
    public sealed class CityStockState
    {
        private readonly SortedDictionary<TradeGoodId,TradeGoodStock> _items=new SortedDictionary<TradeGoodId,TradeGoodStock>();public IReadOnlyCollection<TradeGoodStock> OrderedStocks=>_items.Values;public void AddInitial(TradeGoodStock stock){if(stock==null)throw new ArgumentNullException(nameof(stock));if(_items.ContainsKey(stock.GoodId))throw new InvalidOperationException("Duplicate authoritative City stock record.");_items.Add(stock.GoodId,stock);}public long QuantityOf(TradeGoodId id)=>_items.TryGetValue(id,out var item)?item.Quantity.Value:0;public bool CanAdd(TradeGoodId id,long quantity){if(quantity<0)return false;try{checked{var unused=QuantityOf(id)+quantity;return unused>=0;}}catch(OverflowException){return false;}}public void Add(TradeGoodId id,long quantity){if(quantity<=0)throw new ArgumentOutOfRangeException(nameof(quantity));if(!CanAdd(id,quantity))throw new OverflowException("City stock overflow.");if(!_items.TryGetValue(id,out var item)){item=new TradeGoodStock(id,0);_items.Add(id,item);}item.Quantity=new GoodsQuantity(item.Quantity.Value+quantity);}public void Remove(TradeGoodId id,long quantity){if(quantity<=0)throw new ArgumentOutOfRangeException(nameof(quantity));if(!_items.TryGetValue(id,out var item)||item.Quantity.Value<quantity)throw new InvalidOperationException("Insufficient City stock.");item.Quantity=new GoodsQuantity(item.Quantity.Value-quantity);}
    }
    public sealed class DemandSourceState
    {
        public DemandSourceState(string sourceId,DemandSourceKind kind,TradeGoodId goodId,long quantity){if(string.IsNullOrWhiteSpace(sourceId))throw new ArgumentException("Source ID is required.",nameof(sourceId));if(!Enum.IsDefined(typeof(DemandSourceKind),kind))throw new ArgumentOutOfRangeException(nameof(kind));if(!goodId.IsValid)throw new ArgumentException("TradeGoodId is invalid.",nameof(goodId));if(quantity<=0)throw new ArgumentOutOfRangeException(nameof(quantity));SourceId=sourceId;Kind=kind;GoodId=goodId;Quantity=new GoodsQuantity(quantity);}public string SourceId{get;}public DemandSourceKind Kind{get;}public TradeGoodId GoodId{get;}public GoodsQuantity Quantity{get;}
    }
    public sealed class CityDemandState
    {
        private readonly SortedDictionary<string,DemandSourceState> _items=new SortedDictionary<string,DemandSourceState>(StringComparer.Ordinal);public IReadOnlyCollection<DemandSourceState> OrderedSources=>_items.Values;public void AddSource(DemandSourceState source){if(source==null)throw new ArgumentNullException(nameof(source));var key=source.GoodId.Value+"\n"+source.Kind+"\n"+source.SourceId;if(_items.ContainsKey(key))throw new InvalidOperationException("Duplicate demand source.");_items.Add(key,source);}public long TotalFor(TradeGoodId id){long total=0;checked{foreach(var source in _items.Values)if(source.GoodId.Equals(id))total+=source.Quantity.Value;}return total;}public MarketAvailability Availability(TradeGoodId id,CityStockState stock){var quantity=stock.QuantityOf(id);if(quantity==0)return MarketAvailability.Unavailable;return quantity<TotalFor(id)?MarketAvailability.Shortage:MarketAvailability.Available;}
    }
    public sealed class ConsumptionRequest{public ConsumptionRequest(string sourceId,DemandSourceKind sourceKind,TradeGoodId goodId,long quantity){if(string.IsNullOrWhiteSpace(sourceId))throw new ArgumentException("Source ID is required.",nameof(sourceId));if(!Enum.IsDefined(typeof(DemandSourceKind),sourceKind))throw new ArgumentOutOfRangeException(nameof(sourceKind));if(!goodId.IsValid)throw new ArgumentException("TradeGoodId is invalid.",nameof(goodId));if(quantity<=0)throw new ArgumentOutOfRangeException(nameof(quantity));SourceId=sourceId;SourceKind=sourceKind;GoodId=goodId;Quantity=new GoodsQuantity(quantity);}public string SourceId{get;}public DemandSourceKind SourceKind{get;}public TradeGoodId GoodId{get;}public GoodsQuantity Quantity{get;}}
    public sealed class ConsumptionResult{public ConsumptionResult(long requested,long consumed){Requested=new GoodsQuantity(requested);Consumed=new GoodsQuantity(consumed);Shortage=new GoodsQuantity(requested-consumed);}public GoodsQuantity Requested{get;}public GoodsQuantity Consumed{get;}public GoodsQuantity Shortage{get;}public bool HasShortage=>Shortage.Value>0;}
    public static class ConsumptionRules{public static ConsumptionResult Consume(CityStockState stock,ConsumptionRequest request){if(stock==null)throw new ArgumentNullException(nameof(stock));if(request==null)throw new ArgumentNullException(nameof(request));var consumed=Math.Min(stock.QuantityOf(request.GoodId),request.Quantity.Value);if(consumed>0)stock.Remove(request.GoodId,consumed);return new ConsumptionResult(request.Quantity.Value,consumed);}}

    public sealed class RecipeGoodsLine{public RecipeGoodsLine(TradeGoodId goodId,long quantity){if(!goodId.IsValid)throw new ArgumentException("TradeGoodId is invalid.",nameof(goodId));if(quantity<=0)throw new ArgumentOutOfRangeException(nameof(quantity));GoodId=goodId;Quantity=new GoodsQuantity(quantity);}public TradeGoodId GoodId{get;}public GoodsQuantity Quantity{get;}}
    public sealed class ProductionRecipeDefinition
    {
        private readonly SortedDictionary<TradeGoodId,RecipeGoodsLine> _inputs=new SortedDictionary<TradeGoodId,RecipeGoodsLine>();private readonly SortedDictionary<TradeGoodId,RecipeGoodsLine> _outputs=new SortedDictionary<TradeGoodId,RecipeGoodsLine>();
        public ProductionRecipeDefinition(ProductionRecipeId id,string name,CityBuildingKind buildingKind,IEnumerable<RecipeGoodsLine> inputs,IEnumerable<RecipeGoodsLine> outputs){if(!id.IsValid)throw new ArgumentException("Recipe ID is invalid.",nameof(id));if(string.IsNullOrWhiteSpace(name))throw new ArgumentException("Name is required.",nameof(name));Id=id;Name=name;BuildingKind=buildingKind;if(inputs==null||outputs==null)throw new ArgumentNullException(nameof(inputs));foreach(var x in inputs){if(x==null||_inputs.ContainsKey(x.GoodId))throw new InvalidOperationException("Duplicate recipe input.");_inputs.Add(x.GoodId,x);}foreach(var x in outputs){if(x==null||_outputs.ContainsKey(x.GoodId))throw new InvalidOperationException("Duplicate recipe output.");_outputs.Add(x.GoodId,x);}if(_inputs.Count==0||_outputs.Count==0)throw new InvalidOperationException("Production must have real inputs and outputs.");var area=CityBuildingRules.RequiredArea(buildingKind);if(area!=CityAreaType.ProductionCraft&&area!=CityAreaType.FoodSupply)throw new InvalidOperationException("Recipe building must belong to ProductionCraft or FoodSupply.");}
        public ProductionRecipeId Id{get;}public string Name{get;}public CityBuildingKind BuildingKind{get;}public IReadOnlyCollection<RecipeGoodsLine> OrderedInputs=>_inputs.Values;public IReadOnlyCollection<RecipeGoodsLine> OrderedOutputs=>_outputs.Values;
    }
    public sealed class ProductionRecipeRegistry{private readonly SortedDictionary<ProductionRecipeId,ProductionRecipeDefinition> _items=new SortedDictionary<ProductionRecipeId,ProductionRecipeDefinition>();public IReadOnlyCollection<ProductionRecipeDefinition> OrderedRecipes=>_items.Values;public void Add(ProductionRecipeDefinition recipe){if(recipe==null)throw new ArgumentNullException(nameof(recipe));if(_items.ContainsKey(recipe.Id))throw new InvalidOperationException("Duplicate ProductionRecipeId.");_items.Add(recipe.Id,recipe);}public ProductionRecipeDefinition GetRequired(ProductionRecipeId id){if(!_items.TryGetValue(id,out var item))throw new KeyNotFoundException("Production recipe was not found.");return item;}}

    public sealed class PriceAdjustment{public PriceAdjustment(string sourceId,PriceAdjustmentSource source,long signedUnitAmount){if(string.IsNullOrWhiteSpace(sourceId))throw new ArgumentException("Source ID is required.",nameof(sourceId));if(!Enum.IsDefined(typeof(PriceAdjustmentSource),source))throw new ArgumentOutOfRangeException(nameof(source));SourceId=sourceId;Source=source;SignedUnitAmount=signedUnitAmount;}public string SourceId{get;}public PriceAdjustmentSource Source{get;}public long SignedUnitAmount{get;}}
    public sealed class PriceQuote{public PriceQuote(TradeGoodId goodId,long referenceUnitValue,IEnumerable<PriceAdjustment> adjustments){if(!goodId.IsValid)throw new ArgumentException("TradeGoodId is invalid.",nameof(goodId));if(referenceUnitValue<=0)throw new ArgumentOutOfRangeException(nameof(referenceUnitValue));GoodId=goodId;ReferenceUnitValue=referenceUnitValue;var list=new List<PriceAdjustment>(adjustments??throw new ArgumentNullException(nameof(adjustments)));list.Sort((a,b)=>{var c=a.Source.CompareTo(b.Source);return c!=0?c:StringComparer.Ordinal.Compare(a.SourceId,b.SourceId);});long final=referenceUnitValue;checked{foreach(var adjustment in list){if(adjustment==null)throw new ArgumentException("Adjustment is required.",nameof(adjustments));_adjustments.Add(adjustment);final+=adjustment.SignedUnitAmount;}}if(final<=0)throw new InvalidOperationException("Final unit price must be positive.");FinalUnitValue=final;}private readonly List<PriceAdjustment> _adjustments=new List<PriceAdjustment>();public TradeGoodId GoodId{get;}public long ReferenceUnitValue{get;}public IReadOnlyList<PriceAdjustment> OrderedAdjustments=>_adjustments;public long FinalUnitValue{get;}}
    public static class TradePriceRules{public static PriceQuote FormQuote(TradeGoodDefinition good,IEnumerable<PriceAdjustment> adjustments){if(good==null)throw new ArgumentNullException(nameof(good));if(!good.ReferenceUnitValue.HasValue)throw new InvalidOperationException("Trade Good has no authority/content reference value.");return new PriceQuote(good.Id,good.ReferenceUnitValue.Value,adjustments);}}

    public sealed class CityMarketState
    {
        public CityMarketState(CityId cityId,long cashBalance=0,CityStockState? stock=null,CityDemandState? demand=null){if(!cityId.IsValid)throw new ArgumentException("CityId is invalid.",nameof(cityId));CityId=cityId;CashBalance=new MoneyAmount(cashBalance);Stock=stock??new CityStockState();Demand=demand??new CityDemandState();}public CityId CityId{get;}public CityStockState Stock{get;}public CityDemandState Demand{get;}public MoneyAmount CashBalance{get;private set;}public bool CanCredit(long amount){if(amount<0)return false;try{checked{var unused=CashBalance.Value+amount;return unused>=0;}}catch(OverflowException){return false;}}public void Credit(long amount){if(amount<=0||!CanCredit(amount))throw new InvalidOperationException("Market cash credit is invalid.");CashBalance=new MoneyAmount(CashBalance.Value+amount);}public void Debit(long amount){if(amount<=0||CashBalance.Value<amount)throw new InvalidOperationException("Insufficient market cash.");CashBalance=new MoneyAmount(CashBalance.Value-amount);}
    }
    public readonly struct EconomicOwnerRef:IEquatable<EconomicOwnerRef>{private EconomicOwnerRef(EconomicOwnerKind kind,string id){Kind=kind;Id=id;}public EconomicOwnerKind Kind{get;}public string Id{get;}public static EconomicOwnerRef Character(CharacterId id){if(!id.IsValid)throw new ArgumentException(nameof(id));return new EconomicOwnerRef(EconomicOwnerKind.Character,id.Value);}public static EconomicOwnerRef House(HouseId id){if(!id.IsValid)throw new ArgumentException(nameof(id));return new EconomicOwnerRef(EconomicOwnerKind.House,id.Value);}public static EconomicOwnerRef Organization(OrganizationId id){if(!id.IsValid)throw new ArgumentException(nameof(id));return new EconomicOwnerRef(EconomicOwnerKind.Organization,id.Value);}public bool Equals(EconomicOwnerRef other)=>Kind==other.Kind&&StringComparer.Ordinal.Equals(Id,other.Id);public override bool Equals(object? obj)=>obj is EconomicOwnerRef other&&Equals(other);public override int GetHashCode()=>((int)Kind*397)^StringComparer.Ordinal.GetHashCode(Id??string.Empty);}
    public sealed class TradeRepresentativeReference{public TradeRepresentativeReference(CharacterId characterId,OrganizationId organizationId,AssignmentId assignmentId){if(!characterId.IsValid||!organizationId.IsValid||!assignmentId.IsValid)throw new ArgumentException("Trade representative reference is invalid.");CharacterId=characterId;OrganizationId=organizationId;AssignmentId=assignmentId;}public CharacterId CharacterId{get;}public OrganizationId OrganizationId{get;}public AssignmentId AssignmentId{get;}}
    public sealed class RouteRiskInput{public RouteRiskInput(string sourceId,RouteRiskSource source){if(string.IsNullOrWhiteSpace(sourceId))throw new ArgumentException("Source ID is required.",nameof(sourceId));if(!Enum.IsDefined(typeof(RouteRiskSource),source))throw new ArgumentOutOfRangeException(nameof(source));SourceId=sourceId;Source=source;}public string SourceId{get;}public RouteRiskSource Source{get;}}
    public sealed class CaravanAccountingState
    {
        public CaravanAccountingState(long purchaseCost=0,long saleRevenue=0,long operatingCost=0,long tariffs=0,long losses=0){PurchaseCost=new MoneyAmount(purchaseCost);SaleRevenue=new MoneyAmount(saleRevenue);OperatingCost=new MoneyAmount(operatingCost);Tariffs=new MoneyAmount(tariffs);Losses=new MoneyAmount(losses);}public MoneyAmount PurchaseCost{get;private set;}public MoneyAmount SaleRevenue{get;private set;}public MoneyAmount OperatingCost{get;}public MoneyAmount Tariffs{get;}public MoneyAmount Losses{get;}public long NetResult{get{checked{return SaleRevenue.Value-PurchaseCost.Value-OperatingCost.Value-Tariffs.Value-Losses.Value;}}}public bool CanRecordPurchase(long value)=>CanAdd(PurchaseCost.Value,value);public bool CanRecordSale(long value)=>CanAdd(SaleRevenue.Value,value);public void RecordPurchase(long value){if(value<=0||!CanRecordPurchase(value))throw new InvalidOperationException("Purchase accounting is invalid.");PurchaseCost=new MoneyAmount(PurchaseCost.Value+value);}public void RecordSale(long value){if(value<=0||!CanRecordSale(value))throw new InvalidOperationException("Sale accounting is invalid.");SaleRevenue=new MoneyAmount(SaleRevenue.Value+value);}private static bool CanAdd(long current,long value){if(value<0)return false;try{checked{var unused=current+value;return unused>=0;}}catch(OverflowException){return false;}}
    }
    public sealed class CaravanCargoState
    {
        private readonly SortedDictionary<TradeGoodId,TradeGoodStock> _items=new SortedDictionary<TradeGoodId,TradeGoodStock>();public IReadOnlyCollection<TradeGoodStock> OrderedCargo=>_items.Values;public long QuantityOf(TradeGoodId id)=>_items.TryGetValue(id,out var item)?item.Quantity.Value:0;public long UsedWeight(TradeGoodRegistry goods){long total=0;checked{foreach(var x in _items.Values)total+=x.Quantity.Value*goods.GetRequired(x.GoodId).UnitWeight;}return total;}public bool CanAdd(TradeGoodId id,long quantity,long capacity,TradeGoodRegistry goods){if(quantity<=0)return false;try{checked{return UsedWeight(goods)+quantity*goods.GetRequired(id).UnitWeight<=capacity;}}catch(OverflowException){return false;}}public void Add(TradeGoodId id,long quantity,long capacity,TradeGoodRegistry goods){if(!CanAdd(id,quantity,capacity,goods))throw new InvalidOperationException("Caravan capacity would be exceeded.");if(!_items.TryGetValue(id,out var item)){item=new TradeGoodStock(id,0);_items.Add(id,item);}item.Quantity=new GoodsQuantity(checked(item.Quantity.Value+quantity));}public void Remove(TradeGoodId id,long quantity){if(quantity<=0)throw new ArgumentOutOfRangeException(nameof(quantity));if(!_items.TryGetValue(id,out var item)||item.Quantity.Value<quantity)throw new InvalidOperationException("Insufficient Caravan cargo.");item.Quantity=new GoodsQuantity(item.Quantity.Value-quantity);}
    }
    public sealed class CaravanState
    {
        private readonly List<RouteRiskInput> _riskInputs=new List<RouteRiskInput>();public CaravanState(CaravanId id,EconomicOwnerRef owner,CharacterId managerCharacterId,CityId originCityId,CityId destinationCityId,long weightCapacity,long cashBalance,TradeRepresentativeReference? representative=null,TradeRouteId? routeId=null,CaravanLifecycle lifecycle=CaravanLifecycle.Active,CaravanLocationStage locationStage=CaravanLocationStage.AtOrigin,CaravanCargoState? cargo=null,CaravanAccountingState? accounting=null,IEnumerable<RouteRiskInput>? riskInputs=null){if(!id.IsValid||!managerCharacterId.IsValid||!originCityId.IsValid||!destinationCityId.IsValid)throw new ArgumentException("Caravan references are invalid.");if(originCityId.Equals(destinationCityId))throw new ArgumentException("Caravan origin and destination must differ.");if(string.IsNullOrWhiteSpace(owner.Id)||!Enum.IsDefined(typeof(EconomicOwnerKind),owner.Kind))throw new ArgumentException("Owner is invalid.");if(weightCapacity<0)throw new ArgumentOutOfRangeException(nameof(weightCapacity));if(!Enum.IsDefined(typeof(CaravanLifecycle),lifecycle)||!Enum.IsDefined(typeof(CaravanLocationStage),locationStage))throw new ArgumentOutOfRangeException(nameof(lifecycle));Id=id;Owner=owner;ManagerCharacterId=managerCharacterId;OriginCityId=originCityId;DestinationCityId=destinationCityId;WeightCapacity=weightCapacity;CashBalance=new MoneyAmount(cashBalance);Representative=representative;RouteId=routeId;Lifecycle=lifecycle;LocationStage=locationStage;Cargo=cargo??new CaravanCargoState();Accounting=accounting??new CaravanAccountingState();if(riskInputs!=null){var seen=new HashSet<string>(StringComparer.Ordinal);foreach(var x in riskInputs){if(x==null||!seen.Add(x.Source+"\n"+x.SourceId))throw new InvalidOperationException("Duplicate route risk input.");_riskInputs.Add(x);}_riskInputs.Sort((a,b)=>{var c=a.Source.CompareTo(b.Source);return c!=0?c:StringComparer.Ordinal.Compare(a.SourceId,b.SourceId);});}}
        public CaravanId Id{get;}public EconomicOwnerRef Owner{get;}public CharacterId ManagerCharacterId{get;}public TradeRepresentativeReference? Representative{get;}public CityId OriginCityId{get;}public CityId DestinationCityId{get;}public TradeRouteId? RouteId{get;}public long WeightCapacity{get;}public MoneyAmount CashBalance{get;private set;}public CaravanLifecycle Lifecycle{get;}public CaravanLocationStage LocationStage{get;private set;}public CaravanCargoState Cargo{get;}public CaravanAccountingState Accounting{get;}public IReadOnlyList<RouteRiskInput> OrderedRiskInputs=>_riskInputs;public bool CanCredit(long amount){if(amount<0)return false;try{checked{var unused=CashBalance.Value+amount;return unused>=0;}}catch(OverflowException){return false;}}public void Credit(long amount){if(amount<=0||!CanCredit(amount))throw new InvalidOperationException("Caravan cash credit is invalid.");CashBalance=new MoneyAmount(CashBalance.Value+amount);}public void Debit(long amount){if(amount<=0||CashBalance.Value<amount)throw new InvalidOperationException("Insufficient Caravan cash.");CashBalance=new MoneyAmount(CashBalance.Value-amount);}public void MarkInTransit(){if(LocationStage!=CaravanLocationStage.AtOrigin)throw new InvalidOperationException("Caravan cannot enter transit from its current stage.");LocationStage=CaravanLocationStage.InTransit;}public void MarkAtDestination(){if(LocationStage!=CaravanLocationStage.InTransit)throw new InvalidOperationException("Caravan cannot arrive from its current stage.");LocationStage=CaravanLocationStage.AtDestination;}
    }
    public sealed class CaravanRegistry{private readonly SortedDictionary<CaravanId,CaravanState> _items=new SortedDictionary<CaravanId,CaravanState>();public IReadOnlyCollection<CaravanState> OrderedCaravans=>_items.Values;public void Add(CaravanState caravan){if(caravan==null)throw new ArgumentNullException(nameof(caravan));if(_items.ContainsKey(caravan.Id))throw new InvalidOperationException("Duplicate CaravanId.");_items.Add(caravan.Id,caravan);}public CaravanState GetRequired(CaravanId id){if(!_items.TryGetValue(id,out var item))throw new KeyNotFoundException("Caravan was not found.");return item;}}
    public sealed class EconomyState
    {
        private readonly SortedDictionary<CityId,CityMarketState> _markets=new SortedDictionary<CityId,CityMarketState>();public EconomyState(TradeGoodRegistry? goods=null,ProductionRecipeRegistry? recipes=null,CaravanRegistry? caravans=null){Goods=goods??new TradeGoodRegistry();Recipes=recipes??new ProductionRecipeRegistry();Caravans=caravans??new CaravanRegistry();}public TradeGoodRegistry Goods{get;}public ProductionRecipeRegistry Recipes{get;}public CaravanRegistry Caravans{get;}public IReadOnlyCollection<CityMarketState> OrderedMarkets=>_markets.Values;public void AddMarket(CityMarketState market){if(market==null)throw new ArgumentNullException(nameof(market));if(_markets.ContainsKey(market.CityId))throw new InvalidOperationException("Duplicate City market.");_markets.Add(market.CityId,market);}public CityMarketState GetRequiredMarket(CityId id){if(!_markets.TryGetValue(id,out var item))throw new KeyNotFoundException("City market was not found.");return item;}
    }
}
