using System;

namespace FOC.Domain.Common
{
    public readonly struct AIControllerId:IStableId,IEquatable<AIControllerId>,IComparable<AIControllerId>{private readonly StableId<AIControllerTag> _v;private AIControllerId(StableId<AIControllerTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static AIControllerId Create(string v)=>new AIControllerId(StableId<AIControllerTag>.Create(v));public int CompareTo(AIControllerId o)=>_v.CompareTo(o._v);public bool Equals(AIControllerId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is AIControllerId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct AIPriorityProfileId:IStableId,IEquatable<AIPriorityProfileId>,IComparable<AIPriorityProfileId>{private readonly StableId<AIPriorityProfileTag> _v;private AIPriorityProfileId(StableId<AIPriorityProfileTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static AIPriorityProfileId Create(string v)=>new AIPriorityProfileId(StableId<AIPriorityProfileTag>.Create(v));public int CompareTo(AIPriorityProfileId o)=>_v.CompareTo(o._v);public bool Equals(AIPriorityProfileId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is AIPriorityProfileId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct CharacterAIProfileId:IStableId,IEquatable<CharacterAIProfileId>,IComparable<CharacterAIProfileId>{private readonly StableId<CharacterAIProfileTag> _v;private CharacterAIProfileId(StableId<CharacterAIProfileTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static CharacterAIProfileId Create(string v)=>new CharacterAIProfileId(StableId<CharacterAIProfileTag>.Create(v));public int CompareTo(CharacterAIProfileId o)=>_v.CompareTo(o._v);public bool Equals(CharacterAIProfileId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is CharacterAIProfileId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct AIDecisionQualityProfileId:IStableId,IEquatable<AIDecisionQualityProfileId>,IComparable<AIDecisionQualityProfileId>{private readonly StableId<AIDecisionQualityProfileTag> _v;private AIDecisionQualityProfileId(StableId<AIDecisionQualityProfileTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static AIDecisionQualityProfileId Create(string v)=>new AIDecisionQualityProfileId(StableId<AIDecisionQualityProfileTag>.Create(v));public int CompareTo(AIDecisionQualityProfileId o)=>_v.CompareTo(o._v);public bool Equals(AIDecisionQualityProfileId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is AIDecisionQualityProfileId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct AISchedulingProfileId:IStableId,IEquatable<AISchedulingProfileId>,IComparable<AISchedulingProfileId>{private readonly StableId<AISchedulingProfileTag> _v;private AISchedulingProfileId(StableId<AISchedulingProfileTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static AISchedulingProfileId Create(string v)=>new AISchedulingProfileId(StableId<AISchedulingProfileTag>.Create(v));public int CompareTo(AISchedulingProfileId o)=>_v.CompareTo(o._v);public bool Equals(AISchedulingProfileId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is AISchedulingProfileId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct AICandidateId:IStableId,IEquatable<AICandidateId>,IComparable<AICandidateId>{private readonly StableId<AICandidateTag> _v;private AICandidateId(StableId<AICandidateTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static AICandidateId Create(string v)=>new AICandidateId(StableId<AICandidateTag>.Create(v));public int CompareTo(AICandidateId o)=>_v.CompareTo(o._v);public bool Equals(AICandidateId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is AICandidateId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct AIActionPolicyId:IStableId,IEquatable<AIActionPolicyId>,IComparable<AIActionPolicyId>{private readonly StableId<AIActionPolicyTag> _v;private AIActionPolicyId(StableId<AIActionPolicyTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static AIActionPolicyId Create(string v)=>new AIActionPolicyId(StableId<AIActionPolicyTag>.Create(v));public int CompareTo(AIActionPolicyId o)=>_v.CompareTo(o._v);public bool Equals(AIActionPolicyId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is AIActionPolicyId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct AIUtilityFactorId:IStableId,IEquatable<AIUtilityFactorId>,IComparable<AIUtilityFactorId>{private readonly StableId<AIUtilityFactorTag> _v;private AIUtilityFactorId(StableId<AIUtilityFactorTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static AIUtilityFactorId Create(string v)=>new AIUtilityFactorId(StableId<AIUtilityFactorTag>.Create(v));public int CompareTo(AIUtilityFactorId o)=>_v.CompareTo(o._v);public bool Equals(AIUtilityFactorId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is AIUtilityFactorId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct AIPlanId:IStableId,IEquatable<AIPlanId>,IComparable<AIPlanId>{private readonly StableId<AIPlanTag> _v;private AIPlanId(StableId<AIPlanTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static AIPlanId Create(string v)=>new AIPlanId(StableId<AIPlanTag>.Create(v));public int CompareTo(AIPlanId o)=>_v.CompareTo(o._v);public bool Equals(AIPlanId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is AIPlanId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct AIGoalId:IStableId,IEquatable<AIGoalId>,IComparable<AIGoalId>{private readonly StableId<AIGoalTag> _v;private AIGoalId(StableId<AIGoalTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static AIGoalId Create(string v)=>new AIGoalId(StableId<AIGoalTag>.Create(v));public int CompareTo(AIGoalId o)=>_v.CompareTo(o._v);public bool Equals(AIGoalId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is AIGoalId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
}
