using System;

namespace FOC.Domain.Common
{
    public readonly struct BattleId:IStableId,IEquatable<BattleId>,IComparable<BattleId>{private readonly StableId<BattleTag> _value;private BattleId(StableId<BattleTag> value){_value=value;}public bool IsValid=>_value.IsValid;public string Value=>_value.Value;public static BattleId Create(string value)=>new BattleId(StableId<BattleTag>.Create(value));public int CompareTo(BattleId other)=>_value.CompareTo(other._value);public bool Equals(BattleId other)=>_value.Equals(other._value);public override bool Equals(object? obj)=>obj is BattleId other&&Equals(other);public override int GetHashCode()=>_value.GetHashCode();public override string ToString()=>_value.ToString();}
    public readonly struct BattleSideId:IStableId,IEquatable<BattleSideId>,IComparable<BattleSideId>{private readonly StableId<BattleSideTag> _value;private BattleSideId(StableId<BattleSideTag> value){_value=value;}public bool IsValid=>_value.IsValid;public string Value=>_value.Value;public static BattleSideId Create(string value)=>new BattleSideId(StableId<BattleSideTag>.Create(value));public int CompareTo(BattleSideId other)=>_value.CompareTo(other._value);public bool Equals(BattleSideId other)=>_value.Equals(other._value);public override bool Equals(object? obj)=>obj is BattleSideId other&&Equals(other);public override int GetHashCode()=>_value.GetHashCode();public override string ToString()=>_value.ToString();}
    public readonly struct BattleSectorId:IStableId,IEquatable<BattleSectorId>,IComparable<BattleSectorId>{private readonly StableId<BattleSectorTag> _value;private BattleSectorId(StableId<BattleSectorTag> value){_value=value;}public bool IsValid=>_value.IsValid;public string Value=>_value.Value;public static BattleSectorId Create(string value)=>new BattleSectorId(StableId<BattleSectorTag>.Create(value));public int CompareTo(BattleSectorId other)=>_value.CompareTo(other._value);public bool Equals(BattleSectorId other)=>_value.Equals(other._value);public override bool Equals(object? obj)=>obj is BattleSectorId other&&Equals(other);public override int GetHashCode()=>_value.GetHashCode();public override string ToString()=>_value.ToString();}
    public readonly struct DeploymentGroupId:IStableId,IEquatable<DeploymentGroupId>,IComparable<DeploymentGroupId>{private readonly StableId<DeploymentGroupTag> _value;private DeploymentGroupId(StableId<DeploymentGroupTag> value){_value=value;}public bool IsValid=>_value.IsValid;public string Value=>_value.Value;public static DeploymentGroupId Create(string value)=>new DeploymentGroupId(StableId<DeploymentGroupTag>.Create(value));public int CompareTo(DeploymentGroupId other)=>_value.CompareTo(other._value);public bool Equals(DeploymentGroupId other)=>_value.Equals(other._value);public override bool Equals(object? obj)=>obj is DeploymentGroupId other&&Equals(other);public override int GetHashCode()=>_value.GetHashCode();public override string ToString()=>_value.ToString();}
    public readonly struct BattleOrderId:IStableId,IEquatable<BattleOrderId>,IComparable<BattleOrderId>{private readonly StableId<BattleOrderTag> _value;private BattleOrderId(StableId<BattleOrderTag> value){_value=value;}public bool IsValid=>_value.IsValid;public string Value=>_value.Value;public static BattleOrderId Create(string value)=>new BattleOrderId(StableId<BattleOrderTag>.Create(value));public int CompareTo(BattleOrderId other)=>_value.CompareTo(other._value);public bool Equals(BattleOrderId other)=>_value.Equals(other._value);public override bool Equals(object? obj)=>obj is BattleOrderId other&&Equals(other);public override int GetHashCode()=>_value.GetHashCode();public override string ToString()=>_value.ToString();}
    public readonly struct BattleEventId:IStableId,IEquatable<BattleEventId>,IComparable<BattleEventId>{private readonly StableId<BattleEventTag> _value;private BattleEventId(StableId<BattleEventTag> value){_value=value;}public bool IsValid=>_value.IsValid;public string Value=>_value.Value;public static BattleEventId Create(string value)=>new BattleEventId(StableId<BattleEventTag>.Create(value));public int CompareTo(BattleEventId other)=>_value.CompareTo(other._value);public bool Equals(BattleEventId other)=>_value.Equals(other._value);public override bool Equals(object? obj)=>obj is BattleEventId other&&Equals(other);public override int GetHashCode()=>_value.GetHashCode();public override string ToString()=>_value.ToString();}
}
