using System;

namespace FOC.Domain.Common
{
    public readonly struct DiplomaticRelationId:IStableId,IEquatable<DiplomaticRelationId>,IComparable<DiplomaticRelationId>{private readonly StableId<DiplomaticRelationTag> _v;private DiplomaticRelationId(StableId<DiplomaticRelationTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static DiplomaticRelationId Create(string v)=>new DiplomaticRelationId(StableId<DiplomaticRelationTag>.Create(v));public int CompareTo(DiplomaticRelationId o)=>_v.CompareTo(o._v);public bool Equals(DiplomaticRelationId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is DiplomaticRelationId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct DiplomaticActionId:IStableId,IEquatable<DiplomaticActionId>,IComparable<DiplomaticActionId>{private readonly StableId<DiplomaticActionTag> _v;private DiplomaticActionId(StableId<DiplomaticActionTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static DiplomaticActionId Create(string v)=>new DiplomaticActionId(StableId<DiplomaticActionTag>.Create(v));public int CompareTo(DiplomaticActionId o)=>_v.CompareTo(o._v);public bool Equals(DiplomaticActionId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is DiplomaticActionId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct EnvoyMissionId:IStableId,IEquatable<EnvoyMissionId>,IComparable<EnvoyMissionId>{private readonly StableId<EnvoyMissionTag> _v;private EnvoyMissionId(StableId<EnvoyMissionTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static EnvoyMissionId Create(string v)=>new EnvoyMissionId(StableId<EnvoyMissionTag>.Create(v));public int CompareTo(EnvoyMissionId o)=>_v.CompareTo(o._v);public bool Equals(EnvoyMissionId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is EnvoyMissionId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct DiplomaticMessageId:IStableId,IEquatable<DiplomaticMessageId>,IComparable<DiplomaticMessageId>{private readonly StableId<DiplomaticMessageTag> _v;private DiplomaticMessageId(StableId<DiplomaticMessageTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static DiplomaticMessageId Create(string v)=>new DiplomaticMessageId(StableId<DiplomaticMessageTag>.Create(v));public int CompareTo(DiplomaticMessageId o)=>_v.CompareTo(o._v);public bool Equals(DiplomaticMessageId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is DiplomaticMessageId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct ReportId:IStableId,IEquatable<ReportId>,IComparable<ReportId>{private readonly StableId<ReportTag> _v;private ReportId(StableId<ReportTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static ReportId Create(string v)=>new ReportId(StableId<ReportTag>.Create(v));public int CompareTo(ReportId o)=>_v.CompareTo(o._v);public bool Equals(ReportId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is ReportId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct DiplomaticAgreementId:IStableId,IEquatable<DiplomaticAgreementId>,IComparable<DiplomaticAgreementId>{private readonly StableId<DiplomaticAgreementTag> _v;private DiplomaticAgreementId(StableId<DiplomaticAgreementTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static DiplomaticAgreementId Create(string v)=>new DiplomaticAgreementId(StableId<DiplomaticAgreementTag>.Create(v));public int CompareTo(DiplomaticAgreementId o)=>_v.CompareTo(o._v);public bool Equals(DiplomaticAgreementId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is DiplomaticAgreementId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
}
