using System;

namespace FOC.Domain.Common
{
    public readonly struct EncounterId:IStableId,IEquatable<EncounterId>,IComparable<EncounterId>{private readonly StableId<EncounterTag> _v;private EncounterId(StableId<EncounterTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static EncounterId Create(string v)=>new EncounterId(StableId<EncounterTag>.Create(v));public int CompareTo(EncounterId o)=>_v.CompareTo(o._v);public bool Equals(EncounterId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is EncounterId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct EncounterDefinitionId:IStableId,IEquatable<EncounterDefinitionId>,IComparable<EncounterDefinitionId>{private readonly StableId<EncounterDefinitionTag> _v;private EncounterDefinitionId(StableId<EncounterDefinitionTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static EncounterDefinitionId Create(string v)=>new EncounterDefinitionId(StableId<EncounterDefinitionTag>.Create(v));public int CompareTo(EncounterDefinitionId o)=>_v.CompareTo(o._v);public bool Equals(EncounterDefinitionId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is EncounterDefinitionId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct EncounterChoiceId:IStableId,IEquatable<EncounterChoiceId>,IComparable<EncounterChoiceId>{private readonly StableId<EncounterChoiceTag> _v;private EncounterChoiceId(StableId<EncounterChoiceTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static EncounterChoiceId Create(string v)=>new EncounterChoiceId(StableId<EncounterChoiceTag>.Create(v));public int CompareTo(EncounterChoiceId o)=>_v.CompareTo(o._v);public bool Equals(EncounterChoiceId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is EncounterChoiceId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct EncounterOutcomeId:IStableId,IEquatable<EncounterOutcomeId>,IComparable<EncounterOutcomeId>{private readonly StableId<EncounterOutcomeTag> _v;private EncounterOutcomeId(StableId<EncounterOutcomeTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static EncounterOutcomeId Create(string v)=>new EncounterOutcomeId(StableId<EncounterOutcomeTag>.Create(v));public int CompareTo(EncounterOutcomeId o)=>_v.CompareTo(o._v);public bool Equals(EncounterOutcomeId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is EncounterOutcomeId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct EncounterPolicyId:IStableId,IEquatable<EncounterPolicyId>,IComparable<EncounterPolicyId>{private readonly StableId<EncounterPolicyTag> _v;private EncounterPolicyId(StableId<EncounterPolicyTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static EncounterPolicyId Create(string v)=>new EncounterPolicyId(StableId<EncounterPolicyTag>.Create(v));public int CompareTo(EncounterPolicyId o)=>_v.CompareTo(o._v);public bool Equals(EncounterPolicyId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is EncounterPolicyId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct ContractId:IStableId,IEquatable<ContractId>,IComparable<ContractId>{private readonly StableId<ContractTag> _v;private ContractId(StableId<ContractTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static ContractId Create(string v)=>new ContractId(StableId<ContractTag>.Create(v));public int CompareTo(ContractId o)=>_v.CompareTo(o._v);public bool Equals(ContractId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is ContractId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct ContractDefinitionId:IStableId,IEquatable<ContractDefinitionId>,IComparable<ContractDefinitionId>{private readonly StableId<ContractDefinitionTag> _v;private ContractDefinitionId(StableId<ContractDefinitionTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static ContractDefinitionId Create(string v)=>new ContractDefinitionId(StableId<ContractDefinitionTag>.Create(v));public int CompareTo(ContractDefinitionId o)=>_v.CompareTo(o._v);public bool Equals(ContractDefinitionId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is ContractDefinitionId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct ContractObjectiveId:IStableId,IEquatable<ContractObjectiveId>,IComparable<ContractObjectiveId>{private readonly StableId<ContractObjectiveTag> _v;private ContractObjectiveId(StableId<ContractObjectiveTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static ContractObjectiveId Create(string v)=>new ContractObjectiveId(StableId<ContractObjectiveTag>.Create(v));public int CompareTo(ContractObjectiveId o)=>_v.CompareTo(o._v);public bool Equals(ContractObjectiveId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is ContractObjectiveId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct ContractTargetSlotId:IStableId,IEquatable<ContractTargetSlotId>,IComparable<ContractTargetSlotId>{private readonly StableId<ContractTargetSlotTag> _v;private ContractTargetSlotId(StableId<ContractTargetSlotTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static ContractTargetSlotId Create(string v)=>new ContractTargetSlotId(StableId<ContractTargetSlotTag>.Create(v));public int CompareTo(ContractTargetSlotId o)=>_v.CompareTo(o._v);public bool Equals(ContractTargetSlotId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is ContractTargetSlotId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct ContractEvidenceId:IStableId,IEquatable<ContractEvidenceId>,IComparable<ContractEvidenceId>{private readonly StableId<ContractEvidenceTag> _v;private ContractEvidenceId(StableId<ContractEvidenceTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static ContractEvidenceId Create(string v)=>new ContractEvidenceId(StableId<ContractEvidenceTag>.Create(v));public int CompareTo(ContractEvidenceId o)=>_v.CompareTo(o._v);public bool Equals(ContractEvidenceId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is ContractEvidenceId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
    public readonly struct ContractResolutionProfileId:IStableId,IEquatable<ContractResolutionProfileId>,IComparable<ContractResolutionProfileId>{private readonly StableId<ContractResolutionProfileTag> _v;private ContractResolutionProfileId(StableId<ContractResolutionProfileTag> v){_v=v;}public bool IsValid=>_v.IsValid;public string Value=>_v.Value;public static ContractResolutionProfileId Create(string v)=>new ContractResolutionProfileId(StableId<ContractResolutionProfileTag>.Create(v));public int CompareTo(ContractResolutionProfileId o)=>_v.CompareTo(o._v);public bool Equals(ContractResolutionProfileId o)=>_v.Equals(o._v);public override bool Equals(object? o)=>o is ContractResolutionProfileId x&&Equals(x);public override int GetHashCode()=>_v.GetHashCode();}
}
