using System;

namespace FOC.Domain.Common
{
    public readonly struct UnitGroupId:IStableId,IEquatable<UnitGroupId>,IComparable<UnitGroupId>{private readonly StableId<UnitGroupTag> _value;private UnitGroupId(StableId<UnitGroupTag> value){_value=value;}public bool IsValid=>_value.IsValid;public string Value=>_value.Value;public static UnitGroupId Create(string value)=>new UnitGroupId(StableId<UnitGroupTag>.Create(value));public int CompareTo(UnitGroupId other)=>_value.CompareTo(other._value);public bool Equals(UnitGroupId other)=>_value.Equals(other._value);public override bool Equals(object? obj)=>obj is UnitGroupId other&&Equals(other);public override int GetHashCode()=>_value.GetHashCode();public override string ToString()=>_value.ToString();}
    public readonly struct RecruitmentSourceId:IStableId,IEquatable<RecruitmentSourceId>,IComparable<RecruitmentSourceId>{private readonly StableId<RecruitmentSourceTag> _value;private RecruitmentSourceId(StableId<RecruitmentSourceTag> value){_value=value;}public bool IsValid=>_value.IsValid;public string Value=>_value.Value;public static RecruitmentSourceId Create(string value)=>new RecruitmentSourceId(StableId<RecruitmentSourceTag>.Create(value));public int CompareTo(RecruitmentSourceId other)=>_value.CompareTo(other._value);public bool Equals(RecruitmentSourceId other)=>_value.Equals(other._value);public override bool Equals(object? obj)=>obj is RecruitmentSourceId other&&Equals(other);public override int GetHashCode()=>_value.GetHashCode();public override string ToString()=>_value.ToString();}
    public readonly struct RecruitmentRecordId:IStableId,IEquatable<RecruitmentRecordId>,IComparable<RecruitmentRecordId>{private readonly StableId<RecruitmentRecordTag> _value;private RecruitmentRecordId(StableId<RecruitmentRecordTag> value){_value=value;}public bool IsValid=>_value.IsValid;public string Value=>_value.Value;public static RecruitmentRecordId Create(string value)=>new RecruitmentRecordId(StableId<RecruitmentRecordTag>.Create(value));public int CompareTo(RecruitmentRecordId other)=>_value.CompareTo(other._value);public bool Equals(RecruitmentRecordId other)=>_value.Equals(other._value);public override bool Equals(object? obj)=>obj is RecruitmentRecordId other&&Equals(other);public override int GetHashCode()=>_value.GetHashCode();public override string ToString()=>_value.ToString();}
    public readonly struct PayrollObligationId:IStableId,IEquatable<PayrollObligationId>,IComparable<PayrollObligationId>{private readonly StableId<PayrollObligationTag> _value;private PayrollObligationId(StableId<PayrollObligationTag> value){_value=value;}public bool IsValid=>_value.IsValid;public string Value=>_value.Value;public static PayrollObligationId Create(string value)=>new PayrollObligationId(StableId<PayrollObligationTag>.Create(value));public int CompareTo(PayrollObligationId other)=>_value.CompareTo(other._value);public bool Equals(PayrollObligationId other)=>_value.Equals(other._value);public override bool Equals(object? obj)=>obj is PayrollObligationId other&&Equals(other);public override int GetHashCode()=>_value.GetHashCode();public override string ToString()=>_value.ToString();}
    public readonly struct PayrollPaymentId:IStableId,IEquatable<PayrollPaymentId>,IComparable<PayrollPaymentId>{private readonly StableId<PayrollPaymentTag> _value;private PayrollPaymentId(StableId<PayrollPaymentTag> value){_value=value;}public bool IsValid=>_value.IsValid;public string Value=>_value.Value;public static PayrollPaymentId Create(string value)=>new PayrollPaymentId(StableId<PayrollPaymentTag>.Create(value));public int CompareTo(PayrollPaymentId other)=>_value.CompareTo(other._value);public bool Equals(PayrollPaymentId other)=>_value.Equals(other._value);public override bool Equals(object? obj)=>obj is PayrollPaymentId other&&Equals(other);public override int GetHashCode()=>_value.GetHashCode();public override string ToString()=>_value.ToString();}
}
