using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using FOC.Application.Battle;
using FOC.Application.Save;
using FOC.Domain.Battle;
using FOC.Domain.Characters;
using FOC.Domain.Common;
using FOC.Domain.Military;
using FOC.Domain.Random;
using FOC.Domain.Soldiers;
using FOC.Domain.Time;
using FOC.Domain.Validation;
using FOC.Infrastructure.Save;
using FOC.Visuals.Core;
using NUnit.Framework;

namespace FOC.Tests
{
    public sealed class BattleDeploySectorTests
    {
        [Test]public void BattleCreation_PreservesPersistentIdentityLoadoutAndAggregateRemainder(){var f=BattleTestFactory.Create();var units=f.Battle.OrderedSides.SelectMany(x=>x.OrderedParticipants).SelectMany(x=>x.OrderedUnits).ToList();var unit=units.Single(x=>x.UnitGroupId.Equals(f.UnitA1));var combatant=unit.OrderedCombatants.Single();Assert.That(combatant.SoldierId,Is.EqualTo(f.SoldierA));Assert.That(combatant.OrderedEquipment,Is.EqualTo(new[]{f.SwordA}));Assert.That(unit.CampaignHeadcount,Is.EqualTo(3));Assert.That(unit.AggregateNonInstantiatedStrength,Is.EqualTo(2));var mounted=units.Single(x=>x.UnitGroupId.Equals(f.UnitA2)).OrderedCombatants.Single();Assert.That(mounted.IsMounted,Is.True);Assert.That(mounted.OrderedEquipment.Any(x=>x.Equals(f.LanceMounted)),Is.True);Assert.That(mounted.OrderedEquipment.Any(x=>x.Equals(f.HorseMounted)),Is.True);Assert.That(mounted.OrderedEquipment.Any(x=>x.Equals(f.ArmorMounted)),Is.True);Assert.That(f.Campaign.Soldiers.Soldiers.OrderedSoldiers.Count(),Is.EqualTo(3));}
        [Test]public void ActiveBattle_DoesNotMutateCampaignState(){var f=BattleTestFactory.Create();var unit=f.Campaign.Military.Armies.GetRequired(f.ArmyA).GetRequiredUnit(f.UnitA1);var loadout=f.Campaign.Soldiers.Soldiers.GetRequired(f.SoldierA).Loadout;f.Battle.Issue(new BattleOrder(BattleOrderId.Create("move"),0,BattleOrderKind.MoveSector,f.SideA,CharacterId.Create("commander-a"),f.DeployA,f.SectorMiddle));Assert.That(unit.Headcount,Is.EqualTo(3));Assert.That(f.Campaign.Soldiers.Soldiers.GetRequired(f.SoldierA).Loadout,Is.SameAs(loadout));}
        [Test]public void Lifecycle_RejectsInvalidTransitionsAndTerminalReuse(){var f=BattleTestFactory.Create(startActive:false);Assert.Throws<InvalidOperationException>(()=>f.Battle.BeginDeployment());f.Battle.BeginActive();f.Battle.BeginResolving();var result=Result(f,0,BattleCasualtyOutcome.Survived);f.Battle.Complete(result);Assert.Throws<InvalidOperationException>(()=>f.Battle.BeginActive());Assert.Throws<InvalidOperationException>(()=>f.Battle.Complete(result));}
        [Test]public void Deployment_RejectsDuplicateUnitAndEnemySector(){var f=BattleTestFactory.Create(startActive:false);Assert.Throws<InvalidOperationException>(()=>f.Battle.Deploy(new BattleDeployment(DeploymentGroupId.Create("duplicate"),f.SideA,f.ArmyA,f.UnitA1,f.SectorA,BattleFormation.Line)));Assert.Throws<InvalidOperationException>(()=>f.Battle.Deploy(new BattleDeployment(DeploymentGroupId.Create("wrong"),f.SideA,f.ArmyA,f.UnitA2,f.SectorB,BattleFormation.Line)));}
        [Test]public void SectorGraph_RejectsSelfDuplicateAndDanglingReferences(){var graph=new BattleSectorGraph();var a=new BattleSector(BattleSectorId.Create("a"));var b=new BattleSector(BattleSectorId.Create("b"));graph.Add(a);graph.Add(b);graph.Connect(a.Id,b.Id);Assert.Throws<InvalidOperationException>(()=>graph.Connect(a.Id,b.Id));Assert.Throws<InvalidOperationException>(()=>graph.Connect(a.Id,a.Id));Assert.Throws<System.Collections.Generic.KeyNotFoundException>(()=>graph.Connect(a.Id,BattleSectorId.Create("missing")));}
        [Test]public void Orders_RequireAuthorityAdjacencyAndHostileTargets(){var f=BattleTestFactory.Create();Assert.Throws<InvalidOperationException>(()=>f.Battle.Issue(new BattleOrder(BattleOrderId.Create("far"),0,BattleOrderKind.MoveSector,f.SideA,CharacterId.Create("commander-a"),f.DeployA,f.SectorB)));Assert.Throws<InvalidOperationException>(()=>f.Battle.Issue(new BattleOrder(BattleOrderId.Create("enemy"),1,BattleOrderKind.Hold,f.SideB,CharacterId.Create("commander-b"),f.DeployA)));Assert.Throws<InvalidOperationException>(()=>f.Battle.Issue(new BattleOrder(BattleOrderId.Create("friendly"),2,BattleOrderKind.Attack,f.SideA,CharacterId.Create("commander-a"),f.DeployA,null,f.DeployA)));}
        [Test]public void UnitCommander_CanOnlyCommandOwnDeploymentGroup(){var f=BattleTestFactory.Create();var commander=CharacterId.Create("unit-commander-a");Assert.DoesNotThrow(()=>f.Battle.Issue(new BattleOrder(BattleOrderId.Create("own-unit"),10,BattleOrderKind.Hold,f.SideA,commander,f.DeployA)));Assert.Throws<InvalidOperationException>(()=>f.Battle.Issue(new BattleOrder(BattleOrderId.Create("other-unit"),11,BattleOrderKind.Hold,f.SideA,commander,f.DeployA2)));}
        [Test]public void RangedCombat_RequiresAndConsumesExplicitAmmunition(){var f=BattleTestFactory.Create();var service=new BattleCombatService(f.Campaign);var intent=new BattleAttackIntent(f.DeployB,f.SoldierB,f.SoldierA,f.BowB,AttackMode.Thrust,DamageType.Pierce);service.Resolve(f.Battle.Id,intent,new FixedResolver(BattleCasualtyOutcome.Wounded),new OneUnitAmmoPolicy());Assert.That(f.Battle.Ammunition.QuantityOf(f.SoldierB,AmmoFamilyId.Create("arrow")),Is.EqualTo(1));service.Resolve(f.Battle.Id,intent,new FixedResolver(BattleCasualtyOutcome.Survived,1),new OneUnitAmmoPolicy());Assert.That(f.Battle.Ammunition.QuantityOf(f.SoldierB,AmmoFamilyId.Create("arrow")),Is.Zero);Assert.Throws<InvalidOperationException>(()=>service.Resolve(f.Battle.Id,intent,new FixedResolver(BattleCasualtyOutcome.Survived,2),new OneUnitAmmoPolicy()));}
        [Test]public void Combat_ValidatesDeploymentAndPassesPersistentArmorToPolicy(){var f=BattleTestFactory.Create();var service=new BattleCombatService(f.Campaign);var invalid=new BattleAttackIntent(f.DeployB2,f.SoldierB,f.SoldierMounted,f.BowB,AttackMode.Thrust,DamageType.Pierce);Assert.Throws<InvalidOperationException>(()=>service.Resolve(f.Battle.Id,invalid,new FixedResolver(BattleCasualtyOutcome.Survived),new OneUnitAmmoPolicy()));var policy=new RecordingArmorPolicy();var intent=new BattleAttackIntent(f.DeployB,f.SoldierB,f.SoldierMounted,f.BowB,AttackMode.Thrust,DamageType.Pierce);service.Resolve(f.Battle.Id,intent,new FixedResolver(BattleCasualtyOutcome.Survived),new OneUnitAmmoPolicy(),policy);Assert.That(policy.ArmorIds,Is.EqualTo(new[]{ArmorDefinitionId.Create("armor")}));}
        [Test]public void WeaponCapability_RejectsModeNotDeclaredByDefinition(){var f=BattleTestFactory.Create();var intent=new BattleAttackIntent(f.DeployA,f.SoldierA,f.SoldierB,f.SwordA,AttackMode.Crush,DamageType.Blunt);Assert.Throws<InvalidOperationException>(()=>new BattleCombatService(f.Campaign).Resolve(f.Battle.Id,intent,new FixedResolver(BattleCasualtyOutcome.Survived),new OneUnitAmmoPolicy()));}
        [Test]public void SameSnapshotCommandsAndRng_ProduceSameOutcomeAndContinuation(){var a=BattleTestFactory.Create();var b=BattleTestFactory.Create(reverse:true);var ia=new BattleAttackIntent(a.DeployB,a.SoldierB,a.SoldierA,a.BowB,AttackMode.Thrust,DamageType.Pierce);var ib=new BattleAttackIntent(b.DeployB,b.SoldierB,b.SoldierA,b.BowB,AttackMode.Thrust,DamageType.Pierce);var oa=new BattleCombatService(a.Campaign).Resolve(a.Battle.Id,ia,new RandomResolver(),new OneUnitAmmoPolicy());var ob=new BattleCombatService(b.Campaign).Resolve(b.Battle.Id,ib,new RandomResolver(),new OneUnitAmmoPolicy());Assert.That(ob.Outcome,Is.EqualTo(oa.Outcome));Assert.That(b.Battle.RandomState,Is.EqualTo(a.Battle.RandomState));}
        [Test]public void Reconciliation_IsOneTimeAndPreservesSurvivorAndEquipmentIdentity(){var f=BattleTestFactory.Create();var soldier=f.Campaign.Soldiers.Soldiers.GetRequired(f.SoldierA);var loadout=soldier.Loadout;f.Battle.BeginResolving();f.Campaign.Clock.Advance(new WorldDuration(2));f.Battle.Complete(Result(f,1,BattleCasualtyOutcome.Survived));new BattleReconciliationService(f.Campaign).Apply(f.Battle.Id);Assert.That(f.Campaign.Military.Armies.GetRequired(f.ArmyA).GetRequiredUnit(f.UnitA1).Headcount,Is.EqualTo(2));Assert.That(f.Campaign.Soldiers.Soldiers.GetRequired(f.SoldierA),Is.SameAs(soldier));Assert.That(soldier.Loadout,Is.SameAs(loadout));Assert.That(soldier.Loadout.WeaponAt(WeaponSlot.Main),Is.EqualTo(f.SwordA));Assert.Throws<InvalidOperationException>(()=>new BattleReconciliationService(f.Campaign).Apply(f.Battle.Id));}
        [Test]public void FailedReconciliation_IsAtomic(){var f=BattleTestFactory.Create();f.Battle.BeginResolving();f.Campaign.Clock.Advance(new WorldDuration(2));f.Battle.Complete(Result(f,99,BattleCasualtyOutcome.Killed));var headcount=f.Campaign.Military.Armies.GetRequired(f.ArmyA).GetRequiredUnit(f.UnitA1).Headcount;Assert.Throws<InvalidOperationException>(()=>new BattleReconciliationService(f.Campaign).Apply(f.Battle.Id));Assert.That(f.Campaign.Military.Armies.GetRequired(f.ArmyA).GetRequiredUnit(f.UnitA1).Headcount,Is.EqualTo(headcount));Assert.That(f.Campaign.Soldiers.Soldiers.GetRequired(f.SoldierA).Lifecycle,Is.EqualTo(SoldierLifecycle.Active));Assert.That(f.Battle.IsReconciled,Is.False);}
        [Test]public void KilledSoldier_RemainsHistoricallyIdentifiedButLeavesActiveRoster(){var f=BattleTestFactory.Create();f.Battle.BeginResolving();f.Campaign.Clock.Advance(new WorldDuration(2));f.Battle.Complete(Result(f,1,BattleCasualtyOutcome.Killed));new BattleReconciliationService(f.Campaign).Apply(f.Battle.Id);Assert.That(f.Campaign.Soldiers.Soldiers.GetRequired(f.SoldierA).Lifecycle,Is.EqualTo(SoldierLifecycle.Killed));Assert.That(f.Campaign.Soldiers.Soldiers.CountFor(f.UnitA1),Is.Zero);Assert.That(f.Campaign.Soldiers.Equipment.GetRequired(f.SwordA).Owner.Id,Is.EqualTo(f.SoldierA.Value));}
        [Test]public void CapturedCommander_UsesExistingCaptivityAndVacatesCampaignCommand(){var f=BattleTestFactory.Create();f.Battle.BeginResolving();f.Campaign.Clock.Advance(new WorldDuration(2));var capture=new BattleCharacterOutcome(CharacterId.Create("commander-a"),BattleCasualtyOutcome.Captured,captorId:CharacterId.Create("commander-b"),captorArmyId:f.ArmyB);f.Battle.Complete(Result(f,0,BattleCasualtyOutcome.Survived,capture));new BattleReconciliationService(f.Campaign).Apply(f.Battle.Id);Assert.That(f.Campaign.Characters.GetRequired(CharacterId.Create("commander-a")).Captivity,Is.Not.Null);Assert.That(f.Campaign.Military.Armies.GetRequired(f.ArmyA).Commander,Is.Null);var validation=new MilitaryInvariantValidator().Validate(f.Campaign);Assert.That(validation.IsValid,Is.True,string.Join(" | ",validation.Issues.Select(x=>x.Code+":"+x.Message)));var saveValidation=new CampaignSaveValidator().Validate(CampaignSaveMapper.ToSaveData(f.Campaign));Assert.That(saveValidation.IsValid,Is.True,string.Join(" | ",saveValidation.Issues.Select(x=>x.Code+":"+x.Message)));}
        [Test]public void SaveV10_ActiveBattleRoundTripsRngSnapshotAndPersistentReferences(){var f=BattleTestFactory.Create();var serializer=new CampaignSaveTextSerializer();var save=CampaignSaveMapper.ToSaveData(f.Campaign);var read=serializer.Deserialize(serializer.Serialize(save));Assert.That(read.Success,Is.True,read.Error);var restored=CampaignSaveMapper.ToRuntimeState(read.Data!);var battle=restored.Battles.Battles.GetRequired(f.Battle.Id);Assert.That(battle.Lifecycle,Is.EqualTo(BattleLifecycle.Active));Assert.That(battle.RandomState,Is.EqualTo(f.Battle.RandomState));Assert.That(battle.RequireCombatant(f.SoldierA).OrderedEquipment.Single(),Is.EqualTo(f.SwordA));Assert.That(battle.Sectors.GetRequired(f.SectorMiddle).OrderedAdjacent.Count,Is.EqualTo(2));}
        [Test]public void SaveV10_CompletedResultRoundTripsSidesAmmoAndReconciliationMarker(){var f=BattleTestFactory.Create();f.Battle.BeginResolving();f.Campaign.Clock.Advance(new WorldDuration(2));f.Battle.Complete(Result(f,0,BattleCasualtyOutcome.Survived));new BattleReconciliationService(f.Campaign).Apply(f.Battle.Id);var serializer=new CampaignSaveTextSerializer();var read=serializer.Deserialize(serializer.Serialize(CampaignSaveMapper.ToSaveData(f.Campaign)));Assert.That(read.Success,Is.True,read.Error);var result=CampaignSaveMapper.ToRuntimeState(read.Data!).Battles.Battles.GetRequired(f.Battle.Id);Assert.That(result.IsReconciled,Is.True);Assert.That(result.Result!.OrderedParticipatingSides,Is.EqualTo(new[]{f.SideA,f.SideB}));Assert.That(result.Result.OrderedAmmunitionOutcomes.Single().RemainingQuantity,Is.EqualTo(2));}
        [Test]public void SaveV10_IsCanonicalAcrossInsertionOrder(){var a=new CampaignSaveTextSerializer().Serialize(CampaignSaveMapper.ToSaveData(BattleTestFactory.Create(false).Campaign));var b=new CampaignSaveTextSerializer().Serialize(CampaignSaveMapper.ToSaveData(BattleTestFactory.Create(true).Campaign));Assert.That(b,Is.EqualTo(a));}
        [Test]public void MigrationNineToTen_PreservesStateWithoutInventingBattle(){var source=CampaignSaveMapper.ToSaveData(BattleTestFactory.Create().Campaign);source.SaveVersion=9;source.Battles.Clear();var migrated=new CampaignSaveV9ToV10Migration().Apply(source);Assert.That(migrated.SaveVersion,Is.EqualTo(10));Assert.That(migrated.Battles,Is.Empty);Assert.That(source.SaveVersion,Is.EqualTo(9));Assert.That(migrated.Soldiers.Count,Is.EqualTo(source.Soldiers.Count));}
        [Test]public void HardcodedSchemaNineFixture_MigratesWithoutFakeBattle(){const string fixture="FOC_CAMPAIGN_SAVE\nSaveVersion=9\nCampaignId=Y2FtcGFpZ24tbGVnYWN5\nGameVersion=MC4wLjk=\nContentDataVersion=c29sZGllci0x\nWorldSeed=1648\nWorldGenRevision=1\nWorldTime=9\nRngState=123\nRngDrawCount=2\nCharacterCount=0\nCharacterRelationCount=0\nSocialState=AAAAAAAAAAAAAAAA\nReligionState=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nCityState=AAAAAA==\nEconomyState=AAAAAAAAAAAAAAAAAAAAAA==\nDiplomacyState=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\nMilitaryState=AAAAAAAAAAAAAAAA\nSoldierState=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\n";var read=new CampaignSaveTextSerializer().Deserialize(fixture);Assert.That(read.Success,Is.True,read.Error);var migrated=new CampaignSaveV9ToV10Migration().Apply(read.Data!);Assert.That(migrated.Battles,Is.Empty);Assert.That(migrated.SaveVersion,Is.EqualTo(10));}
        [Test]public void DomainBattleSources_AreUnityAndPresentationFree(){var root=FindRepoRoot();foreach(var path in Directory.GetFiles(Path.Combine(root,"UnityProject","Assets","FOC","Domain","Battle"),"*.cs",SearchOption.AllDirectories)){var source=File.ReadAllText(path);Assert.That(source,Does.Not.Contain("UnityEngine"),path);Assert.That(source,Does.Not.Contain("FOC.Presentation"),path);Assert.That(source,Does.Not.Contain("System.Random"),path);Assert.That(source,Does.Not.Contain("DateTime.Now"),path);}}
        [Test]public void BattleResult_IsNotCampaignStateAndUsesNoUnityObjects(){Assert.That(typeof(FOC.Domain.Campaign.IDomainState).IsAssignableFrom(typeof(BattleResult)),Is.False);Assert.That(typeof(CampaignSaveData).IsAssignableFrom(typeof(BattleState)),Is.False);}
        [Test]public void BattleVisualBinding_UsesExactPersistentLoadoutAndRejectsReroll(){var f=BattleTestFactory.Create();var snapshot=f.Battle.RequireCombatant(f.SoldierA);var soldier=f.Campaign.Soldiers.Soldiers.GetRequired(f.SoldierA);var equipment=f.Campaign.Soldiers.Equipment.OrderedEquipment.ToDictionary(x=>x.Id);Assert.DoesNotThrow(()=>BattleVisualBinding.Validate(snapshot,soldier,equipment));var rerolled=new SoldierInstance(soldier.Id,soldier.UnitGroupId,soldier.TroopDefinitionId,soldier.Recruitment,new SoldierLoadout(),soldier.CombatRoleId);Assert.Throws<InvalidOperationException>(()=>BattleVisualBinding.Validate(snapshot,rerolled,equipment));}
        private static BattleResult Result(BattleFixture f,long losses,BattleCasualtyOutcome outcome,params BattleCharacterOutcome[] characters)=>new BattleResult(f.Battle.Id,BattleEndReason.ObjectiveResolved,new WorldTimestamp(12),f.Battle.Step,f.SideA,new[]{new BattleUnitOutcome(f.UnitA1,losses,MoraleAssessment.Steady,FatigueAssessment.Fatigued,DisciplineAssessment.Ordered),new BattleUnitOutcome(f.UnitA2,0,MoraleAssessment.Steady,FatigueAssessment.Rested,DisciplineAssessment.Ordered),new BattleUnitOutcome(f.UnitB1,0,MoraleAssessment.Steady,FatigueAssessment.Rested,DisciplineAssessment.Ordered),new BattleUnitOutcome(f.UnitB2,0,MoraleAssessment.Steady,FatigueAssessment.Rested,DisciplineAssessment.Ordered)},new[]{new BattleSoldierOutcome(f.SoldierA,outcome),new BattleSoldierOutcome(f.SoldierB,BattleCasualtyOutcome.Survived),new BattleSoldierOutcome(f.SoldierMounted,BattleCasualtyOutcome.Survived)},characters,f.Battle.OrderedSides.Select(x=>x.Id),f.Battle.Ammunition.OrderedAllocations.Select(x=>new BattleAmmoOutcome(x.SoldierId,x.FamilyId,x.Quantity)));
        private static string FindRepoRoot(){var current=new DirectoryInfo(TestContext.CurrentContext.TestDirectory);while(current!=null&&!File.Exists(Path.Combine(current.FullName,"FallOfCavalry.sln")))current=current.Parent;return current?.FullName??throw new DirectoryNotFoundException();}
        private sealed class OneUnitAmmoPolicy:IBattleAmmunitionPolicy{public long RequiredUnits(BattleAttackIntent intent,WeaponDefinition weapon)=>1;}
        private sealed class FixedResolver:IBattleCombatResolver{private readonly BattleCasualtyOutcome _outcome;private readonly long _sequence;public FixedResolver(BattleCasualtyOutcome outcome,long sequence=0){_outcome=outcome;_sequence=sequence;}public BattleCombatOutcome Resolve(BattleState battle,BattleAttackIntent intent,FOC.Domain.Random.IRandomSource random)=>new BattleCombatOutcome(BattleEventId.Create("event-"+_sequence),_sequence,intent.Target,_outcome);}
        private sealed class RandomResolver:IBattleCombatResolver{public BattleCombatOutcome Resolve(BattleState battle,BattleAttackIntent intent,FOC.Domain.Random.IRandomSource random){var value=random.NextInt(0,2)==0?BattleCasualtyOutcome.Survived:BattleCasualtyOutcome.Wounded;return new BattleCombatOutcome(BattleEventId.Create("event-random"),0,intent.Target,value);}}
        private sealed class RecordingArmorPolicy:IBattleArmorPolicy{public IReadOnlyList<ArmorDefinitionId> ArmorIds=Array.Empty<ArmorDefinitionId>();public BattleCombatOutcome Resolve(BattleState battle,BattleAttackIntent intent,WeaponDefinition weapon,IReadOnlyList<ArmorDefinition> armor,FOC.Domain.Random.IRandomSource random){ArmorIds=armor.Select(x=>x.Id).ToList();return new BattleCombatOutcome(BattleEventId.Create("event-armor"),0,intent.Target,BattleCasualtyOutcome.Survived);}}
    }
}
