using System;
using System.Linq;
using FOC.Application.Cities;
using FOC.Application.Characters;
using FOC.Domain.Characters;
using FOC.Domain.Cities;
using FOC.Domain.Common;
using FOC.Domain.Organizations;
using FOC.Domain.Religion;
using FOC.Domain.Houses;
using FOC.Domain.Cliques;
using NUnit.Framework;

namespace FOC.Tests
{
    public sealed class CityTests
    {
        [Test]public void CityId_IsTypedStableIdentity(){Assert.That(CityId.Create("a").Equals(CityId.Create("a")),Is.True);Assert.That(CityId.Create("a").CompareTo(CityId.Create("b")),Is.LessThan(0));Assert.That(CityId.Create("same").Equals(FactionId.Create("same")),Is.False);}
        [Test]public void Registry_RejectsDuplicatesAndOrdersDeterministically(){var r=new CityRegistry();r.Add(CityTestFactory.State("z"));r.Add(CityTestFactory.State("a"));Assert.That(r.OrderedCities.Select(x=>x.Id.Value),Is.EqualTo(new[]{"a","z"}));Assert.Throws<InvalidOperationException>(()=>r.Add(CityTestFactory.State("a")));}
        [Test]public void CityRequiresExactlyEveryAuthoritativeArea(){var areas=CityTestFactory.Definition().OrderedAreas.Where(x=>x.Type!=CityAreaType.Health);Assert.Throws<InvalidOperationException>(()=>new CityDefinition(CityId.Create("incomplete"),"Incomplete",areas));Assert.That(Enum.GetNames(typeof(CityAreaType)),Is.EqualTo(new[]{"InnerCastle","Trade","InnCaravan","Housing","Military","Health","ProductionCraft","FoodSupply","SquareCulture"}));}
        [TestCase(CityAreaFullness.Empty)][TestCase(CityAreaFullness.Low)][TestCase(CityAreaFullness.Half)]public void InnerCastle_RejectsEveryNonFullState(CityAreaFullness fullness){var inner=CityTestFactory.State().GetRequiredArea(CityAreaType.InnerCastle);Assert.That(inner.Fullness,Is.EqualTo(CityAreaFullness.Full));Assert.Throws<InvalidOperationException>(()=>inner.SetFullness(fullness));}
        [TestCase(CityAreaFullness.Empty)][TestCase(CityAreaFullness.Low)][TestCase(CityAreaFullness.Half)][TestCase(CityAreaFullness.Full)]public void OtherAreas_AcceptEveryAuthorizedFullness(CityAreaFullness fullness){var area=CityTestFactory.State().GetRequiredArea(CityAreaType.Housing);Assert.DoesNotThrow(()=>area.SetFullness(fullness));Assert.That(area.Fullness,Is.EqualTo(fullness));}
        [Test]public void ActiveBuilding_MustBelongToPool(){var area=CityTestFactory.State().GetRequiredArea(CityAreaType.Trade);area.SetFullness(CityAreaFullness.Low);Assert.Throws<System.Collections.Generic.KeyNotFoundException>(()=>area.ActivateBuilding(CityBuildingId.Create("outside")));}
        [Test]public void DuplicateActiveBuilding_IsRejected(){var area=CityTestFactory.State().GetRequiredArea(CityAreaType.Trade);area.SetFullness(CityAreaFullness.Low);area.ActivateBuilding(CityBuildingId.Create("market"));Assert.Throws<InvalidOperationException>(()=>area.ActivateBuilding(CityBuildingId.Create("market")));Assert.Throws<InvalidOperationException>(()=>area.SetFullness(CityAreaFullness.Empty));}
        [Test]public void RemovedBuilding_CannotBecomeActive(){var area=CityTestFactory.State().GetRequiredArea(CityAreaType.Trade);area.SetFullness(CityAreaFullness.Low);Assert.Throws<InvalidOperationException>(()=>area.ActivateBuilding(CityBuildingId.Create("removed-bedesten")));}
        [Test]public void RemovedTopLevelAreas_DoNotExist(){var names=Enum.GetNames(typeof(CityAreaType));Assert.That(names,Does.Not.Contain("Diplomacy"));Assert.That(names,Does.Not.Contain("Port"));Assert.That(names,Does.Not.Contain("Sea"));Assert.That(names,Does.Not.Contain("RegionalSpecial"));Assert.That(names,Does.Not.Contain("Infrastructure"));Assert.That(names,Does.Not.Contain("Divan"));Assert.That(names,Does.Not.Contain("TaxOffice"));}
        [Test]public void RemovedAndFoodBuildingAuthority_IsEnforced(){Assert.That(Enum.GetNames(typeof(CityBuildingKind)),Does.Not.Contain("RopeWorkshop"));Assert.That(CityBuildingRules.RequiredArea(CityBuildingKind.Butcher),Is.EqualTo(CityAreaType.FoodSupply));Assert.That(CityBuildingRules.RequiredArea(CityBuildingKind.Fishery),Is.EqualTo(CityAreaType.FoodSupply));Assert.Throws<InvalidOperationException>(()=>new CityBuildingDefinition(CityBuildingId.Create("bad"),"Butcher",CityBuildingKind.Butcher,CityAreaType.ProductionCraft));}
        [Test]public void MilitaryPoolCapability_ContainsAuthorityKindsWithoutGameplayEffects(){var kinds=new[]{CityBuildingKind.Barracks,CityBuildingKind.TrainingGround,CityBuildingKind.Arsenal,CityBuildingKind.CavalryStables,CityBuildingKind.GuardFacilities,CityBuildingKind.CultureSpecificMilitaryTraining};Assert.That(kinds.All(x=>CityBuildingRules.RequiredArea(x)==CityAreaType.Military),Is.True);Assert.That(typeof(CityBuildingDefinition).GetProperty("CombatBonus"),Is.Null);}
        [Test]public void Infrastructure_IsNeitherAreaNorBuildingAndSupportsExactTypes(){Assert.That(typeof(CityAreaState).IsAssignableFrom(typeof(CityInfrastructureState)),Is.False);Assert.That(typeof(CityBuildingDefinition).IsAssignableFrom(typeof(CityInfrastructureState)),Is.False);Assert.That(Enum.GetNames(typeof(CityInfrastructureType)),Is.EqualTo(new[]{"Well","Fountain","Cistern","WaterChannel","MainPavedRoad","SecondaryRoad","BridgeCrossing","DrainageLine","WasteSewageChannel"}));}
        [Test]public void Metrics_RejectInventedNegativePopulationAndExposeNoNumericScale(){Assert.Throws<ArgumentOutOfRangeException>(()=>new CityMetricsState(-1));var metrics=new CityMetricsState(10);Assert.That(metrics.Order,Is.EqualTo(CityMetricAssessment.Unassessed));Assert.That(Enum.GetNames(typeof(CityMetricAssessment)),Is.EqualTo(new[]{"Unassessed"}));}
        [Test]public void Kethuda_UsesRealRemoteCapableCharacterAssignmentWithoutSideEffects(){var setup=OfficialSetup(false);var character=setup.Characters.GetRequired(CharacterId.Create("official"));var loyalty=character.CurrentLoyalty.Value;var houses=new HouseRegistry();var cliques=new CliqueRegistry();var religion=new ReligionCampaignState();new CityCommandService(setup.Cities,setup.Characters,setup.Organizations).AddKethuda(CityId.Create("city-main"),OrganizationId.Create("org"),AssignmentId.Create("kethuda"));Assert.That(setup.Cities.GetRequired(CityId.Create("city-main")).OrderedOfficials.Count,Is.EqualTo(1));Assert.That(character.Id.Value,Is.EqualTo("official"));Assert.That(character.CurrentLoyalty.Value,Is.EqualTo(loyalty));Assert.That(setup.Organizations.GetRequired(OrganizationId.Create("org")).Memberships,Is.Empty);Assert.That(houses.Count,Is.Zero);Assert.That(cliques.Count,Is.Zero);Assert.That(religion.Characters.OrderedStates,Is.Empty);}
        [Test]public void Kethuda_RejectsFakeCharacterReference(){var setup=OfficialSetup(true);Assert.Throws<System.Collections.Generic.KeyNotFoundException>(()=>new CityCommandService(setup.Cities,setup.Characters,setup.Organizations).AddKethuda(CityId.Create("city-main"),OrganizationId.Create("org"),AssignmentId.Create("kethuda")));}
        [Test]public void Kethuda_RejectsCaptiveCharacter(){var setup=OfficialSetup(false);setup.Characters.GetRequired(CharacterId.Create("official")).Capture(new CaptivityState(CharacterId.Create("captor"),CaptivitySite.InCity(CityId.Create("other-city"))),new FOC.Domain.Time.WorldTimestamp(1));Assert.Throws<InvalidOperationException>(()=>new CityCommandService(setup.Cities,setup.Characters,setup.Organizations).AddKethuda(CityId.Create("city-main"),OrganizationId.Create("org"),AssignmentId.Create("kethuda")));}
        [Test]public void Kethuda_RejectsDeadCharacter(){var setup=OfficialSetup(false);var death=new CharacterCommandService(setup.Characters,new FOC.Domain.Time.WorldClock(new FOC.Domain.Time.WorldTimestamp(1)),new FOC.Domain.Random.SeededRandomSource(1),new ImportanceStoryGuardDeathPolicy()).Kill(CharacterId.Create("official"),CharacterDeathCause.Battle,CharacterLocation.InCity(CityId.Create("city-main")),"Died in battle.");Assert.That(death.Success,Is.True);Assert.Throws<InvalidOperationException>(()=>new CityCommandService(setup.Cities,setup.Characters,setup.Organizations).AddKethuda(CityId.Create("city-main"),OrganizationId.Create("org"),AssignmentId.Create("kethuda")));}
        [Test]public void CityReligionProfile_RequiresRealCityAndPreservesMultiReligionWithoutOrderEffect(){var cities=new CityRegistry();cities.Add(CityTestFactory.State());var profile=new ReligionProfile(ReligionProfileTarget.City(CityId.Create("city-main")));profile.Add(new ReligionProfileEntry(ReligionId.Create("a"),null,2));profile.Add(new ReligionProfileEntry(ReligionId.Create("b"),null,1));var order=cities.GetRequired(CityId.Create("city-main")).Metrics.Order;Assert.DoesNotThrow(()=>CityReligionIntegrationRules.RequireRealCityProfile(profile,cities));Assert.Throws<System.Collections.Generic.KeyNotFoundException>(()=>CityReligionIntegrationRules.RequireRealCityProfile(new ReligionProfile(ReligionProfileTarget.City(CityId.Create("missing"))),cities));Assert.That(profile.Entries.Count,Is.EqualTo(2));Assert.That(new ReligionDifferenceAssessment(true).AutomaticUnrest,Is.False);Assert.That(cities.GetRequired(CityId.Create("city-main")).Metrics.Order,Is.EqualTo(order));}
        private static Setup OfficialSetup(bool fakeCharacter)
        {
            var cities=new CityRegistry();cities.Add(CityTestFactory.State());var characters=new CharacterRoster();if(!fakeCharacter)characters.Add(CharacterTestFactory.Named("official"));var organizations=new OrganizationRegistry();var organization=new OrganizationState(OrganizationId.Create("org"),"Organization");organization.AddAssignment(new AssignmentState(AssignmentId.Create("kethuda"),CharacterId.Create("official"),OrganizationBranch.Settlements,CityOfficialRoles.KethudaAssignmentRoleCode,AssignmentAuthority.Responsible,AssignmentTarget.City(CityId.Create("city-main")),AssignmentPresence.RemoteCapable,new FOC.Domain.Time.WorldTimestamp(0)));organizations.Add(organization);return new Setup(cities,characters,organizations);
        }
        private sealed class Setup{public Setup(CityRegistry cities,CharacterRoster characters,OrganizationRegistry organizations){Cities=cities;Characters=characters;Organizations=organizations;}public CityRegistry Cities{get;}public CharacterRoster Characters{get;}public OrganizationRegistry Organizations{get;}}
    }
}
