using System.Linq;
using FOC.Application.Cities;
using FOC.Application.Save;
using FOC.Domain.Campaign;
using FOC.Domain.Characters;
using FOC.Domain.Cities;
using FOC.Domain.Common;
using FOC.Domain.Organizations;
using FOC.Domain.Random;
using FOC.Domain.Religion;
using FOC.Domain.Time;
using FOC.Infrastructure.Save;
using NUnit.Framework;

namespace FOC.Tests
{
    public sealed class CitySaveTests
    {
        [Test]public void SchemaFive_SemanticRoundTripPreservesCityStateAndReferences(){var serializer=new CampaignSaveTextSerializer();var text=serializer.Serialize(CampaignSaveMapper.ToSaveData(Runtime(false)));var read=serializer.Deserialize(text);Assert.That(read.Success,Is.True,read.Error);Assert.That(new CampaignSaveValidator().Validate(read.Data!).IsValid,Is.True);var restored=CampaignSaveMapper.ToRuntimeState(read.Data!);var city=restored.Cities.GetRequired(CityId.Create("city-main"));Assert.That(city.Metrics.PopulationCount,Is.EqualTo(1250));Assert.That(city.GetRequiredArea(CityAreaType.InnerCastle).Fullness,Is.EqualTo(CityAreaFullness.Full));Assert.That(city.GetRequiredArea(CityAreaType.Trade).OrderedActiveBuildings.Single().Id.Value,Is.EqualTo("market"));Assert.That(city.GetRequiredArea(CityAreaType.Trade).OrderedLockedBuildingIds.Single().Value,Is.EqualTo("removed-bedesten"));Assert.That(city.GetRequiredArea(CityAreaType.Housing).Definition.VisualVariantHook,Is.EqualTo("future-housing-variant"));Assert.That(city.OrderedInfrastructure.Single().Type,Is.EqualTo(CityInfrastructureType.Cistern));Assert.That(city.OrderedOfficials.Single().AssignmentId.Value,Is.EqualTo("kethuda"));Assert.That(restored.Religion.OrderedProfiles.Single().Target.Id,Is.EqualTo("city-main"));}
        [Test]public void SchemaFiveSerialization_IsDeterministicAcrossDefinitionInsertionOrder(){var serializer=new CampaignSaveTextSerializer();Assert.That(serializer.Serialize(CampaignSaveMapper.ToSaveData(Runtime(false))),Is.EqualTo(serializer.Serialize(CampaignSaveMapper.ToSaveData(Runtime(true)))));}
        [Test]public void HardcodedSchemaFourFixture_MigratesWithoutInventingCity(){const string fixture="FOC_CAMPAIGN_SAVE\nSaveVersion=4\nCampaignId=Y2FtcGFpZ24tbGVnYWN5\nGameVersion=MC4wLjQ=\nContentDataVersion=cmVsaWdpb24tMQ==\nWorldSeed=1648\nWorldGenRevision=1\nWorldTime=9\nRngState=123\nRngDrawCount=2\nCharacterCount=0\nCharacterRelationCount=0\nSocialState=AAAAAAAAAAAAAAAA\nReligionState=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n";var read=new CampaignSaveTextSerializer().Deserialize(fixture);Assert.That(read.Success,Is.True,read.Error);var migrated=new CampaignSaveV4ToV5Migration().Apply(read.Data!);Assert.That(migrated.SaveVersion,Is.EqualTo(5));Assert.That(migrated.Cities,Is.Empty);Assert.That(migrated.Religions,Is.Empty);Assert.That(migrated.Organizations,Is.Empty);}
        [Test]public void FullMigrationChain_ReachesFiveWithNoInventedCity(){var source=new CampaignSaveData{SaveVersion=1,CampaignId="legacy",GameVersion="0.1",ContentDataVersion="one",WorldSeed=1,RngState=1};var pipeline=new SaveMigrationPipeline(new ISaveMigration[]{new CampaignSaveV1ToV2Migration(),new CampaignSaveV2ToV3Migration(),new CampaignSaveV3ToV4Migration(),new CampaignSaveV4ToV5Migration()});var result=pipeline.Migrate(source,5);Assert.That(result.Success,Is.True,result.Error);Assert.That(result.Data!.Cities,Is.Empty);Assert.That(result.Data.Characters,Is.Empty);Assert.That(result.Data.Religions,Is.Empty);}
        [Test]public void MigrationFourToFive_PreservesCharacterSocialAndReligionData(){var source=CampaignSaveMapper.ToSaveData(Runtime(false));source.SaveVersion=4;var migrated=new CampaignSaveV4ToV5Migration().Apply(source);Assert.That(migrated.Characters.Single().CharacterId,Is.EqualTo("official"));Assert.That(migrated.Organizations.Single().OrganizationId,Is.EqualTo("org"));Assert.That(migrated.Religions.Single().ReligionId,Is.EqualTo("faith"));Assert.That(migrated.ReligionProfiles.Single().TargetId,Is.EqualTo("city-main"));Assert.That(migrated.Cities,Is.Empty);}
        [Test]public void SaveDataAndRuntimeCityTypes_RemainSeparate(){Assert.That(typeof(CitySaveData).IsAssignableFrom(typeof(CityState)),Is.False);Assert.That(typeof(CityAreaSaveData).IsAssignableFrom(typeof(CityAreaState)),Is.False);Assert.That(typeof(CityInfrastructureSaveData).IsAssignableFrom(typeof(CityInfrastructureState)),Is.False);}
        [Test]public void SaveValidator_RejectsDanglingCityOfficialAssignment(){var data=CampaignSaveMapper.ToSaveData(Runtime(false));data.Cities.Single().Officials.Single().AssignmentId="missing";Assert.That(new CampaignSaveValidator().Validate(data).IsValid,Is.False);}
        private static CampaignRuntimeState Runtime(bool reverse)
        {
            var roster=new CharacterRoster();roster.Add(CharacterTestFactory.Named("official"));var organizations=new OrganizationRegistry();var organization=new OrganizationState(OrganizationId.Create("org"),"Organization");organization.AddAssignment(new AssignmentState(AssignmentId.Create("kethuda"),CharacterId.Create("official"),OrganizationBranch.Settlements,CityOfficialRoles.KethudaAssignmentRoleCode,AssignmentAuthority.Responsible,AssignmentTarget.City(CityId.Create("city-main")),AssignmentPresence.RemoteCapable,new WorldTimestamp(0)));organizations.Add(organization);var cities=new CityRegistry();var city=new CityState(CityTestFactory.Definition("city-main",reverse),new CityMetricsState(1250));city.GetRequiredArea(CityAreaType.Trade).SetFullness(CityAreaFullness.Low);city.GetRequiredArea(CityAreaType.Trade).ActivateBuilding(CityBuildingId.Create("market"));city.GetRequiredArea(CityAreaType.Trade).LockBuilding(CityBuildingId.Create("removed-bedesten"));city.SetInfrastructure(new CityInfrastructureState(CityInfrastructureType.Cistern,true,CityInfrastructureCondition.Serviceable));city.AddOfficial(new CityOfficialReference(CityOfficialRole.Kethuda,OrganizationId.Create("org"),AssignmentId.Create("kethuda")));cities.Add(city);var definitions=new ReligionRegistry();definitions.AddReligion(new ReligionDefinition(ReligionId.Create("faith"),"Faith"));var religion=new ReligionCampaignState(definitions);var profile=new ReligionProfile(ReligionProfileTarget.City(CityId.Create("city-main")));profile.Add(new ReligionProfileEntry(ReligionId.Create("faith"),null,1));religion.AddProfile(profile);return new CampaignRuntimeState(StableId<CampaignTag>.Create("campaign"),"0.4","city-1",10,1,new WorldClock(new WorldTimestamp(0)),new SeededRandomSource(10),roster,organizations,null,null,religion,cities);
        }
    }
}
