using System;
using System.Linq;
using FOC.Application.Characters;
using FOC.Application.Diplomacy;
using FOC.Application.Save;
using FOC.Domain.Campaign;
using FOC.Domain.Characters;
using FOC.Domain.Common;
using FOC.Domain.Diplomacy;
using FOC.Domain.Organizations;
using FOC.Domain.Random;
using FOC.Domain.Religion;
using FOC.Domain.Time;
using FOC.Domain.Validation;
using FOC.Infrastructure.Save;
using NUnit.Framework;

namespace FOC.Tests
{
    public sealed class DiplomacyEnvoyReportTests
    {
        [Test]public void RelationPair_IsCanonicalAndDuplicatePairRejected(){var d=new DiplomacyState();Actors(d);var first=new DiplomaticRelationState(new DiplomaticActorPair(FactionId.Create("b"),FactionId.Create("a")),DiplomaticDisposition.Neutral,T(0));d.Relations.Add(first);Assert.That(first.Pair.First.Value,Is.EqualTo("a"));Assert.That(first.Pair.Second.Value,Is.EqualTo("b"));Assert.Throws<InvalidOperationException>(()=>d.Relations.Add(new DiplomaticRelationState(new DiplomaticActorPair(FactionId.Create("a"),FactionId.Create("b")),DiplomaticDisposition.Cordial,T(1))));}
        [Test]public void RelationFactors_AreSeparateExplicitAndDeterministicallyOrdered(){var relation=new DiplomaticRelationState(new DiplomaticActorPair(FactionId.Create("a"),FactionId.Create("b")),DiplomaticDisposition.Neutral,T(0));relation.AddFactor(new DiplomaticFactor("trade",DiplomaticFactorSource.TradeRelationship,DiplomaticFactorDirection.Positive,T(2)));relation.AddFactor(new DiplomaticFactor("insult",DiplomaticFactorSource.Insult,DiplomaticFactorDirection.Negative,T(1)));Assert.That(relation.OrderedFactors.Select(x=>x.Source),Is.EqualTo(new[]{DiplomaticFactorSource.Insult,DiplomaticFactorSource.TradeRelationship}));Assert.That(relation.Disposition,Is.EqualTo(DiplomaticDisposition.Neutral));}
        [Test]public void DifferentReligionOrSectAloneCreatesNoHostilityOrFactor(){var s=Setup();var definitions=new ReligionRegistry();definitions.AddReligion(new ReligionDefinition(ReligionId.Create("faith-a"),"A"));definitions.AddReligion(new ReligionDefinition(ReligionId.Create("faith-b"),"B"));definitions.AddSect(new SectDefinition(SectId.Create("sect-a"),ReligionId.Create("faith-a"),"Sect A"));var religion=new ReligionCampaignState(definitions);var a=new ReligionProfile(ReligionProfileTarget.Faction(FactionId.Create("a")));a.Add(new ReligionProfileEntry(ReligionId.Create("faith-a"),SectId.Create("sect-a"),1));var b=new ReligionProfile(ReligionProfileTarget.Faction(FactionId.Create("b")));b.Add(new ReligionProfileEntry(ReligionId.Create("faith-b"),null,1));religion.AddProfile(a);religion.AddProfile(b);Assert.That(s.Relation.Disposition,Is.EqualTo(DiplomaticDisposition.Neutral));Assert.That(s.Relation.OrderedFactors,Is.Empty);}
        [Test]public void Envoy_IsNormalCharacterWithDiplomacyAssignmentNotSubtype(){var s=Setup();Assert.That(s.Mission.CharacterId,Is.EqualTo(CharacterId.Create("envoy")));Assert.That(s.Runtime.Characters.GetRequired(s.Mission.CharacterId),Is.TypeOf<CharacterState>());Assert.That(typeof(CharacterState).IsAssignableFrom(typeof(EnvoyMissionState)),Is.False);Assert.That(s.Mission.AssignmentId.Value,Is.EqualTo("envoy-assignment"));}
        [Test]public void FakeDeadOrCaptiveEnvoyCannotRegisterOrArrive(){var captive=Setup(register:false);captive.Runtime.Characters.GetRequired(CharacterId.Create("envoy")).Capture(new CaptivityState(CharacterId.Create("messenger"),CaptivitySite.InCity(CityId.Create("prison"))),T(1));Assert.Throws<InvalidOperationException>(()=>new DiplomacyCommandService(captive.Runtime).RegisterOrder(captive.Mission,captive.Message,captive.Action));var dead=Setup();var result=new CharacterCommandService(dead.Runtime.Characters,new WorldClock(T(1)),new SeededRandomSource(1),new ImportanceStoryGuardDeathPolicy()).Kill(CharacterId.Create("envoy"),CharacterDeathCause.Battle,CharacterLocation.InCity(CityId.Create("city-home")),"Battle death");Assert.That(result.Success,Is.True);MoveTo(dead,4);Assert.Throws<InvalidOperationException>(()=>new DiplomacyCommandService(dead.Runtime).Arrive(dead.Mission.Id,T(4)));}
        [Test]public void ConcludeMandateRequiresFullAuthority(){var s=Setup(register:false,authority:AssignmentAuthority.Responsible,scope:DiplomaticAuthorityScope.Conclude,kind:DiplomaticActionKind.Peace);Assert.Throws<InvalidOperationException>(()=>new DiplomacyCommandService(s.Runtime).RegisterOrder(s.Mission,s.Message,s.Action));}
        [Test]public void MissionCannotArriveSameTickAndCannotCompleteTwice(){var s=Setup();var service=new DiplomacyCommandService(s.Runtime);MoveTo(s,2);service.Dispatch(s.Action.Id,T(2));Assert.Throws<InvalidOperationException>(()=>service.Arrive(s.Mission.Id,T(2)));MoveTo(s,3);service.Arrive(s.Mission.Id,T(3));s.Mission.BeginReturn();s.Mission.Complete(T(5));Assert.Throws<InvalidOperationException>(()=>s.Mission.Complete(T(6)));}
        [Test]public void PausedWorldClockCannotAdvanceDiplomaticCommunication(){var s=Setup();var service=new DiplomacyCommandService(s.Runtime);s.Runtime.Clock.Pause();Assert.Throws<InvalidOperationException>(()=>service.Dispatch(s.Action.Id,T(1)));Assert.That(s.Mission.Phase,Is.EqualTo(EnvoyMissionPhase.PendingDeparture));s.Runtime.Clock.Resume();MoveTo(s,1);service.Dispatch(s.Action.Id,T(1));Assert.That(s.Mission.Phase,Is.EqualTo(EnvoyMissionPhase.Travelling));}
        [Test]public void MessageChronologyWrongRecipientAndDuplicateDeliveryAreRejected(){var message=MessengerMessage();Assert.Throws<InvalidOperationException>(()=>message.Deliver(FactionId.Create("b"),T(1)));message.Dispatch(T(1));Assert.Throws<InvalidOperationException>(()=>message.Deliver(FactionId.Create("a"),T(2)));message.Deliver(FactionId.Create("b"),T(2));Assert.Throws<InvalidOperationException>(()=>message.Deliver(FactionId.Create("b"),T(3)));}
        [Test]public void MessengerAndEnvoyCarrierContractsRemainDistinct(){var messenger=MessengerMessage();Assert.That(messenger.CarrierKind,Is.EqualTo(MessageCarrierKind.MessengerCharacter));Assert.That(messenger.EnvoyMissionId,Is.Null);Assert.Throws<ArgumentException>(()=>new DiplomaticMessageState(DiplomaticMessageId.Create("bad"),FactionId.Create("a"),FactionId.Create("b"),MessageKind.Proposal,MessageCarrierKind.MessengerCharacter,CharacterId.Create("messenger"),T(0),EnvoyMissionId.Create("mission")));}
        [Test]public void ActionCannotResolveBeforeDeliveryOrTwice(){var s=Setup();var service=new DiplomacyCommandService(s.Runtime);MoveTo(s,1);service.Dispatch(s.Action.Id,T(1));MoveTo(s,2);Assert.Throws<InvalidOperationException>(()=>service.DeliverAndResolve(s.Action.Id,DiplomaticActionOutcome.Accepted,T(2)));MoveTo(s,3);service.Arrive(s.Mission.Id,T(3));MoveTo(s,4);service.DeliverAndResolve(s.Action.Id,DiplomaticActionOutcome.Accepted,T(4));Assert.That(s.Action.Outcome,Is.EqualTo(DiplomaticActionOutcome.Accepted));MoveTo(s,5);Assert.Throws<InvalidOperationException>(()=>service.DeliverAndResolve(s.Action.Id,DiplomaticActionOutcome.Accepted,T(5)));}
        [Test]public void ReportChronologyAndStalenessAreDeterministic(){var report=Report();Assert.That(report.StalenessAt(T(10)),Is.EqualTo(8));Assert.Throws<InvalidOperationException>(()=>report.Dispatch(T(1)));report.Dispatch(T(3));Assert.That(report.StalenessAt(T(10)),Is.EqualTo(8));}
        [Test]public void UndeliveredReportIsUnavailableAndDuplicateDeliveryRejected(){var s=Setup();var report=Report();s.Runtime.Diplomacy.Reports.Add(report);var delivery=new ReportDeliveryService(s.Runtime);Assert.Throws<System.Collections.Generic.KeyNotFoundException>(()=>s.InfoA.GetRequired(report.Id));MoveTo(s,3);delivery.Dispatch(report.Id,T(3));MoveTo(s,6);delivery.Deliver(report.Id,FactionId.Create("a"),T(6));Assert.That(s.InfoA.GetRequired(report.Id),Is.SameAs(report));MoveTo(s,7);Assert.Throws<InvalidOperationException>(()=>delivery.Deliver(report.Id,FactionId.Create("a"),T(7)));}
        [Test]public void LowQualityDoesNotAlterOrRandomizeObservation(){var report=Report(ReportQuality.Low);var observation=report.OrderedObservations.Single();Assert.That(observation.Precision,Is.EqualTo(ObservationPrecision.Range));Assert.That(observation.Lower,Is.EqualTo(10));Assert.That(observation.Upper,Is.EqualTo(20));Assert.That(report.OrderedObservations.Single().Lower,Is.EqualTo(10));}
        [Test]public void OldObservationRemainsOldAfterLaterArrival(){var s=Setup();var report=Report();s.Runtime.Diplomacy.Reports.Add(report);var delivery=new ReportDeliveryService(s.Runtime);MoveTo(s,4);delivery.Dispatch(report.Id,T(4));MoveTo(s,9);delivery.Deliver(report.Id,FactionId.Create("a"),T(9));Assert.That(report.ObservedAt.Ticks,Is.EqualTo(2));Assert.That(report.ArrivedAt!.Value.Ticks,Is.EqualTo(9));Assert.That(report.StalenessAt(T(12)),Is.EqualTo(10));}
        [Test]public void InvalidInstitutionSourceDoesNotInventBonusAndFailsInvariant(){var s=Setup();var report=new ReportState(ReportId.Create("institution-report"),ReportType.Diplomatic,ReportSourceRef.Institution(CityId.Create("missing"),FOC.Domain.Cities.CityBuildingId.Create("chief-scribe")),FactionId.Create("a"),ReportQuality.High,ReportDetailLevel.Detailed,T(1),new[]{Observation()});s.Runtime.Diplomacy.Reports.Add(report);Assert.That(new DiplomacyInvariantValidator().Validate(s.Runtime).IsValid,Is.False);Assert.That(typeof(ReportSourceRef).GetProperties().Any(x=>x.PropertyType==typeof(double)||x.PropertyType==typeof(float)),Is.False);}
        [Test]public void DiplomacyDoesNotMutateEconomyWithoutExplicitEconomyHook(){var s=Setup();var before=s.Runtime.Economy.Goods.Count;var service=new DiplomacyCommandService(s.Runtime);MoveTo(s,1);service.Dispatch(s.Action.Id,T(1));MoveTo(s,3);service.Arrive(s.Mission.Id,T(3));MoveTo(s,4);service.DeliverAndResolve(s.Action.Id,DiplomaticActionOutcome.Accepted,T(4));Assert.That(s.Runtime.Economy.Goods.Count,Is.EqualTo(before));}
        [Test]public void AgreementIsPersistentResultNotOfferAndExpiryIsExplicit(){var agreement=new DiplomaticAgreementState(DiplomaticAgreementId.Create("agreement"),new DiplomaticActorPair(FactionId.Create("a"),FactionId.Create("b")),DiplomaticAgreementKind.TradeAgreement,T(2),T(3),new[]{new DiplomaticAgreementTerm(DiplomaticAgreementTermKind.MarketAccess)},T(8));Assert.That(agreement.IsEffectiveAt(T(7)),Is.True);Assert.That(agreement.IsEffectiveAt(T(8)),Is.False);Assert.That(typeof(DiplomaticAgreementState),Is.Not.EqualTo(typeof(DiplomaticActionState)));}
        [Test]public void VerticalSlice_OrderTravelsArrivesResolvesAndReturnsStaleReport(){var s=Setup();var commands=new DiplomacyCommandService(s.Runtime);MoveTo(s,1);commands.Dispatch(s.Action.Id,T(1));MoveTo(s,4);commands.Arrive(s.Mission.Id,T(4));MoveTo(s,5);commands.DeliverAndResolve(s.Action.Id,DiplomaticActionOutcome.Accepted,T(5));var response=MessengerMessage("response",FactionId.Create("b"),FactionId.Create("a"),MessageKind.Response);s.Runtime.Diplomacy.Messages.Add(response);response.Dispatch(T(6));response.Deliver(FactionId.Create("a"),T(9));var report=Report();s.Runtime.Diplomacy.Reports.Add(report);var reports=new ReportDeliveryService(s.Runtime);MoveTo(s,6);reports.Dispatch(report.Id,T(6));MoveTo(s,10);reports.Deliver(report.Id,FactionId.Create("a"),T(10));Assert.That(s.Action.Status,Is.EqualTo(DiplomaticActionStatus.Resolved));Assert.That(response.DeliveredAt!.Value.Ticks,Is.EqualTo(9));Assert.That(s.InfoA.GetRequired(report.Id).ObservedAt.Ticks,Is.EqualTo(2));Assert.That(report.StalenessAt(T(10)),Is.EqualTo(8));}
        [Test]public void SchemaSevenRoundTripPreservesDiplomacyCommunicationAndKnowledge(){var s=Populated();var serializer=new CampaignSaveTextSerializer();var text=serializer.Serialize(CampaignSaveMapper.ToSaveData(s.Runtime));var read=serializer.Deserialize(text);Assert.That(read.Success,Is.True,read.Error);Assert.That(new CampaignSaveValidator().Validate(read.Data!).IsValid,Is.True);var restored=CampaignSaveMapper.ToRuntimeState(read.Data!);Assert.That(restored.Diplomacy.Actors.OrderedActors.Count,Is.EqualTo(2));Assert.That(restored.Diplomacy.Relations.OrderedRelations.Single().OrderedFactors.Count,Is.EqualTo(1));Assert.That(restored.Diplomacy.Missions.OrderedMissions.Single().CompletedAt!.Value.Ticks,Is.EqualTo(12));Assert.That(restored.Diplomacy.Messages.OrderedMessages.Count,Is.EqualTo(2));Assert.That(restored.Diplomacy.Reports.OrderedReports.Single().ObservedAt.Ticks,Is.EqualTo(2));Assert.That(restored.Diplomacy.Information.GetRequired(FactionId.Create("a")).OrderedAvailableReports.Count,Is.EqualTo(1));Assert.That(restored.Diplomacy.Agreements.OrderedAgreements.Count,Is.EqualTo(1));}
        [Test]public void SaveValidatorRejectsFakeDiplomaticActorReference(){var data=CampaignSaveMapper.ToSaveData(Populated().Runtime);data.EnvoyMissions.Single().TargetActorId="missing";Assert.That(new CampaignSaveValidator().Validate(data).IsValid,Is.False);}
        [Test]public void DiplomacySerializationIsCanonicalAcrossInsertionOrder(){var a=Populated(false);var b=Populated(true);var serializer=new CampaignSaveTextSerializer();Assert.That(serializer.Serialize(CampaignSaveMapper.ToSaveData(a.Runtime)),Is.EqualTo(serializer.Serialize(CampaignSaveMapper.ToSaveData(b.Runtime))));}
        [Test]public void HardcodedSchemaSixFixtureMigratesWithoutInventingDiplomacy(){const string fixture="FOC_CAMPAIGN_SAVE\nSaveVersion=6\nCampaignId=Y2FtcGFpZ24tbGVnYWN5\nGameVersion=MC4wLjY=\nContentDataVersion=ZWNvbm9teS0x\nWorldSeed=1648\nWorldGenRevision=1\nWorldTime=9\nRngState=123\nRngDrawCount=2\nCharacterCount=0\nCharacterRelationCount=0\nSocialState=AAAAAAAAAAAAAAAA\nReligionState=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nCityState=AAAAAA==\nEconomyState=AAAAAAAAAAAAAAAAAAAAAA==\n";var read=new CampaignSaveTextSerializer().Deserialize(fixture);Assert.That(read.Success,Is.True,read.Error);var migrated=new CampaignSaveV6ToV7Migration().Apply(read.Data!);Assert.That(migrated.SaveVersion,Is.EqualTo(7));Assert.That(migrated.DiplomaticActors,Is.Empty);Assert.That(migrated.Reports,Is.Empty);Assert.That(migrated.TradeGoods,Is.Empty);}
        [Test]public void FullMigrationChainReachesSevenWithoutInventingDiplomacy(){var source=new CampaignSaveData{SaveVersion=1,CampaignId="legacy",GameVersion="0.1",ContentDataVersion="one",WorldSeed=1,RngState=1};var pipeline=new SaveMigrationPipeline(new ISaveMigration[]{new CampaignSaveV1ToV2Migration(),new CampaignSaveV2ToV3Migration(),new CampaignSaveV3ToV4Migration(),new CampaignSaveV4ToV5Migration(),new CampaignSaveV5ToV6Migration(),new CampaignSaveV6ToV7Migration()});var result=pipeline.Migrate(source,7);Assert.That(result.Success,Is.True,result.Error);Assert.That(result.Data!.DiplomaticActors,Is.Empty);Assert.That(result.Data.EnvoyMissions,Is.Empty);Assert.That(result.Data.Reports,Is.Empty);}
        [Test]public void SaveDataAndRuntimeDiplomacyTypesRemainSeparate(){Assert.That(typeof(DiplomaticRelationSaveData).IsAssignableFrom(typeof(DiplomaticRelationState)),Is.False);Assert.That(typeof(ReportSaveData).IsAssignableFrom(typeof(ReportState)),Is.False);Assert.That(typeof(CampaignSaveData).IsAssignableFrom(typeof(DiplomacyState)),Is.False);}

        private sealed class SetupData{public CampaignRuntimeState Runtime=null!;public DiplomaticRelationState Relation=null!;public EnvoyMissionState Mission=null!;public DiplomaticMessageState Message=null!;public DiplomaticActionState Action=null!;public ActorInformationState InfoA=null!;}
        private static SetupData Setup(bool reverse=false,bool register=true,AssignmentAuthority authority=AssignmentAuthority.FullAuthority,DiplomaticAuthorityScope scope=DiplomaticAuthorityScope.Negotiate,DiplomaticActionKind kind=DiplomaticActionKind.Demand)
        {var characters=new CharacterRoster();var envoy=CharacterTestFactory.Named("envoy");var messenger=CharacterTestFactory.Named("messenger");if(reverse){characters.Add(messenger);characters.Add(envoy);}else{characters.Add(envoy);characters.Add(messenger);}var organizations=new OrganizationRegistry();var org=new OrganizationState(OrganizationId.Create("diplomacy-org"),"Diplomacy Organization");org.AddAssignment(new AssignmentState(AssignmentId.Create("envoy-assignment"),envoy.Id,OrganizationBranch.Diplomacy,"temporary-envoy",authority,AssignmentTarget.Organization(OrganizationId.Create("diplomacy-org")),AssignmentPresence.RemoteCapable,T(0)));organizations.Add(org);var diplomacy=new DiplomacyState();Actors(diplomacy,reverse);var relation=new DiplomaticRelationState(new DiplomaticActorPair(FactionId.Create("a"),FactionId.Create("b")),DiplomaticDisposition.Neutral,T(0));diplomacy.Relations.Add(relation);var infoA=new ActorInformationState(FactionId.Create("a"));var infoB=new ActorInformationState(FactionId.Create("b"));if(reverse){diplomacy.Information.Add(infoB);diplomacy.Information.Add(infoA);}else{diplomacy.Information.Add(infoA);diplomacy.Information.Add(infoB);}var runtime=new CampaignRuntimeState(StableId<CampaignTag>.Create("campaign"),"0.6","diplomacy-1",66,1,new WorldClock(T(0)),new SeededRandomSource(66),characters,organizations,null,null,null,null,null,diplomacy);var mandate=new DiplomaticMandate(scope,new[]{kind});var mission=new EnvoyMissionState(EnvoyMissionId.Create("mission"),envoy.Id,org.Id,AssignmentId.Create("envoy-assignment"),FactionId.Create("a"),FactionId.Create("b"),EnvoyMissionType.DeliverDemand,mandate,T(0));var message=new DiplomaticMessageState(DiplomaticMessageId.Create("message"),FactionId.Create("a"),FactionId.Create("b"),MessageKind.Demand,MessageCarrierKind.EnvoyMission,envoy.Id,T(0),mission.Id);var action=new DiplomaticActionState(DiplomaticActionId.Create("action"),FactionId.Create("a"),FactionId.Create("b"),kind,mission.Id,message.Id,T(0));if(register)new DiplomacyCommandService(runtime).RegisterOrder(mission,message,action);return new SetupData{Runtime=runtime,Relation=relation,Mission=mission,Message=message,Action=action,InfoA=infoA};}
        private static SetupData Populated(bool reverse=false){var s=Setup(reverse);s.Relation.AddFactor(new DiplomaticFactor("trade",DiplomaticFactorSource.TradeRelationship,DiplomaticFactorDirection.Positive,T(1)));var commands=new DiplomacyCommandService(s.Runtime);MoveTo(s,2);commands.Dispatch(s.Action.Id,T(2));MoveTo(s,5);commands.Arrive(s.Mission.Id,T(5));MoveTo(s,6);commands.DeliverAndResolve(s.Action.Id,DiplomaticActionOutcome.Accepted,T(6));s.Mission.BeginReturn();var response=MessengerMessage("response",FactionId.Create("b"),FactionId.Create("a"),MessageKind.Response);s.Runtime.Diplomacy.Messages.Add(response);response.Dispatch(T(7));response.Deliver(FactionId.Create("a"),T(9));var report=Report();s.Runtime.Diplomacy.Reports.Add(report);var delivery=new ReportDeliveryService(s.Runtime);delivery.Dispatch(report.Id,T(6));MoveTo(s,10);delivery.Deliver(report.Id,FactionId.Create("a"),T(10));MoveTo(s,12);s.Mission.Complete(T(12));s.Runtime.Diplomacy.Agreements.Add(new DiplomaticAgreementState(DiplomaticAgreementId.Create("agreement"),new DiplomaticActorPair(FactionId.Create("a"),FactionId.Create("b")),DiplomaticAgreementKind.TradeAgreement,T(6),T(7),new[]{new DiplomaticAgreementTerm(DiplomaticAgreementTermKind.MarketAccess)},T(20)));return s;}
        private static void Actors(DiplomacyState d,bool reverse=false){var a=new DiplomaticActorState(FactionId.Create("a"),"Actor A");var b=new DiplomaticActorState(FactionId.Create("b"),"Actor B");if(reverse){d.Actors.Add(b);d.Actors.Add(a);}else{d.Actors.Add(a);d.Actors.Add(b);}}
        private static DiplomaticMessageState MessengerMessage(string id="messenger-message",FactionId? sender=null,FactionId? recipient=null,MessageKind kind=MessageKind.Response)=>new DiplomaticMessageState(DiplomaticMessageId.Create(id),sender??FactionId.Create("a"),recipient??FactionId.Create("b"),kind,MessageCarrierKind.MessengerCharacter,CharacterId.Create("messenger"),T(0));
        private static ReportState Report(ReportQuality quality=ReportQuality.Low)=>new ReportState(ReportId.Create("report"),ReportType.Diplomatic,ReportSourceRef.Character(ReportSourceKind.Envoy,CharacterId.Create("envoy")),FactionId.Create("a"),quality,ReportDetailLevel.Summary,T(2),new[]{Observation()});
        private static ReportObservation Observation()=>new ReportObservation(new ReportSubjectRef(ReportSubjectKind.Faction,"b"),ReportObservationKind.DiplomaticDisposition,ObservationPrecision.Range,10,20);
        private static WorldTimestamp T(long ticks)=>new WorldTimestamp(ticks);
        private static void MoveTo(SetupData s,long ticks){var delta=ticks-s.Runtime.Clock.Now.Ticks;if(delta<0)throw new InvalidOperationException("Cannot rewind test clock.");if(delta>0)s.Runtime.Clock.Advance(new WorldDuration(delta));}
    }
}
