using System;
using System.Linq;
using FOC.Application.Economy;
using FOC.Application.Save;
using FOC.Domain.Campaign;
using FOC.Domain.Characters;
using FOC.Domain.Cities;
using FOC.Domain.Common;
using FOC.Domain.Economy;
using FOC.Domain.Organizations;
using FOC.Domain.Random;
using FOC.Domain.Time;
using FOC.Domain.Validation;
using FOC.Infrastructure.Save;
using NUnit.Framework;

namespace FOC.Tests
{
    public sealed class EconomyTradeCaravanTests
    {
        [Test]public void TradeGoods_AreTypedCategorizedAndDeterministicallyOrdered(){var goods=new TradeGoodRegistry();goods.Add(Good("wheat","Wheat",TradeGoodCategory.Food,2,10));goods.Add(Good("iron","Iron",TradeGoodCategory.RawMaterial,5,30));Assert.That(goods.OrderedGoods.Select(x=>x.Id.Value),Is.EqualTo(new[]{"iron","wheat"}));Assert.Throws<InvalidOperationException>(()=>goods.Add(Good("iron","Other",TradeGoodCategory.RawMaterial,1,1)));Assert.Throws<InvalidOperationException>(()=>new TradeGoodDefinition(TradeGoodId.Create("bad"),"Bad",TradeGoodCategory.Food,1,false));}
        [Test]public void Stock_NeverBecomesNegativeAndRejectsDuplicateAuthority(){var stock=new CityStockState();var wheat=TradeGoodId.Create("wheat");stock.AddInitial(new TradeGoodStock(wheat,10));Assert.Throws<InvalidOperationException>(()=>stock.AddInitial(new TradeGoodStock(wheat,1)));Assert.Throws<InvalidOperationException>(()=>stock.Remove(wheat,11));Assert.That(stock.QuantityOf(wheat),Is.EqualTo(10));stock.Remove(wheat,4);stock.Add(wheat,2);Assert.That(stock.QuantityOf(wheat),Is.EqualTo(8));}
        [Test]public void Consumption_ConsumesAvailableStockAndReportsShortage(){var stock=new CityStockState();var wheat=TradeGoodId.Create("wheat");stock.AddInitial(new TradeGoodStock(wheat,3));var result=ConsumptionRules.Consume(stock,new ConsumptionRequest("population",DemandSourceKind.Population,wheat,5));Assert.That(result.Consumed.Value,Is.EqualTo(3));Assert.That(result.Shortage.Value,Is.EqualTo(2));Assert.That(stock.QuantityOf(wheat),Is.Zero);}
        [Test]public void Demand_IsSourceDrivenAndAvailabilityUsesAuthoritativeStock(){var wheat=TradeGoodId.Create("wheat");var demand=new CityDemandState();demand.AddSource(new DemandSourceState("population",DemandSourceKind.Population,wheat,5));var stock=new CityStockState();Assert.That(demand.Availability(wheat,stock),Is.EqualTo(MarketAvailability.Unavailable));stock.Add(wheat,3);Assert.That(demand.Availability(wheat,stock),Is.EqualTo(MarketAvailability.Shortage));stock.Add(wheat,2);Assert.That(demand.Availability(wheat,stock),Is.EqualTo(MarketAvailability.Available));}
        [Test]public void Production_ConsumesRealInputsAndAddsRealOutputs(){var context=ProductionContext(true,10);new ProductionService(context.Cities,context.Economy).Execute(CityId.Create("origin"),ProductionRecipeId.Create("milling"));Assert.That(context.Market.Stock.QuantityOf(TradeGoodId.Create("wheat")),Is.EqualTo(8));Assert.That(context.Market.Stock.QuantityOf(TradeGoodId.Create("flour")),Is.EqualTo(1));}
        [Test]public void Production_RequiresActiveCompatibleBuildingAndIsAtomicOnShortage(){var inactive=ProductionContext(false,10);Assert.Throws<InvalidOperationException>(()=>new ProductionService(inactive.Cities,inactive.Economy).Execute(CityId.Create("origin"),ProductionRecipeId.Create("milling")));Assert.That(inactive.Market.Stock.QuantityOf(TradeGoodId.Create("wheat")),Is.EqualTo(10));var shortage=ProductionContext(true,1);Assert.Throws<InvalidOperationException>(()=>new ProductionService(shortage.Cities,shortage.Economy).Execute(CityId.Create("origin"),ProductionRecipeId.Create("milling")));Assert.That(shortage.Market.Stock.QuantityOf(TradeGoodId.Create("wheat")),Is.EqualTo(1));Assert.That(shortage.Market.Stock.QuantityOf(TradeGoodId.Create("flour")),Is.Zero);}
        [Test]public void Recipe_RejectsIncompatibleAreaAndRemovedBuildingCannotActivate(){Assert.Throws<InvalidOperationException>(()=>new ProductionRecipeDefinition(ProductionRecipeId.Create("bad"),"Bad",CityBuildingKind.Market,new[]{new RecipeGoodsLine(TradeGoodId.Create("wheat"),1)},new[]{new RecipeGoodsLine(TradeGoodId.Create("flour"),1)}));var city=CityTestFactory.State();Assert.Throws<InvalidOperationException>(()=>city.GetRequiredArea(CityAreaType.Trade).ActivateBuilding(CityBuildingId.Create("removed-bedesten")));}
        [Test]public void PriceQuote_IsDeterministicAuditableAndRespondsOnlyToExplicitInputs(){var good=Good("wheat","Wheat",TradeGoodCategory.Food,1,10);var a=TradePriceRules.FormQuote(good,new[]{new PriceAdjustment("demand",PriceAdjustmentSource.Demand,3),new PriceAdjustment("stock",PriceAdjustmentSource.StockScarcity,2)});var b=TradePriceRules.FormQuote(good,new[]{new PriceAdjustment("stock",PriceAdjustmentSource.StockScarcity,2),new PriceAdjustment("demand",PriceAdjustmentSource.Demand,3)});Assert.That(a.FinalUnitValue,Is.EqualTo(15));Assert.That(a.OrderedAdjustments.Select(x=>x.SourceId),Is.EqualTo(b.OrderedAdjustments.Select(x=>x.SourceId)));Assert.Throws<InvalidOperationException>(()=>TradePriceRules.FormQuote(new TradeGoodDefinition(TradeGoodId.Create("unknown"),"Unknown",TradeGoodCategory.RawMaterial,1),Array.Empty<PriceAdjustment>()));}
        [Test]public void CaravanTransaction_MovesRealGoodsAndMoneyExactlyOnce(){var context=TradeContext();var service=new TradeTransactionService(context.Cities,context.Economy);var quote=TradePriceRules.FormQuote(context.Good,Array.Empty<PriceAdjustment>());service.PurchaseAndLoad(context.Caravan.Id,context.Origin.CityId,context.Good.Id,50,quote);Assert.That(context.Origin.Stock.QuantityOf(context.Good.Id),Is.EqualTo(50));Assert.That(context.Caravan.Cargo.QuantityOf(context.Good.Id),Is.EqualTo(50));Assert.That(context.Caravan.CashBalance.Value,Is.EqualTo(500));Assert.That(context.Origin.CashBalance.Value,Is.EqualTo(500));context.Caravan.MarkInTransit();context.Caravan.MarkAtDestination();service.SellAndUnload(context.Caravan.Id,context.Destination.CityId,context.Good.Id,50,quote);Assert.That(context.Caravan.Cargo.QuantityOf(context.Good.Id),Is.Zero);Assert.That(context.Destination.Stock.QuantityOf(context.Good.Id),Is.EqualTo(50));Assert.That(context.Caravan.CashBalance.Value,Is.EqualTo(1000));Assert.That(context.Destination.CashBalance.Value,Is.EqualTo(500));Assert.That(context.Caravan.Accounting.PurchaseCost.Value,Is.EqualTo(500));Assert.That(context.Caravan.Accounting.SaleRevenue.Value,Is.EqualTo(500));Assert.That(context.Origin.Stock.QuantityOf(context.Good.Id)+context.Destination.Stock.QuantityOf(context.Good.Id)+context.Caravan.Cargo.QuantityOf(context.Good.Id),Is.EqualTo(100));}
        [Test]public void VerticalSlice_ProducesLoadsMovesSellsAndPreservesTheProducedGood(){var production=ProductionContext(true,2);var destination=CityTestFactory.State("destination");production.Cities.Add(destination);var destinationMarket=new CityMarketState(destination.Id,100);production.Economy.AddMarket(destinationMarket);var caravan=new CaravanState(CaravanId.Create("flour-caravan"),EconomicOwnerRef.Character(CharacterId.Create("owner")),CharacterId.Create("manager"),CityId.Create("origin"),destination.Id,1,20);production.Economy.Caravans.Add(caravan);new ProductionService(production.Cities,production.Economy).Execute(CityId.Create("origin"),ProductionRecipeId.Create("milling"));var flour=production.Economy.Goods.GetRequired(TradeGoodId.Create("flour"));var quote=TradePriceRules.FormQuote(flour,Array.Empty<PriceAdjustment>());var trade=new TradeTransactionService(production.Cities,production.Economy);trade.PurchaseAndLoad(caravan.Id,CityId.Create("origin"),flour.Id,1,quote);caravan.MarkInTransit();caravan.MarkAtDestination();trade.SellAndUnload(caravan.Id,destination.Id,flour.Id,1,quote);Assert.That(production.Market.Stock.QuantityOf(flour.Id),Is.Zero);Assert.That(caravan.Cargo.QuantityOf(flour.Id),Is.Zero);Assert.That(destinationMarket.Stock.QuantityOf(flour.Id),Is.EqualTo(1));Assert.That(caravan.Accounting.NetResult,Is.Zero);}
        [Test]public void CaravanPurchase_IsAtomicWhenStockCapacityOrCashIsInsufficient(){var context=TradeContext();var quote=TradePriceRules.FormQuote(context.Good,Array.Empty<PriceAdjustment>());Assert.Throws<InvalidOperationException>(()=>new TradeTransactionService(context.Cities,context.Economy).PurchaseAndLoad(context.Caravan.Id,context.Origin.CityId,context.Good.Id,101,quote));Assert.That(context.Origin.Stock.QuantityOf(context.Good.Id),Is.EqualTo(100));Assert.That(context.Caravan.Cargo.QuantityOf(context.Good.Id),Is.Zero);Assert.That(context.Caravan.CashBalance.Value,Is.EqualTo(1000));Assert.That(context.Origin.CashBalance.Value,Is.Zero);}
        [Test]public void CaravanCapacityAndLifecycleStagesAreEnforced(){var context=TradeContext();Assert.Throws<InvalidOperationException>(()=>context.Caravan.Cargo.Add(context.Good.Id,101,context.Caravan.WeightCapacity,context.Economy.Goods));context.Caravan.MarkInTransit();Assert.Throws<InvalidOperationException>(()=>context.Caravan.MarkInTransit());context.Caravan.MarkAtDestination();Assert.Throws<InvalidOperationException>(()=>context.Caravan.MarkAtDestination());}
        [Test]public void CaravanRegistryRejectsDuplicateAndCargoRejectsNegativeQuantity(){var context=TradeContext();Assert.Throws<InvalidOperationException>(()=>context.Economy.Caravans.Add(context.Caravan));Assert.Throws<ArgumentOutOfRangeException>(()=>new TradeGoodStock(context.Good.Id,-1));}
        [Test]public void EconomyInvariantValidator_RejectsFakeCityAndManagerReferences(){var runtime=Runtime(TradeContext());Assert.That(new EconomyInvariantValidator().Validate(runtime).IsValid,Is.True);var badEconomy=new EconomyState(runtime.Economy.Goods,runtime.Economy.Recipes);badEconomy.AddMarket(new CityMarketState(CityId.Create("missing")));var bad=Runtime(TradeContext(),badEconomy);Assert.That(new EconomyInvariantValidator().Validate(bad).IsValid,Is.False);}
        [Test]public void RepresentativeMustBeASeparateActiveTradeAssignment(){var context=TradeContext(true);var runtime=Runtime(context);Assert.That(new EconomyInvariantValidator().Validate(runtime).IsValid,Is.True);Assert.That(context.Caravan.Owner.Kind,Is.EqualTo(EconomicOwnerKind.Character));Assert.That(context.Caravan.Representative!.AssignmentId.Value,Is.EqualTo("trade-rep"));}
        [Test]public void SchemaSix_SemanticRoundTripPreservesEconomyAndCaravan(){var runtime=Runtime(TradeContext(true));var serializer=new CampaignSaveTextSerializer();var text=serializer.Serialize(CampaignSaveMapper.ToSaveData(runtime));var read=serializer.Deserialize(text);Assert.That(read.Success,Is.True,read.Error);Assert.That(new CampaignSaveValidator().Validate(read.Data!).IsValid,Is.True);var restored=CampaignSaveMapper.ToRuntimeState(read.Data!);Assert.That(restored.Economy.Goods.Count,Is.EqualTo(1));var caravan=restored.Economy.Caravans.OrderedCaravans.Single();Assert.That(caravan.Owner.Kind,Is.EqualTo(EconomicOwnerKind.Character));Assert.That(caravan.Representative!.AssignmentId.Value,Is.EqualTo("trade-rep"));Assert.That(restored.Economy.OrderedMarkets.Count,Is.EqualTo(2));}
        [Test]public void SchemaSixSerialization_IsDeterministicAcrossInsertionOrder(){var first=Runtime(TradeContext(true));var second=Runtime(TradeContext(true,true));var serializer=new CampaignSaveTextSerializer();Assert.That(serializer.Serialize(CampaignSaveMapper.ToSaveData(first)),Is.EqualTo(serializer.Serialize(CampaignSaveMapper.ToSaveData(second))));}
        [Test]public void MigrationFiveToSix_PreservesOldSystemsWithoutInventingEconomy(){var source=CampaignSaveMapper.ToSaveData(Runtime(TradeContext(true)));source.SaveVersion=5;var migrated=new CampaignSaveV5ToV6Migration().Apply(source);Assert.That(migrated.SaveVersion,Is.EqualTo(6));Assert.That(migrated.Characters.Count,Is.EqualTo(2));Assert.That(migrated.Cities.Count,Is.EqualTo(2));Assert.That(migrated.TradeGoods,Is.Empty);Assert.That(migrated.CityMarkets,Is.Empty);Assert.That(migrated.Caravans,Is.Empty);}
        [Test]public void HardcodedSchemaFiveFixture_MigratesWithoutInventingEconomy(){const string fixture="FOC_CAMPAIGN_SAVE\nSaveVersion=5\nCampaignId=Y2FtcGFpZ24tbGVnYWN5\nGameVersion=MC4wLjU=\nContentDataVersion=Y2l0eS0x\nWorldSeed=1648\nWorldGenRevision=1\nWorldTime=9\nRngState=123\nRngDrawCount=2\nCharacterCount=0\nCharacterRelationCount=0\nSocialState=AAAAAAAAAAAAAAAA\nReligionState=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nCityState=AAAAAA==\n";var read=new CampaignSaveTextSerializer().Deserialize(fixture);Assert.That(read.Success,Is.True,read.Error);var migrated=new CampaignSaveV5ToV6Migration().Apply(read.Data!);Assert.That(migrated.SaveVersion,Is.EqualTo(6));Assert.That(migrated.Cities,Is.Empty);Assert.That(migrated.TradeGoods,Is.Empty);Assert.That(migrated.CityMarkets,Is.Empty);Assert.That(migrated.Caravans,Is.Empty);}
        [Test]public void FullMigrationChain_ReachesSixWithoutInventingEconomy(){var source=new CampaignSaveData{SaveVersion=1,CampaignId="legacy",GameVersion="0.1",ContentDataVersion="one",WorldSeed=1,RngState=1};var pipeline=new SaveMigrationPipeline(new ISaveMigration[]{new CampaignSaveV1ToV2Migration(),new CampaignSaveV2ToV3Migration(),new CampaignSaveV3ToV4Migration(),new CampaignSaveV4ToV5Migration(),new CampaignSaveV5ToV6Migration()});var result=pipeline.Migrate(source,6);Assert.That(result.Success,Is.True,result.Error);Assert.That(result.Data!.TradeGoods,Is.Empty);Assert.That(result.Data.ProductionRecipes,Is.Empty);Assert.That(result.Data.CityMarkets,Is.Empty);Assert.That(result.Data.Caravans,Is.Empty);}
        [Test]public void SaveDataAndRuntimeEconomyTypesRemainSeparate(){Assert.That(typeof(TradeGoodSaveData).IsAssignableFrom(typeof(TradeGoodDefinition)),Is.False);Assert.That(typeof(CityMarketSaveData).IsAssignableFrom(typeof(CityMarketState)),Is.False);Assert.That(typeof(CaravanSaveData).IsAssignableFrom(typeof(CaravanState)),Is.False);}

        private static TradeGoodDefinition Good(string id,string name,TradeGoodCategory category,long weight,long? value=null)=>new TradeGoodDefinition(TradeGoodId.Create(id),name,category,weight,category==TradeGoodCategory.Food,category==TradeGoodCategory.Military,category==TradeGoodCategory.Luxury,value);
        private static (CityRegistry Cities,EconomyState Economy,CityMarketState Market) ProductionContext(bool active,long wheat)
        {var cities=new CityRegistry();var city=CityTestFactory.State("origin");city.GetRequiredArea(CityAreaType.FoodSupply).SetFullness(CityAreaFullness.Low);if(active)city.GetRequiredArea(CityAreaType.FoodSupply).ActivateBuilding(CityBuildingId.Create("mill"));cities.Add(city);var goods=new TradeGoodRegistry();goods.Add(Good("wheat","Wheat",TradeGoodCategory.Food,1,10));goods.Add(Good("flour","Flour",TradeGoodCategory.Processed,1,20));var recipes=new ProductionRecipeRegistry();recipes.Add(new ProductionRecipeDefinition(ProductionRecipeId.Create("milling"),"Milling",CityBuildingKind.Mill,new[]{new RecipeGoodsLine(TradeGoodId.Create("wheat"),2)},new[]{new RecipeGoodsLine(TradeGoodId.Create("flour"),1)}));var economy=new EconomyState(goods,recipes);var stock=new CityStockState();stock.AddInitial(new TradeGoodStock(TradeGoodId.Create("wheat"),wheat));var market=new CityMarketState(city.Id,0,stock);economy.AddMarket(market);return(cities,economy,market);}
        private sealed class TradeContextData{public CityRegistry Cities=null!;public EconomyState Economy=null!;public TradeGoodDefinition Good=null!;public CityMarketState Origin=null!;public CityMarketState Destination=null!;public CaravanState Caravan=null!;public CharacterRoster Characters=null!;public OrganizationRegistry Organizations=null!;}
        private static TradeContextData TradeContext(bool representative=false,bool reverse=false)
        {var data=new TradeContextData();data.Characters=new CharacterRoster();data.Characters.Add(CharacterTestFactory.Named("manager"));data.Characters.Add(CharacterTestFactory.Named("owner"));data.Organizations=new OrganizationRegistry();var org=new OrganizationState(OrganizationId.Create("trade-org"),"Trade Organization");if(representative)org.AddAssignment(new AssignmentState(AssignmentId.Create("trade-rep"),CharacterId.Create("manager"),OrganizationBranch.Trade,"trade-representative",AssignmentAuthority.Responsible,AssignmentTarget.Organization(OrganizationId.Create("trade-org")),AssignmentPresence.RemoteCapable,new WorldTimestamp(0)));data.Organizations.Add(org);data.Cities=new CityRegistry();var origin=CityTestFactory.State("origin",reverse);var destination=CityTestFactory.State("destination",!reverse);if(reverse){data.Cities.Add(origin);data.Cities.Add(destination);}else{data.Cities.Add(destination);data.Cities.Add(origin);}var goods=new TradeGoodRegistry();data.Good=Good("wheat","Wheat",TradeGoodCategory.Food,1,10);goods.Add(data.Good);data.Economy=new EconomyState(goods);var originStock=new CityStockState();originStock.AddInitial(new TradeGoodStock(data.Good.Id,100));data.Origin=new CityMarketState(origin.Id,0,originStock);data.Destination=new CityMarketState(destination.Id,1000);if(reverse){data.Economy.AddMarket(data.Origin);data.Economy.AddMarket(data.Destination);}else{data.Economy.AddMarket(data.Destination);data.Economy.AddMarket(data.Origin);}var rep=representative?new TradeRepresentativeReference(CharacterId.Create("manager"),OrganizationId.Create("trade-org"),AssignmentId.Create("trade-rep")):null;data.Caravan=new CaravanState(CaravanId.Create("caravan"),EconomicOwnerRef.Character(CharacterId.Create("owner")),CharacterId.Create("manager"),origin.Id,destination.Id,100,1000,rep,TradeRouteId.Create("route"),riskInputs:new[]{new RouteRiskInput("roads",RouteRiskSource.PoorRoads)});data.Economy.Caravans.Add(data.Caravan);return data;}
        private static CampaignRuntimeState Runtime(TradeContextData context,EconomyState? economy=null)=>new CampaignRuntimeState(StableId<CampaignTag>.Create("campaign"),"0.5","economy-1",55,1,new WorldClock(new WorldTimestamp(3)),new SeededRandomSource(55),context.Characters,context.Organizations,null,null,null,context.Cities,economy??context.Economy);
    }
}
