using System;
using System.Linq;
using FOC.Application.Organizations;
using FOC.Domain.Characters;
using FOC.Domain.Common;
using FOC.Domain.Organizations;
using FOC.Domain.Random;
using FOC.Domain.Time;
using NUnit.Framework;

namespace FOC.Tests
{
    public sealed class OrganizationTests
    {
        [Test] public void MembershipAssignmentLoyaltyAndLocation_AreDistinctContracts() { Assert.That(typeof(OrganizationMembershipState), Is.Not.EqualTo(typeof(AssignmentState))); Assert.That(typeof(OrganizationMembershipState).GetProperties().Any(x => x.Name.Contains("Loyalty")), Is.False); Assert.That(typeof(AssignmentState).GetProperties().Any(x => x.PropertyType == typeof(CharacterLocation)), Is.False); }
        [Test] public void AssignmentAuthority_IsSeparateTypedValue() { var a = Assignment("a", AssignmentTarget.City(CityId.Create("city-a")), AssignmentPresence.RemoteCapable); Assert.That(a.Authority, Is.EqualTo(AssignmentAuthority.Deputy)); Assert.That(typeof(AssignmentAuthority).IsEnum, Is.True); }
        [Test] public void FinalBranches_AreExact() => Assert.That(Enum.GetNames(typeof(OrganizationBranch)), Is.EqualTo(new[] { "Party", "Household", "Army", "Settlements", "Estates", "Production", "Trade", "Diplomacy" }));
        [Test] public void RemovedSpecialAgentsBranch_DoesNotExist() => Assert.That(Enum.GetNames(typeof(OrganizationBranch)), Does.Not.Contain("SpecialAgents"));
        [Test] public void MembershipTypes_AreExact() => Assert.That(Enum.GetNames(typeof(OrganizationMembershipType)), Is.EqualTo(new[] { "Full", "Temporary", "Salaried", "Contact", "Protected", "Contract", "Volunteer" }));
        [Test] public void MultiBranchMembership_Works() { var state = Organization(); var id = CharacterId.Create("c"); state.AddMembership(new OrganizationMembershipState(id, OrganizationBranch.Household, OrganizationMembershipType.Full, new WorldTimestamp(1))); state.AddMembership(new OrganizationMembershipState(id, OrganizationBranch.Diplomacy, OrganizationMembershipType.Contact, new WorldTimestamp(2))); Assert.That(state.Memberships.Count, Is.EqualTo(2)); }
        [Test] public void DuplicateActiveBranchMembership_IsRejected() { var state = Organization(); var id = CharacterId.Create("c"); state.AddMembership(new OrganizationMembershipState(id, OrganizationBranch.Party, OrganizationMembershipType.Full, new WorldTimestamp(1))); Assert.Throws<InvalidOperationException>(() => state.AddMembership(new OrganizationMembershipState(id, OrganizationBranch.Party, OrganizationMembershipType.Temporary, new WorldTimestamp(2)))); }
        [Test] public void SameCharacter_CanHoldMultipleRemoteAssignments() { var state = Organization(); state.AddAssignment(Assignment("a", AssignmentTarget.City(CityId.Create("a")), AssignmentPresence.RemoteCapable)); state.AddAssignment(Assignment("b", AssignmentTarget.City(CityId.Create("b")), AssignmentPresence.RemoteCapable)); Assert.That(state.OrderedAssignments.Count, Is.EqualTo(2)); }
        [Test] public void SamePhysicalTarget_AllowsMultipleAssignments() { var state = Organization(); state.AddAssignment(Assignment("a", AssignmentTarget.City(CityId.Create("a")), AssignmentPresence.PhysicalPresenceRequired)); state.AddAssignment(Assignment("b", AssignmentTarget.City(CityId.Create("a")), AssignmentPresence.PhysicalPresenceRequired)); Assert.That(state.OrderedAssignments.Count, Is.EqualTo(2)); }
        [Test] public void DifferentPhysicalTargets_AreRejected() { var state = Organization(); state.AddAssignment(Assignment("a", AssignmentTarget.City(CityId.Create("a")), AssignmentPresence.PhysicalPresenceRequired)); Assert.Throws<InvalidOperationException>(() => state.AddAssignment(Assignment("b", AssignmentTarget.City(CityId.Create("b")), AssignmentPresence.PhysicalPresenceRequired))); }
        [Test] public void DeadCharacter_ActiveAssignmentRejectedByApplicationBoundary() { var character = CharacterTestFactory.Named("c"); CharacterDeathRules.TryApply(character, new CharacterDeathContext(CharacterDeathCause.Battle, new WorldTimestamp(5), CharacterLocation.At(default), "Dead."), new ImportanceStoryGuardDeathPolicy(), new SeededRandomSource(1)); var roster = new CharacterRoster(); roster.Add(character); var registry = Registry(); Assert.Throws<InvalidOperationException>(() => new OrganizationCommandService(roster, registry).AddAssignment(OrganizationId.Create("org"), Assignment("a", AssignmentTarget.City(CityId.Create("a")), AssignmentPresence.RemoteCapable))); }
        [Test] public void CaptiveCharacter_PhysicalAssignmentRejectedByApplicationBoundary() { var captive = CharacterTestFactory.Named("c"); var captor = CharacterTestFactory.Named("captor"); captive.Capture(new CaptivityState(captor.Id, CaptivitySite.InCity(CityId.Create("prison"))), new WorldTimestamp(2)); var roster = new CharacterRoster(); roster.Add(captive); roster.Add(captor); Assert.Throws<InvalidOperationException>(() => new OrganizationCommandService(roster, Registry()).AddAssignment(OrganizationId.Create("org"), Assignment("a", AssignmentTarget.City(CityId.Create("a")), AssignmentPresence.PhysicalPresenceRequired))); }
        [Test] public void Assignment_DoesNotSilentlyMoveCharacter() { var character = CharacterTestFactory.Named("c"); var roster = new CharacterRoster(); roster.Add(character); var before = character.Location; new OrganizationCommandService(roster, Registry()).AddAssignment(OrganizationId.Create("org"), Assignment("a", AssignmentTarget.City(CityId.Create("elsewhere")), AssignmentPresence.RemoteCapable)); Assert.That(character.Location, Is.SameAs(before)); }
        [Test] public void PhysicalAssignment_MustMatchAuthoritativeLocation() { var character = CharacterTestFactory.Named("c"); var roster = new CharacterRoster(); roster.Add(character); Assert.Throws<InvalidOperationException>(() => new OrganizationCommandService(roster, Registry()).AddAssignment(OrganizationId.Create("org"), Assignment("a", AssignmentTarget.City(CityId.Create("elsewhere")), AssignmentPresence.PhysicalPresenceRequired))); }
        [Test] public void Assignments_AreDeterministicallyOrderedByTypedId() { var state = Organization(); state.AddAssignment(Assignment("z", AssignmentTarget.City(CityId.Create("a")), AssignmentPresence.RemoteCapable)); state.AddAssignment(Assignment("a", AssignmentTarget.City(CityId.Create("a")), AssignmentPresence.RemoteCapable)); Assert.That(state.OrderedAssignments.Select(x => x.Id.Value), Is.EqualTo(new[] { "a", "z" })); }
        [Test] public void OrganizationRegistry_IsDeterministicallyOrdered() { var registry = new OrganizationRegistry(); registry.Add(new OrganizationState(OrganizationId.Create("z"), "Z")); registry.Add(new OrganizationState(OrganizationId.Create("a"), "A")); Assert.That(registry.OrderedOrganizations.Select(x => x.Id.Value), Is.EqualTo(new[] { "a", "z" })); }

        private static OrganizationState Organization() => new OrganizationState(OrganizationId.Create("org"), "Organization");
        private static OrganizationRegistry Registry() { var registry = new OrganizationRegistry(); registry.Add(Organization()); return registry; }
        private static AssignmentState Assignment(string id, AssignmentTarget target, AssignmentPresence presence) => new AssignmentState(AssignmentId.Create(id), CharacterId.Create("c"), OrganizationBranch.Settlements, "steward", AssignmentAuthority.Deputy, target, presence, new WorldTimestamp(1));
    }
}
