using System;
using System.Linq;
using FOC.Application.Religion;
using FOC.Domain.Campaign;
using FOC.Domain.Characters;
using FOC.Domain.Cliques;
using FOC.Domain.Common;
using FOC.Domain.Random;
using FOC.Domain.Religion;
using FOC.Domain.Organizations;
using FOC.Domain.Time;
using FOC.Domain.Validation;
using NUnit.Framework;

namespace FOC.Tests
{
    public sealed class ReligionSectTests
    {
        [Test] public void TypedIdentity_KeepsReligionAndSectDistinct(){Assert.That(ReligionId.Create("shared").Equals(SectId.Create("shared")),Is.False);Assert.That(ReligionId.Create("a").CompareTo(ReligionId.Create("b")),Is.LessThan(0));}
        [Test] public void Definitions_AreImmutableAndContentDriven(){var item=new ReligionDefinition(ReligionId.Create("faith-a"),"Faith A");Assert.That(item.Name,Is.EqualTo("Faith A"));Assert.That(typeof(ReligionDefinition).GetProperties().All(x=>!x.CanWrite),Is.True);}
        [Test] public void Sect_RequiresExistingParentAndCompatiblePair(){var r=new ReligionRegistry();r.AddReligion(new ReligionDefinition(ReligionId.Create("a"),"A"));r.AddReligion(new ReligionDefinition(ReligionId.Create("b"),"B"));Assert.Throws<InvalidOperationException>(()=>r.AddSect(new SectDefinition(SectId.Create("missing"),ReligionId.Create("c"),"Missing")));r.AddSect(new SectDefinition(SectId.Create("a-one"),ReligionId.Create("a"),"A One"));Assert.DoesNotThrow(()=>r.RequireCompatible(ReligionId.Create("a"),SectId.Create("a-one")));Assert.Throws<InvalidOperationException>(()=>r.RequireCompatible(ReligionId.Create("b"),SectId.Create("a-one")));}
        [Test] public void OptionalSect_IsAllowed(){var r=Definitions();Assert.DoesNotThrow(()=>r.RequireCompatible(ReligionId.Create("faith"),null));}
        [Test] public void DuplicateDefinitionsAndCharacterAssignments_AreRejected(){var r=Definitions();Assert.Throws<InvalidOperationException>(()=>r.AddReligion(new ReligionDefinition(ReligionId.Create("faith"),"Duplicate")));var c=new CharacterReligionRegistry();var state=new CharacterReligionState(CharacterId.Create("c"),ReligionId.Create("faith"));c.Add(state);Assert.Throws<InvalidOperationException>(()=>c.Add(state));}
        [Test] public void Command_ChangesOnlyReligiousIdentity(){var campaign=Campaign();var clique=new CliqueState(new CliqueDefinition(CliqueId.Create("religious"),"Circle",CliqueType.Religious));campaign.Cliques.Add(clique);var character=campaign.Characters.GetRequired(CharacterId.Create("character"));var loyalty=character.CurrentLoyalty.Value;campaign.Characters.Relations.TryGet(character.Id,CharacterId.Create("other"),out var relation);var organizationCount=campaign.Organizations.Count;new ReligionCommandService(campaign.Characters,campaign.Cliques,campaign.Religion).SetCharacterReligion(character.Id,ReligionId.Create("faith"),SectId.Create("sect"));Assert.That(character.CurrentLoyalty.Value,Is.EqualTo(loyalty));Assert.That(campaign.Characters.Relations.TryGet(character.Id,CharacterId.Create("other"),out var after),Is.True);Assert.That(after!.Value,Is.EqualTo(relation!.Value));Assert.That(campaign.Organizations.Count,Is.EqualTo(organizationCount));Assert.That(campaign.Organizations.GetRequired(OrganizationId.Create("org")).Memberships.Count,Is.EqualTo(1));Assert.That(campaign.Cliques.Count,Is.EqualTo(1));}
        [Test] public void ReligiousClique_IsAssociationNotSecondGroupAndKeepsOwnershipCombatInvariants(){var campaign=Campaign();var religious=new CliqueState(new CliqueDefinition(CliqueId.Create("religious"),"Circle",CliqueType.Religious));campaign.Cliques.Add(religious);new ReligionCommandService(campaign.Characters,campaign.Cliques,campaign.Religion).AssociateReligiousClique(religious.Id,ReligionId.Create("faith"));Assert.That(campaign.Religion.OrderedCliqueAssociations.Count,Is.EqualTo(1));Assert.That(religious.CanOwnGoods,Is.False);Assert.That(religious.CanOwnSoldiers,Is.False);Assert.That(religious.CombatBonus,Is.Zero);}
        [Test] public void NonReligiousClique_CannotReceiveReligiousAssociation(){var campaign=Campaign();var c=new CliqueState(new CliqueDefinition(CliqueId.Create("merchant"),"Merchants",CliqueType.Merchant));campaign.Cliques.Add(c);Assert.Throws<InvalidOperationException>(()=>new ReligionCommandService(campaign.Characters,campaign.Cliques,campaign.Religion).AssociateReligiousClique(c.Id,ReligionId.Create("faith")));}
        [Test] public void DifferenceAlone_HasNoPoliticalOrCombatEffect(){var x=new ReligionDifferenceAssessment(true);Assert.That(x.AutomaticUnrest,Is.False);Assert.That(x.LoyaltyDelta,Is.Zero);Assert.That(x.RelationDelta,Is.Zero);Assert.That(x.AutomaticRebellionCause,Is.False);Assert.That(x.AutomaticWarCause,Is.False);Assert.That(x.CombatModifier,Is.Zero);}
        [Test] public void Profiles_AreMultiComponentDeterministicAndRejectDuplicates(){var a=new ReligionProfile(ReligionProfileTarget.City(CityId.Create("city")));a.Add(new ReligionProfileEntry(ReligionId.Create("z"),null,2));a.Add(new ReligionProfileEntry(ReligionId.Create("a"),null,1));Assert.That(a.Entries.Select(x=>x.ReligionId.Value),Is.EqualTo(new[]{"a","z"}));Assert.Throws<InvalidOperationException>(()=>a.Add(new ReligionProfileEntry(ReligionId.Create("a"),null,5)));}
        [Test] public void RuntimeValidator_RejectsWrongProfileAndPolicySectPair(){var campaign=Campaign();var profile=new ReligionProfile(ReligionProfileTarget.Region(RegionId.Create("region")));profile.Add(new ReligionProfileEntry(ReligionId.Create("faith"),SectId.Create("foreign-sect"),1));campaign.Religion.AddProfile(profile);var policy=new ReligionPolicy(ReligionProfileTarget.Faction(FactionId.Create("faction")));policy.Add(new ReligionPolicyRule(ReligionId.Create("faith"),SectId.Create("foreign-sect"),ReligionRecognition.Recognized,ReligionTreatment.Tolerated,ReligionEnforcement.Nominal));campaign.Religion.AddPolicy(policy);Assert.That(new ReligionInvariantValidator().Validate(campaign).IsValid,Is.False);}
        [Test] public void Policy_IsTypedContextWithoutNumericEffects(){var policy=new ReligionPolicy(ReligionProfileTarget.Faction(FactionId.Create("faction")));policy.Add(new ReligionPolicyRule(ReligionId.Create("faith"),SectId.Create("sect"),ReligionRecognition.Recognized,ReligionTreatment.Tolerated,ReligionEnforcement.LocalDiscretion));Assert.That(policy.Rules.Single().Treatment,Is.EqualTo(ReligionTreatment.Tolerated));Assert.That(typeof(ReligionPolicyRule).GetProperties().Any(x=>x.PropertyType==typeof(double)||x.PropertyType==typeof(float)),Is.False);}
        [Test] public void RuntimeValidator_RejectsDanglingCharacterReligion(){var campaign=Campaign();campaign.Religion.Characters.Add(new CharacterReligionState(CharacterId.Create("missing"),ReligionId.Create("faith")));Assert.That(new ReligionInvariantValidator().Validate(campaign).IsValid,Is.False);}
        private static ReligionRegistry Definitions(){var r=new ReligionRegistry();r.AddReligion(new ReligionDefinition(ReligionId.Create("faith"),"Faith"));r.AddReligion(new ReligionDefinition(ReligionId.Create("foreign-faith"),"Foreign Faith"));r.AddSect(new SectDefinition(SectId.Create("sect"),ReligionId.Create("faith"),"Sect"));r.AddSect(new SectDefinition(SectId.Create("foreign-sect"),ReligionId.Create("foreign-faith"),"Foreign Sect"));return r;}
        private static CampaignRuntimeState Campaign(){var roster=new CharacterRoster();roster.Add(CharacterTestFactory.Named("character"));roster.Add(CharacterTestFactory.Named("other"));roster.SetRelation(CharacterId.Create("character"),CharacterId.Create("other"),17);var organizations=new OrganizationRegistry();var organization=new OrganizationState(OrganizationId.Create("org"),"Organization");organization.AddMembership(new OrganizationMembershipState(CharacterId.Create("character"),OrganizationBranch.Party,OrganizationMembershipType.Full,new WorldTimestamp(0)));organizations.Add(organization);return new CampaignRuntimeState(StableId<CampaignTag>.Create("campaign"),"0.3","religion-1",10,1,new WorldClock(new WorldTimestamp(0)),new SeededRandomSource(10),roster,organizations,null,null,new ReligionCampaignState(Definitions()));}
    }
}
