using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using NUnit.Framework;
using FOC.Application.Save;
using FOC.Domain.Characters;
using FOC.Domain.Cities;
using FOC.Domain.Common;
using FOC.Domain.Soldiers;
using FOC.Domain.Time;
using FOC.Visuals.Core;

namespace FOC.Tests.EditMode
{
    [TestFixture]
    public sealed class VisualArchitectureCoreTests
    {
        [Test]public void VisualCoreAndDomainRemainUnityFree(){Assert.That(typeof(VisualCatalog).Assembly.GetReferencedAssemblies().Any(x=>x.Name!=null&&x.Name.StartsWith("Unity",StringComparison.Ordinal)),Is.False);Assert.That(typeof(SoldierInstance).Assembly.GetReferencedAssemblies().Any(x=>x.Name!=null&&x.Name.StartsWith("Unity",StringComparison.Ordinal)),Is.False);}
        [Test]public void GameplayAndSaveContractsContainNoUnityAssetReferences(){var forbidden=new[]{"GameObject","Mesh","Material","Texture","Animator","Avatar","Prefab","UnityAssetGuid"};Assert.That(typeof(WeaponDefinition).GetProperties().Select(x=>x.PropertyType.Name).Any(x=>forbidden.Any(f=>x.Contains(f))),Is.False);Assert.That(typeof(CampaignSaveData).Assembly.GetTypes().Where(x=>x.Namespace=="FOC.Application.Save").SelectMany(x=>x.GetProperties()).Any(x=>forbidden.Any(f=>x.Name.Contains(f)||x.PropertyType.Name.Contains(f))),Is.False);Assert.That(CampaignSaveData.CurrentSaveVersion,Is.EqualTo(9));}
        [Test]public void CatalogRejectsDuplicateIdsAndReportsMissingMappings(){var c=new VisualCatalog();var a=Asset("BODY_A",VisualAssetCategory.Body);c.Add(a);Assert.Throws<InvalidOperationException>(()=>c.Add(a));c.Add(new VisualProfile(VisualProfileId.Create("missing-profile"),"standard-human",VisualAssetId.Create("BODY_A"),VisualAssetId.Create("HEAD_MISSING"),VisualAssetId.Create("CLOTH_MISSING"),null,VisualQualityTier.Standard,"generic"));var result=c.Validate();Assert.That(result.IsValid,Is.False);Assert.That(result.Errors.Count,Is.EqualTo(2));}
        [Test]public void CatalogLookupIsCanonicalAndMissingMappingFails(){var c=Catalog();var ids=c.OrderedAssets.Select(x=>x.Id.Value).ToArray();Assert.That(ids,Is.EqualTo(ids.OrderBy(x=>x,StringComparer.Ordinal).ToArray()));Assert.Throws<KeyNotFoundException>(()=>c.GetEquipment(EquipmentDefinitionRef.Weapon(WeaponDefinitionId.Create("missing"))));}
        [Test]public void CanonicalHumanRigPassesAndMissingOrUnknownBoneFails(){var valid=new RigDescriptor(RigKind.Humanoid,CanonicalRig.HumanBones,CanonicalRig.HumanSockets.Values,true,4,"meters-1.0","+Z");Assert.That(RigValidator.Validate(valid).IsValid,Is.True);var invalid=new RigDescriptor(RigKind.Humanoid,CanonicalRig.HumanBones.Where(x=>x!="Head").Concat(new[]{"UnknownBone_X"}),CanonicalRig.HumanSockets.Values,false,8,"centimeters","-Z");var result=RigValidator.Validate(invalid);Assert.That(result.IsValid,Is.False);Assert.That(result.Errors.Any(x=>x.Contains("Head")),Is.True);Assert.That(result.Errors,Does.Contain("Unknown bone: UnknownBone_X"));}
        [Test]public void CanonicalMountRigRequiresSeparateRiderSocket(){var valid=new RigDescriptor(RigKind.GenericMount,CanonicalRig.MountBones,new[]{CanonicalRig.RiderSocket},true,4,"meters-1.0","+Z");Assert.That(RigValidator.Validate(valid).IsValid,Is.True);var invalid=new RigDescriptor(RigKind.GenericMount,CanonicalRig.MountBones,Array.Empty<string>(),true,4,"meters-1.0","+Z");Assert.That(RigValidator.Validate(invalid).Errors,Does.Contain("Missing socket: Socket_Rider"));}
        [Test]public void LodPolicyRequiresThreeDescendingTiers(){var profile=new CharacterLodProfile("battle",0.60f,0.25f,0.08f,6,4);Assert.That(profile.Lod2,Is.LessThan(profile.Lod1));Assert.Throws<ArgumentException>(()=>new CharacterLodProfile("bad",0.5f,0.6f,0.1f,6,4));}
        [Test]public void PersistentLoadoutMapsToCorrectVisualEquipment(){var fixture=Fixture();var plan=fixture.Planner.Plan(fixture.Soldier,fixture.Troop,fixture.Equipment);Assert.That(plan.Modules.Select(x=>x.AssetId.Value),Does.Contain("WPN_Lance_Proof"));Assert.That(plan.Modules.Select(x=>x.AssetId.Value),Does.Contain("WPN_Sword_Proof"));Assert.That(plan.Modules.Select(x=>x.AssetId.Value),Does.Contain("MNT_Horse_Proof"));Assert.That(plan.Modules.Single(x=>x.AssetId.Value=="WPN_Lance_Proof").Socket,Is.EqualTo(VisualSocket.RightHand));}
        [Test]public void RepeatedPlanningIsDeterministicAndDoesNotMutateGameplay(){var fixture=Fixture();var before=fixture.Soldier.Loadout;var first=fixture.Planner.Plan(fixture.Soldier,fixture.Troop,fixture.Equipment);for(var i=0;i<10;i++)Assert.That(fixture.Planner.Plan(fixture.Soldier,fixture.Troop,fixture.Equipment).Signature,Is.EqualTo(first.Signature));Assert.That(fixture.Soldier.Loadout,Is.SameAs(before));}
        [Test]public void StableAppearanceVariesByIdentityWithoutGameplayRandom(){var a=Fixture("soldier-a");var b=Fixture("soldier-b");var pa=a.Planner.Plan(a.Soldier,a.Troop,a.Equipment);var pb=b.Planner.Plan(b.Soldier,b.Troop,b.Equipment);Assert.That(pa.AppearanceVariant,Is.Not.EqualTo(pb.AppearanceVariant));Assert.That(pa.AppearanceVariant,Is.EqualTo(VisualSoldierPlanner.StableHash("soldier-a|deli")));}
        [Test]public void DifferentSoldiersWithSameVisualConfigurationShareReusableSignatureButNotIdentity(){var a=Fixture("soldier-a");var b=Fixture("soldier-b");var pa=a.Planner.Plan(a.Soldier,a.Troop,a.Equipment);var pb=b.Planner.Plan(b.Soldier,b.Troop,b.Equipment);Assert.That(pa.Signature,Is.EqualTo(pb.Signature));Assert.That(pa.SoldierId,Is.Not.EqualTo(pb.SoldierId));Assert.That(pa.AppearanceVariant,Is.Not.EqualTo(pb.AppearanceVariant));}
        [Test]public void QualityTierSelectsConsolidatedModularOrCrowdRuntimePolicy(){Assert.That(PlanForTier(VisualQualityTier.Standard).RepresentationKind,Is.EqualTo(VisualRepresentationKind.Consolidated));Assert.That(PlanForTier(VisualQualityTier.Narrative).RepresentationKind,Is.EqualTo(VisualRepresentationKind.Modular));Assert.That(PlanForTier(VisualQualityTier.Crowd).RepresentationKind,Is.EqualTo(VisualRepresentationKind.Crowd));}
        [Test]public void VisualBindingDetachAndRebindDoesNotLeakIdentity(){var a=Fixture("soldier-a");var b=Fixture("soldier-b");var binding=new VisualSoldierBindingState();binding.Bind(a.Planner.Plan(a.Soldier,a.Troop,a.Equipment));Assert.That(binding.SoldierId!.Value.Value,Is.EqualTo("soldier-a"));binding.Clear();Assert.That(binding.IsBound,Is.False);binding.Bind(b.Planner.Plan(b.Soldier,b.Troop,b.Equipment));Assert.That(binding.SoldierId!.Value.Value,Is.EqualTo("soldier-b"));}
        [Test]public void SignatureCacheIsBoundedAndSaveIndependent(){var cache=new BoundedSignatureCache<string>(2);cache.Put(new VisualSoldierSignature("a"),"A");cache.Put(new VisualSoldierSignature("b"),"B");cache.Put(new VisualSoldierSignature("c"),"C");Assert.That(cache.Count,Is.EqualTo(2));Assert.That(cache.TryGet(new VisualSoldierSignature("a"),out _),Is.False);Assert.That(typeof(CampaignSaveData).GetProperties().Any(x=>x.PropertyType.Name.Contains("Cache")),Is.False);}
        [Test]public void VisualBodyCompatibilityRejectsMechanicalMismatch(){var fixture=Fixture();var c=Catalog("other-body");Assert.Throws<InvalidOperationException>(()=>new VisualSoldierPlanner(c).Plan(fixture.Soldier,fixture.Troop,fixture.Equipment));}
        [Test]public void AssetSpecPreservesAiProvenanceAndCanonicalMetadata(){var spec=new VisualAssetSpec(VisualAssetId.Create("WPN_Test"),VisualAssetCategory.Weapon,"1648-1650","generic","sidearm","standard-human","wood and steel",RigKind.Humanoid,new[]{VisualSocket.RightHand},new[]{"standard-human"},"battle-3-tier","standard-1k","meters-1.0","weapon:test","Original proof",new[]{"grounded","historical","grounded"},new VisualAssetProvenance("Unity procedural generator","repository-authored","CC0/project-owned","2026-09-20","1"),VisualAssetLifecycle.Validated);Assert.That(spec.StyleTags,Is.EqualTo(new[]{"grounded","historical"}));Assert.That(spec.Provenance.License,Is.EqualTo("CC0/project-owned"));}
        [Test]public void ReplacingResourceBehindStableVisualIdDoesNotChangeSignatureOrSave(){var fixture=Fixture();var first=fixture.Planner.Plan(fixture.Soldier,fixture.Troop,fixture.Equipment);var replacement=Catalog();var record=replacement.GetAsset(VisualAssetId.Create("WPN_Sword_Proof"));Assert.That(record.ResourceKey,Does.Contain("WPN_Sword_Proof"));var second=new VisualSoldierPlanner(replacement).Plan(fixture.Soldier,fixture.Troop,fixture.Equipment);Assert.That(second.Signature,Is.EqualTo(first.Signature));Assert.That(CampaignSaveData.CurrentSaveVersion,Is.EqualTo(9));}
        [Test]public void HistoricalProfilesUseGenericPipelineWithoutNameBranches(){foreach(var profile in new[]{"deli","humbaraci","bostanci"}){var f=Fixture(profile+"-soldier",profile);var plan=f.Planner.Plan(f.Soldier,f.Troop,f.Equipment);Assert.That(plan.Modules.Count,Is.GreaterThanOrEqualTo(5));}var root=FindRepositoryRoot();var source=File.ReadAllText(Path.Combine(root,"UnityProject","Assets","FOC","Presentation","Visuals","Core","VisualAssembler.cs"));Assert.That(source,Does.Not.Contain("troop == Deli").And.Not.Contain("troop == Humbar").And.Not.Contain("troop == Bostan"));}
        [Test]public void RuntimeHardeningConsumesRealPoolWithoutGameplayRandomOrMaterialConstruction(){var root=FindRepositoryRoot();var unity=Path.Combine(root,"UnityProject","Assets","FOC","Presentation","Visuals","Unity");var assembler=File.ReadAllText(Path.Combine(unity,"VisualSoldier3DAssembler.cs"));var pool=File.ReadAllText(Path.Combine(unity,"VisualSoldierPool.cs"));Assert.That(assembler,Does.Not.Contain("prototypeCache").And.Not.Contain("UnityEngine.Random").And.Not.Contain("new Material"));Assert.That(assembler,Does.Contain("pool.Available.Pop()").And.Contain("ReleasedToPool"));Assert.That(pool,Does.Contain("value.ReleaseVisual()").And.Not.Contain("value.ClearVisual()"));Assert.That(CampaignSaveData.CurrentSaveVersion,Is.EqualTo(9));}

        private sealed class FixtureData{public VisualSoldierPlanner Planner=null!;public SoldierInstance Soldier=null!;public TroopDefinition Troop=null!;public Dictionary<EquipmentInstanceId,EquipmentInstance> Equipment=null!;}
        private static FixtureData Fixture(string soldierId="soldier-1",string profile="deli")
        {
            var sid=SoldierId.Create(soldierId);var lance=E("eq-lance");var sword=E("eq-sword");var mount=E("eq-mount");var loadout=new SoldierLoadout(new[]{new WeaponSlotAssignment(WeaponSlot.Main,lance),new WeaponSlotAssignment(WeaponSlot.Sidearm,sword)},mount:mount);var soldier=new SoldierInstance(sid,UnitGroupId.Create("unit"),TroopDefinitionId.Create(profile),new SoldierRecruitmentProvenance(RecruitmentSourceId.Create("source"),RecruitmentRecordId.Create("record")),loadout,CombatRoleId.Create("role"));var troop=new TroopDefinition(TroopDefinitionId.Create(profile),profile,UnitClassId.Create("class"),CombatRoleId.Create("role"),MountContext.MountedOnly,VisualProfileId.Create(profile));var equipment=new Dictionary<EquipmentInstanceId,EquipmentInstance>{{lance,Instance(lance,EquipmentDefinitionRef.Weapon(WeaponDefinitionId.Create("lance")),sid)},{sword,Instance(sword,EquipmentDefinitionRef.Weapon(WeaponDefinitionId.Create("sword")),sid)},{mount,Instance(mount,EquipmentDefinitionRef.Mount(MountDefinitionId.Create("fast-mount")),sid)}};return new FixtureData{Planner=new VisualSoldierPlanner(Catalog()),Soldier=soldier,Troop=troop,Equipment=equipment};
        }
        private static EquipmentInstance Instance(EquipmentInstanceId id,EquipmentDefinitionRef definition,SoldierId owner)=>new EquipmentInstance(id,definition,EquipmentOwnerRef.Soldier(owner),EquipmentAcquisitionProvenance.CityMarket(CityId.Create("city"),TradeGoodId.Create("good"),new WorldTimestamp(0)));
        private static VisualCatalog Catalog(string equipmentBody="standard-human")
        {
            var c=new VisualCatalog();foreach(var asset in new[]{Asset("BODY_Human_Proof",VisualAssetCategory.Body),Asset("HEAD_A_Proof",VisualAssetCategory.Head),Asset("HEAD_B_Proof",VisualAssetCategory.Head),Asset("CLTH_Light_Proof",VisualAssetCategory.Clothing),Asset("CLTH_Specialist_Proof",VisualAssetCategory.Clothing),Asset("ARM_Guard_Proof",VisualAssetCategory.Clothing),Asset("HDG_Wrapped_Proof",VisualAssetCategory.Headgear),Asset("HDG_Cap_Proof",VisualAssetCategory.Headgear),Asset("HDG_Guard_Proof",VisualAssetCategory.Headgear),Asset("WPN_Lance_Proof",VisualAssetCategory.Weapon),Asset("WPN_Sword_Proof",VisualAssetCategory.Weapon),Asset("MNT_Horse_Proof",VisualAssetCategory.Mount)})c.Add(asset);c.Add(new VisualProfile(VisualProfileId.Create("deli"),"standard-human",V("BODY_Human_Proof"),V("HEAD_A_Proof"),V("CLTH_Light_Proof"),V("HDG_Wrapped_Proof"),VisualQualityTier.Standard,"ottoman"));c.Add(new VisualProfile(VisualProfileId.Create("humbaraci"),"standard-human",V("BODY_Human_Proof"),V("HEAD_B_Proof"),V("CLTH_Specialist_Proof"),V("HDG_Cap_Proof"),VisualQualityTier.Standard,"ottoman"));c.Add(new VisualProfile(VisualProfileId.Create("bostanci"),"standard-human",V("BODY_Human_Proof"),V("HEAD_A_Proof"),V("ARM_Guard_Proof"),V("HDG_Guard_Proof"),VisualQualityTier.Standard,"ottoman"));c.Add(new EquipmentVisualMapping(EquipmentDefinitionRef.Weapon(WeaponDefinitionId.Create("lance")),V("WPN_Lance_Proof"),VisualSocket.RightHand,equipmentBody));c.Add(new EquipmentVisualMapping(EquipmentDefinitionRef.Weapon(WeaponDefinitionId.Create("sword")),V("WPN_Sword_Proof"),VisualSocket.HipLeft,equipmentBody));c.Add(new EquipmentVisualMapping(EquipmentDefinitionRef.Mount(MountDefinitionId.Create("fast-mount")),V("MNT_Horse_Proof"),VisualSocket.Rider,equipmentBody));return c;
        }
        private static VisualAssetRecord Asset(string id,VisualAssetCategory category)=>new VisualAssetRecord(V(id),category,"Assets/FOC/Generated/"+id+".prefab",category==VisualAssetCategory.Mount?RigKind.GenericMount:RigKind.Humanoid,3,1,1);private static VisualAssetId V(string id)=>VisualAssetId.Create(id);private static EquipmentInstanceId E(string id)=>EquipmentInstanceId.Create(id);
        private static VisualAssemblyPlan PlanForTier(VisualQualityTier tier){var id="tier-"+tier.ToString().ToLowerInvariant();var c=new VisualCatalog();c.Add(Asset("BODY",VisualAssetCategory.Body));c.Add(Asset("HEAD",VisualAssetCategory.Head));c.Add(Asset("CLOTH",VisualAssetCategory.Clothing));c.Add(new VisualProfile(VisualProfileId.Create(id),"standard-human",V("BODY"),V("HEAD"),V("CLOTH"),null,tier,"proof"));var soldier=new SoldierInstance(SoldierId.Create(id),UnitGroupId.Create("unit"),TroopDefinitionId.Create(id),new SoldierRecruitmentProvenance(RecruitmentSourceId.Create("source"),RecruitmentRecordId.Create("record")),new SoldierLoadout(),CombatRoleId.Create("role"));var troop=new TroopDefinition(TroopDefinitionId.Create(id),id,UnitClassId.Create("class"),CombatRoleId.Create("role"),MountContext.InfantryOnly,VisualProfileId.Create(id));return new VisualSoldierPlanner(c).Plan(soldier,troop,new Dictionary<EquipmentInstanceId,EquipmentInstance>());}
        private static string FindRepositoryRoot(){var current=new DirectoryInfo(TestContext.CurrentContext.TestDirectory);while(current!=null&&!File.Exists(Path.Combine(current.FullName,"FallOfCavalry.sln")))current=current.Parent;return current?.FullName??throw new DirectoryNotFoundException("Repository root not found.");}
    }
}
