using System;
using System.Collections.Generic;
using System.Linq;
using FOC.Domain.Characters;
using FOC.Domain.Common;
using FOC.Domain.Economy;
using FOC.Domain.Military;
using FOC.Domain.Random;
using FOC.Domain.Soldiers;
using FOC.Domain.Time;

namespace FOC.Domain.Battle
{
    public enum BattleLifecycle { Preparing, Deployment, Active, Resolving, Completed, Aborted }
    public enum BattleTerrainTag { Open, Rough, Forest, Slope, Urban, Bridge }
    public enum BattleFormation { Unspecified, Line, Column, Reserve }
    public enum BattleOrderKind { Hold, Advance, MoveSector, Attack, Withdraw, ChangeFormation }
    public enum BattleCasualtyOutcome { Survived, Wounded, Killed, Captured }
    public enum BattleEndReason { ObjectiveResolved, Withdrawal, Rout, MutualDisengagement, Aborted }

    public sealed class BattleCombatantSnapshot
    {
        private readonly List<EquipmentInstanceId> _equipment;
        public BattleCombatantSnapshot(SoldierId soldierId,UnitGroupId unitGroupId,TroopDefinitionId troopDefinitionId,CombatRoleId roleId,IEnumerable<EquipmentInstanceId> equipment,bool mounted)
        {if(!soldierId.IsValid||!unitGroupId.IsValid||!troopDefinitionId.IsValid||!roleId.IsValid)throw new ArgumentException("Combatant references are invalid.");_equipment=(equipment??throw new ArgumentNullException(nameof(equipment))).Distinct().OrderBy(x=>x).ToList();if(_equipment.Any(x=>!x.IsValid))throw new ArgumentException("Equipment reference is invalid.");SoldierId=soldierId;UnitGroupId=unitGroupId;TroopDefinitionId=troopDefinitionId;CombatRoleId=roleId;IsMounted=mounted;}
        public SoldierId SoldierId{get;}public UnitGroupId UnitGroupId{get;}public TroopDefinitionId TroopDefinitionId{get;}public CombatRoleId CombatRoleId{get;}public IReadOnlyList<EquipmentInstanceId> OrderedEquipment=>_equipment;public bool IsMounted{get;}
    }

    public sealed class BattleUnitSnapshot
    {
        private readonly SortedDictionary<SoldierId,BattleCombatantSnapshot> _combatants;
        public BattleUnitSnapshot(ArmyId armyId,UnitGroupId unitGroupId,CharacterId? commanderId,long campaignHeadcount,IEnumerable<BattleCombatantSnapshot> combatants,MoraleAssessment morale,FatigueAssessment fatigue,DisciplineAssessment discipline)
        {if(!armyId.IsValid||!unitGroupId.IsValid||campaignHeadcount<0)throw new ArgumentException("Unit snapshot is invalid.");_combatants=new SortedDictionary<SoldierId,BattleCombatantSnapshot>();foreach(var x in combatants??throw new ArgumentNullException(nameof(combatants))){if(x==null||!x.UnitGroupId.Equals(unitGroupId)||_combatants.ContainsKey(x.SoldierId))throw new InvalidOperationException("Combatant snapshot does not belong to the Unit Group or is duplicated.");_combatants.Add(x.SoldierId,x);}if(_combatants.Count>campaignHeadcount)throw new InvalidOperationException("Instantiated Soldier count cannot exceed aggregate headcount.");ArmyId=armyId;UnitGroupId=unitGroupId;CommanderId=commanderId;CampaignHeadcount=campaignHeadcount;Morale=morale;Fatigue=fatigue;Discipline=discipline;}
        public ArmyId ArmyId{get;}public UnitGroupId UnitGroupId{get;}public CharacterId? CommanderId{get;}public long CampaignHeadcount{get;}public long AggregateNonInstantiatedStrength=>CampaignHeadcount-_combatants.Count;public IReadOnlyCollection<BattleCombatantSnapshot> OrderedCombatants=>_combatants.Values;public MoraleAssessment Morale{get;}public FatigueAssessment Fatigue{get;}public DisciplineAssessment Discipline{get;}
    }

    public sealed class BattleParticipantSnapshot
    {
        private readonly SortedDictionary<UnitGroupId,BattleUnitSnapshot> _units;
        private readonly SortedDictionary<TradeGoodId,long> _supply;
        public BattleParticipantSnapshot(ArmyId armyId,CharacterId commanderId,IEnumerable<BattleUnitSnapshot> units,IEnumerable<KeyValuePair<TradeGoodId,long>> supply)
        {if(!armyId.IsValid||!commanderId.IsValid)throw new ArgumentException("Participant references are invalid.");_units=new SortedDictionary<UnitGroupId,BattleUnitSnapshot>();foreach(var x in units??throw new ArgumentNullException(nameof(units))){if(x==null||!x.ArmyId.Equals(armyId)||_units.ContainsKey(x.UnitGroupId))throw new InvalidOperationException("Unit snapshot is invalid or duplicated.");_units.Add(x.UnitGroupId,x);}_supply=new SortedDictionary<TradeGoodId,long>();foreach(var x in supply??throw new ArgumentNullException(nameof(supply))){if(!x.Key.IsValid||x.Value<0||_supply.ContainsKey(x.Key))throw new InvalidOperationException("Supply snapshot is invalid or duplicated.");_supply.Add(x.Key,x.Value);}ArmyId=armyId;CommanderId=commanderId;}
        public ArmyId ArmyId{get;}public CharacterId CommanderId{get;}public IReadOnlyCollection<BattleUnitSnapshot> OrderedUnits=>_units.Values;public IReadOnlyDictionary<TradeGoodId,long> OrderedSupply=>_supply;
    }

    public sealed class BattleSideState
    {
        private readonly SortedDictionary<ArmyId,BattleParticipantSnapshot> _participants=new SortedDictionary<ArmyId,BattleParticipantSnapshot>();
        public BattleSideState(BattleSideId id,CharacterId commanderId,IEnumerable<BattleParticipantSnapshot> participants){if(!id.IsValid||!commanderId.IsValid)throw new ArgumentException("Battle side is invalid.");Id=id;CommanderId=commanderId;foreach(var x in participants??throw new ArgumentNullException(nameof(participants))){if(x==null||_participants.ContainsKey(x.ArmyId))throw new InvalidOperationException("Battle participant is duplicated.");_participants.Add(x.ArmyId,x);}if(_participants.Count==0)throw new ArgumentException("Battle side needs a participant.");}
        public BattleSideId Id{get;}public CharacterId CommanderId{get;}public IReadOnlyCollection<BattleParticipantSnapshot> OrderedParticipants=>_participants.Values;public bool ContainsArmy(ArmyId id)=>_participants.ContainsKey(id);
    }

    public sealed class BattleSector
    {
        private readonly SortedSet<BattleSectorId> _adjacent=new SortedSet<BattleSectorId>();private readonly SortedSet<BattleTerrainTag> _terrain=new SortedSet<BattleTerrainTag>();private readonly SortedSet<BattleSideId> _eligibleSides=new SortedSet<BattleSideId>();
        public BattleSector(BattleSectorId id,IEnumerable<BattleTerrainTag>? terrain=null,IEnumerable<BattleSideId>? eligibleSides=null){if(!id.IsValid)throw new ArgumentException(nameof(id));Id=id;foreach(var x in terrain??Array.Empty<BattleTerrainTag>()){if(!Enum.IsDefined(typeof(BattleTerrainTag),x)||!_terrain.Add(x))throw new ArgumentException("Terrain tag is invalid or duplicated.");}foreach(var x in eligibleSides??Array.Empty<BattleSideId>()){if(!x.IsValid||!_eligibleSides.Add(x))throw new ArgumentException("Eligible side is invalid or duplicated.");}}
        public BattleSectorId Id{get;}public IReadOnlyCollection<BattleSectorId> OrderedAdjacent=>_adjacent;public IReadOnlyCollection<BattleTerrainTag> OrderedTerrain=>_terrain;public IReadOnlyCollection<BattleSideId> OrderedEligibleSides=>_eligibleSides;public bool Allows(BattleSideId side)=>_eligibleSides.Count==0||_eligibleSides.Contains(side);internal void Connect(BattleSectorId other){if(!other.IsValid||other.Equals(Id)||!_adjacent.Add(other))throw new InvalidOperationException("Sector adjacency is invalid or duplicated.");}public bool IsAdjacent(BattleSectorId other)=>_adjacent.Contains(other);
    }

    public sealed class BattleSectorGraph
    {
        private readonly SortedDictionary<BattleSectorId,BattleSector> _sectors=new SortedDictionary<BattleSectorId,BattleSector>();public IReadOnlyCollection<BattleSector> OrderedSectors=>_sectors.Values;public void Add(BattleSector sector){if(sector==null||_sectors.ContainsKey(sector.Id))throw new InvalidOperationException("Sector is null or duplicated.");_sectors.Add(sector.Id,sector);}public BattleSector GetRequired(BattleSectorId id){if(!_sectors.TryGetValue(id,out var value))throw new KeyNotFoundException("Battle sector was not found.");return value;}public void Connect(BattleSectorId first,BattleSectorId second){var a=GetRequired(first);var b=GetRequired(second);a.Connect(second);b.Connect(first);}
    }

    public sealed class BattleDeployment
    {
        public BattleDeployment(DeploymentGroupId id,BattleSideId sideId,ArmyId armyId,UnitGroupId unitGroupId,BattleSectorId sectorId,BattleFormation formation,bool reserve=false){if(!id.IsValid||!sideId.IsValid||!armyId.IsValid||!unitGroupId.IsValid||!sectorId.IsValid||!Enum.IsDefined(typeof(BattleFormation),formation))throw new ArgumentException("Deployment is invalid.");Id=id;SideId=sideId;ArmyId=armyId;UnitGroupId=unitGroupId;SectorId=sectorId;Formation=formation;IsReserve=reserve;}public DeploymentGroupId Id{get;}public BattleSideId SideId{get;}public ArmyId ArmyId{get;}public UnitGroupId UnitGroupId{get;}public BattleSectorId SectorId{get;private set;}public BattleFormation Formation{get;private set;}public bool IsReserve{get;}internal void Move(BattleSectorId sector)=>SectorId=sector;internal void ChangeFormation(BattleFormation formation)=>Formation=formation;
    }

    public sealed class BattleOrder
    {
        public BattleOrder(BattleOrderId id,long sequence,BattleOrderKind kind,BattleSideId sideId,CharacterId issuerId,DeploymentGroupId groupId,BattleSectorId? targetSector=null,DeploymentGroupId? targetGroup=null,BattleFormation? formation=null){if(!id.IsValid||sequence<0||!Enum.IsDefined(typeof(BattleOrderKind),kind)||!sideId.IsValid||!issuerId.IsValid||!groupId.IsValid)throw new ArgumentException("Battle order is invalid.");Id=id;Sequence=sequence;Kind=kind;SideId=sideId;IssuerId=issuerId;GroupId=groupId;TargetSector=targetSector;TargetGroup=targetGroup;Formation=formation;}public BattleOrderId Id{get;}public long Sequence{get;}public BattleOrderKind Kind{get;}public BattleSideId SideId{get;}public CharacterId IssuerId{get;}public DeploymentGroupId GroupId{get;}public BattleSectorId? TargetSector{get;}public DeploymentGroupId? TargetGroup{get;}public BattleFormation? Formation{get;}
    }

    public sealed class BattleAttackIntent
    {
        public BattleAttackIntent(DeploymentGroupId attackerGroup,SoldierId attacker,SoldierId target,EquipmentInstanceId weapon,AttackMode attackMode,DamageType damageType){if(!attackerGroup.IsValid||!attacker.IsValid||!target.IsValid||!weapon.IsValid||!Enum.IsDefined(typeof(AttackMode),attackMode)||!Enum.IsDefined(typeof(DamageType),damageType))throw new ArgumentException("Attack intent is invalid.");AttackerGroup=attackerGroup;Attacker=attacker;Target=target;Weapon=weapon;AttackMode=attackMode;DamageType=damageType;}public DeploymentGroupId AttackerGroup{get;}public SoldierId Attacker{get;}public SoldierId Target{get;}public EquipmentInstanceId Weapon{get;}public AttackMode AttackMode{get;}public DamageType DamageType{get;}
    }

    public sealed class BattleCombatOutcome
    {
        public BattleCombatOutcome(BattleEventId eventId,long sequence,SoldierId target,BattleCasualtyOutcome outcome){if(!eventId.IsValid||sequence<0||!target.IsValid||!Enum.IsDefined(typeof(BattleCasualtyOutcome),outcome))throw new ArgumentException("Combat outcome is invalid.");EventId=eventId;Sequence=sequence;Target=target;Outcome=outcome;}public BattleEventId EventId{get;}public long Sequence{get;}public SoldierId Target{get;}public BattleCasualtyOutcome Outcome{get;}
    }

    public sealed class BattleAmmoAllocation
    {public BattleAmmoAllocation(SoldierId soldierId,AmmoFamilyId familyId,long quantity){if(!soldierId.IsValid||!familyId.IsValid||quantity<0)throw new ArgumentException("Ammunition allocation is invalid.");SoldierId=soldierId;FamilyId=familyId;Quantity=quantity;}public SoldierId SoldierId{get;}public AmmoFamilyId FamilyId{get;}public long Quantity{get;private set;}internal void Consume(long quantity){if(quantity<=0||quantity>Quantity)throw new InvalidOperationException("Battle ammunition is insufficient.");Quantity-=quantity;}}
    public sealed class BattleAmmunitionState
    {private readonly SortedDictionary<string,BattleAmmoAllocation> _items=new SortedDictionary<string,BattleAmmoAllocation>(StringComparer.Ordinal);public IReadOnlyCollection<BattleAmmoAllocation> OrderedAllocations=>_items.Values;public void Add(BattleAmmoAllocation item){if(item==null)throw new ArgumentNullException(nameof(item));var key=Key(item.SoldierId,item.FamilyId);if(_items.ContainsKey(key))throw new InvalidOperationException("Ammunition allocation is duplicated.");_items.Add(key,item);}public long QuantityOf(SoldierId soldier,AmmoFamilyId family)=>_items.TryGetValue(Key(soldier,family),out var x)?x.Quantity:0;public void Consume(SoldierId soldier,AmmoFamilyId family,long quantity){if(!_items.TryGetValue(Key(soldier,family),out var x))throw new InvalidOperationException("No battle ammunition allocation exists.");x.Consume(quantity);}private static string Key(SoldierId soldier,AmmoFamilyId family)=>soldier.Value+"\n"+family.Value;}

    public interface IBattleCombatResolver{BattleCombatOutcome Resolve(BattleState battle,BattleAttackIntent intent,IRandomSource random);}
    public interface IBattleAmmunitionPolicy{long RequiredUnits(BattleAttackIntent intent,WeaponDefinition weapon);}
    public interface IBattleArmorPolicy{BattleCombatOutcome Resolve(BattleState battle,BattleAttackIntent intent,WeaponDefinition weapon,IReadOnlyList<ArmorDefinition> armor,IRandomSource random);}

    public sealed class BattleUnitOutcome
    {public BattleUnitOutcome(UnitGroupId unitGroupId,long aggregateLosses,MoraleAssessment morale,FatigueAssessment fatigue,DisciplineAssessment discipline){if(!unitGroupId.IsValid||aggregateLosses<0)throw new ArgumentException("Unit outcome is invalid.");UnitGroupId=unitGroupId;AggregateLosses=aggregateLosses;Morale=morale;Fatigue=fatigue;Discipline=discipline;}public UnitGroupId UnitGroupId{get;}public long AggregateLosses{get;}public MoraleAssessment Morale{get;}public FatigueAssessment Fatigue{get;}public DisciplineAssessment Discipline{get;}}
    public sealed class BattleSoldierOutcome
    {public BattleSoldierOutcome(SoldierId soldierId,BattleCasualtyOutcome outcome){if(!soldierId.IsValid||!Enum.IsDefined(typeof(BattleCasualtyOutcome),outcome))throw new ArgumentException("Soldier outcome is invalid.");SoldierId=soldierId;Outcome=outcome;}public SoldierId SoldierId{get;}public BattleCasualtyOutcome Outcome{get;}}
    public sealed class BattleCharacterOutcome
    {public BattleCharacterOutcome(CharacterId characterId,BattleCasualtyOutcome outcome,CharacterInjurySeverity? injurySeverity=null,CharacterId? captorId=null,ArmyId? captorArmyId=null){if(!characterId.IsValid||!Enum.IsDefined(typeof(BattleCasualtyOutcome),outcome)||(outcome==BattleCasualtyOutcome.Wounded)!=injurySeverity.HasValue||(outcome==BattleCasualtyOutcome.Captured)!=(captorId.HasValue&&captorArmyId.HasValue))throw new ArgumentException("Character outcome is invalid or incomplete.");CharacterId=characterId;Outcome=outcome;InjurySeverity=injurySeverity;CaptorId=captorId;CaptorArmyId=captorArmyId;}public CharacterId CharacterId{get;}public BattleCasualtyOutcome Outcome{get;}public CharacterInjurySeverity? InjurySeverity{get;}public CharacterId? CaptorId{get;}public ArmyId? CaptorArmyId{get;}}
    public sealed class BattleAmmoOutcome
    {public BattleAmmoOutcome(SoldierId soldierId,AmmoFamilyId familyId,long remainingQuantity){if(!soldierId.IsValid||!familyId.IsValid||remainingQuantity<0)throw new ArgumentException("Ammunition outcome is invalid.");SoldierId=soldierId;FamilyId=familyId;RemainingQuantity=remainingQuantity;}public SoldierId SoldierId{get;}public AmmoFamilyId FamilyId{get;}public long RemainingQuantity{get;}}

    public sealed class BattleResult
    {
        public BattleResult(BattleId battleId,BattleEndReason endReason,WorldTimestamp completedAt,long elapsedSteps,BattleSideId? winningSide,IEnumerable<BattleUnitOutcome> units,IEnumerable<BattleSoldierOutcome> soldiers,IEnumerable<BattleCharacterOutcome>? characters=null,IEnumerable<BattleSideId>? participatingSides=null,IEnumerable<BattleAmmoOutcome>? ammunition=null){if(!battleId.IsValid||!Enum.IsDefined(typeof(BattleEndReason),endReason)||elapsedSteps<0)throw new ArgumentException("Battle result is invalid.");BattleId=battleId;EndReason=endReason;CompletedAt=completedAt;ElapsedSteps=elapsedSteps;WinningSide=winningSide;OrderedParticipatingSides=(participatingSides??throw new ArgumentNullException(nameof(participatingSides))).OrderBy(x=>x).ToList();OrderedUnitOutcomes=(units??throw new ArgumentNullException(nameof(units))).OrderBy(x=>x.UnitGroupId).ToList();OrderedSoldierOutcomes=(soldiers??throw new ArgumentNullException(nameof(soldiers))).OrderBy(x=>x.SoldierId).ToList();OrderedCharacterOutcomes=(characters??Array.Empty<BattleCharacterOutcome>()).OrderBy(x=>x.CharacterId).ToList();OrderedAmmunitionOutcomes=(ammunition??Array.Empty<BattleAmmoOutcome>()).OrderBy(x=>x.SoldierId).ThenBy(x=>x.FamilyId).ToList();if(OrderedParticipatingSides.Count<2||OrderedParticipatingSides.Any(x=>!x.IsValid)||OrderedParticipatingSides.Distinct().Count()!=OrderedParticipatingSides.Count||OrderedUnitOutcomes.Select(x=>x.UnitGroupId).Distinct().Count()!=OrderedUnitOutcomes.Count||OrderedSoldierOutcomes.Select(x=>x.SoldierId).Distinct().Count()!=OrderedSoldierOutcomes.Count||OrderedCharacterOutcomes.Select(x=>x.CharacterId).Distinct().Count()!=OrderedCharacterOutcomes.Count||OrderedAmmunitionOutcomes.Select(x=>x.SoldierId.Value+"\n"+x.FamilyId.Value).Distinct(StringComparer.Ordinal).Count()!=OrderedAmmunitionOutcomes.Count)throw new InvalidOperationException("Battle result outcomes are invalid or duplicated.");}
        public BattleId BattleId{get;}public BattleEndReason EndReason{get;}public WorldTimestamp CompletedAt{get;}public long ElapsedSteps{get;}public BattleSideId? WinningSide{get;}public IReadOnlyList<BattleSideId> OrderedParticipatingSides{get;}public IReadOnlyList<BattleUnitOutcome> OrderedUnitOutcomes{get;}public IReadOnlyList<BattleSoldierOutcome> OrderedSoldierOutcomes{get;}public IReadOnlyList<BattleCharacterOutcome> OrderedCharacterOutcomes{get;}public IReadOnlyList<BattleAmmoOutcome> OrderedAmmunitionOutcomes{get;}
    }

    public sealed class BattleState
    {
        private readonly SortedDictionary<BattleSideId,BattleSideState> _sides=new SortedDictionary<BattleSideId,BattleSideState>();private readonly SortedDictionary<DeploymentGroupId,BattleDeployment> _deployments=new SortedDictionary<DeploymentGroupId,BattleDeployment>();private readonly SortedDictionary<BattleOrderId,BattleOrder> _orders=new SortedDictionary<BattleOrderId,BattleOrder>();private readonly List<BattleCombatOutcome> _events=new List<BattleCombatOutcome>();
        public BattleState(BattleId id,WorldTimestamp startedAt,RandomState randomState,IEnumerable<BattleSideState> sides,BattleSectorGraph sectors,BattleAmmunitionState? ammunition=null,BattleLifecycle lifecycle=BattleLifecycle.Preparing,long step=0,bool reconciled=false){if(!id.IsValid||step<0||!Enum.IsDefined(typeof(BattleLifecycle),lifecycle))throw new ArgumentException("Battle state is invalid.");Id=id;StartedAt=startedAt;RandomState=randomState;Sectors=sectors??throw new ArgumentNullException(nameof(sectors));Ammunition=ammunition??new BattleAmmunitionState();Lifecycle=lifecycle;Step=step;IsReconciled=reconciled;foreach(var x in sides??throw new ArgumentNullException(nameof(sides))){if(x==null||_sides.ContainsKey(x.Id))throw new InvalidOperationException("Battle side is duplicated.");_sides.Add(x.Id,x);}if(_sides.Count<2)throw new ArgumentException("Battle requires at least two sides.");}
        public BattleId Id{get;}public WorldTimestamp StartedAt{get;}public BattleLifecycle Lifecycle{get;private set;}public long Step{get;private set;}public RandomState RandomState{get;private set;}public bool IsReconciled{get;private set;}public BattleResult? Result{get;private set;}public BattleSectorGraph Sectors{get;}public BattleAmmunitionState Ammunition{get;}public IReadOnlyCollection<BattleSideState> OrderedSides=>_sides.Values;public IReadOnlyCollection<BattleDeployment> OrderedDeployments=>_deployments.Values;public IReadOnlyCollection<BattleOrder> OrderedOrders=>_orders.Values;public IReadOnlyList<BattleCombatOutcome> OrderedEvents=>_events;
        public void BeginDeployment(){Transition(BattleLifecycle.Preparing,BattleLifecycle.Deployment);}public void BeginActive(){if(_deployments.Count==0)throw new InvalidOperationException("At least one deployment is required.");Transition(BattleLifecycle.Deployment,BattleLifecycle.Active);}public void BeginResolving()=>Transition(BattleLifecycle.Active,BattleLifecycle.Resolving);public void Abort(){if(Lifecycle==BattleLifecycle.Completed||Lifecycle==BattleLifecycle.Aborted)throw new InvalidOperationException("Battle is terminal.");Lifecycle=BattleLifecycle.Aborted;}
        public void Deploy(BattleDeployment deployment){if(Lifecycle!=BattleLifecycle.Deployment)throw new InvalidOperationException("Deployment phase is not active.");if(deployment==null||_deployments.ContainsKey(deployment.Id)||_deployments.Values.Any(x=>x.UnitGroupId.Equals(deployment.UnitGroupId)))throw new InvalidOperationException("Deployment is null or duplicates a Unit Group.");var side=GetSide(deployment.SideId);if(!side.ContainsArmy(deployment.ArmyId))throw new InvalidOperationException("Army does not participate on the deployment side.");var participant=side.OrderedParticipants.Single(x=>x.ArmyId.Equals(deployment.ArmyId));if(!participant.OrderedUnits.Any(x=>x.UnitGroupId.Equals(deployment.UnitGroupId)))throw new InvalidOperationException("Unit Group does not participate.");if(!Sectors.GetRequired(deployment.SectorId).Allows(deployment.SideId))throw new InvalidOperationException("Sector does not allow this side.");_deployments.Add(deployment.Id,deployment);}
        public void Issue(BattleOrder order){if(Lifecycle!=BattleLifecycle.Active)throw new InvalidOperationException("Orders require an active battle.");if(order==null||_orders.ContainsKey(order.Id)||_orders.Values.Any(x=>x.Sequence==order.Sequence))throw new InvalidOperationException("Order is null or duplicated.");var group=GetDeployment(order.GroupId);if(!group.SideId.Equals(order.SideId)||!CanCommand(order.SideId,order.IssuerId,group))throw new InvalidOperationException("Issuer lacks command authority.");if(order.Kind==BattleOrderKind.MoveSector||order.Kind==BattleOrderKind.Advance){if(!order.TargetSector.HasValue||!Sectors.GetRequired(group.SectorId).IsAdjacent(order.TargetSector.Value))throw new InvalidOperationException("Movement target is not adjacent.");group.Move(order.TargetSector.Value);}if(order.Kind==BattleOrderKind.Attack){if(!order.TargetGroup.HasValue||GetDeployment(order.TargetGroup.Value).SideId.Equals(order.SideId))throw new InvalidOperationException("Attack target must be hostile.");}if(order.Kind==BattleOrderKind.ChangeFormation){if(!order.Formation.HasValue)throw new InvalidOperationException("Formation order needs a formation.");group.ChangeFormation(order.Formation.Value);}_orders.Add(order.Id,order);Step++;}
        public void Record(BattleCombatOutcome outcome,RandomState nextRandomState){if(Lifecycle!=BattleLifecycle.Active||outcome==null||_events.Any(x=>x.EventId.Equals(outcome.EventId)||x.Sequence==outcome.Sequence))throw new InvalidOperationException("Combat outcome is invalid or duplicated.");RequireCombatant(outcome.Target);_events.Add(outcome);_events.Sort((a,b)=>a.Sequence.CompareTo(b.Sequence));RandomState=nextRandomState;Step++;}
        public void Complete(BattleResult result){if(Lifecycle!=BattleLifecycle.Resolving||result==null||!result.BattleId.Equals(Id)||result.CompletedAt.CompareTo(StartedAt)<0||!result.OrderedParticipatingSides.SequenceEqual(_sides.Keys)||!AmmoMatches(result))throw new InvalidOperationException("Battle cannot complete with this result.");Result=result;Lifecycle=BattleLifecycle.Completed;}
        public void MarkReconciled(){if(Lifecycle!=BattleLifecycle.Completed||Result==null||IsReconciled)throw new InvalidOperationException("Battle result cannot be reconciled.");IsReconciled=true;}
        public void RestoreDeployment(BattleDeployment deployment){if(deployment==null||_deployments.ContainsKey(deployment.Id)||_deployments.Values.Any(x=>x.UnitGroupId.Equals(deployment.UnitGroupId)))throw new InvalidOperationException("Restored deployment is invalid or duplicated.");_deployments.Add(deployment.Id,deployment);}public void RestoreOrder(BattleOrder order){if(order==null||_orders.ContainsKey(order.Id)||_orders.Values.Any(x=>x.Sequence==order.Sequence))throw new InvalidOperationException("Restored order is invalid or duplicated.");_orders.Add(order.Id,order);}public void RestoreEvent(BattleCombatOutcome outcome){if(outcome==null||_events.Any(x=>x.EventId.Equals(outcome.EventId)||x.Sequence==outcome.Sequence))throw new InvalidOperationException("Restored battle event is invalid or duplicated.");_events.Add(outcome);_events.Sort((a,b)=>a.Sequence.CompareTo(b.Sequence));}public void RestoreResult(BattleResult result){if(result==null||!result.BattleId.Equals(Id)||Lifecycle!=BattleLifecycle.Completed||!result.OrderedParticipatingSides.SequenceEqual(_sides.Keys)||!AmmoMatches(result))throw new InvalidOperationException("Restored result conflicts with battle state.");Result=result;}
        public BattleSideState GetSide(BattleSideId id){if(!_sides.TryGetValue(id,out var value))throw new KeyNotFoundException("Battle side was not found.");return value;}public BattleDeployment GetDeployment(DeploymentGroupId id){if(!_deployments.TryGetValue(id,out var value))throw new KeyNotFoundException("Deployment was not found.");return value;}public BattleCombatantSnapshot RequireCombatant(SoldierId id){foreach(var side in _sides.Values)foreach(var p in side.OrderedParticipants)foreach(var u in p.OrderedUnits)foreach(var c in u.OrderedCombatants)if(c.SoldierId.Equals(id))return c;throw new KeyNotFoundException("Battle combatant was not found.");}
        private bool CanCommand(BattleSideId sideId,CharacterId characterId,BattleDeployment group){var side=GetSide(sideId);if(side.CommanderId.Equals(characterId))return true;var participant=side.OrderedParticipants.Single(x=>x.ArmyId.Equals(group.ArmyId));if(participant.CommanderId.Equals(characterId))return true;var unit=participant.OrderedUnits.Single(x=>x.UnitGroupId.Equals(group.UnitGroupId));return unit.CommanderId.HasValue&&unit.CommanderId.Value.Equals(characterId);}private bool AmmoMatches(BattleResult result){var current=Ammunition.OrderedAllocations.Select(x=>x.SoldierId.Value+"\n"+x.FamilyId.Value+"\n"+x.Quantity).ToList();var reported=result.OrderedAmmunitionOutcomes.Select(x=>x.SoldierId.Value+"\n"+x.FamilyId.Value+"\n"+x.RemainingQuantity).ToList();return current.SequenceEqual(reported,StringComparer.Ordinal);}private void Transition(BattleLifecycle from,BattleLifecycle to){if(Lifecycle!=from)throw new InvalidOperationException("Invalid battle lifecycle transition.");Lifecycle=to;} 
    }

    public sealed class BattleRegistry
    {
        private readonly SortedDictionary<BattleId,BattleState> _items=new SortedDictionary<BattleId,BattleState>();public IReadOnlyCollection<BattleState> OrderedBattles=>_items.Values;public void Add(BattleState battle){if(battle==null||_items.ContainsKey(battle.Id))throw new InvalidOperationException("Battle is null or duplicated.");_items.Add(battle.Id,battle);}public BattleState GetRequired(BattleId id){if(!_items.TryGetValue(id,out var value))throw new KeyNotFoundException("Battle was not found.");return value;}public bool Contains(BattleId id)=>_items.ContainsKey(id);
    }
    public sealed class BattleCampaignState{public BattleCampaignState(BattleRegistry? battles=null){Battles=battles??new BattleRegistry();}public BattleRegistry Battles{get;}}
}
