#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using FOC.Application.HistoricalContent;
using FOC.Domain.AI;
using FOC.Domain.Campaign;
using FOC.Domain.Characters;
using FOC.Domain.Cities;
using FOC.Domain.Cliques;
using FOC.Domain.Common;
using FOC.Domain.Diplomacy;
using FOC.Domain.Economy;
using FOC.Domain.Geography;
using FOC.Domain.Houses;
using FOC.Domain.Military;
using FOC.Domain.Organizations;
using FOC.Domain.Random;
using FOC.Domain.Religion;
using FOC.Domain.Soldiers;
using FOC.Domain.Time;

namespace FOC.Application.Geography
{
    /// <summary>Production-candidate deterministic 1648 vertical-slice composition. No proof fixture is used.</summary>
    public static class VerticalSliceCampaignFactory
    {
        public const string ContentVersion="VERTICAL_SLICE_HISTORICAL-1648-09-01-r1";
        public const string HistoricalAnchorDate="1648-09-01";
        public const string PlayerContentStatus="SLICE_PLAYER";
        public static CampaignRuntimeState Create(string locations,string routes,string historicalContent)
        {
            var content=new HistoricalSliceContentLoader().Load(historicalContent);if(content.ContentVersion!=ContentVersion||content.AnchorDate!=HistoricalAnchorDate)throw new InvalidOperationException("Historical content revision does not match the production factory.");
            var clock=new WorldClock(new WorldTimestamp(0));var characters=Characters(content);var organizations=Organizations();var houses=Houses(characters);var cliques=Cliques();var religion=Religion(content);var cities=Cities(content,organizations);var economy=Economy(content);var diplomacy=Diplomacy();var military=Military(organizations);var soldiers=Soldiers(clock);var ai=AI();var geography=new GeographyCampaignState(new HistoricalGeographyContentLoader().Load(locations,routes));
            return new CampaignRuntimeState(StableId<CampaignTag>.Create("fall-of-cavalry-1648-vertical-slice"),"0.14b-dev",ContentVersion,16480901,2,clock,new SeededRandomSource(16480901),characters,organizations,houses,cliques,religion,cities,economy,diplomacy,military,soldiers,ai:ai,geography:geography);
        }

        private static CharacterRoster Characters(HistoricalSliceContent content)
        {
            var roster=new CharacterRoster();foreach(var x in content.Characters.OrderBy(v=>v.Id,StringComparer.Ordinal)){var s=x.Stats;var importance=(CharacterImportance)Enum.Parse(typeof(CharacterImportance),x.Importance,false);var provenance=x.Truth==HistoricalContentTruth.HistoricalAttested?CharacterProvenance.Historical:CharacterProvenance.Registered;roster.Add(new CharacterState(new NamedCharacter(CharacterId.Create(x.Id),x.Name,provenance),new CharacterStats(s[0],s[1],s[2],s[3],s[4],s[5],s[6],s[7],s[8]),CharacterLocation.InCity(CityId.Create(x.CityId)),55,55,50,35,35,importance));}
            roster.SetRelation(CharacterId.Create("hasan-aga"),CharacterId.Create("ali-cavus"),18);roster.SetRelation(CharacterId.Create("kosem-sultan"),CharacterId.Create("sultan-mehmed-iv"),35);return roster;
        }

        private static OrganizationRegistry Organizations()
        {
            var registry=new OrganizationRegistry();
            var divan=new OrganizationState(OrganizationId.Create("org-imperial-divan"),"Divan-ı Hümayun");divan.AddMembership(new OrganizationMembershipState(CharacterId.Create("sofu-mehmed-pasa"),OrganizationBranch.Party,OrganizationMembershipType.Full,new WorldTimestamp(0)));divan.AddMembership(new OrganizationMembershipState(CharacterId.Create("yusuf-katip"),OrganizationBranch.Diplomacy,OrganizationMembershipType.Salaried,new WorldTimestamp(0)));registry.Add(divan);
            var city=new OrganizationState(OrganizationId.Create("org-istanbul-administration"),"İstanbul Şehir İdaresi");city.AddMembership(new OrganizationMembershipState(CharacterId.Create("ahmed-efendi-kethuda"),OrganizationBranch.Settlements,OrganizationMembershipType.Salaried,new WorldTimestamp(0)));city.AddAssignment(new AssignmentState(AssignmentId.Create("assignment-istanbul-kethuda"),CharacterId.Create("ahmed-efendi-kethuda"),OrganizationBranch.Settlements,CityOfficialRoles.KethudaAssignmentRoleCode,AssignmentAuthority.Responsible,AssignmentTarget.City(CityId.Create("city-istanbul")),AssignmentPresence.PhysicalPresenceRequired,new WorldTimestamp(0)));registry.Add(city);
            var retinue=new OrganizationState(OrganizationId.Create("org-hasan-retinue"),"Hasan Ağa Kapı Halkı");retinue.AddMembership(new OrganizationMembershipState(CharacterId.Create("hasan-aga"),OrganizationBranch.Army,OrganizationMembershipType.Full,new WorldTimestamp(0)));retinue.AddMembership(new OrganizationMembershipState(CharacterId.Create("ali-cavus"),OrganizationBranch.Army,OrganizationMembershipType.Salaried,new WorldTimestamp(0)));retinue.AddAssignment(new AssignmentState(AssignmentId.Create("assignment-hasan-army-command"),CharacterId.Create("hasan-aga"),OrganizationBranch.Army,"army-commander",AssignmentAuthority.FullAuthority,AssignmentTarget.Army(ArmyId.Create("army-hasan-retinue")),AssignmentPresence.RemoteCapable,new WorldTimestamp(0)));registry.Add(retinue);
            var trade=new OrganizationState(OrganizationId.Create("org-marmara-caravan"),"Marmara Ticaret Kervanı");trade.AddMembership(new OrganizationMembershipState(CharacterId.Create("mehmed-celebi-tacir"),OrganizationBranch.Trade,OrganizationMembershipType.Full,new WorldTimestamp(0)));trade.AddAssignment(new AssignmentState(AssignmentId.Create("assignment-marmara-caravan-manager"),CharacterId.Create("mehmed-celebi-tacir"),OrganizationBranch.Trade,"caravan-manager",AssignmentAuthority.Manager,AssignmentTarget.Caravan(CaravanId.Create("caravan-bursa-istanbul")),AssignmentPresence.RemoteCapable,new WorldTimestamp(0)));registry.Add(trade);return registry;
        }

        private static HouseRegistry Houses(CharacterRoster characters){var house=new HouseState(new HouseDefinition(HouseId.Create("house-hasan-aga"),"Hasan Ağa Hanesi"),8,120);house.AddMember(new HouseMember(CharacterId.Create("hasan-aga"),new WorldTimestamp(0)));house.SetHead(CharacterId.Create("hasan-aga"),characters);var registry=new HouseRegistry();registry.Add(house);return registry;}
        private static CliqueRegistry Cliques(){var clique=new CliqueState(new CliqueDefinition(CliqueId.Create("clique-marmara-merchants"),"Marmara Tacirleri Çevresi",CliqueType.Merchant),attitude:CliqueAttitude.Neutral);clique.AddMembership(new CliqueMembership(CharacterId.Create("mehmed-celebi-tacir"),"merchant-representative",new WorldTimestamp(0)));clique.SetLeader(CharacterId.Create("mehmed-celebi-tacir"));clique.AddInfluenceSource(new CliqueInfluenceSourceState(CharacterId.Create("mehmed-celebi-tacir"),InfluenceSourceKind.MemberNetwork,15));var registry=new CliqueRegistry();registry.Add(clique);return registry;}

        private static ReligionCampaignState Religion(HistoricalSliceContent content)
        {
            var definitions=new ReligionRegistry();var islam=new ReligionDefinition(ReligionId.Create("religion-islam"),"İslam");definitions.AddReligion(islam);var hanafi=new SectDefinition(SectId.Create("sect-hanafi"),islam.Id,"Hanefî");definitions.AddSect(hanafi);var christianity=new ReligionDefinition(ReligionId.Create("religion-christianity"),"Hristiyanlık");definitions.AddReligion(christianity);var orthodox=new SectDefinition(SectId.Create("sect-orthodox"),christianity.Id,"Ortodoks");definitions.AddSect(orthodox);var judaism=new ReligionDefinition(ReligionId.Create("religion-judaism"),"Yahudilik");definitions.AddReligion(judaism);var rabbinic=new SectDefinition(SectId.Create("sect-rabbinic"),judaism.Id,"Rabbânî");definitions.AddSect(rabbinic);
            var characterStates=new CharacterReligionRegistry();foreach(var x in content.Characters)characterStates.Add(new CharacterReligionState(CharacterId.Create(x.Id),islam.Id,hanafi.Id));var state=new ReligionCampaignState(definitions,characterStates);foreach(var city in content.Cities){var profile=new ReligionProfile(ReligionProfileTarget.City(CityId.Create(city.Id)));profile.Add(new ReligionProfileEntry(islam.Id,hanafi.Id,1));profile.Add(new ReligionProfileEntry(christianity.Id,orthodox.Id,1));profile.Add(new ReligionProfileEntry(judaism.Id,rabbinic.Id,1));state.AddProfile(profile);}return state;
        }

        private static CityRegistry Cities(HistoricalSliceContent content,OrganizationRegistry organizations)
        {
            var registry=new CityRegistry();foreach(var record in content.Cities.OrderBy(x=>x.Id,StringComparer.Ordinal)){var city=new CityState(new CityDefinition(CityId.Create(record.Id),record.Name,Areas(record.Id)),new CityMetricsState(1));foreach(var buildingName in record.Buildings){var kind=(CityBuildingKind)Enum.Parse(typeof(CityBuildingKind),buildingName,false);var area=city.GetRequiredArea(CityBuildingRules.RequiredArea(kind));if(area.Fullness==CityAreaFullness.Empty)area.SetFullness(CityAreaFullness.Low);area.ActivateBuilding(BuildingId(record.Id,kind));}foreach(var name in record.Infrastructure){var kind=(CityInfrastructureType)Enum.Parse(typeof(CityInfrastructureType),name,false);city.SetInfrastructure(new CityInfrastructureState(kind,true,CityInfrastructureCondition.Serviceable));}if(record.Id=="city-istanbul")city.AddOfficial(new CityOfficialReference(CityOfficialRole.Kethuda,organizations.GetRequired(OrganizationId.Create("org-istanbul-administration")).Id,AssignmentId.Create("assignment-istanbul-kethuda")));registry.Add(city);}return registry;
        }
        private static IEnumerable<CityAreaDefinition> Areas(string cityId){foreach(CityAreaType area in Enum.GetValues(typeof(CityAreaType))){var buildings=new List<CityBuildingDefinition>();foreach(CityBuildingKind kind in Enum.GetValues(typeof(CityBuildingKind)))if(CityBuildingRules.RequiredArea(kind)==area)buildings.Add(new CityBuildingDefinition(BuildingId(cityId,kind),DisplayBuilding(kind),kind,area));yield return new CityAreaDefinition(area,buildings,"ottoman-1648");}}
        private static CityBuildingId BuildingId(string cityId,CityBuildingKind kind)=>CityBuildingId.Create("building-"+cityId.Substring(5)+"-"+kind.ToString().ToLowerInvariant());
        private static string DisplayBuilding(CityBuildingKind kind)=>kind switch{CityBuildingKind.Market=>"Pazar",CityBuildingKind.Inn=>"Han",CityBuildingKind.Blacksmith=>"Demirci",CityBuildingKind.Carpenter=>"Marangoz",CityBuildingKind.Tannery=>"Tabakhane",CityBuildingKind.Soapworks=>"Sabunhane",CityBuildingKind.PaperMill=>"Kâğıt İmalathanesi",_=>kind.ToString()};

        private static EconomyState Economy(HistoricalSliceContent content)
        {
            var goods=new TradeGoodRegistry();foreach(var x in content.Goods)goods.Add(new TradeGoodDefinition(TradeGoodId.Create(x.Id),x.Name,(TradeGoodCategory)Enum.Parse(typeof(TradeGoodCategory),x.Category,false),x.Weight,x.Food,x.Military,x.Luxury,x.Value));
            var recipes=new ProductionRecipeRegistry();foreach(var x in content.Recipes)recipes.Add(new ProductionRecipeDefinition(ProductionRecipeId.Create(x.Id),x.Name,(CityBuildingKind)Enum.Parse(typeof(CityBuildingKind),x.Building,false),Lines(x.Inputs),Lines(x.Outputs)));var state=new EconomyState(goods,recipes);
            foreach(var city in content.Cities){var stock=new CityStockState();var demand=new CityDemandState();foreach(var x in content.Stocks.Where(v=>v.CityId==city.Id)){stock.AddInitial(new TradeGoodStock(TradeGoodId.Create(x.GoodId),x.Quantity));if(x.Demand>0)demand.AddSource(new DemandSourceState("slice-tuning-"+city.Id+"-"+x.GoodId,DemandSourceKind.Population,TradeGoodId.Create(x.GoodId),x.Demand));}state.AddMarket(new CityMarketState(CityId.Create(city.Id),500,stock,demand));}
            var caravan=new CaravanState(CaravanId.Create("caravan-bursa-istanbul"),EconomicOwnerRef.Character(CharacterId.Create("mehmed-celebi-tacir")),CharacterId.Create("mehmed-celebi-tacir"),CityId.Create("city-bursa"),CityId.Create("city-istanbul"),200,300,new TradeRepresentativeReference(CharacterId.Create("mehmed-celebi-tacir"),OrganizationId.Create("org-marmara-caravan"),AssignmentId.Create("assignment-marmara-caravan-manager")));caravan.Cargo.Add(TradeGoodId.Create("silk-cloth"),4,caravan.WeightCapacity,goods);state.Caravans.Add(caravan);return state;
        }
        private static IEnumerable<RecipeGoodsLine> Lines(string value){foreach(var pair in value.Split(';')){var p=pair.Split(':');yield return new RecipeGoodsLine(TradeGoodId.Create(p[0]),long.Parse(p[1],System.Globalization.CultureInfo.InvariantCulture));}}

        private static DiplomacyState Diplomacy()
        {
            var state=new DiplomacyState();var own=FactionId.Create("faction-ottoman-state");var venice=FactionId.Create("faction-republic-of-venice");state.Actors.Add(new DiplomaticActorState(own,"Devlet-i Aliyye"));state.Actors.Add(new DiplomaticActorState(venice,"Venedik Cumhuriyeti"));state.Relations.Add(new DiplomaticRelationState(new DiplomaticActorPair(own,venice),DiplomaticDisposition.Tense,new WorldTimestamp(0)));var ownInfo=new ActorInformationState(own);state.Information.Add(ownInfo);state.Information.Add(new ActorInformationState(venice));var report=new ReportState(ReportId.Create("report-istanbul-city-condition"),ReportType.City,ReportSourceRef.Character(ReportSourceKind.Official,CharacterId.Create("yusuf-katip")),own,ReportQuality.Medium,ReportDetailLevel.Standard,new WorldTimestamp(0),new[]{new ReportObservation(new ReportSubjectRef(ReportSubjectKind.City,"city-istanbul"),ReportObservationKind.CityCondition,ObservationPrecision.Qualitative,qualitative:QualitativeObservation.Stable)});state.Reports.Add(report);return state;
        }

        private static CampaignMilitaryState Military(OrganizationRegistry organizations)
        {
            var state=new CampaignMilitaryState();var commander=CharacterId.Create("hasan-aga");var org=organizations.GetRequired(OrganizationId.Create("org-hasan-retinue"));var assignment=AssignmentId.Create("assignment-hasan-army-command");var source=new RecruitmentSourceState(RecruitmentSourceId.Create("recruitment-hasan-retinue"),RecruitmentType.Retinue,20,new RecruitmentAuthorityReference(commander,org.Id,assignment));state.RecruitmentSources.Add(source);var armyId=ArmyId.Create("army-hasan-retinue");var army=new ArmyState(armyId,"Hasan Ağa Kapı Halkı",ArmyOwnerRef.Character(commander),ArmyOwnerRef.Character(commander),ArmyLocation.InCity(CityId.Create("city-istanbul")),new ArmyCommanderReference(commander,org.Id,assignment));army.SetLifecycle(ArmyLifecycle.Active);army.Supply.AddInitial(TradeGoodId.Create("grain"),16);army.Supply.AddInitial(TradeGoodId.Create("ammunition"),12);army.AddSupplyRequirement(new SupplyRequirementState(TradeGoodId.Create("grain"),SupplyPurpose.Food,8));army.AddSupplyRequirement(new SupplyRequirementState(TradeGoodId.Create("ammunition"),SupplyPurpose.Ammunition,6));state.Armies.Add(army);
            AddUnit(state,source,armyId,"unit-hasan-sipahi","troop-timarli-sipahi",4,commander,"record-hasan-sipahi");AddUnit(state,source,armyId,"unit-hasan-cebeli","troop-cebeli",4,CharacterId.Create("ali-cavus"),"record-hasan-cebeli");AddUnit(state,source,armyId,"unit-hasan-tufekci","troop-tufekli-piyade",4,null,"record-hasan-tufekci");return state;
        }
        private static void AddUnit(CampaignMilitaryState state,RecruitmentSourceState source,ArmyId army,string unit,string troop,long count,CharacterId? commander,string record){var value=new UnitGroupState(UnitGroupId.Create(unit),army,source.Id,troop,count,commander,new MoraleState(MoraleAssessment.Steady),new FatigueState(FatigueAssessment.Rested),new DisciplineState(DisciplineAssessment.Ordered));state.RestoreUnit(value);state.RestoreRecord(new RecruitmentRecord(RecruitmentRecordId.Create(record),source.Id,army,value.Id,count,new WorldTimestamp(0)));}

        private static SoldierCampaignState Soldiers(WorldClock clock)
        {
            var state=new SoldierCampaignState();state.Definitions.Add(new TroopDefinition(TroopDefinitionId.Create("troop-timarli-sipahi"),"Timarlı Sipahi",UnitClassId.Create("mounted"),CombatRoleId.Create("mounted-shock"),MountContext.MountedOnly,VisualProfileId.Create("sipahi"),new[]{WeaponFamily.Lance,WeaponFamily.Sabre}));state.Definitions.Add(new TroopDefinition(TroopDefinitionId.Create("troop-cebeli"),"Cebeli",UnitClassId.Create("mounted-support"),CombatRoleId.Create("mounted-support"),MountContext.MountedOnly,VisualProfileId.Create("cebeli"),new[]{WeaponFamily.Lance,WeaponFamily.Sabre}));state.Definitions.Add(new TroopDefinition(TroopDefinitionId.Create("troop-tufekli-piyade"),"Tüfekli Piyade",UnitClassId.Create("infantry"),CombatRoleId.Create("firearm"),MountContext.InfantryOnly,VisualProfileId.Create("tufekci"),new[]{WeaponFamily.Firearm,WeaponFamily.Yatagan}));
            state.Definitions.Add(new WeaponDefinition(WeaponDefinitionId.Create("kilic"),"Kılıç",WeaponFamily.Sabre,new[]{WeaponSlot.Sidearm},new[]{new WeaponAttackOption(AttackMode.Slash,DamageType.Cut)},MountContext.Either,TradeGoodId.Create("weapons"),VisualProfileId.Create("kilic")));state.Definitions.Add(new WeaponDefinition(WeaponDefinitionId.Create("mizrak"),"Mızrak",WeaponFamily.Lance,new[]{WeaponSlot.Main},new[]{new WeaponAttackOption(AttackMode.Thrust,DamageType.Pierce)},MountContext.MountedOnly,TradeGoodId.Create("weapons"),VisualProfileId.Create("mizrak")));state.Definitions.Add(new WeaponDefinition(WeaponDefinitionId.Create("fitilli-tufek"),"Fitilli Tüfek",WeaponFamily.Firearm,new[]{WeaponSlot.Main},new[]{new WeaponAttackOption(AttackMode.Thrust,DamageType.Pierce)},MountContext.InfantryOnly,TradeGoodId.Create("weapons"),VisualProfileId.Create("fitilli-tufek"),true,AmmoFamilyId.Create("lead-shot")));state.Definitions.Add(new ArmorDefinition(ArmorDefinitionId.Create("zirh-gomlek"),"Zırh Gömlek",ArmorSlot.Body,TradeGoodId.Create("armor"),VisualProfileId.Create("zirh-gomlek"),"slice-tuning-serviceable"));state.Definitions.Add(new ShieldDefinition(ShieldDefinitionId.Create("kalkan"),"Kalkan",TradeGoodId.Create("armor"),VisualProfileId.Create("kalkan"),"round"));state.Definitions.Add(new MountDefinition(MountDefinitionId.Create("sipahi-ati"),"Sipahi Atı",TradeGoodId.Create("horses"),VisualProfileId.Create("sipahi-ati"),"mounted"));state.Definitions.Add(new AuxiliaryEquipmentDefinition(AuxiliaryEquipmentDefinitionId.Create("tufek-muhimmat"),"Tüfek Mühimmatı",AuxiliaryEquipmentKind.Ammunition,TradeGoodId.Create("ammunition"),VisualProfileId.Create("tufek-muhimmat"),AmmoFamilyId.Create("lead-shot")));
            AddMountedSoldier(state,"soldier-hasan-01","unit-hasan-sipahi","troop-timarli-sipahi","record-hasan-sipahi",clock.Now,true);AddMountedSoldier(state,"soldier-hasan-02","unit-hasan-sipahi","troop-timarli-sipahi","record-hasan-sipahi",clock.Now,false);AddMountedSoldier(state,"soldier-cebeli-01","unit-hasan-cebeli","troop-cebeli","record-hasan-cebeli",clock.Now,true);AddMountedSoldier(state,"soldier-cebeli-02","unit-hasan-cebeli","troop-cebeli","record-hasan-cebeli",clock.Now,false);AddFirearmSoldier(state,"soldier-tufekci-01",clock.Now);AddFirearmSoldier(state,"soldier-tufekci-02",clock.Now);return state;
        }
        private static void AddMountedSoldier(SoldierCampaignState state,string soldier,string unit,string troop,string record,WorldTimestamp at,bool shield)
        {
            var sid=SoldierId.Create(soldier);var lance=Equipment(state,soldier+"-mizrak",EquipmentDefinitionRef.Weapon(WeaponDefinitionId.Create("mizrak")),sid,record,"weapons",at);var sword=Equipment(state,soldier+"-kilic",EquipmentDefinitionRef.Weapon(WeaponDefinitionId.Create("kilic")),sid,record,"weapons",at);var armor=Equipment(state,soldier+"-zirh",EquipmentDefinitionRef.Armor(ArmorDefinitionId.Create("zirh-gomlek")),sid,record,"armor",at);var mount=Equipment(state,soldier+"-at",EquipmentDefinitionRef.Mount(MountDefinitionId.Create("sipahi-ati")),sid,record,"horses",at);EquipmentInstanceId? shieldId=null;if(shield)shieldId=Equipment(state,soldier+"-kalkan",EquipmentDefinitionRef.Shield(ShieldDefinitionId.Create("kalkan")),sid,record,"armor",at).Id;state.RestoreSoldier(new SoldierInstance(sid,UnitGroupId.Create(unit),TroopDefinitionId.Create(troop),new SoldierRecruitmentProvenance(RecruitmentSourceId.Create("recruitment-hasan-retinue"),RecruitmentRecordId.Create(record)),new SoldierLoadout(new[]{new WeaponSlotAssignment(WeaponSlot.Main,lance.Id),new WeaponSlotAssignment(WeaponSlot.Sidearm,sword.Id)},new[]{new ArmorSlotAssignment(ArmorSlot.Body,armor.Id)},shieldId,mount.Id),CombatRoleId.Create(troop=="troop-timarli-sipahi"?"mounted-shock":"mounted-support"),SoldierExperienceAssessment.Experienced,SoldierTrainingAssessment.Trained));
        }
        private static void AddFirearmSoldier(SoldierCampaignState state,string soldier,WorldTimestamp at){var sid=SoldierId.Create(soldier);const string record="record-hasan-tufekci";var gun=Equipment(state,soldier+"-tufek",EquipmentDefinitionRef.Weapon(WeaponDefinitionId.Create("fitilli-tufek")),sid,record,"weapons",at);var ammo=Equipment(state,soldier+"-muhimmat",EquipmentDefinitionRef.Auxiliary(AuxiliaryEquipmentDefinitionId.Create("tufek-muhimmat")),sid,record,"ammunition",at);state.RestoreSoldier(new SoldierInstance(sid,UnitGroupId.Create("unit-hasan-tufekci"),TroopDefinitionId.Create("troop-tufekli-piyade"),new SoldierRecruitmentProvenance(RecruitmentSourceId.Create("recruitment-hasan-retinue"),RecruitmentRecordId.Create(record)),new SoldierLoadout(new[]{new WeaponSlotAssignment(WeaponSlot.Main,gun.Id),new WeaponSlotAssignment(WeaponSlot.Ammo,ammo.Id)}),CombatRoleId.Create("firearm"),SoldierExperienceAssessment.Inexperienced,SoldierTrainingAssessment.Trained));}
        private static EquipmentInstance Equipment(SoldierCampaignState state,string id,EquipmentDefinitionRef definition,SoldierId soldier,string record,string good,WorldTimestamp at){var item=new EquipmentInstance(EquipmentInstanceId.Create("equipment-"+id),definition,EquipmentOwnerRef.Soldier(soldier),EquipmentAcquisitionProvenance.RecruitmentProvided(RecruitmentRecordId.Create(record),TradeGoodId.Create(good),at),"slice-tuning-serviceable");state.RestoreEquipment(item);return item;}
        private static AICampaignState AI(){var state=new AICampaignState();state.Controllers.Add(new AIControllerState(AIControllerId.Create("controller-mehmed-celebi-trade"),AIDecisionOwnerRef.Character(CharacterId.Create("mehmed-celebi-tacir")),AIPriorityProfileId.Create("priority-trade-slice-tuning"),AIDecisionQualityProfileId.Create("quality-standard-slice-tuning"),AISchedulingProfileId.Create("schedule-regular-slice-tuning"),new RandomState(1648,0),CharacterAIProfileId.Create("character-prudent-merchant")));return state;}
    }
}
