using System;
using FOC.Domain.Campaign;
using FOC.Domain.Common;
using FOC.Domain.Diplomacy;
using FOC.Domain.Validation;
using FOC.Domain.Time;

namespace FOC.Application.Diplomacy
{
    public sealed class DiplomacyCommandService
    {
        private readonly CampaignRuntimeState _campaign;public DiplomacyCommandService(CampaignRuntimeState campaign){_campaign=campaign??throw new ArgumentNullException(nameof(campaign));}
        public void RegisterOrder(EnvoyMissionState mission,DiplomaticMessageState message,DiplomaticActionState action){if(mission==null||message==null||action==null)throw new ArgumentNullException();if(_campaign.Diplomacy.Missions.Contains(mission.Id)||_campaign.Diplomacy.Messages.Contains(message.Id)||_campaign.Diplomacy.Actions.Contains(action.Id))throw new InvalidOperationException("Duplicate diplomatic order component.");if(!mission.Id.Equals(action.MissionId)||!message.Id.Equals(action.MessageId)||message.CarrierKind!=MessageCarrierKind.EnvoyMission||!message.EnvoyMissionId!.Value.Equals(mission.Id)||!mission.Mandate.Allows(action.Kind))throw new InvalidOperationException("Order contracts do not match.");var probe=new DiplomacyState(_campaign.Diplomacy.Actors,_campaign.Diplomacy.Relations,new DiplomaticActionRegistry(),new EnvoyMissionRegistry(),new DiplomaticMessageRegistry(),_campaign.Diplomacy.Reports,_campaign.Diplomacy.Information,_campaign.Diplomacy.Agreements);probe.Missions.Add(mission);probe.Messages.Add(message);probe.Actions.Add(action);var candidate=new CampaignRuntimeState(_campaign.CampaignId,_campaign.GameVersion,_campaign.ContentDataVersion,_campaign.WorldSeed,_campaign.WorldGenRevision,_campaign.Clock,_campaign.Random,_campaign.Characters,_campaign.Organizations,_campaign.Houses,_campaign.Cliques,_campaign.Religion,_campaign.Cities,_campaign.Economy,probe);if(!new DiplomacyInvariantValidator().Validate(candidate).IsValid)throw new InvalidOperationException("Diplomatic order violates authority or references.");_campaign.Diplomacy.Missions.Add(mission);_campaign.Diplomacy.Messages.Add(message);_campaign.Diplomacy.Actions.Add(action);}
        public void Dispatch(DiplomaticActionId actionId,WorldTimestamp at){RequireCurrent(at);var action=_campaign.Diplomacy.Actions.GetRequired(actionId);var mission=_campaign.Diplomacy.Missions.GetRequired(action.MissionId);var message=_campaign.Diplomacy.Messages.GetRequired(action.MessageId);if(action.Status!=DiplomaticActionStatus.Ordered||mission.Phase!=EnvoyMissionPhase.PendingDeparture||message.Status!=CommunicationStatus.Created)throw new InvalidOperationException("Order cannot dispatch twice.");mission.Depart(at);message.Dispatch(at);action.MarkDispatched();}
        public void Arrive(EnvoyMissionId missionId,WorldTimestamp at){RequireCurrent(at);var mission=_campaign.Diplomacy.Missions.GetRequired(missionId);var character=_campaign.Characters.GetRequired(mission.CharacterId);if(character.IsDead||character.Location.Kind==FOC.Domain.Characters.CharacterLocationKind.Captivity)throw new InvalidOperationException("Unavailable Envoy cannot arrive.");mission.Arrive(at);}
        public void DeliverAndResolve(DiplomaticActionId actionId,DiplomaticActionOutcome outcome,WorldTimestamp at){RequireCurrent(at);if(!Enum.IsDefined(typeof(DiplomaticActionOutcome),outcome))throw new ArgumentOutOfRangeException(nameof(outcome));var action=_campaign.Diplomacy.Actions.GetRequired(actionId);var mission=_campaign.Diplomacy.Missions.GetRequired(action.MissionId);var message=_campaign.Diplomacy.Messages.GetRequired(action.MessageId);if(mission.Phase!=EnvoyMissionPhase.Arrived&&mission.Phase!=EnvoyMissionPhase.AwaitingAudience)throw new InvalidOperationException("Envoy has not arrived.");if(message.Status!=CommunicationStatus.Dispatched||!message.DispatchedAt.HasValue||at.Ticks<=message.DispatchedAt.Value.Ticks||action.Status!=DiplomaticActionStatus.Dispatched)throw new InvalidOperationException("Action cannot resolve instantly or twice.");message.Deliver(action.TargetActorId,at);action.Resolve(message,outcome,at);}
        private void RequireCurrent(WorldTimestamp at){if(!at.Equals(_campaign.Clock.Now))throw new InvalidOperationException("Diplomacy progress must use current WorldClock time.");}
    }
    public sealed class ReportDeliveryService
    {
        private readonly CampaignRuntimeState _campaign;public ReportDeliveryService(CampaignRuntimeState campaign){_campaign=campaign??throw new ArgumentNullException(nameof(campaign));}public void Dispatch(ReportId id,WorldTimestamp at){RequireCurrent(at);_campaign.Diplomacy.Reports.GetRequired(id).Dispatch(at);}public void Deliver(ReportId id,FactionId recipient,WorldTimestamp at){RequireCurrent(at);var report=_campaign.Diplomacy.Reports.GetRequired(id);if(!report.RecipientActorId.Equals(recipient))throw new InvalidOperationException("Wrong recipient.");var information=_campaign.Diplomacy.Information.GetRequired(recipient);information.Receive(report,at);}private void RequireCurrent(WorldTimestamp at){if(!at.Equals(_campaign.Clock.Now))throw new InvalidOperationException("Report progress must use current WorldClock time.");}
    }
}
