using System;
using System.Collections.Generic;
using FOC.Domain.Characters;
using FOC.Domain.Cities;
using FOC.Domain.Common;
using FOC.Domain.Economy;
using FOC.Domain.Organizations;
using FOC.Domain.Time;

namespace FOC.Domain.Military
{
    public enum ArmyOwnerKind{Character,Faction,Organization,CityGarrison,Institution,MercenaryCompany,CaravanSecurity}
    public enum ArmyLifecycle{Assembling,Active,Disbanding,Disbanded}
    public enum ArmyLocationKind{City,Camp,InTransit}
    public enum RecruitmentType{Retinue,TimarService,CentralSalaried,Garrison,LocalLevy,Mercenary,Irregular}
    public enum SupplyPurpose{Food,Fodder,Ammunition,General}
    public enum SupplyCondition{Supplied,Insufficient,Exhausted,NotRequired}
    public enum MoraleAssessment{Unassessed,Steady,Shaken,Wavering}
    public enum FatigueAssessment{Unassessed,Rested,Fatigued,Exhausted}
    public enum DisciplineAssessment{Unassessed,Ordered,Disrupted}
    public enum PayrollFundingSourceKind{CityMarket,Caravan}
    public enum CommandNodeKind{Army,UnitGroup}

    public readonly struct ArmyOwnerRef:IEquatable<ArmyOwnerRef>
    {
        private ArmyOwnerRef(ArmyOwnerKind kind,string id){if(string.IsNullOrWhiteSpace(id))throw new ArgumentException("Owner ID is required.",nameof(id));Kind=kind;Id=id;}
        public ArmyOwnerKind Kind{get;}public string Id{get;}
        public static ArmyOwnerRef Character(CharacterId id){Require(id.IsValid);return new ArmyOwnerRef(ArmyOwnerKind.Character,id.Value);}public static ArmyOwnerRef Faction(FactionId id){Require(id.IsValid);return new ArmyOwnerRef(ArmyOwnerKind.Faction,id.Value);}public static ArmyOwnerRef Organization(OrganizationId id){Require(id.IsValid);return new ArmyOwnerRef(ArmyOwnerKind.Organization,id.Value);}public static ArmyOwnerRef CityGarrison(CityId id){Require(id.IsValid);return new ArmyOwnerRef(ArmyOwnerKind.CityGarrison,id.Value);}public static ArmyOwnerRef Institution(CityBuildingId id){Require(id.IsValid);return new ArmyOwnerRef(ArmyOwnerKind.Institution,id.Value);}public static ArmyOwnerRef MercenaryCompany(string id)=>new ArmyOwnerRef(ArmyOwnerKind.MercenaryCompany,id);public static ArmyOwnerRef CaravanSecurity(CaravanId id){Require(id.IsValid);return new ArmyOwnerRef(ArmyOwnerKind.CaravanSecurity,id.Value);}
        public bool Equals(ArmyOwnerRef other)=>Kind==other.Kind&&StringComparer.Ordinal.Equals(Id,other.Id);public override bool Equals(object? obj)=>obj is ArmyOwnerRef other&&Equals(other);public override int GetHashCode()=>((int)Kind*397)^StringComparer.Ordinal.GetHashCode(Id??string.Empty);private static void Require(bool valid){if(!valid)throw new ArgumentException("Owner ID is invalid.");}
    }

    public sealed class ArmyLocation
    {
        private ArmyLocation(ArmyLocationKind kind,CityId? cityId,WorldPosition position){Kind=kind;CityId=cityId;Position=position;}
        public ArmyLocationKind Kind{get;}public CityId? CityId{get;}public WorldPosition Position{get;}
        public static ArmyLocation InCity(CityId id){if(!id.IsValid)throw new ArgumentException(nameof(id));return new ArmyLocation(ArmyLocationKind.City,id,default);}
        public static ArmyLocation AtCamp(WorldPosition position)=>new ArmyLocation(ArmyLocationKind.Camp,null,position);
        public static ArmyLocation InTransit(WorldPosition position)=>new ArmyLocation(ArmyLocationKind.InTransit,null,position);
    }

    public sealed class ArmyCommanderReference
    {
        public ArmyCommanderReference(CharacterId characterId,OrganizationId organizationId,AssignmentId assignmentId){if(!characterId.IsValid||!organizationId.IsValid||!assignmentId.IsValid)throw new ArgumentException("Commander reference is invalid.");CharacterId=characterId;OrganizationId=organizationId;AssignmentId=assignmentId;}
        public CharacterId CharacterId{get;}public OrganizationId OrganizationId{get;}public AssignmentId AssignmentId{get;}
    }

    public sealed class RecruitmentAuthorityReference
    {
        public RecruitmentAuthorityReference(CharacterId characterId,OrganizationId organizationId,AssignmentId assignmentId){if(!characterId.IsValid||!organizationId.IsValid||!assignmentId.IsValid)throw new ArgumentException("Recruitment authority reference is invalid.");CharacterId=characterId;OrganizationId=organizationId;AssignmentId=assignmentId;}
        public CharacterId CharacterId{get;}public OrganizationId OrganizationId{get;}public AssignmentId AssignmentId{get;}
    }

    public sealed class RecruitmentSourceState
    {
        public RecruitmentSourceState(RecruitmentSourceId id,RecruitmentType type,long availableHeadcount,RecruitmentAuthorityReference authority,CityId? cityId=null,CityBuildingId? institutionId=null,string obligationOrContractId="",bool active=true)
        {
            if(!id.IsValid)throw new ArgumentException("RecruitmentSourceId is invalid.",nameof(id));if(!Enum.IsDefined(typeof(RecruitmentType),type))throw new ArgumentOutOfRangeException(nameof(type));if(availableHeadcount<0)throw new ArgumentOutOfRangeException(nameof(availableHeadcount));if(cityId.HasValue&&!cityId.Value.IsValid)throw new ArgumentException("City reference is invalid.",nameof(cityId));if(institutionId.HasValue&&!institutionId.Value.IsValid)throw new ArgumentException("Institution reference is invalid.",nameof(institutionId));if(institutionId.HasValue&&!cityId.HasValue)throw new ArgumentException("Institution recruitment requires a City.",nameof(institutionId));if(type==RecruitmentType.Garrison&&!cityId.HasValue)throw new ArgumentException("Garrison recruitment requires a City.",nameof(cityId));if((type==RecruitmentType.TimarService||type==RecruitmentType.Mercenary)&&string.IsNullOrWhiteSpace(obligationOrContractId))throw new ArgumentException("Service and mercenary recruitment require an explicit obligation/contract reference.",nameof(obligationOrContractId));
            Id=id;Type=type;AvailableHeadcount=availableHeadcount;Authority=authority??throw new ArgumentNullException(nameof(authority));CityId=cityId;InstitutionId=institutionId;ObligationOrContractId=obligationOrContractId??string.Empty;IsActive=active;
        }
        public RecruitmentSourceId Id{get;}public RecruitmentType Type{get;}public long AvailableHeadcount{get;private set;}public RecruitmentAuthorityReference Authority{get;}public CityId? CityId{get;}public CityBuildingId? InstitutionId{get;}public string ObligationOrContractId{get;}public bool IsActive{get;private set;}public bool CanConsume(long quantity)=>IsActive&&quantity>0&&AvailableHeadcount>=quantity;
        public void Consume(long quantity){if(!IsActive||quantity<=0||AvailableHeadcount<quantity)throw new InvalidOperationException("Recruitment source cannot provide the requested headcount.");AvailableHeadcount-=quantity;}public void Deactivate()=>IsActive=false;
    }

    public sealed class RecruitmentSourceRegistry
    {
        private readonly SortedDictionary<RecruitmentSourceId,RecruitmentSourceState> _items=new SortedDictionary<RecruitmentSourceId,RecruitmentSourceState>();public IReadOnlyCollection<RecruitmentSourceState> OrderedSources=>_items.Values;public int Count=>_items.Count;public void Add(RecruitmentSourceState item){if(item==null)throw new ArgumentNullException(nameof(item));if(_items.ContainsKey(item.Id))throw new InvalidOperationException("Duplicate RecruitmentSourceId.");_items.Add(item.Id,item);}public RecruitmentSourceState GetRequired(RecruitmentSourceId id){if(!_items.TryGetValue(id,out var item))throw new KeyNotFoundException("Recruitment source was not found.");return item;}
    }

    public sealed class MoraleState{public MoraleState(MoraleAssessment assessment=MoraleAssessment.Unassessed){Set(assessment);}public MoraleAssessment Assessment{get;private set;}public void Set(MoraleAssessment value){if(!Enum.IsDefined(typeof(MoraleAssessment),value))throw new ArgumentOutOfRangeException(nameof(value));Assessment=value;}}
    public sealed class FatigueState{public FatigueState(FatigueAssessment assessment=FatigueAssessment.Unassessed){Set(assessment);}public FatigueAssessment Assessment{get;private set;}public void Set(FatigueAssessment value){if(!Enum.IsDefined(typeof(FatigueAssessment),value))throw new ArgumentOutOfRangeException(nameof(value));Assessment=value;}}
    public sealed class DisciplineState{public DisciplineState(DisciplineAssessment assessment=DisciplineAssessment.Unassessed){Set(assessment);}public DisciplineAssessment Assessment{get;private set;}public void Set(DisciplineAssessment value){if(!Enum.IsDefined(typeof(DisciplineAssessment),value))throw new ArgumentOutOfRangeException(nameof(value));Assessment=value;}}

    public sealed class UnitGroupState
    {
        public UnitGroupState(UnitGroupId id,ArmyId armyId,RecruitmentSourceId sourceId,string troopDefinitionId,long headcount,CharacterId? commanderId=null,MoraleState? morale=null,FatigueState? fatigue=null,DisciplineState? discipline=null)
        {if(!id.IsValid||!armyId.IsValid||!sourceId.IsValid)throw new ArgumentException("Unit Group references are invalid.");if(string.IsNullOrWhiteSpace(troopDefinitionId))throw new ArgumentException("Troop definition reference is required.",nameof(troopDefinitionId));if(headcount<0)throw new ArgumentOutOfRangeException(nameof(headcount));if(commanderId.HasValue&&!commanderId.Value.IsValid)throw new ArgumentException("Commander ID is invalid.",nameof(commanderId));Id=id;ArmyId=armyId;SourceId=sourceId;TroopDefinitionId=troopDefinitionId;Headcount=headcount;CommanderId=commanderId;Morale=morale??new MoraleState();Fatigue=fatigue??new FatigueState();Discipline=discipline??new DisciplineState();}
        public UnitGroupId Id{get;}public ArmyId ArmyId{get;}public RecruitmentSourceId SourceId{get;}public string TroopDefinitionId{get;}public long Headcount{get;private set;}public CharacterId? CommanderId{get;private set;}public MoraleState Morale{get;}public FatigueState Fatigue{get;}public DisciplineState Discipline{get;}
        internal bool CanAddHeadcount(long quantity){if(quantity<=0)return false;try{checked{var unused=Headcount+quantity;return unused>=0;}}catch(OverflowException){return false;}}internal void AddHeadcount(long quantity){if(!CanAddHeadcount(quantity))throw new InvalidOperationException("Headcount increase is invalid.");Headcount+=quantity;}public bool CanApplyBattleLosses(long losses)=>losses>=0&&losses<=Headcount;public void ApplyBattleLosses(long losses){if(!CanApplyBattleLosses(losses))throw new InvalidOperationException("Battle losses exceed Unit Group headcount.");Headcount-=losses;}public void VacateCommander(CharacterId characterId){if(CommanderId.HasValue&&CommanderId.Value.Equals(characterId))CommanderId=null;}
    }

    public readonly struct CommandNodeRef:IEquatable<CommandNodeRef>,IComparable<CommandNodeRef>
    {
        private CommandNodeRef(CommandNodeKind kind,string id){Kind=kind;Id=id;}public CommandNodeKind Kind{get;}public string Id{get;}public static CommandNodeRef Army(ArmyId id){if(!id.IsValid)throw new ArgumentException(nameof(id));return new CommandNodeRef(CommandNodeKind.Army,id.Value);}public static CommandNodeRef Unit(UnitGroupId id){if(!id.IsValid)throw new ArgumentException(nameof(id));return new CommandNodeRef(CommandNodeKind.UnitGroup,id.Value);}public int CompareTo(CommandNodeRef other){var c=Kind.CompareTo(other.Kind);return c!=0?c:StringComparer.Ordinal.Compare(Id,other.Id);}public bool Equals(CommandNodeRef other)=>Kind==other.Kind&&StringComparer.Ordinal.Equals(Id,other.Id);public override bool Equals(object? obj)=>obj is CommandNodeRef other&&Equals(other);public override int GetHashCode()=>((int)Kind*397)^StringComparer.Ordinal.GetHashCode(Id??string.Empty);
    }
    public sealed class CommandRelationship{public CommandRelationship(CommandNodeRef parent,CommandNodeRef child){if(parent.Equals(child))throw new ArgumentException("Command relationship cannot be self-referential.");Parent=parent;Child=child;}public CommandNodeRef Parent{get;}public CommandNodeRef Child{get;}}
    public sealed class CommandHierarchy
    {
        private readonly SortedDictionary<CommandNodeRef,CommandRelationship> _byChild=new SortedDictionary<CommandNodeRef,CommandRelationship>();public CommandHierarchy(ArmyId armyId){if(!armyId.IsValid)throw new ArgumentException(nameof(armyId));ArmyId=armyId;}public ArmyId ArmyId{get;}public IReadOnlyCollection<CommandRelationship> OrderedRelationships=>_byChild.Values;
        public void Add(CommandRelationship relationship){if(relationship==null)throw new ArgumentNullException(nameof(relationship));if(relationship.Child.Kind==CommandNodeKind.Army||(relationship.Parent.Kind==CommandNodeKind.Army&&!StringComparer.Ordinal.Equals(relationship.Parent.Id,ArmyId.Value)))throw new InvalidOperationException("The Army command root cannot be a child or reference another Army.");if(_byChild.ContainsKey(relationship.Child))throw new InvalidOperationException("A command node cannot have two active parents.");var cursor=relationship.Parent;while(_byChild.TryGetValue(cursor,out var parent)){cursor=parent.Parent;if(cursor.Equals(relationship.Child))throw new InvalidOperationException("Circular command hierarchy is forbidden.");}if(cursor.Equals(relationship.Child))throw new InvalidOperationException("Circular command hierarchy is forbidden.");_byChild.Add(relationship.Child,relationship);}
    }

    public sealed class ArmySupplyInventory
    {
        private readonly SortedDictionary<TradeGoodId,TradeGoodStock> _items=new SortedDictionary<TradeGoodId,TradeGoodStock>();public IReadOnlyCollection<TradeGoodStock> OrderedGoods=>_items.Values;public long QuantityOf(TradeGoodId id)=>_items.TryGetValue(id,out var x)?x.Quantity.Value:0;public bool CanAdd(TradeGoodId id,long quantity){if(!id.IsValid||quantity<=0)return false;try{checked{var unused=QuantityOf(id)+quantity;return unused>=0;}}catch(OverflowException){return false;}}public void AddInitial(TradeGoodId id,long quantity){if(!id.IsValid||quantity<0)throw new ArgumentOutOfRangeException(nameof(quantity));if(_items.ContainsKey(id))throw new InvalidOperationException("Duplicate Army supply good.");_items.Add(id,new TradeGoodStock(id,quantity));}private void Add(TradeGoodId id,long quantity){if(!CanAdd(id,quantity))throw new InvalidOperationException("Army supply increase is invalid.");if(!_items.TryGetValue(id,out var item)){item=new TradeGoodStock(id,0);_items.Add(id,item);}item.Quantity=new GoodsQuantity(item.Quantity.Value+quantity);}private void Remove(TradeGoodId id,long quantity){if(quantity<=0||!_items.TryGetValue(id,out var item)||item.Quantity.Value<quantity)throw new InvalidOperationException("Insufficient Army supply.");item.Quantity=new GoodsQuantity(item.Quantity.Value-quantity);}public void TransferFrom(CityStockState source,TradeGoodId id,long quantity){if(source==null)throw new ArgumentNullException(nameof(source));if(source.QuantityOf(id)<quantity||!CanAdd(id,quantity))throw new InvalidOperationException("City-to-Army supply transfer cannot complete atomically.");source.Remove(id,quantity);Add(id,quantity);}public void TransferFrom(CaravanCargoState source,TradeGoodId id,long quantity){if(source==null)throw new ArgumentNullException(nameof(source));if(source.QuantityOf(id)<quantity||!CanAdd(id,quantity))throw new InvalidOperationException("Caravan-to-Army supply transfer cannot complete atomically.");source.Remove(id,quantity);Add(id,quantity);}public ArmySupplyConsumptionResult Consume(TradeGoodId id,long requested){if(requested<=0)throw new ArgumentOutOfRangeException(nameof(requested));var consumed=Math.Min(requested,QuantityOf(id));if(consumed>0)Remove(id,consumed);return new ArmySupplyConsumptionResult(requested,consumed);}
    }
    public sealed class SupplyRequirementState
    {
        public SupplyRequirementState(TradeGoodId goodId,SupplyPurpose purpose,long requiredQuantity){if(!goodId.IsValid)throw new ArgumentException(nameof(goodId));if(!Enum.IsDefined(typeof(SupplyPurpose),purpose))throw new ArgumentOutOfRangeException(nameof(purpose));if(requiredQuantity<0)throw new ArgumentOutOfRangeException(nameof(requiredQuantity));GoodId=goodId;Purpose=purpose;RequiredQuantity=requiredQuantity;}public TradeGoodId GoodId{get;}public SupplyPurpose Purpose{get;}public long RequiredQuantity{get;}public SupplyCondition Assess(ArmySupplyInventory inventory){var available=inventory.QuantityOf(GoodId);if(RequiredQuantity==0)return SupplyCondition.NotRequired;if(available==0)return SupplyCondition.Exhausted;return available<RequiredQuantity?SupplyCondition.Insufficient:SupplyCondition.Supplied;}
    }

    public readonly struct PayrollFundingSourceRef:IEquatable<PayrollFundingSourceRef>
    {private PayrollFundingSourceRef(PayrollFundingSourceKind kind,string id){if(!Enum.IsDefined(typeof(PayrollFundingSourceKind),kind)||string.IsNullOrWhiteSpace(id))throw new ArgumentException("Payroll funding source is invalid.");Kind=kind;Id=id;}public PayrollFundingSourceKind Kind{get;}public string Id{get;}public static PayrollFundingSourceRef CityMarket(CityId id){if(!id.IsValid)throw new ArgumentException(nameof(id));return new PayrollFundingSourceRef(PayrollFundingSourceKind.CityMarket,id.Value);}public static PayrollFundingSourceRef Caravan(CaravanId id){if(!id.IsValid)throw new ArgumentException(nameof(id));return new PayrollFundingSourceRef(PayrollFundingSourceKind.Caravan,id.Value);}public bool Equals(PayrollFundingSourceRef other)=>Kind==other.Kind&&StringComparer.Ordinal.Equals(Id,other.Id);public override bool Equals(object? obj)=>obj is PayrollFundingSourceRef other&&Equals(other);public override int GetHashCode()=>((int)Kind*397)^StringComparer.Ordinal.GetHashCode(Id??string.Empty);}
    public sealed class PayrollObligationState
    {public PayrollObligationState(PayrollObligationId id,long amountOwed,WorldTimestamp dueAt,PayrollFundingSourceRef fundingSource,long amountPaid=0){if(!id.IsValid)throw new ArgumentException(nameof(id));if(amountOwed<=0||amountPaid<0||amountPaid>amountOwed)throw new ArgumentOutOfRangeException(nameof(amountOwed));Id=id;AmountOwed=amountOwed;AmountPaid=amountPaid;DueAt=dueAt;FundingSource=fundingSource;}public PayrollObligationId Id{get;}public long AmountOwed{get;}public long AmountPaid{get;private set;}public long Arrears=>AmountOwed-AmountPaid;public WorldTimestamp DueAt{get;}public PayrollFundingSourceRef FundingSource{get;}internal void ApplyPayment(long amount){if(amount<=0||amount>Arrears)throw new InvalidOperationException("Payment exceeds the outstanding obligation.");AmountPaid+=amount;}}
    public sealed class PayrollPaymentState{public PayrollPaymentState(PayrollPaymentId id,PayrollObligationId obligationId,long amount,WorldTimestamp paidAt,PayrollFundingSourceRef source){if(!id.IsValid||!obligationId.IsValid||amount<=0)throw new ArgumentException("Payroll payment is invalid.");Id=id;ObligationId=obligationId;Amount=amount;PaidAt=paidAt;Source=source;}public PayrollPaymentId Id{get;}public PayrollObligationId ObligationId{get;}public long Amount{get;}public WorldTimestamp PaidAt{get;}public PayrollFundingSourceRef Source{get;}}
    public sealed class PayrollState
    {
        private readonly SortedDictionary<PayrollObligationId,PayrollObligationState> _obligations=new SortedDictionary<PayrollObligationId,PayrollObligationState>();private readonly SortedDictionary<PayrollPaymentId,PayrollPaymentState> _payments=new SortedDictionary<PayrollPaymentId,PayrollPaymentState>();public IReadOnlyCollection<PayrollObligationState> OrderedObligations=>_obligations.Values;public IReadOnlyCollection<PayrollPaymentState> OrderedPayments=>_payments.Values;public void AddObligation(PayrollObligationState item){if(item==null)throw new ArgumentNullException(nameof(item));if(_obligations.ContainsKey(item.Id))throw new InvalidOperationException("Duplicate payroll obligation.");_obligations.Add(item.Id,item);}public PayrollObligationState GetRequired(PayrollObligationId id){if(!_obligations.TryGetValue(id,out var x))throw new KeyNotFoundException("Payroll obligation was not found.");return x;}public bool CanRecord(PayrollPaymentState p)=>p!=null&&!_payments.ContainsKey(p.Id)&&_obligations.ContainsKey(p.ObligationId)&&p.Source.Equals(_obligations[p.ObligationId].FundingSource)&&p.Amount<=_obligations[p.ObligationId].Arrears;private void Record(PayrollPaymentState p){if(!CanRecord(p))throw new InvalidOperationException("Payroll payment cannot be recorded.");_obligations[p.ObligationId].ApplyPayment(p.Amount);_payments.Add(p.Id,p);}public void PayFrom(CityMarketState source,PayrollPaymentState payment){if(source==null)throw new ArgumentNullException(nameof(source));if(payment==null||payment.Source.Kind!=PayrollFundingSourceKind.CityMarket||payment.Source.Id!=source.CityId.Value||!CanRecord(payment)||source.CashBalance.Value<payment.Amount)throw new InvalidOperationException("City-market payroll cannot complete atomically.");source.Debit(payment.Amount);Record(payment);}public void PayFrom(CaravanState source,PayrollPaymentState payment){if(source==null)throw new ArgumentNullException(nameof(source));if(payment==null||payment.Source.Kind!=PayrollFundingSourceKind.Caravan||payment.Source.Id!=source.Id.Value||!CanRecord(payment)||source.CashBalance.Value<payment.Amount)throw new InvalidOperationException("Caravan payroll cannot complete atomically.");source.Debit(payment.Amount);Record(payment);}public void RestorePayment(PayrollPaymentState payment){Record(payment);}
    }

    public sealed class ArmyState
    {
        private readonly SortedDictionary<UnitGroupId,UnitGroupState> _units=new SortedDictionary<UnitGroupId,UnitGroupState>();private readonly SortedDictionary<TradeGoodId,SupplyRequirementState> _requirements=new SortedDictionary<TradeGoodId,SupplyRequirementState>();
        public ArmyState(ArmyId id,string name,ArmyOwnerRef owner,ArmyOwnerRef controller,ArmyLocation location,ArmyCommanderReference? commander=null,ArmyLifecycle lifecycle=ArmyLifecycle.Assembling,ArmySupplyInventory? supply=null,PayrollState? payroll=null,MoraleState? morale=null,FatigueState? fatigue=null,DisciplineState? discipline=null)
        {if(!id.IsValid)throw new ArgumentException(nameof(id));if(string.IsNullOrWhiteSpace(name))throw new ArgumentException("Army name is required.",nameof(name));if(!Enum.IsDefined(typeof(ArmyLifecycle),lifecycle))throw new ArgumentOutOfRangeException(nameof(lifecycle));Id=id;Name=name;Owner=owner;Controller=controller;Location=location??throw new ArgumentNullException(nameof(location));Commander=commander;Lifecycle=lifecycle;Supply=supply??new ArmySupplyInventory();Payroll=payroll??new PayrollState();Morale=morale??new MoraleState();Fatigue=fatigue??new FatigueState();Discipline=discipline??new DisciplineState();Command=new CommandHierarchy(id);}
        public ArmyId Id{get;}public string Name{get;}public ArmyOwnerRef Owner{get;}public ArmyOwnerRef Controller{get;}public ArmyCommanderReference? Commander{get;private set;}public ArmyLocation Location{get;private set;}public ArmyLifecycle Lifecycle{get;private set;}public IReadOnlyCollection<UnitGroupState> OrderedUnits=>_units.Values;public ArmySupplyInventory Supply{get;}public IReadOnlyCollection<SupplyRequirementState> OrderedSupplyRequirements=>_requirements.Values;public PayrollState Payroll{get;}public MoraleState Morale{get;}public FatigueState Fatigue{get;}public DisciplineState Discipline{get;}public CommandHierarchy Command{get;}public long Headcount{get{long total=0;checked{foreach(var x in _units.Values)total+=x.Headcount;}return total;}}
        internal void AddUnit(UnitGroupState unit){if(unit==null||unit.ArmyId!=Id)throw new InvalidOperationException("Unit Group belongs to another Army.");if(_units.ContainsKey(unit.Id))throw new InvalidOperationException("Duplicate UnitGroupId in Army.");_units.Add(unit.Id,unit);}public UnitGroupState GetRequiredUnit(UnitGroupId id){if(!_units.TryGetValue(id,out var x))throw new KeyNotFoundException("Unit Group was not found.");return x;}public void AddSupplyRequirement(SupplyRequirementState item){if(item==null)throw new ArgumentNullException(nameof(item));if(_requirements.ContainsKey(item.GoodId))throw new InvalidOperationException("Duplicate supply requirement for Trade Good.");_requirements.Add(item.GoodId,item);}public void SetLifecycle(ArmyLifecycle value){if(!Enum.IsDefined(typeof(ArmyLifecycle),value))throw new ArgumentOutOfRangeException(nameof(value));var valid=Lifecycle==ArmyLifecycle.Assembling&&(value==ArmyLifecycle.Active||value==ArmyLifecycle.Disbanding)||Lifecycle==ArmyLifecycle.Active&&value==ArmyLifecycle.Disbanding||Lifecycle==ArmyLifecycle.Disbanding&&value==ArmyLifecycle.Disbanded;if(!valid)throw new InvalidOperationException("Invalid Army lifecycle transition.");Lifecycle=value;}public void SetLocation(ArmyLocation value){if(Lifecycle==ArmyLifecycle.Disbanded)throw new InvalidOperationException("Disbanded Army cannot move.");Location=value??throw new ArgumentNullException(nameof(value));}public void VacateCommander(CharacterId characterId){if(Commander!=null&&Commander.CharacterId.Equals(characterId))Commander=null;foreach(var unit in _units.Values)unit.VacateCommander(characterId);}
    }

    public sealed class ArmyRegistry
    {
        private readonly SortedDictionary<ArmyId,ArmyState> _armies=new SortedDictionary<ArmyId,ArmyState>();private readonly SortedDictionary<UnitGroupId,ArmyId> _unitOwners=new SortedDictionary<UnitGroupId,ArmyId>();public IReadOnlyCollection<ArmyState> OrderedArmies=>_armies.Values;public int Count=>_armies.Count;public bool ContainsUnit(UnitGroupId id)=>_unitOwners.ContainsKey(id);public void Add(ArmyState army){if(army==null)throw new ArgumentNullException(nameof(army));if(_armies.ContainsKey(army.Id))throw new InvalidOperationException("Duplicate ArmyId.");foreach(var u in army.OrderedUnits)if(_unitOwners.ContainsKey(u.Id))throw new InvalidOperationException("Unit Group already belongs to another Army.");_armies.Add(army.Id,army);foreach(var u in army.OrderedUnits)_unitOwners.Add(u.Id,army.Id);}public ArmyState GetRequired(ArmyId id){if(!_armies.TryGetValue(id,out var x))throw new KeyNotFoundException("Army was not found.");return x;}internal void AddUnit(ArmyId armyId,UnitGroupState unit){if(_unitOwners.ContainsKey(unit.Id))throw new InvalidOperationException("Unit Group already belongs to an Army.");var army=GetRequired(armyId);army.AddUnit(unit);_unitOwners.Add(unit.Id,armyId);}
    }

    public sealed class RecruitmentRecord
    {public RecruitmentRecord(RecruitmentRecordId id,RecruitmentSourceId sourceId,ArmyId armyId,UnitGroupId unitGroupId,long headcount,WorldTimestamp occurredAt){if(!id.IsValid||!sourceId.IsValid||!armyId.IsValid||!unitGroupId.IsValid||headcount<=0)throw new ArgumentException("Recruitment record is invalid.");Id=id;SourceId=sourceId;ArmyId=armyId;UnitGroupId=unitGroupId;Headcount=headcount;OccurredAt=occurredAt;}public RecruitmentRecordId Id{get;}public RecruitmentSourceId SourceId{get;}public ArmyId ArmyId{get;}public UnitGroupId UnitGroupId{get;}public long Headcount{get;}public WorldTimestamp OccurredAt{get;}}
    public sealed class RecruitmentRecordRegistry{private readonly SortedDictionary<RecruitmentRecordId,RecruitmentRecord> _items=new SortedDictionary<RecruitmentRecordId,RecruitmentRecord>();public IReadOnlyCollection<RecruitmentRecord> OrderedRecords=>_items.Values;public bool Contains(RecruitmentRecordId id)=>_items.ContainsKey(id);internal void Add(RecruitmentRecord item){if(item==null)throw new ArgumentNullException(nameof(item));if(_items.ContainsKey(item.Id))throw new InvalidOperationException("Duplicate RecruitmentRecordId.");_items.Add(item.Id,item);}}

    public sealed class CampaignMilitaryState
    {public CampaignMilitaryState(ArmyRegistry? armies=null,RecruitmentSourceRegistry? sources=null,RecruitmentRecordRegistry? records=null){Armies=armies??new ArmyRegistry();RecruitmentSources=sources??new RecruitmentSourceRegistry();RecruitmentRecords=records??new RecruitmentRecordRegistry();}public ArmyRegistry Armies{get;}public RecruitmentSourceRegistry RecruitmentSources{get;}public RecruitmentRecordRegistry RecruitmentRecords{get;}public void ApplyRecruitment(RecruitmentSourceState source,UnitGroupState unit,RecruitmentRecord record){if(source==null||unit==null||record==null||!source.Id.Equals(unit.SourceId)||!source.Id.Equals(record.SourceId)||!unit.ArmyId.Equals(record.ArmyId)||!unit.Id.Equals(record.UnitGroupId)||unit.Headcount!=record.Headcount||!source.CanConsume(record.Headcount)||Armies.ContainsUnit(unit.Id)||RecruitmentRecords.Contains(record.Id))throw new InvalidOperationException("Recruitment transaction cannot complete atomically.");source.Consume(record.Headcount);Armies.AddUnit(unit.ArmyId,unit);RecruitmentRecords.Add(record);}public void RestoreUnit(UnitGroupState unit){if(unit==null)throw new ArgumentNullException(nameof(unit));Armies.AddUnit(unit.ArmyId,unit);}public void RestoreRecord(RecruitmentRecord record){RecruitmentRecords.Add(record);}}

    public sealed class ArmyReadinessProjection
    {public ArmyReadinessProjection(ArmyState army){if(army==null)throw new ArgumentNullException(nameof(army));Morale=army.Morale.Assessment;Fatigue=army.Fatigue.Assessment;Discipline=army.Discipline.Assessment;var list=new List<SupplyCondition>();foreach(var x in army.OrderedSupplyRequirements)list.Add(x.Assess(army.Supply));SupplyConditions=list;}public MoraleAssessment Morale{get;}public FatigueAssessment Fatigue{get;}public DisciplineAssessment Discipline{get;}public IReadOnlyList<SupplyCondition> SupplyConditions{get;}}
    public sealed class ArmySupplyConsumptionResult{public ArmySupplyConsumptionResult(long requested,long consumed){Requested=requested;Consumed=consumed;Shortage=requested-consumed;}public long Requested{get;}public long Consumed{get;}public long Shortage{get;}public bool HasShortage=>Shortage>0;}
}
