using System;
using System.Collections.Generic;
using System.Linq;
using FOC.Application.Battle;
using FOC.Domain.Battle;
using FOC.Domain.Campaign;
using FOC.Domain.Characters;
using FOC.Domain.Common;
using FOC.Domain.Diplomacy;
using FOC.Domain.Economy;
using FOC.Domain.EncountersContracts;
using FOC.Domain.Random;
using FOC.Domain.Time;

namespace FOC.Application.EncountersContracts
{
    public interface IEncounterPresenceProvider{bool IsPresent(EncounterEntityRef entity,EncounterContext context);}
    public interface IEncounterTriggerPolicy{bool IsEligible(CampaignRuntimeState campaign,EncounterDefinition definition,EncounterContext context);}
    public interface IEncounterChoiceRequirementPolicy{bool CanSelect(CampaignRuntimeState campaign,EncounterState encounter,EncounterChoiceDefinition choice);}
    public interface IEncounterChoiceResolver{EncounterResolution Resolve(CampaignRuntimeState campaign,EncounterState encounter,EncounterChoiceDefinition choice,IRandomSource random,WorldTimestamp at);}
    public interface IAtomicEncounterEffectPolicy{void Preflight(CampaignRuntimeState campaign,EncounterState encounter,EncounterResolution resolution);void ApplyPreflighted(CampaignRuntimeState campaign,EncounterState encounter,EncounterResolution resolution);}
    public interface IAtomicContractOutcomePolicy{void Preflight(CampaignRuntimeState campaign,ContractState contract);void ApplyPreflighted(CampaignRuntimeState campaign,ContractState contract);}

    public sealed class EncounterService
    {
        private readonly CampaignRuntimeState _campaign;private readonly EncounterDefinitionCatalog _definitions;public EncounterService(CampaignRuntimeState campaign,EncounterDefinitionCatalog definitions){_campaign=campaign??throw new ArgumentNullException(nameof(campaign));_definitions=definitions??throw new ArgumentNullException(nameof(definitions));}
        public EncounterState Trigger(EncounterId id,EncounterDefinitionId definitionId,EncounterContext context,RandomState randomState,IEncounterTriggerPolicy policy){if(policy==null)throw new ArgumentNullException(nameof(policy));var definition=_definitions.GetRequired(definitionId);if(_campaign.EncounterContracts.Encounters.Contains(id)||!policy.IsEligible(_campaign,definition,context))throw new InvalidOperationException("Encounter trigger is ineligible or duplicated.");EncounterReferenceValidator.Validate(_campaign,context.Source);foreach(var x in context.OrderedParticipants)EncounterReferenceValidator.Validate(_campaign,x);var state=new EncounterState(id,definition.Id,definition.Family,definition.Type,_campaign.Clock.Now,context,randomState);_campaign.EncounterContracts.Encounters.Add(state);return state;}
        public void Engage(EncounterId id)=>_campaign.EncounterContracts.Encounters.GetRequired(id).Engage(_campaign.Clock.Now);
        public EncounterResolution Resolve(EncounterId id,EncounterChoiceId choiceId,IEncounterChoiceRequirementPolicy requirements,IEncounterChoiceResolver resolver,IAtomicEncounterEffectPolicy effects){if(requirements==null||resolver==null||effects==null)throw new ArgumentNullException();var encounter=_campaign.EncounterContracts.Encounters.GetRequired(id);if(encounter.Lifecycle!=EncounterLifecycle.Engaged)throw new InvalidOperationException("Encounter is not engaged.");var definition=_definitions.GetRequired(encounter.DefinitionId);var choice=definition.GetRequiredChoice(choiceId);if(!requirements.CanSelect(_campaign,encounter,choice))throw new InvalidOperationException("Encounter choice requirements are not satisfied.");var random=new SeededRandomSource(encounter.RandomState);var resolution=resolver.Resolve(_campaign,encounter,choice,random,_campaign.Clock.Now);if(resolution==null||!resolution.SelectedChoiceId.Equals(choice.Id)||!resolution.PolicyId.Equals(choice.PolicyId)||!resolution.RandomState.Equals(random.CaptureState()))throw new InvalidOperationException("Encounter resolver returned an incompatible or non-deterministic resolution state.");effects.Preflight(_campaign,encounter,resolution);effects.ApplyPreflighted(_campaign,encounter,resolution);encounter.Resolve(resolution);encounter.MarkOutcomeApplied();return resolution;}
        public BattleState CreateLinkedBattle(EncounterId id,BattleCreationRequest request){var encounter=_campaign.EncounterContracts.Encounters.GetRequired(id);var definition=_definitions.GetRequired(encounter.DefinitionId);if(encounter.Lifecycle!=EncounterLifecycle.Resolved||!encounter.IsOutcomeApplied||(definition.Capabilities&EncounterCapability.Battle)==0)throw new InvalidOperationException("Encounter cannot create a Battle request.");var battle=new BattleCreationService(_campaign).Create(request);encounter.LinkBattle(battle.Id);return battle;}
        public ContractState CreateLinkedContract(EncounterId id,ContractService contracts,ContractId contractId,ContractDefinitionId definitionId,ContractIssuerRef issuer,IEnumerable<ContractTargetBinding> targets,CharacterId? assignee=null,WorldTimestamp? deadline=null){if(contracts==null)throw new ArgumentNullException(nameof(contracts));var encounter=_campaign.EncounterContracts.Encounters.GetRequired(id);var definition=_definitions.GetRequired(encounter.DefinitionId);if(encounter.Lifecycle!=EncounterLifecycle.Resolved||!encounter.IsOutcomeApplied||(definition.Capabilities&EncounterCapability.Contract)==0)throw new InvalidOperationException("Encounter cannot offer a Contract.");var contract=contracts.Offer(contractId,definitionId,issuer,targets,assignee,deadline,id,null);encounter.LinkContract(contract.Id);return contract;}
    }

    public sealed class ContractService
    {
        private readonly CampaignRuntimeState _campaign;private readonly ContractDefinitionCatalog _definitions;public ContractService(CampaignRuntimeState campaign,ContractDefinitionCatalog definitions){_campaign=campaign??throw new ArgumentNullException(nameof(campaign));_definitions=definitions??throw new ArgumentNullException(nameof(definitions));}
        public ContractState Offer(ContractId id,ContractDefinitionId definitionId,ContractIssuerRef issuer,IEnumerable<ContractTargetBinding> targets,CharacterId? assignee=null,WorldTimestamp? deadline=null,EncounterId? linkedEncounter=null,BattleId? linkedBattle=null){if(_campaign.EncounterContracts.Contracts.Contains(id))throw new InvalidOperationException("ContractId is duplicated.");var definition=_definitions.GetRequired(definitionId);ValidateIssuer(issuer);if(assignee.HasValue)RequireAvailable(assignee.Value);if(linkedEncounter.HasValue)_campaign.EncounterContracts.Encounters.GetRequired(linkedEncounter.Value);if(linkedBattle.HasValue)_campaign.Battles.Battles.GetRequired(linkedBattle.Value);var bindings=(targets??throw new ArgumentNullException(nameof(targets))).OrderBy(x=>x.SlotId).ToList();ValidateBindings(definition,bindings);var objectives=definition.OrderedObjectives.Select(x=>new ContractObjectiveState(x.Id,x.EvidenceKind,x.TargetSlotId,x.RequiredEvidenceCount));var state=new ContractState(id,definition.Id,definition.Category,issuer,bindings,objectives,_campaign.Clock.Now,assignee,deadline,linkedEncounter,linkedBattle);_campaign.EncounterContracts.Contracts.Add(state);return state;}
        public void Accept(ContractId id){var state=_campaign.EncounterContracts.Contracts.GetRequired(id);_definitions.GetRequired(state.DefinitionId);ValidateIssuer(state.Issuer);if(state.AssigneeId.HasValue)RequireAvailable(state.AssigneeId.Value);state.Accept(_campaign.Clock.Now);}
        public void SubmitEvidence(ContractId id,ContractObjectiveId objectiveId,ContractEvidence evidence){if(evidence==null)throw new ArgumentNullException(nameof(evidence));var state=_campaign.EncounterContracts.Contracts.GetRequired(id);if(state.Lifecycle!=ContractLifecycle.Active)throw new InvalidOperationException("Contract is not active.");ValidateEvidenceTruth(evidence);var objective=state.GetRequiredObjective(objectiveId);if(objective.TargetSlotId.HasValue){var target=state.GetRequiredTarget(objective.TargetSlotId.Value);if(target.Kind!=evidence.TargetKind||!StringComparer.Ordinal.Equals(target.TargetId,evidence.TargetId))throw new InvalidOperationException("Contract evidence does not match its variable typed target.");}objective.AddEvidence(evidence);}
        public void Complete(ContractId id,IAtomicContractOutcomePolicy policy){if(policy==null)throw new ArgumentNullException(nameof(policy));var state=_campaign.EncounterContracts.Contracts.GetRequired(id);if(state.Lifecycle!=ContractLifecycle.Active||!state.AllObjectivesSatisfied)throw new InvalidOperationException("Contract completion prerequisites are not satisfied.");policy.Preflight(_campaign,state);policy.ApplyPreflighted(_campaign,state);state.Complete(_campaign.Clock.Now);state.MarkOutcomeApplied();}
        public void Fail(ContractId id,IAtomicContractOutcomePolicy policy){if(policy==null)throw new ArgumentNullException(nameof(policy));var state=_campaign.EncounterContracts.Contracts.GetRequired(id);if(state.Lifecycle!=ContractLifecycle.Active)throw new InvalidOperationException("Contract cannot fail from its current lifecycle.");policy.Preflight(_campaign,state);policy.ApplyPreflighted(_campaign,state);state.Fail(_campaign.Clock.Now);state.MarkOutcomeApplied();}
        public void Cancel(ContractId id)=>_campaign.EncounterContracts.Contracts.GetRequired(id).Cancel(_campaign.Clock.Now);
        private void ValidateBindings(ContractDefinition definition,IReadOnlyList<ContractTargetBinding> bindings){if(bindings.Select(x=>x.SlotId).Distinct().Count()!=bindings.Count)throw new InvalidOperationException("Contract target slot is duplicated.");foreach(var slot in definition.OrderedTargetSlots){var matches=bindings.Where(x=>x.SlotId.Equals(slot.Id)).ToList();if(slot.Required&&matches.Count!=1||!slot.Required&&matches.Count>1||matches.Any(x=>x.Kind!=slot.Kind))throw new InvalidOperationException("Contract target binding is missing or has the wrong type.");}if(bindings.Any(x=>!definition.OrderedTargetSlots.Any(s=>s.Id.Equals(x.SlotId))))throw new InvalidOperationException("Contract includes an unknown target slot.");foreach(var x in bindings)ValidateTarget(x);}
        private void ValidateTarget(ContractTargetBinding x){switch(x.Kind){case ContractTargetKind.City:_campaign.Cities.GetRequired(CityId.Create(x.TargetId));break;case ContractTargetKind.Character:_campaign.Characters.GetRequired(CharacterId.Create(x.TargetId));break;case ContractTargetKind.Army:_campaign.Military.Armies.GetRequired(ArmyId.Create(x.TargetId));break;case ContractTargetKind.Caravan:_campaign.Economy.Caravans.GetRequired(CaravanId.Create(x.TargetId));break;case ContractTargetKind.Faction:_campaign.Diplomacy.Actors.GetRequired(FactionId.Create(x.TargetId));break;case ContractTargetKind.Clique:_campaign.Cliques.GetRequired(CliqueId.Create(x.TargetId));break;case ContractTargetKind.Battle:_campaign.Battles.Battles.GetRequired(BattleId.Create(x.TargetId));break;case ContractTargetKind.Encounter:_campaign.EncounterContracts.Encounters.GetRequired(EncounterId.Create(x.TargetId));break;default:throw new InvalidOperationException("Contract target type is invalid.");}}
        private void ValidateIssuer(ContractIssuerRef x){switch(x.Kind){case ContractIssuerKind.Character:RequireAvailable(CharacterId.Create(x.Id));break;case ContractIssuerKind.City:_campaign.Cities.GetRequired(CityId.Create(x.Id));break;case ContractIssuerKind.Faction:_campaign.Diplomacy.Actors.GetRequired(FactionId.Create(x.Id));break;case ContractIssuerKind.Clique:_campaign.Cliques.GetRequired(CliqueId.Create(x.Id));break;case ContractIssuerKind.Organization:_campaign.Organizations.GetRequired(OrganizationId.Create(x.Id));break;default:throw new InvalidOperationException("Contract issuer type is invalid.");}}
        private void ValidateEvidenceTruth(ContractEvidence x){if(x.OccurredAt.Ticks>_campaign.Clock.Now.Ticks)throw new InvalidOperationException("Contract evidence cannot come from the future.");switch(x.Kind){case ContractEvidenceKind.BattleCompleted:var battle=_campaign.Battles.Battles.GetRequired(BattleId.Create(x.TargetId));if(battle.Lifecycle!=BattleLifecycle.Completed||battle.Result==null)throw new InvalidOperationException("Battle evidence is not completed truth.");break;case ContractEvidenceKind.EncounterResolved:var encounter=_campaign.EncounterContracts.Encounters.GetRequired(EncounterId.Create(x.TargetId));if(encounter.Lifecycle!=EncounterLifecycle.Resolved||!encounter.IsOutcomeApplied)throw new InvalidOperationException("Encounter evidence is not resolved truth.");break;case ContractEvidenceKind.CaravanArrived:if(_campaign.Economy.Caravans.GetRequired(CaravanId.Create(x.TargetId)).LocationStage!=CaravanLocationStage.AtDestination)throw new InvalidOperationException("Caravan has not arrived.");break;case ContractEvidenceKind.TradeCompleted:var caravan=_campaign.Economy.Caravans.GetRequired(CaravanId.Create(x.TargetId));if(caravan.Accounting.PurchaseCost.Value==0&&caravan.Accounting.SaleRevenue.Value==0)throw new InvalidOperationException("Trade evidence lacks a real transaction.");break;case ContractEvidenceKind.DiplomaticReportDelivered:if(!_campaign.Diplomacy.Information.GetRequired(FactionId.Create(x.TargetId)).OrderedAvailableReports.Any())throw new InvalidOperationException("Diplomatic evidence is not delivered information.");break;case ContractEvidenceKind.CityStateChanged:_campaign.Cities.GetRequired(CityId.Create(x.TargetId));break;case ContractEvidenceKind.CharacterAssignmentChanged:_campaign.Characters.GetRequired(CharacterId.Create(x.TargetId));break;case ContractEvidenceKind.DiplomaticActionResolved:_campaign.Diplomacy.Actors.GetRequired(FactionId.Create(x.TargetId));break;default:throw new InvalidOperationException("Contract evidence type is invalid.");}}
        private CharacterState RequireAvailable(CharacterId id){var x=_campaign.Characters.GetRequired(id);if(x.IsDead||x.Captivity!=null)throw new InvalidOperationException("Contract Character is unavailable.");return x;}
    }

    internal static class EncounterReferenceValidator
    {public static void Validate(CampaignRuntimeState c,EncounterEntityRef x){switch(x.Kind){case EncounterEntityKind.Character:c.Characters.GetRequired(CharacterId.Create(x.Id));break;case EncounterEntityKind.Army:c.Military.Armies.GetRequired(ArmyId.Create(x.Id));break;case EncounterEntityKind.Caravan:c.Economy.Caravans.GetRequired(CaravanId.Create(x.Id));break;case EncounterEntityKind.City:c.Cities.GetRequired(CityId.Create(x.Id));break;case EncounterEntityKind.Faction:c.Diplomacy.Actors.GetRequired(FactionId.Create(x.Id));break;case EncounterEntityKind.Battle:c.Battles.Battles.GetRequired(BattleId.Create(x.Id));break;case EncounterEntityKind.Region:break;default:throw new InvalidOperationException("Encounter entity type is invalid.");}}}

    public sealed class EncounterContractInvariantValidator
    {
        public void ValidateOrThrow(CampaignRuntimeState campaign,EncounterDefinitionCatalog encounters,ContractDefinitionCatalog contracts){if(campaign==null||encounters==null||contracts==null)throw new ArgumentNullException();foreach(var x in campaign.EncounterContracts.Encounters.OrderedEncounters){var d=encounters.GetRequired(x.DefinitionId);if(d.Family!=x.Family||d.Type!=x.Type)throw new InvalidOperationException("Encounter definition and instance disagree.");EncounterReferenceValidator.Validate(campaign,x.Context.Source);foreach(var p in x.Context.OrderedParticipants)EncounterReferenceValidator.Validate(campaign,p);if(x.SelectedChoice.HasValue)d.GetRequiredChoice(x.SelectedChoice.Value);if(x.LinkedContractId.HasValue)campaign.EncounterContracts.Contracts.GetRequired(x.LinkedContractId.Value);if(x.LinkedBattleId.HasValue)campaign.Battles.Battles.GetRequired(x.LinkedBattleId.Value);}foreach(var x in campaign.EncounterContracts.Contracts.OrderedContracts){var d=contracts.GetRequired(x.DefinitionId);if(d.Category!=x.Category)throw new InvalidOperationException("Contract definition and instance disagree.");var required=d.OrderedTargetSlots.Where(s=>s.Required).Select(s=>s.Id).ToList();if(required.Any(s=>!x.OrderedTargets.Any(t=>t.SlotId.Equals(s))))throw new InvalidOperationException("Contract required target is missing.");foreach(var t in x.OrderedTargets){var slot=d.GetRequiredSlot(t.SlotId);if(slot.Kind!=t.Kind)throw new InvalidOperationException("Contract target type is wrong.");}if(x.Lifecycle==ContractLifecycle.Completed&&!x.AllObjectivesSatisfied)throw new InvalidOperationException("Completed Contract has unsatisfied objectives.");}}
    }

    public static class ProofEncounterContractContent
    {
        public static EncounterDefinitionCatalog Encounters(){var c=new EncounterDefinitionCatalog();Add(c,"bandit",EncounterFamily.Roaming,EncounterType.Bandit,EncounterCapability.Recruitment|EncounterCapability.Battle|EncounterCapability.Contract,new[]{"join","fight","pass"});Add(c,"caravan",EncounterFamily.Roaming,EncounterType.Caravan,EncounterCapability.Toll|EncounterCapability.Bribe|EncounterCapability.Contract,new[]{"toll","bribe","peace"});Add(c,"noble",EncounterFamily.Roaming,EncounterType.Noble,EncounterCapability.Contract,new[]{"engage","pass"});Add(c,"enemy-patrol",EncounterFamily.Roaming,EncounterType.EnemyPatrol,EncounterCapability.Battle,new[]{"engage","avoid"});Add(c,"refugee",EncounterFamily.Roaming,EncounterType.Refugee,EncounterCapability.Contract,new[]{"assist","pass"});Add(c,"abandoned-caravan",EncounterFamily.SurpriseEvent,EncounterType.AbandonedCaravan,EncounterCapability.None,new[]{"inspect","leave"});Add(c,"epidemic",EncounterFamily.SurpriseEvent,EncounterType.Epidemic,EncounterCapability.Contract,new[]{"assist","avoid"});Add(c,"road-collapse",EncounterFamily.SurpriseEvent,EncounterType.RoadCollapse,EncounterCapability.None,new[]{"inspect","avoid"});Add(c,"storm",EncounterFamily.SurpriseEvent,EncounterType.Storm,EncounterCapability.None,new[]{"shelter","continue"});Add(c,"wounded-soldier",EncounterFamily.SurpriseEvent,EncounterType.WoundedSoldier,EncounterCapability.Recruitment|EncounterCapability.Contract,new[]{"assist","leave"});return c;}
        public static ContractDefinitionCatalog Contracts(){var c=new ContractDefinitionCatalog();AddContract(c,"proof-military",ContractCategory.Military,ContractTargetKind.Battle,ContractEvidenceKind.BattleCompleted);AddContract(c,"proof-diplomatic",ContractCategory.Diplomatic,ContractTargetKind.Faction,ContractEvidenceKind.DiplomaticReportDelivered);AddContract(c,"proof-economic",ContractCategory.Economic,ContractTargetKind.Caravan,ContractEvidenceKind.TradeCompleted);AddContract(c,"proof-internal",ContractCategory.InternalManagement,ContractTargetKind.City,ContractEvidenceKind.CityStateChanged);AddContract(c,"proof-encounter",ContractCategory.InternalManagement,ContractTargetKind.Encounter,ContractEvidenceKind.EncounterResolved);return c;}
        private static void Add(EncounterDefinitionCatalog c,string id,EncounterFamily family,EncounterType type,EncounterCapability capability,IEnumerable<string> choices){c.Add(new EncounterDefinition(EncounterDefinitionId.Create("proof-"+id),family,type,choices.Select(x=>new EncounterChoiceDefinition(EncounterChoiceId.Create(x),EncounterPolicyId.Create("proof-policy-"+x),EncounterRequirementKind.None,null,"proof.encounter."+id+"."+x)),capability,"proof.encounter."+id));}
        private static void AddContract(ContractDefinitionCatalog c,string id,ContractCategory category,ContractTargetKind kind,ContractEvidenceKind evidence){var slot=ContractTargetSlotId.Create("target");c.Add(new ContractDefinition(ContractDefinitionId.Create(id),category,new[]{new ContractTargetSlotDefinition(slot,kind)},new[]{new ContractObjectiveDefinition(ContractObjectiveId.Create("objective"),evidence,slot)},"proof.contract."+id));}
    }
}
