using System;
using FOC.Domain.Characters;
using FOC.Domain.Common;
using FOC.Domain.Military;
using FOC.Domain.Time;

namespace FOC.Application.Save
{
    public static partial class CampaignSaveMapper
    {
        private static void AddMilitarySaveData(FOC.Domain.Campaign.CampaignRuntimeState state,CampaignSaveData data)
        {
            foreach(var source in state.Military.RecruitmentSources.OrderedSources)data.RecruitmentSources.Add(new RecruitmentSourceSaveData{RecruitmentSourceId=source.Id.Value,Type=(int)source.Type,AvailableHeadcount=source.AvailableHeadcount,AuthorityCharacterId=source.Authority.CharacterId.Value,AuthorityOrganizationId=source.Authority.OrganizationId.Value,AuthorityAssignmentId=source.Authority.AssignmentId.Value,CityId=source.CityId?.Value??string.Empty,InstitutionId=source.InstitutionId?.Value??string.Empty,ObligationOrContractId=source.ObligationOrContractId,IsActive=source.IsActive});
            foreach(var army in state.Military.Armies.OrderedArmies){var dto=new ArmySaveData{ArmyId=army.Id.Value,Name=army.Name,OwnerKind=(int)army.Owner.Kind,OwnerId=army.Owner.Id,ControllerKind=(int)army.Controller.Kind,ControllerId=army.Controller.Id,LocationKind=(int)army.Location.Kind,CityId=army.Location.CityId?.Value??string.Empty,LocationX=army.Location.Position.X,LocationY=army.Location.Position.Y,Lifecycle=(int)army.Lifecycle,Morale=(int)army.Morale.Assessment,Fatigue=(int)army.Fatigue.Assessment,Discipline=(int)army.Discipline.Assessment};if(army.Commander!=null){dto.CommanderCharacterId=army.Commander.CharacterId.Value;dto.CommanderOrganizationId=army.Commander.OrganizationId.Value;dto.CommanderAssignmentId=army.Commander.AssignmentId.Value;}foreach(var unit in army.OrderedUnits)dto.Units.Add(new UnitGroupSaveData{UnitGroupId=unit.Id.Value,RecruitmentSourceId=unit.SourceId.Value,TroopDefinitionId=unit.TroopDefinitionId,Headcount=unit.Headcount,CommanderCharacterId=unit.CommanderId?.Value??string.Empty,Morale=(int)unit.Morale.Assessment,Fatigue=(int)unit.Fatigue.Assessment,Discipline=(int)unit.Discipline.Assessment});foreach(var x in army.Command.OrderedRelationships)dto.CommandRelationships.Add(new CommandRelationshipSaveData{ParentKind=(int)x.Parent.Kind,ParentId=x.Parent.Id,ChildKind=(int)x.Child.Kind,ChildId=x.Child.Id});foreach(var x in army.Supply.OrderedGoods)dto.Supply.Add(new ArmySupplySaveData{TradeGoodId=x.GoodId.Value,Quantity=x.Quantity.Value});foreach(var x in army.OrderedSupplyRequirements)dto.SupplyRequirements.Add(new SupplyRequirementSaveData{TradeGoodId=x.GoodId.Value,Purpose=(int)x.Purpose,RequiredQuantity=x.RequiredQuantity});foreach(var x in army.Payroll.OrderedObligations)dto.PayrollObligations.Add(new PayrollObligationSaveData{PayrollObligationId=x.Id.Value,AmountOwed=x.AmountOwed,AmountPaid=x.AmountPaid,DueAt=x.DueAt.Ticks,FundingSourceKind=(int)x.FundingSource.Kind,FundingSourceId=x.FundingSource.Id});foreach(var x in army.Payroll.OrderedPayments)dto.PayrollPayments.Add(new PayrollPaymentSaveData{PayrollPaymentId=x.Id.Value,PayrollObligationId=x.ObligationId.Value,Amount=x.Amount,PaidAt=x.PaidAt.Ticks,FundingSourceKind=(int)x.Source.Kind,FundingSourceId=x.Source.Id});data.Armies.Add(dto);}
            foreach(var x in state.Military.RecruitmentRecords.OrderedRecords)data.RecruitmentRecords.Add(new RecruitmentRecordSaveData{RecruitmentRecordId=x.Id.Value,RecruitmentSourceId=x.SourceId.Value,ArmyId=x.ArmyId.Value,UnitGroupId=x.UnitGroupId.Value,Headcount=x.Headcount,OccurredAt=x.OccurredAt.Ticks});
        }

        private static CampaignMilitaryState RestoreMilitary(CampaignSaveData data)
        {
            var result=new CampaignMilitaryState();foreach(var x in data.RecruitmentSources){var source=new RecruitmentSourceState(RecruitmentSourceId.Create(x.RecruitmentSourceId),(RecruitmentType)x.Type,x.AvailableHeadcount,new RecruitmentAuthorityReference(CharacterId.Create(x.AuthorityCharacterId),OrganizationId.Create(x.AuthorityOrganizationId),AssignmentId.Create(x.AuthorityAssignmentId)),string.IsNullOrEmpty(x.CityId)?(CityId?)null:CityId.Create(x.CityId),string.IsNullOrEmpty(x.InstitutionId)?(FOC.Domain.Cities.CityBuildingId?)null:FOC.Domain.Cities.CityBuildingId.Create(x.InstitutionId),x.ObligationOrContractId,x.IsActive);result.RecruitmentSources.Add(source);}
            foreach(var x in data.Armies){var supply=new ArmySupplyInventory();foreach(var s in x.Supply)supply.AddInitial(TradeGoodId.Create(s.TradeGoodId),s.Quantity);var payroll=new PayrollState();foreach(var o in x.PayrollObligations)payroll.AddObligation(new PayrollObligationState(PayrollObligationId.Create(o.PayrollObligationId),o.AmountOwed,new WorldTimestamp(o.DueAt),Funding((PayrollFundingSourceKind)o.FundingSourceKind,o.FundingSourceId)));foreach(var p in x.PayrollPayments)payroll.RestorePayment(new PayrollPaymentState(PayrollPaymentId.Create(p.PayrollPaymentId),PayrollObligationId.Create(p.PayrollObligationId),p.Amount,new WorldTimestamp(p.PaidAt),Funding((PayrollFundingSourceKind)p.FundingSourceKind,p.FundingSourceId)));ArmyCommanderReference? commander=string.IsNullOrEmpty(x.CommanderCharacterId)?null:new ArmyCommanderReference(CharacterId.Create(x.CommanderCharacterId),OrganizationId.Create(x.CommanderOrganizationId),AssignmentId.Create(x.CommanderAssignmentId));var army=new ArmyState(ArmyId.Create(x.ArmyId),x.Name,Owner((ArmyOwnerKind)x.OwnerKind,x.OwnerId),Owner((ArmyOwnerKind)x.ControllerKind,x.ControllerId),Location((ArmyLocationKind)x.LocationKind,x.CityId,x.LocationX,x.LocationY),commander,(ArmyLifecycle)x.Lifecycle,supply,payroll,new MoraleState((MoraleAssessment)x.Morale),new FatigueState((FatigueAssessment)x.Fatigue),new DisciplineState((DisciplineAssessment)x.Discipline));result.Armies.Add(army);foreach(var u in x.Units)result.RestoreUnit(new UnitGroupState(UnitGroupId.Create(u.UnitGroupId),army.Id,RecruitmentSourceId.Create(u.RecruitmentSourceId),u.TroopDefinitionId,u.Headcount,string.IsNullOrEmpty(u.CommanderCharacterId)?(CharacterId?)null:CharacterId.Create(u.CommanderCharacterId),new MoraleState((MoraleAssessment)u.Morale),new FatigueState((FatigueAssessment)u.Fatigue),new DisciplineState((DisciplineAssessment)u.Discipline)));foreach(var q in x.SupplyRequirements)army.AddSupplyRequirement(new SupplyRequirementState(TradeGoodId.Create(q.TradeGoodId),(SupplyPurpose)q.Purpose,q.RequiredQuantity));foreach(var c in x.CommandRelationships)army.Command.Add(new CommandRelationship(Node((CommandNodeKind)c.ParentKind,c.ParentId),Node((CommandNodeKind)c.ChildKind,c.ChildId)));}
            foreach(var x in data.RecruitmentRecords)result.RestoreRecord(new RecruitmentRecord(RecruitmentRecordId.Create(x.RecruitmentRecordId),RecruitmentSourceId.Create(x.RecruitmentSourceId),ArmyId.Create(x.ArmyId),UnitGroupId.Create(x.UnitGroupId),x.Headcount,new WorldTimestamp(x.OccurredAt)));return result;
        }

        private static ArmyOwnerRef Owner(ArmyOwnerKind kind,string id){switch(kind){case ArmyOwnerKind.Character:return ArmyOwnerRef.Character(CharacterId.Create(id));case ArmyOwnerKind.Faction:return ArmyOwnerRef.Faction(FactionId.Create(id));case ArmyOwnerKind.Organization:return ArmyOwnerRef.Organization(OrganizationId.Create(id));case ArmyOwnerKind.CityGarrison:return ArmyOwnerRef.CityGarrison(CityId.Create(id));case ArmyOwnerKind.Institution:return ArmyOwnerRef.Institution(FOC.Domain.Cities.CityBuildingId.Create(id));case ArmyOwnerKind.MercenaryCompany:return ArmyOwnerRef.MercenaryCompany(id);case ArmyOwnerKind.CaravanSecurity:return ArmyOwnerRef.CaravanSecurity(CaravanId.Create(id));default:throw new InvalidOperationException("Unknown Army owner kind.");}}
        private static ArmyLocation Location(ArmyLocationKind kind,string city,long x,long y){switch(kind){case ArmyLocationKind.City:return ArmyLocation.InCity(CityId.Create(city));case ArmyLocationKind.Camp:return ArmyLocation.AtCamp(new WorldPosition(x,y));case ArmyLocationKind.InTransit:return ArmyLocation.InTransit(new WorldPosition(x,y));default:throw new InvalidOperationException("Unknown Army location kind.");}}
        private static PayrollFundingSourceRef Funding(PayrollFundingSourceKind kind,string id)=>kind==PayrollFundingSourceKind.CityMarket?PayrollFundingSourceRef.CityMarket(CityId.Create(id)):kind==PayrollFundingSourceKind.Caravan?PayrollFundingSourceRef.Caravan(CaravanId.Create(id)):throw new InvalidOperationException("Unknown payroll funding source.");
        private static CommandNodeRef Node(CommandNodeKind kind,string id)=>kind==CommandNodeKind.Army?CommandNodeRef.Army(ArmyId.Create(id)):kind==CommandNodeKind.UnitGroup?CommandNodeRef.Unit(UnitGroupId.Create(id)):throw new InvalidOperationException("Unknown command node kind.");
    }
}
