using System.Collections.Generic;
using FOC.Domain.Characters;
using FOC.Domain.Common;
using FOC.Domain.Economy;

namespace FOC.Application.Save
{
    public static partial class CampaignSaveMapper
    {
        private static void AddEconomySaveData(FOC.Domain.Campaign.CampaignRuntimeState state,CampaignSaveData data)
        {
            foreach(var x in state.Economy.Goods.OrderedGoods)data.TradeGoods.Add(new TradeGoodSaveData{TradeGoodId=x.Id.Value,Name=x.Name,Category=(int)x.Category,UnitWeight=x.UnitWeight,IsFood=x.IsFood,IsMilitaryGood=x.IsMilitaryGood,IsLuxury=x.IsLuxury,ReferenceUnitValue=x.ReferenceUnitValue});foreach(var x in state.Economy.Recipes.OrderedRecipes){var dto=new ProductionRecipeSaveData{ProductionRecipeId=x.Id.Value,Name=x.Name,BuildingKind=(int)x.BuildingKind};foreach(var line in x.OrderedInputs)dto.Inputs.Add(new RecipeGoodsLineSaveData{TradeGoodId=line.GoodId.Value,Quantity=line.Quantity.Value});foreach(var line in x.OrderedOutputs)dto.Outputs.Add(new RecipeGoodsLineSaveData{TradeGoodId=line.GoodId.Value,Quantity=line.Quantity.Value});data.ProductionRecipes.Add(dto);}foreach(var x in state.Economy.OrderedMarkets){var dto=new CityMarketSaveData{CityId=x.CityId.Value,CashBalance=x.CashBalance.Value};foreach(var stock in x.Stock.OrderedStocks)dto.Stocks.Add(new TradeGoodStockSaveData{TradeGoodId=stock.GoodId.Value,Quantity=stock.Quantity.Value});foreach(var demand in x.Demand.OrderedSources)dto.DemandSources.Add(new DemandSourceSaveData{SourceId=demand.SourceId,Kind=(int)demand.Kind,TradeGoodId=demand.GoodId.Value,Quantity=demand.Quantity.Value});data.CityMarkets.Add(dto);}foreach(var x in state.Economy.Caravans.OrderedCaravans){var dto=new CaravanSaveData{CaravanId=x.Id.Value,OwnerKind=(int)x.Owner.Kind,OwnerId=x.Owner.Id,ManagerCharacterId=x.ManagerCharacterId.Value,OriginCityId=x.OriginCityId.Value,DestinationCityId=x.DestinationCityId.Value,RouteId=x.RouteId?.Value??string.Empty,WeightCapacity=x.WeightCapacity,CashBalance=x.CashBalance.Value,Lifecycle=(int)x.Lifecycle,LocationStage=(int)x.LocationStage,PurchaseCost=x.Accounting.PurchaseCost.Value,SaleRevenue=x.Accounting.SaleRevenue.Value,OperatingCost=x.Accounting.OperatingCost.Value,Tariffs=x.Accounting.Tariffs.Value,Losses=x.Accounting.Losses.Value};if(x.Representative!=null){dto.RepresentativeCharacterId=x.Representative.CharacterId.Value;dto.RepresentativeOrganizationId=x.Representative.OrganizationId.Value;dto.RepresentativeAssignmentId=x.Representative.AssignmentId.Value;}foreach(var cargo in x.Cargo.OrderedCargo)dto.Cargo.Add(new TradeGoodStockSaveData{TradeGoodId=cargo.GoodId.Value,Quantity=cargo.Quantity.Value});foreach(var risk in x.OrderedRiskInputs)dto.RiskInputs.Add(new RouteRiskSaveData{SourceId=risk.SourceId,Source=(int)risk.Source});data.Caravans.Add(dto);}
        }
        private static EconomyState RestoreEconomy(CampaignSaveData data)
        {
            var goods=new TradeGoodRegistry();foreach(var x in data.TradeGoods)goods.Add(new TradeGoodDefinition(TradeGoodId.Create(x.TradeGoodId),x.Name,(TradeGoodCategory)x.Category,x.UnitWeight,x.IsFood,x.IsMilitaryGood,x.IsLuxury,x.ReferenceUnitValue));var recipes=new ProductionRecipeRegistry();foreach(var x in data.ProductionRecipes){var inputs=new List<RecipeGoodsLine>();var outputs=new List<RecipeGoodsLine>();foreach(var line in x.Inputs)inputs.Add(new RecipeGoodsLine(TradeGoodId.Create(line.TradeGoodId),line.Quantity));foreach(var line in x.Outputs)outputs.Add(new RecipeGoodsLine(TradeGoodId.Create(line.TradeGoodId),line.Quantity));recipes.Add(new ProductionRecipeDefinition(ProductionRecipeId.Create(x.ProductionRecipeId),x.Name,(FOC.Domain.Cities.CityBuildingKind)x.BuildingKind,inputs,outputs));}var caravans=new CaravanRegistry();var result=new EconomyState(goods,recipes,caravans);foreach(var x in data.CityMarkets){var stock=new CityStockState();foreach(var item in x.Stocks)stock.AddInitial(new TradeGoodStock(TradeGoodId.Create(item.TradeGoodId),item.Quantity));var demand=new CityDemandState();foreach(var item in x.DemandSources)demand.AddSource(new DemandSourceState(item.SourceId,(DemandSourceKind)item.Kind,TradeGoodId.Create(item.TradeGoodId),item.Quantity));result.AddMarket(new CityMarketState(CityId.Create(x.CityId),x.CashBalance,stock,demand));}foreach(var x in data.Caravans){var cargo=new CaravanCargoState();foreach(var item in x.Cargo)cargo.Add(TradeGoodId.Create(item.TradeGoodId),item.Quantity,x.WeightCapacity,goods);TradeRepresentativeReference? representative=string.IsNullOrEmpty(x.RepresentativeCharacterId)?null:new TradeRepresentativeReference(CharacterId.Create(x.RepresentativeCharacterId),OrganizationId.Create(x.RepresentativeOrganizationId),AssignmentId.Create(x.RepresentativeAssignmentId));var risks=new List<RouteRiskInput>();foreach(var risk in x.RiskInputs)risks.Add(new RouteRiskInput(risk.SourceId,(RouteRiskSource)risk.Source));caravans.Add(new CaravanState(CaravanId.Create(x.CaravanId),RestoreOwner(x.OwnerKind,x.OwnerId),CharacterId.Create(x.ManagerCharacterId),CityId.Create(x.OriginCityId),CityId.Create(x.DestinationCityId),x.WeightCapacity,x.CashBalance,representative,string.IsNullOrEmpty(x.RouteId)?(TradeRouteId?)null:TradeRouteId.Create(x.RouteId),(CaravanLifecycle)x.Lifecycle,(CaravanLocationStage)x.LocationStage,cargo,new CaravanAccountingState(x.PurchaseCost,x.SaleRevenue,x.OperatingCost,x.Tariffs,x.Losses),risks));}return result;
        }
        private static EconomicOwnerRef RestoreOwner(int kind,string id){switch((EconomicOwnerKind)kind){case EconomicOwnerKind.Character:return EconomicOwnerRef.Character(CharacterId.Create(id));case EconomicOwnerKind.House:return EconomicOwnerRef.House(HouseId.Create(id));case EconomicOwnerKind.Organization:return EconomicOwnerRef.Organization(OrganizationId.Create(id));default:throw new System.InvalidOperationException("Unknown Economy owner kind.");}}
    }
}
