using System;
using System.Linq;
using FOC.Domain.Characters;
using FOC.Domain.Common;
using FOC.Domain.EncountersContracts;
using FOC.Domain.Random;
using FOC.Domain.Time;

namespace FOC.Application.Save
{
    public static partial class CampaignSaveMapper
    {
        private static void AddEncounterContractSaveData(FOC.Domain.Campaign.CampaignRuntimeState state,CampaignSaveData data)
        {
            foreach(var x in state.EncounterContracts.Encounters.OrderedEncounters){var d=new EncounterSaveData{EncounterId=x.Id.Value,DefinitionId=x.DefinitionId.Value,Family=(int)x.Family,Type=(int)x.Type,CreatedAt=x.CreatedAt.Ticks,SourceKind=(int)x.Context.Source.Kind,SourceId=x.Context.Source.Id,RngState=x.RandomState.State,RngDrawCount=x.RandomState.DrawCount,Lifecycle=(int)x.Lifecycle,EngagedAt=x.EngagedAt.HasValue?(long?)x.EngagedAt.Value.Ticks:null,SelectedChoiceId=x.SelectedChoice.HasValue?x.SelectedChoice.Value.Value:string.Empty,LinkedContractId=x.LinkedContractId.HasValue?x.LinkedContractId.Value.Value:string.Empty,LinkedBattleId=x.LinkedBattleId.HasValue?x.LinkedBattleId.Value.Value:string.Empty,OutcomeApplied=x.IsOutcomeApplied};foreach(var p in x.Context.OrderedParticipants)d.Participants.Add(new EncounterEntityRefSaveData{Kind=(int)p.Kind,Id=p.Id});if(x.Resolution!=null)d.Resolution=new EncounterResolutionSaveData{OutcomeId=x.Resolution.OutcomeId.Value,SelectedChoiceId=x.Resolution.SelectedChoiceId.Value,PolicyId=x.Resolution.PolicyId.Value,ResolvedAt=x.Resolution.ResolvedAt.Ticks,RngState=x.Resolution.RandomState.State,RngDrawCount=x.Resolution.RandomState.DrawCount};data.Encounters.Add(d);}
            foreach(var x in state.EncounterContracts.Contracts.OrderedContracts){var d=new ContractSaveData{ContractId=x.Id.Value,DefinitionId=x.DefinitionId.Value,Category=(int)x.Category,IssuerKind=(int)x.Issuer.Kind,IssuerId=x.Issuer.Id,OfferedAt=x.OfferedAt.Ticks,AssigneeCharacterId=x.AssigneeId.HasValue?x.AssigneeId.Value.Value:string.Empty,AcceptedAt=x.AcceptedAt.HasValue?(long?)x.AcceptedAt.Value.Ticks:null,Deadline=x.Deadline.HasValue?(long?)x.Deadline.Value.Ticks:null,TerminalAt=x.TerminalAt.HasValue?(long?)x.TerminalAt.Value.Ticks:null,LinkedEncounterId=x.LinkedEncounterId.HasValue?x.LinkedEncounterId.Value.Value:string.Empty,LinkedBattleId=x.LinkedBattleId.HasValue?x.LinkedBattleId.Value.Value:string.Empty,Lifecycle=(int)x.Lifecycle,OutcomeApplied=x.IsOutcomeApplied};foreach(var t in x.OrderedTargets)d.Targets.Add(new ContractTargetSaveData{SlotId=t.SlotId.Value,Kind=(int)t.Kind,TargetId=t.TargetId});foreach(var o in x.OrderedObjectives){var q=new ContractObjectiveSaveData{ObjectiveId=o.Id.Value,EvidenceKind=(int)o.EvidenceKind,TargetSlotId=o.TargetSlotId.HasValue?o.TargetSlotId.Value.Value:string.Empty,RequiredEvidenceCount=o.RequiredEvidenceCount};foreach(var e in o.OrderedEvidence)q.Evidence.Add(new ContractEvidenceSaveData{EvidenceId=e.Id.Value,Kind=(int)e.Kind,TargetKind=(int)e.TargetKind,TargetId=e.TargetId,OccurredAt=e.OccurredAt.Ticks});d.Objectives.Add(q);}data.Contracts.Add(d);}
        }
        private static EncounterContractCampaignState RestoreEncounterContracts(CampaignSaveData data)
        {
            var encounters=new EncounterRegistry();foreach(var x in data.Encounters){var context=new EncounterContext(EncounterEntityRef.Restore((EncounterEntityKind)x.SourceKind,x.SourceId),x.Participants.Select(p=>EncounterEntityRef.Restore((EncounterEntityKind)p.Kind,p.Id)));EncounterResolution? resolution=null;if(x.Resolution!=null)resolution=new EncounterResolution(EncounterOutcomeId.Create(x.Resolution.OutcomeId),EncounterChoiceId.Create(x.Resolution.SelectedChoiceId),EncounterPolicyId.Create(x.Resolution.PolicyId),new WorldTimestamp(x.Resolution.ResolvedAt),new RandomState(x.Resolution.RngState,x.Resolution.RngDrawCount));encounters.Add(new EncounterState(EncounterId.Create(x.EncounterId),EncounterDefinitionId.Create(x.DefinitionId),(EncounterFamily)x.Family,(EncounterType)x.Type,new WorldTimestamp(x.CreatedAt),context,new RandomState(x.RngState,x.RngDrawCount),(EncounterLifecycle)x.Lifecycle,x.EngagedAt.HasValue?(WorldTimestamp?)new WorldTimestamp(x.EngagedAt.Value):null,string.IsNullOrEmpty(x.SelectedChoiceId)?(EncounterChoiceId?)null:EncounterChoiceId.Create(x.SelectedChoiceId),resolution,string.IsNullOrEmpty(x.LinkedContractId)?(ContractId?)null:ContractId.Create(x.LinkedContractId),string.IsNullOrEmpty(x.LinkedBattleId)?(BattleId?)null:BattleId.Create(x.LinkedBattleId),x.OutcomeApplied));}
            var contracts=new ContractRegistry();foreach(var x in data.Contracts){var targets=x.Targets.Select(t=>ContractTargetBinding.Restore(ContractTargetSlotId.Create(t.SlotId),(ContractTargetKind)t.Kind,t.TargetId));var objectives=x.Objectives.Select(o=>new ContractObjectiveState(ContractObjectiveId.Create(o.ObjectiveId),(ContractEvidenceKind)o.EvidenceKind,string.IsNullOrEmpty(o.TargetSlotId)?(ContractTargetSlotId?)null:ContractTargetSlotId.Create(o.TargetSlotId),o.RequiredEvidenceCount,o.Evidence.Select(e=>ContractEvidence.Restore(ContractEvidenceId.Create(e.EvidenceId),(ContractEvidenceKind)e.Kind,(ContractTargetKind)e.TargetKind,e.TargetId,new WorldTimestamp(e.OccurredAt)))));contracts.Add(new ContractState(ContractId.Create(x.ContractId),ContractDefinitionId.Create(x.DefinitionId),(ContractCategory)x.Category,ContractIssuerRef.Restore((ContractIssuerKind)x.IssuerKind,x.IssuerId),targets,objectives,new WorldTimestamp(x.OfferedAt),string.IsNullOrEmpty(x.AssigneeCharacterId)?(CharacterId?)null:CharacterId.Create(x.AssigneeCharacterId),x.Deadline.HasValue?(WorldTimestamp?)new WorldTimestamp(x.Deadline.Value):null,string.IsNullOrEmpty(x.LinkedEncounterId)?(EncounterId?)null:EncounterId.Create(x.LinkedEncounterId),string.IsNullOrEmpty(x.LinkedBattleId)?(BattleId?)null:BattleId.Create(x.LinkedBattleId),(ContractLifecycle)x.Lifecycle,x.AcceptedAt.HasValue?(WorldTimestamp?)new WorldTimestamp(x.AcceptedAt.Value):null,x.TerminalAt.HasValue?(WorldTimestamp?)new WorldTimestamp(x.TerminalAt.Value):null,x.OutcomeApplied));}
            return new EncounterContractCampaignState(encounters,contracts);
        }
    }
}
