using System;
using System.Linq;
using FOC.Domain.Characters;
using FOC.Domain.Cities;
using FOC.Domain.Common;
using FOC.Domain.Soldiers;
using FOC.Domain.Time;

namespace FOC.Application.Save
{
    public static partial class CampaignSaveMapper
    {
        private static void AddSoldierSaveData(FOC.Domain.Campaign.CampaignRuntimeState state,CampaignSaveData data)
        {
            foreach(var x in state.Soldiers.Definitions.OrderedTroops){var d=new TroopDefinitionSaveData{TroopDefinitionId=x.Id.Value,Name=x.Name,UnitClassId=x.UnitClassId.Value,DefaultCombatRoleId=x.DefaultCombatRoleId.Value,MountContext=(int)x.MountContext,VisualProfileId=x.VisualProfileId.Value,AllowsArmor=x.AllowsArmor,AllowsShield=x.AllowsShield};foreach(var f in x.AllowedWeaponFamilies)d.AllowedWeaponFamilies.Add((int)f);data.TroopDefinitions.Add(d);}
            foreach(var x in state.Soldiers.Definitions.OrderedWeapons){var d=new WeaponDefinitionSaveData{WeaponDefinitionId=x.Id.Value,Name=x.Name,Family=(int)x.Family,MountContext=(int)x.MountContext,EconomicGoodId=x.EconomicGoodId.Value,VisualProfileId=x.VisualProfileId.Value,IsRanged=x.IsRanged,AmmoFamilyId=x.AmmoFamilyId?.Value??string.Empty};foreach(var slot in x.AllowedSlots)d.AllowedSlots.Add((int)slot);foreach(var a in x.AttackOptions)d.AttackOptions.Add(new WeaponAttackOptionSaveData{Mode=(int)a.Mode,DamageType=(int)a.DamageType});data.WeaponDefinitions.Add(d);}
            foreach(var x in state.Soldiers.Definitions.OrderedArmor)data.ArmorDefinitions.Add(new ArmorDefinitionSaveData{ArmorDefinitionId=x.Id.Value,Name=x.Name,Slot=(int)x.Slot,EconomicGoodId=x.EconomicGoodId.Value,VisualProfileId=x.VisualProfileId.Value,QualityCode=x.QualityCode});foreach(var x in state.Soldiers.Definitions.OrderedShields)data.ShieldDefinitions.Add(new ShieldDefinitionSaveData{ShieldDefinitionId=x.Id.Value,Name=x.Name,EconomicGoodId=x.EconomicGoodId.Value,VisualProfileId=x.VisualProfileId.Value,Classification=x.Classification});foreach(var x in state.Soldiers.Definitions.OrderedMounts)data.MountDefinitions.Add(new MountDefinitionSaveData{MountDefinitionId=x.Id.Value,Name=x.Name,EconomicGoodId=x.EconomicGoodId.Value,VisualProfileId=x.VisualProfileId.Value,MobilityClass=x.MobilityClass});foreach(var x in state.Soldiers.Definitions.OrderedAuxiliary)data.AuxiliaryEquipmentDefinitions.Add(new AuxiliaryEquipmentDefinitionSaveData{AuxiliaryEquipmentDefinitionId=x.Id.Value,Name=x.Name,Kind=(int)x.Kind,EconomicGoodId=x.EconomicGoodId.Value,VisualProfileId=x.VisualProfileId.Value,AmmoFamilyId=x.AmmoFamilyId?.Value??string.Empty});
            foreach(var x in state.Soldiers.Equipment.OrderedEquipment)data.EquipmentInstances.Add(new EquipmentInstanceSaveData{EquipmentInstanceId=x.Id.Value,DefinitionKind=(int)x.Definition.Kind,DefinitionId=x.Definition.Id,OwnerKind=(int)x.Owner.Kind,OwnerId=x.Owner.Id,AcquisitionKind=(int)x.Provenance.Kind,AcquisitionSourceId=x.Provenance.SourceId,EconomicGoodId=x.Provenance.EconomicGoodId.Value,AcquiredAt=x.Provenance.AcquiredAt.Ticks,QualityCode=x.QualityCode});
            foreach(var x in state.Soldiers.Soldiers.OrderedSoldiers){var d=new SoldierSaveData{SoldierId=x.Id.Value,UnitGroupId=x.UnitGroupId.Value,TroopDefinitionId=x.TroopDefinitionId.Value,RecruitmentSourceId=x.Recruitment.SourceId.Value,RecruitmentRecordId=x.Recruitment.RecordId.Value,CombatRoleId=x.CombatRoleId.Value,Experience=(int)x.Experience,Training=(int)x.Training,Lifecycle=(int)x.Lifecycle,ShieldEquipmentId=x.Loadout.Shield?.Value??string.Empty,MountEquipmentId=x.Loadout.Mount?.Value??string.Empty};foreach(var w in x.Loadout.OrderedWeapons)d.Weapons.Add(new WeaponSlotAssignmentSaveData{Slot=(int)w.Slot,EquipmentInstanceId=w.EquipmentId.Value});foreach(var a in x.Loadout.OrderedArmor)d.Armor.Add(new ArmorSlotAssignmentSaveData{Slot=(int)a.Slot,EquipmentInstanceId=a.EquipmentId.Value});data.Soldiers.Add(d);}
        }

        private static SoldierCampaignState RestoreSoldiers(CampaignSaveData data)
        {
            var result=new SoldierCampaignState();foreach(var x in data.TroopDefinitions)result.Definitions.Add(new TroopDefinition(TroopDefinitionId.Create(x.TroopDefinitionId),x.Name,UnitClassId.Create(x.UnitClassId),CombatRoleId.Create(x.DefaultCombatRoleId),(MountContext)x.MountContext,VisualProfileId.Create(x.VisualProfileId),x.AllowedWeaponFamilies.Select(v=>(WeaponFamily)v),x.AllowsArmor,x.AllowsShield));foreach(var x in data.WeaponDefinitions)result.Definitions.Add(new WeaponDefinition(WeaponDefinitionId.Create(x.WeaponDefinitionId),x.Name,(WeaponFamily)x.Family,x.AllowedSlots.Select(v=>(WeaponSlot)v),x.AttackOptions.Select(a=>new WeaponAttackOption((AttackMode)a.Mode,(DamageType)a.DamageType)),(MountContext)x.MountContext,TradeGoodId.Create(x.EconomicGoodId),VisualProfileId.Create(x.VisualProfileId),x.IsRanged,string.IsNullOrEmpty(x.AmmoFamilyId)?(AmmoFamilyId?)null:AmmoFamilyId.Create(x.AmmoFamilyId)));foreach(var x in data.ArmorDefinitions)result.Definitions.Add(new ArmorDefinition(ArmorDefinitionId.Create(x.ArmorDefinitionId),x.Name,(ArmorSlot)x.Slot,TradeGoodId.Create(x.EconomicGoodId),VisualProfileId.Create(x.VisualProfileId),x.QualityCode));foreach(var x in data.ShieldDefinitions)result.Definitions.Add(new ShieldDefinition(ShieldDefinitionId.Create(x.ShieldDefinitionId),x.Name,TradeGoodId.Create(x.EconomicGoodId),VisualProfileId.Create(x.VisualProfileId),x.Classification));foreach(var x in data.MountDefinitions)result.Definitions.Add(new MountDefinition(MountDefinitionId.Create(x.MountDefinitionId),x.Name,TradeGoodId.Create(x.EconomicGoodId),VisualProfileId.Create(x.VisualProfileId),x.MobilityClass));foreach(var x in data.AuxiliaryEquipmentDefinitions)result.Definitions.Add(new AuxiliaryEquipmentDefinition(AuxiliaryEquipmentDefinitionId.Create(x.AuxiliaryEquipmentDefinitionId),x.Name,(AuxiliaryEquipmentKind)x.Kind,TradeGoodId.Create(x.EconomicGoodId),VisualProfileId.Create(x.VisualProfileId),string.IsNullOrEmpty(x.AmmoFamilyId)?(AmmoFamilyId?)null:AmmoFamilyId.Create(x.AmmoFamilyId)));
            foreach(var x in data.EquipmentInstances)result.RestoreEquipment(new EquipmentInstance(EquipmentInstanceId.Create(x.EquipmentInstanceId),Definition((EquipmentKind)x.DefinitionKind,x.DefinitionId),Owner((EquipmentOwnerKind)x.OwnerKind,x.OwnerId),Acquisition((EquipmentAcquisitionKind)x.AcquisitionKind,x.AcquisitionSourceId,TradeGoodId.Create(x.EconomicGoodId),new WorldTimestamp(x.AcquiredAt)),x.QualityCode));foreach(var x in data.Soldiers){var loadout=new SoldierLoadout(x.Weapons.Select(w=>new WeaponSlotAssignment((WeaponSlot)w.Slot,EquipmentInstanceId.Create(w.EquipmentInstanceId))),x.Armor.Select(a=>new ArmorSlotAssignment((ArmorSlot)a.Slot,EquipmentInstanceId.Create(a.EquipmentInstanceId))),string.IsNullOrEmpty(x.ShieldEquipmentId)?(EquipmentInstanceId?)null:EquipmentInstanceId.Create(x.ShieldEquipmentId),string.IsNullOrEmpty(x.MountEquipmentId)?(EquipmentInstanceId?)null:EquipmentInstanceId.Create(x.MountEquipmentId));result.RestoreSoldier(new SoldierInstance(SoldierId.Create(x.SoldierId),UnitGroupId.Create(x.UnitGroupId),TroopDefinitionId.Create(x.TroopDefinitionId),new SoldierRecruitmentProvenance(RecruitmentSourceId.Create(x.RecruitmentSourceId),RecruitmentRecordId.Create(x.RecruitmentRecordId)),loadout,CombatRoleId.Create(x.CombatRoleId),(SoldierExperienceAssessment)x.Experience,(SoldierTrainingAssessment)x.Training,(SoldierLifecycle)x.Lifecycle));}return result;
        }
        private static EquipmentDefinitionRef Definition(EquipmentKind kind,string id){switch(kind){case EquipmentKind.Weapon:return EquipmentDefinitionRef.Weapon(WeaponDefinitionId.Create(id));case EquipmentKind.Armor:return EquipmentDefinitionRef.Armor(ArmorDefinitionId.Create(id));case EquipmentKind.Shield:return EquipmentDefinitionRef.Shield(ShieldDefinitionId.Create(id));case EquipmentKind.Mount:return EquipmentDefinitionRef.Mount(MountDefinitionId.Create(id));case EquipmentKind.Auxiliary:return EquipmentDefinitionRef.Auxiliary(AuxiliaryEquipmentDefinitionId.Create(id));default:throw new InvalidOperationException("Unknown equipment definition kind.");}}
        private static EquipmentOwnerRef Owner(EquipmentOwnerKind kind,string id){switch(kind){case EquipmentOwnerKind.Soldier:return EquipmentOwnerRef.Soldier(SoldierId.Create(id));case EquipmentOwnerKind.Character:return EquipmentOwnerRef.Character(CharacterId.Create(id));case EquipmentOwnerKind.ArmyInventory:return EquipmentOwnerRef.ArmyInventory(ArmyId.Create(id));case EquipmentOwnerKind.Institution:return EquipmentOwnerRef.Institution(CityBuildingId.Create(id));case EquipmentOwnerKind.Caravan:return EquipmentOwnerRef.Caravan(CaravanId.Create(id));default:throw new InvalidOperationException("Unknown equipment owner kind.");}}
        private static EquipmentAcquisitionProvenance Acquisition(EquipmentAcquisitionKind kind,string id,TradeGoodId good,WorldTimestamp at)=>kind==EquipmentAcquisitionKind.CityMarket?EquipmentAcquisitionProvenance.CityMarket(CityId.Create(id),good,at):kind==EquipmentAcquisitionKind.RecruitmentProvided?EquipmentAcquisitionProvenance.RecruitmentProvided(RecruitmentRecordId.Create(id),good,at):throw new InvalidOperationException("Unknown equipment acquisition kind.");
    }
}
