using System.Linq;
using System.Collections.Generic;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;
using FOC.Domain.Common;
using FOC.Domain.Battle;
using FOC.Domain.Soldiers;
using FOC.Editor.Visuals;
using FOC.Presentation.Visuals;
using FOC.Visuals.Core;

namespace FOC.Tests.VisualPipeline
{
    [TestFixture]
    public sealed class VisualPipelineUnityTests
    {
        [Test]public void GeneratedCatalogLoadsAndValidates(){var asset=AssetDatabase.LoadAssetAtPath<VisualCatalogAsset>(VisualProofAssetGenerator.CatalogPath);Assert.That(asset,Is.Not.Null);var validation=asset.BuildCoreCatalog().Validate();Assert.That(validation.IsValid,Is.True,string.Join("\n",validation.Errors));Assert.That(asset.Assets.Count,Is.GreaterThanOrEqualTo(20));Assert.That(typeof(VisualSoldier3D),Is.Not.EqualTo(typeof(SoldierInstance)));Assert.That(typeof(CharacterView3D).Name,Is.Not.EqualTo("CharacterState"));}
        [Test]public void FullProjectVisualValidatorPasses(){var result=VisualProjectValidator.ValidateAll();Assert.That(result.IsValid,Is.True,string.Join("\n",result.Errors));}
        [Test]public void GenericHistoricalSmokeConfigurationsAssemble(){var result=VisualSmokeRunner.Run();Assert.That(result.Count,Is.EqualTo(3));Assert.That(result.All(x=>x.Contains("PASS")),Is.True);}
        [Test]public void CanonicalHumanPrefabHasSkinRigSocketsLodAvatarAndCulling(){var prefab=AssetDatabase.LoadAssetAtPath<GameObject>(VisualProofAssetGenerator.Root+"/Prefabs/BODY_Human_Proof.prefab");Assert.That(prefab,Is.Not.Null);Assert.That(prefab.GetComponentInChildren<SkinnedMeshRenderer>(true),Is.Not.Null);Assert.That(prefab.GetComponent<LODGroup>().GetLODs().Length,Is.EqualTo(3));Assert.That(prefab.GetComponentsInChildren<Transform>(true).Select(x=>x.name),Does.Contain("Socket_RightHand").And.Contain("Socket_Head"));var animator=prefab.GetComponent<Animator>();Assert.That(animator.cullingMode,Is.EqualTo(AnimatorCullingMode.CullUpdateTransforms));Assert.That(animator.avatar,Is.Not.Null);Assert.That(animator.avatar.isValid&&animator.avatar.isHuman,Is.True);}
        [Test]public void MountPrefabKeepsRiderSocketAndSeparateRig(){var prefab=AssetDatabase.LoadAssetAtPath<GameObject>(VisualProofAssetGenerator.Root+"/Prefabs/MNT_Horse_Proof.prefab");Assert.That(prefab.GetComponentsInChildren<Transform>(true).Select(x=>x.name),Does.Contain(CanonicalRig.RiderSocket).And.Contain("MountRoot"));Assert.That(prefab.GetComponentsInChildren<Transform>(true).Select(x=>x.name),Does.Not.Contain("Pelvis"));}
        [Test]public void PoolReturnClearsIdentityBeforeRebind(){var prefab=AssetDatabase.LoadAssetAtPath<GameObject>(VisualProofAssetGenerator.ViewPrefabPath).GetComponent<VisualSoldier3D>();var host=new GameObject("PoolTest");try{var pool=host.AddComponent<VisualSoldierPool>();pool.Configure(prefab,2);var first=pool.Rent();Assert.That(pool.LeasedCount,Is.EqualTo(1));pool.Return(first);Assert.That(first.Binding.IsBound,Is.False);var second=pool.Rent();Assert.That(second,Is.SameAs(first));Assert.That(second.Binding.IsBound,Is.False);pool.Return(second);}finally{Object.DestroyImmediate(host);}}
        [Test]public void SameSignatureReturnAndReassembleReusesWholeHierarchyWithoutDestroy(){var fixture=VisualSmokeRunner.CreateProof("deli");var host=new GameObject("ReuseTest");try{var view=host.AddComponent<VisualSoldier3D>();var assembler=host.AddComponent<VisualSoldier3DAssembler>();assembler.Configure(Catalog(),8,16);assembler.Assemble(view,fixture.soldier,fixture.troop,fixture.equipment);var root=view.ActiveRepresentationRoot;var created=assembler.Metrics.CreatedModules;view.ReleaseVisual();Assert.That(assembler.Metrics.DestroyedRepresentations,Is.Zero);assembler.Assemble(view,fixture.soldier,fixture.troop,fixture.equipment);Assert.That(view.ActiveRepresentationRoot,Is.SameAs(root));Assert.That(assembler.Metrics.CreatedModules,Is.EqualTo(created));Assert.That(assembler.Metrics.ReusedRepresentations,Is.EqualTo(1));Assert.That(assembler.Metrics.PoolHits,Is.EqualTo(1));}finally{Object.DestroyImmediate(host);}}
        [Test]public void DifferentSoldiersSameSignatureReuseResourcesWithoutSharingBinding(){var fixture=VisualSmokeRunner.CreateProof("deli");var host=new GameObject("IdentityReuseTest");try{var view=host.AddComponent<VisualSoldier3D>();var assembler=host.AddComponent<VisualSoldier3DAssembler>();assembler.Configure(Catalog(),8,16);var first=assembler.Assemble(view,fixture.soldier,fixture.troop,fixture.equipment);var root=view.ActiveRepresentationRoot;view.ReleaseVisual();var secondSoldier=new SoldierInstance(SoldierId.Create("proof-deli-second"),fixture.soldier.UnitGroupId,fixture.soldier.TroopDefinitionId,fixture.soldier.Recruitment,fixture.soldier.Loadout,fixture.soldier.CombatRoleId);var second=assembler.Assemble(view,secondSoldier,fixture.troop,fixture.equipment);Assert.That(second.Signature,Is.EqualTo(first.Signature));Assert.That(view.ActiveRepresentationRoot,Is.SameAs(root));Assert.That(view.Binding.SoldierId!.Value,Is.EqualTo(secondSoldier.Id));Assert.That(view.Binding.SoldierId!.Value,Is.Not.EqualTo(fixture.soldier.Id));}finally{Object.DestroyImmediate(host);}}
        [Test]public void LoadoutChangeProducesNewVariantWithoutOldEquipmentOrGameplayMutation(){var fixture=VisualSmokeRunner.CreateProof("deli");var host=new GameObject("LoadoutChangeTest");try{var view=host.AddComponent<VisualSoldier3D>();var assembler=host.AddComponent<VisualSoldier3DAssembler>();assembler.Configure(Catalog(),8,16);var originalLoadout=fixture.soldier.Loadout;var first=assembler.Assemble(view,fixture.soldier,fixture.troop,fixture.equipment);var sword=originalLoadout.OrderedWeapons.Single(x=>x.Slot==WeaponSlot.Sidearm);var changedLoadout=new SoldierLoadout(new[]{sword});var changed=new SoldierInstance(fixture.soldier.Id,fixture.soldier.UnitGroupId,fixture.soldier.TroopDefinitionId,fixture.soldier.Recruitment,changedLoadout,fixture.soldier.CombatRoleId);var second=assembler.Assemble(view,changed,fixture.troop,fixture.equipment);Assert.That(second.Signature,Is.Not.EqualTo(first.Signature));Assert.That(view.SpawnedModules.Select(x=>x.name),Does.Not.Contain("MNT_Horse_Proof").And.Not.Contain("WPN_Lance_Proof"));Assert.That(view.SpawnedModules.Select(x=>x.name),Does.Contain("WPN_Sword_Proof"));Assert.That(fixture.soldier.Loadout,Is.SameAs(originalLoadout));Assert.That(changed.Loadout,Is.SameAs(changedLoadout));}finally{Object.DestroyImmediate(host);}}
        [Test]public void StandardNarrativeAndCrowdSelectExecutableRuntimePolicies(){var fixture=VisualSmokeRunner.CreateProof("deli");var host=new GameObject("TierPolicyTest");try{var view=host.AddComponent<VisualSoldier3D>();var assembler=host.AddComponent<VisualSoldier3DAssembler>();assembler.Configure(Catalog(),8,16);assembler.Assemble(view,fixture.soldier,fixture.troop,fixture.equipment);Assert.That(view.ActiveRepresentationKind,Is.EqualTo(VisualRepresentationKind.Consolidated));Assert.That(view.SpawnedModules.Select(x=>x.name),Does.Contain("CHR_Consolidated_Proof").And.Not.Contain("BODY_Human_Proof"));var narrative=TroopForProfile(fixture.troop,"proof-narrative");assembler.Assemble(view,fixture.soldier,narrative,fixture.equipment);Assert.That(view.ActiveRepresentationKind,Is.EqualTo(VisualRepresentationKind.Modular));Assert.That(view.SpawnedModules.Select(x=>x.name),Does.Contain("BODY_Human_Proof").And.Not.Contain("CHR_Consolidated_Proof"));var crowd=TroopForProfile(fixture.troop,"proof-crowd");assembler.Assemble(view,fixture.soldier,crowd,fixture.equipment);Assert.That(view.ActiveRepresentationKind,Is.EqualTo(VisualRepresentationKind.Crowd));Assert.That(view.SpawnedModules.Select(x=>x.name),Is.EqualTo(new[]{"CRWD_Far_Proof"}));Assert.That(view.ActiveRepresentationRoot.GetComponentsInChildren<Renderer>(true).Length,Is.EqualTo(1));}finally{Object.DestroyImmediate(host);}}
        [Test]public void CacheEvictionNeverDestroysActiveLeaseAndRetiredLeaseDiesOnReturn(){var deli=VisualSmokeRunner.CreateProof("deli");var hum=VisualSmokeRunner.CreateProof("humbaraci");var host=new GameObject("EvictionTest");var a=new GameObject("A").AddComponent<VisualSoldier3D>();var b=new GameObject("B").AddComponent<VisualSoldier3D>();try{var assembler=host.AddComponent<VisualSoldier3DAssembler>();assembler.Configure(Catalog(),1,4);assembler.Assemble(a,deli.soldier,deli.troop,deli.equipment);var activeRoot=a.ActiveRepresentationRoot;assembler.Assemble(b,hum.soldier,hum.troop,hum.equipment);Assert.That(assembler.Metrics.Evictions,Is.EqualTo(1));Assert.That(activeRoot,Is.Not.Null);Assert.That(assembler.Metrics.DestroyedRepresentations,Is.Zero);a.ReleaseVisual();Assert.That(activeRoot==null,Is.True);Assert.That(assembler.Metrics.DestroyedRepresentations,Is.EqualTo(1));b.ReleaseVisual();Assert.That(assembler.PooledInstanceCount,Is.EqualTo(1));}finally{Object.DestroyImmediate(a.gameObject);Object.DestroyImmediate(b.gameObject);Object.DestroyImmediate(host);}}
        [Test]public void MountedVariantAndAnimationStateSurviveCleanReuse(){var fixture=VisualSmokeRunner.CreateProof("deli");var host=new GameObject("MountReuseTest");try{var view=host.AddComponent<VisualSoldier3D>();var assembler=host.AddComponent<VisualSoldier3DAssembler>();assembler.Configure(Catalog(),8,16);assembler.Assemble(view,fixture.soldier,fixture.troop,fixture.equipment);var root=view.ActiveRepresentationRoot;Assert.That(view.SpawnedModules.Count(x=>x.name=="MNT_Horse_Proof"),Is.EqualTo(1));Assert.That(view.SpawnedModules.Count(x=>x.name=="HAR_Harness_Proof"),Is.EqualTo(1));Assert.That(view.TryGetSocket(VisualSocket.Rider,out var rider)&&rider!=null,Is.True);Assert.That(view.SpawnedModules.Single(x=>x.name=="CHR_Consolidated_Proof").transform.IsChildOf(rider),Is.True);foreach(var animator in root.GetComponentsInChildren<Animator>(true))animator.speed=0.25f;view.ReleaseVisual();assembler.Assemble(view,fixture.soldier,fixture.troop,fixture.equipment);Assert.That(view.ActiveRepresentationRoot,Is.SameAs(root));Assert.That(view.SpawnedModules.Count(x=>x.name=="MNT_Horse_Proof"),Is.EqualTo(1));Assert.That(view.SpawnedModules.Count(x=>x.name=="HAR_Harness_Proof"),Is.EqualTo(1));Assert.That(root.GetComponentsInChildren<Animator>(true).All(x=>x.speed==1f),Is.True);Assert.That(view.Binding.SoldierId!.Value,Is.EqualTo(fixture.soldier.Id));}finally{Object.DestroyImmediate(host);}}
        [Test]public void ExplicitCatalogInvalidationDestroysOnlyIdleCacheAndForcesColdRebuild(){var fixture=VisualSmokeRunner.CreateProof("humbaraci");var host=new GameObject("InvalidationTest");try{var view=host.AddComponent<VisualSoldier3D>();var assembler=host.AddComponent<VisualSoldier3DAssembler>();assembler.Configure(Catalog(),8,16);assembler.Assemble(view,fixture.soldier,fixture.troop,fixture.equipment);var old=view.ActiveRepresentationRoot;view.ReleaseVisual();assembler.InvalidateCache();Assert.That(old==null,Is.True);Assert.That(assembler.CachedVariantCount,Is.Zero);Assert.That(assembler.PooledInstanceCount,Is.Zero);var before=assembler.Metrics.CreatedRepresentations;assembler.Assemble(view,fixture.soldier,fixture.troop,fixture.equipment);Assert.That(assembler.Metrics.CreatedRepresentations,Is.EqualTo(before+1));Assert.That(assembler.Metrics.Invalidations,Is.EqualTo(1));}finally{Object.DestroyImmediate(host);}}
        [Test]public void OuterPoolReturnKeepsReusableChildrenAndReusesView(){var fixture=VisualSmokeRunner.CreateProof("deli");var prefab=AssetDatabase.LoadAssetAtPath<GameObject>(VisualProofAssetGenerator.ViewPrefabPath).GetComponent<VisualSoldier3D>();var host=new GameObject("WholePoolTest");try{var assembler=host.AddComponent<VisualSoldier3DAssembler>();assembler.Configure(Catalog(),8,16);var pool=host.AddComponent<VisualSoldierPool>();pool.Configure(prefab,2);var first=pool.Rent();assembler.Assemble(first,fixture.soldier,fixture.troop,fixture.equipment);var root=first.ActiveRepresentationRoot;pool.Return(first);Assert.That(assembler.Metrics.DestroyedRepresentations,Is.Zero);var second=pool.Rent();assembler.Assemble(second,fixture.soldier,fixture.troop,fixture.equipment);Assert.That(second,Is.SameAs(first));Assert.That(second.ActiveRepresentationRoot,Is.SameAs(root));Assert.That(pool.CreatedViewCount,Is.EqualTo(1));Assert.That(pool.ReusedViewCount,Is.EqualTo(1));pool.Return(second);}finally{Object.DestroyImmediate(host);}}
        [Test]public void GeneratedMaterialsAreSharedAssetsNotPerSoldierInstances(){var asset=AssetDatabase.LoadAssetAtPath<VisualCatalogAsset>(VisualProofAssetGenerator.CatalogPath);foreach(var entry in asset.Assets){var renderers=entry.prefab.GetComponentsInChildren<Renderer>(true);Assert.That(renderers.SelectMany(x=>x.sharedMaterials).All(x=>x!=null&&AssetDatabase.Contains(x)),Is.True,entry.id);}}
        [Test]public void BenchmarkSceneAndMachineReadableSpecsExist(){Assert.That(AssetDatabase.LoadAssetAtPath<SceneAsset>(VisualProofAssetGenerator.BenchmarkScenePath),Is.Not.Null);Assert.That(AssetDatabase.LoadAssetAtPath<TextAsset>(VisualProofAssetGenerator.Root+"/Specs/BODY_Human_Proof.json"),Is.Not.Null);Assert.That(AssetDatabase.LoadAssetAtPath<TextAsset>(VisualProofAssetGenerator.Root+"/Specs/WPN_Sword_Proof.json"),Is.Not.Null);}
        [Test]public void BattleViewBindingUsesExistingAssemblerAndDespawnDoesNotMutateSoldier(){var fixture=VisualSmokeRunner.CreateProof("deli");var ids=fixture.soldier.Loadout.OrderedWeapons.Select(x=>x.EquipmentId).Concat(fixture.soldier.Loadout.OrderedArmor.Select(x=>x.EquipmentId)).ToList();if(fixture.soldier.Loadout.Shield.HasValue)ids.Add(fixture.soldier.Loadout.Shield.Value);if(fixture.soldier.Loadout.Mount.HasValue)ids.Add(fixture.soldier.Loadout.Mount.Value);var snapshot=new BattleCombatantSnapshot(fixture.soldier.Id,fixture.soldier.UnitGroupId,fixture.soldier.TroopDefinitionId,fixture.soldier.CombatRoleId,ids,fixture.soldier.Loadout.Mount.HasValue);var host=new GameObject("BattleBindingTest");try{var view=host.AddComponent<VisualSoldier3D>();var assembler=host.AddComponent<VisualSoldier3DAssembler>();assembler.Configure(Catalog(),8,16);var binding=host.AddComponent<BattleCombatantViewBinding>();binding.Configure(view,assembler);var loadout=fixture.soldier.Loadout;binding.Bind(snapshot,fixture.soldier,fixture.troop,fixture.equipment);Assert.That(binding.SoldierId!.Value,Is.EqualTo(fixture.soldier.Id));binding.Despawn();Assert.That(binding.SoldierId.HasValue,Is.False);Assert.That(fixture.soldier.Loadout,Is.SameAs(loadout));Assert.That(fixture.soldier.Lifecycle,Is.EqualTo(SoldierLifecycle.Active));}finally{Object.DestroyImmediate(host);}}
        private static VisualCatalogAsset Catalog()=>AssetDatabase.LoadAssetAtPath<VisualCatalogAsset>(VisualProofAssetGenerator.CatalogPath);
        private static TroopDefinition TroopForProfile(TroopDefinition source,string profile)=>new TroopDefinition(source.Id,source.Name,source.UnitClassId,source.DefaultCombatRoleId,source.MountContext,VisualProfileId.Create(profile));
    }
}
