using System;
using System.Collections.Generic;
using System.Linq;
using FOC.Domain.Characters;
using FOC.Domain.Common;
using FOC.Domain.Random;
using FOC.Domain.Time;

namespace FOC.Domain.EncountersContracts
{
    public enum EncounterFamily{Roaming,SurpriseEvent}
    public enum EncounterType{Bandit,Caravan,Noble,EnemyPatrol,Refugee,AbandonedCaravan,Epidemic,RoadCollapse,Storm,WoundedSoldier}
    public enum EncounterLifecycle{Available,Engaged,Resolved,Cancelled}
    public enum EncounterEntityKind{Character,Army,Caravan,City,Faction,Region,Battle}
    public enum EncounterRequirementKind{None,CharacterAvailable,ArmyActive,CaravanActive,CityExists,FundsAvailable,EquipmentCapability,DiplomaticContext,ContractState}
    [Flags]public enum EncounterCapability{None=0,Recruitment=1,Toll=2,Bribe=4,Battle=8,Contract=16}

    public readonly struct EncounterEntityRef:IEquatable<EncounterEntityRef>,IComparable<EncounterEntityRef>
    {
        private EncounterEntityRef(EncounterEntityKind kind,string id){if(!Enum.IsDefined(typeof(EncounterEntityKind),kind)||string.IsNullOrWhiteSpace(id))throw new ArgumentException("Encounter entity reference is invalid.");Kind=kind;Id=id;}
        public EncounterEntityKind Kind{get;}public string Id{get;}
        public static EncounterEntityRef Character(CharacterId id)=>new EncounterEntityRef(EncounterEntityKind.Character,Require(id.IsValid,id.Value));public static EncounterEntityRef Army(ArmyId id)=>new EncounterEntityRef(EncounterEntityKind.Army,Require(id.IsValid,id.Value));public static EncounterEntityRef Caravan(CaravanId id)=>new EncounterEntityRef(EncounterEntityKind.Caravan,Require(id.IsValid,id.Value));public static EncounterEntityRef City(CityId id)=>new EncounterEntityRef(EncounterEntityKind.City,Require(id.IsValid,id.Value));public static EncounterEntityRef Faction(FactionId id)=>new EncounterEntityRef(EncounterEntityKind.Faction,Require(id.IsValid,id.Value));public static EncounterEntityRef Region(RegionId id)=>new EncounterEntityRef(EncounterEntityKind.Region,Require(id.IsValid,id.Value));public static EncounterEntityRef Battle(BattleId id)=>new EncounterEntityRef(EncounterEntityKind.Battle,Require(id.IsValid,id.Value));internal static EncounterEntityRef Restore(EncounterEntityKind kind,string id)=>new EncounterEntityRef(kind,id);
        public int CompareTo(EncounterEntityRef o){var c=Kind.CompareTo(o.Kind);return c!=0?c:StringComparer.Ordinal.Compare(Id,o.Id);}public bool Equals(EncounterEntityRef o)=>Kind==o.Kind&&StringComparer.Ordinal.Equals(Id,o.Id);public override bool Equals(object? o)=>o is EncounterEntityRef x&&Equals(x);public override int GetHashCode()=>((int)Kind*397)^StringComparer.Ordinal.GetHashCode(Id);private static string Require(bool valid,string value){if(!valid)throw new ArgumentException("Typed entity ID is invalid.");return value;}
    }

    public sealed class EncounterChoiceDefinition
    {public EncounterChoiceDefinition(EncounterChoiceId id,EncounterPolicyId policyId,EncounterRequirementKind requirement=EncounterRequirementKind.None,EncounterEntityKind? targetKind=null,string contentKey="choice"){if(!id.IsValid||!policyId.IsValid||!Enum.IsDefined(typeof(EncounterRequirementKind),requirement)||(targetKind.HasValue&&!Enum.IsDefined(typeof(EncounterEntityKind),targetKind.Value))||string.IsNullOrWhiteSpace(contentKey))throw new ArgumentException("Encounter choice definition is invalid.");Id=id;PolicyId=policyId;Requirement=requirement;TargetKind=targetKind;ContentKey=contentKey;}public EncounterChoiceId Id{get;}public EncounterPolicyId PolicyId{get;}public EncounterRequirementKind Requirement{get;}public EncounterEntityKind? TargetKind{get;}public string ContentKey{get;}}
    public sealed class EncounterDefinition
    {private readonly SortedDictionary<EncounterChoiceId,EncounterChoiceDefinition> _choices=new SortedDictionary<EncounterChoiceId,EncounterChoiceDefinition>();public EncounterDefinition(EncounterDefinitionId id,EncounterFamily family,EncounterType type,IEnumerable<EncounterChoiceDefinition> choices,EncounterCapability capabilities,string contentKey){const EncounterCapability all=EncounterCapability.Recruitment|EncounterCapability.Toll|EncounterCapability.Bribe|EncounterCapability.Battle|EncounterCapability.Contract;if(!id.IsValid||!EncounterAuthority.Matches(family,type)||(capabilities&~all)!=0||string.IsNullOrWhiteSpace(contentKey))throw new ArgumentException("Encounter definition is invalid.");Id=id;Family=family;Type=type;Capabilities=capabilities;ContentKey=contentKey;foreach(var x in choices??throw new ArgumentNullException(nameof(choices)))if(x==null||_choices.ContainsKey(x.Id))throw new InvalidOperationException("Encounter choice is null or duplicated.");else _choices.Add(x.Id,x);if(_choices.Count==0)throw new ArgumentException("Encounter definition requires choices.");}public EncounterDefinitionId Id{get;}public EncounterFamily Family{get;}public EncounterType Type{get;}public EncounterCapability Capabilities{get;}public string ContentKey{get;}public IReadOnlyCollection<EncounterChoiceDefinition> OrderedChoices=>_choices.Values;public EncounterChoiceDefinition GetRequiredChoice(EncounterChoiceId id){if(!_choices.TryGetValue(id,out var x))throw new KeyNotFoundException("Encounter choice was not found.");return x;}}
    public static class EncounterAuthority
    {public static bool Matches(EncounterFamily family,EncounterType type){if(!Enum.IsDefined(typeof(EncounterFamily),family)||!Enum.IsDefined(typeof(EncounterType),type))return false;return family==EncounterFamily.Roaming?(type==EncounterType.Bandit||type==EncounterType.Caravan||type==EncounterType.Noble||type==EncounterType.EnemyPatrol||type==EncounterType.Refugee):(type==EncounterType.AbandonedCaravan||type==EncounterType.Epidemic||type==EncounterType.RoadCollapse||type==EncounterType.Storm||type==EncounterType.WoundedSoldier);}}
    public sealed class EncounterDefinitionCatalog
    {private readonly SortedDictionary<EncounterDefinitionId,EncounterDefinition> _items=new SortedDictionary<EncounterDefinitionId,EncounterDefinition>();public IReadOnlyCollection<EncounterDefinition> OrderedDefinitions=>_items.Values;public void Add(EncounterDefinition x){if(x==null||_items.ContainsKey(x.Id))throw new InvalidOperationException("Encounter definition is null or duplicated.");_items.Add(x.Id,x);}public EncounterDefinition GetRequired(EncounterDefinitionId id){if(!_items.TryGetValue(id,out var x))throw new KeyNotFoundException("Encounter definition was not found.");return x;}public bool Contains(EncounterDefinitionId id)=>_items.ContainsKey(id);}
    public sealed class EncounterContext
    {private readonly SortedSet<EncounterEntityRef> _participants=new SortedSet<EncounterEntityRef>();public EncounterContext(EncounterEntityRef source,IEnumerable<EncounterEntityRef> participants){Source=source;foreach(var x in participants??throw new ArgumentNullException(nameof(participants)))if(!_participants.Add(x))throw new InvalidOperationException("Encounter participant is duplicated.");if(_participants.Count==0)throw new ArgumentException("Encounter context requires participants.");}public EncounterEntityRef Source{get;}public IReadOnlyCollection<EncounterEntityRef> OrderedParticipants=>_participants;}
    public sealed class EncounterResolution
    {public EncounterResolution(EncounterOutcomeId outcomeId,EncounterChoiceId selectedChoiceId,EncounterPolicyId policyId,WorldTimestamp resolvedAt,RandomState randomState){if(!outcomeId.IsValid||!selectedChoiceId.IsValid||!policyId.IsValid)throw new ArgumentException("Encounter resolution is invalid.");OutcomeId=outcomeId;SelectedChoiceId=selectedChoiceId;PolicyId=policyId;ResolvedAt=resolvedAt;RandomState=randomState;}public EncounterOutcomeId OutcomeId{get;}public EncounterChoiceId SelectedChoiceId{get;}public EncounterPolicyId PolicyId{get;}public WorldTimestamp ResolvedAt{get;}public RandomState RandomState{get;}}
    public sealed class EncounterState
    {
        public EncounterState(EncounterId id,EncounterDefinitionId definitionId,EncounterFamily family,EncounterType type,WorldTimestamp createdAt,EncounterContext context,RandomState randomState,EncounterLifecycle lifecycle=EncounterLifecycle.Available,WorldTimestamp? engagedAt=null,EncounterChoiceId? selectedChoice=null,EncounterResolution? resolution=null,ContractId? linkedContract=null,BattleId? linkedBattle=null,bool outcomeApplied=false){if(!id.IsValid||!definitionId.IsValid||!EncounterAuthority.Matches(family,type)||!Enum.IsDefined(typeof(EncounterLifecycle),lifecycle))throw new ArgumentException("Encounter state is invalid.");Id=id;DefinitionId=definitionId;Family=family;Type=type;CreatedAt=createdAt;Context=context??throw new ArgumentNullException(nameof(context));RandomState=randomState;Lifecycle=lifecycle;EngagedAt=engagedAt;SelectedChoice=selectedChoice;Resolution=resolution;LinkedContractId=linkedContract;LinkedBattleId=linkedBattle;IsOutcomeApplied=outcomeApplied;Validate();}
        public EncounterId Id{get;}public EncounterDefinitionId DefinitionId{get;}public EncounterFamily Family{get;}public EncounterType Type{get;}public WorldTimestamp CreatedAt{get;}public WorldTimestamp? EngagedAt{get;private set;}public EncounterContext Context{get;}public RandomState RandomState{get;private set;}public EncounterLifecycle Lifecycle{get;private set;}public EncounterChoiceId? SelectedChoice{get;private set;}public EncounterResolution? Resolution{get;private set;}public ContractId? LinkedContractId{get;private set;}public BattleId? LinkedBattleId{get;private set;}public bool IsOutcomeApplied{get;private set;}
        public void Engage(WorldTimestamp at){if(Lifecycle!=EncounterLifecycle.Available||at.Ticks<CreatedAt.Ticks)throw new InvalidOperationException("Encounter cannot be engaged.");EngagedAt=at;Lifecycle=EncounterLifecycle.Engaged;}public void Resolve(EncounterResolution resolution){if(Lifecycle!=EncounterLifecycle.Engaged||resolution==null||resolution.ResolvedAt.Ticks<EngagedAt!.Value.Ticks)throw new InvalidOperationException("Encounter cannot resolve.");SelectedChoice=resolution.SelectedChoiceId;Resolution=resolution;RandomState=resolution.RandomState;Lifecycle=EncounterLifecycle.Resolved;}public void Cancel(){if(Lifecycle==EncounterLifecycle.Resolved||Lifecycle==EncounterLifecycle.Cancelled)throw new InvalidOperationException("Encounter is terminal.");Lifecycle=EncounterLifecycle.Cancelled;}public void MarkOutcomeApplied(){if(Lifecycle!=EncounterLifecycle.Resolved||Resolution==null||IsOutcomeApplied)throw new InvalidOperationException("Encounter outcome is unavailable or already applied.");IsOutcomeApplied=true;}public void LinkContract(ContractId id){if(!id.IsValid||LinkedContractId.HasValue)throw new InvalidOperationException("Encounter Contract link is invalid or duplicated.");LinkedContractId=id;}public void LinkBattle(BattleId id){if(!id.IsValid||LinkedBattleId.HasValue)throw new InvalidOperationException("Encounter Battle link is invalid or duplicated.");LinkedBattleId=id;}
        private void Validate(){if((Lifecycle==EncounterLifecycle.Available)&&(EngagedAt.HasValue||SelectedChoice.HasValue||Resolution!=null||IsOutcomeApplied)||Lifecycle==EncounterLifecycle.Engaged&&(!EngagedAt.HasValue||SelectedChoice.HasValue||Resolution!=null||IsOutcomeApplied)||Lifecycle==EncounterLifecycle.Resolved&&(!EngagedAt.HasValue||!SelectedChoice.HasValue||Resolution==null)||(Lifecycle==EncounterLifecycle.Cancelled&&(Resolution!=null||IsOutcomeApplied)))throw new ArgumentException("Encounter lifecycle and resolution disagree.");if(Resolution!=null&&!Resolution.SelectedChoiceId.Equals(SelectedChoice!.Value))throw new ArgumentException("Encounter selected choice and resolution disagree.");}
    }
    public sealed class EncounterRegistry{private readonly SortedDictionary<EncounterId,EncounterState> _items=new SortedDictionary<EncounterId,EncounterState>();public IReadOnlyCollection<EncounterState> OrderedEncounters=>_items.Values;public void Add(EncounterState x){if(x==null||_items.ContainsKey(x.Id))throw new InvalidOperationException("Encounter is null or duplicated.");_items.Add(x.Id,x);}public EncounterState GetRequired(EncounterId id){if(!_items.TryGetValue(id,out var x))throw new KeyNotFoundException("Encounter was not found.");return x;}public bool Contains(EncounterId id)=>_items.ContainsKey(id);}

    public enum ContractCategory{Military,Diplomatic,Economic,InternalManagement}
    public enum ContractLifecycle{Offered,Active,Completed,Failed,Cancelled}
    public enum ContractTargetKind{City,Character,Army,Caravan,Faction,Clique,Battle,Encounter}
    public enum ContractIssuerKind{Character,City,Faction,Clique,Organization}
    public enum ContractEvidenceKind{BattleCompleted,EncounterResolved,TradeCompleted,CaravanArrived,DiplomaticReportDelivered,DiplomaticActionResolved,CityStateChanged,CharacterAssignmentChanged}
    public enum CharacterStatKind{Intelligence,Observation,Persuasion,Leadership,Command,Trade,Administration,Courage,Experience}

    public sealed class ContractTargetSlotDefinition{public ContractTargetSlotDefinition(ContractTargetSlotId id,ContractTargetKind kind,bool required=true){if(!id.IsValid||!Enum.IsDefined(typeof(ContractTargetKind),kind))throw new ArgumentException("Contract target slot is invalid.");Id=id;Kind=kind;Required=required;}public ContractTargetSlotId Id{get;}public ContractTargetKind Kind{get;}public bool Required{get;}}
    public readonly struct ContractTargetBinding:IEquatable<ContractTargetBinding>,IComparable<ContractTargetBinding>
    {private ContractTargetBinding(ContractTargetSlotId slot,ContractTargetKind kind,string id){if(!slot.IsValid||!Enum.IsDefined(typeof(ContractTargetKind),kind)||string.IsNullOrWhiteSpace(id))throw new ArgumentException("Contract target binding is invalid.");SlotId=slot;Kind=kind;TargetId=id;}public ContractTargetSlotId SlotId{get;}public ContractTargetKind Kind{get;}public string TargetId{get;}public static ContractTargetBinding City(ContractTargetSlotId s,CityId id)=>new ContractTargetBinding(s,ContractTargetKind.City,Need(id.IsValid,id.Value));public static ContractTargetBinding Character(ContractTargetSlotId s,CharacterId id)=>new ContractTargetBinding(s,ContractTargetKind.Character,Need(id.IsValid,id.Value));public static ContractTargetBinding Army(ContractTargetSlotId s,ArmyId id)=>new ContractTargetBinding(s,ContractTargetKind.Army,Need(id.IsValid,id.Value));public static ContractTargetBinding Caravan(ContractTargetSlotId s,CaravanId id)=>new ContractTargetBinding(s,ContractTargetKind.Caravan,Need(id.IsValid,id.Value));public static ContractTargetBinding Faction(ContractTargetSlotId s,FactionId id)=>new ContractTargetBinding(s,ContractTargetKind.Faction,Need(id.IsValid,id.Value));public static ContractTargetBinding Clique(ContractTargetSlotId s,CliqueId id)=>new ContractTargetBinding(s,ContractTargetKind.Clique,Need(id.IsValid,id.Value));public static ContractTargetBinding Battle(ContractTargetSlotId s,BattleId id)=>new ContractTargetBinding(s,ContractTargetKind.Battle,Need(id.IsValid,id.Value));public static ContractTargetBinding Encounter(ContractTargetSlotId s,EncounterId id)=>new ContractTargetBinding(s,ContractTargetKind.Encounter,Need(id.IsValid,id.Value));internal static ContractTargetBinding Restore(ContractTargetSlotId s,ContractTargetKind k,string id)=>new ContractTargetBinding(s,k,id);public int CompareTo(ContractTargetBinding o)=>SlotId.CompareTo(o.SlotId);public bool Equals(ContractTargetBinding o)=>SlotId.Equals(o.SlotId)&&Kind==o.Kind&&StringComparer.Ordinal.Equals(TargetId,o.TargetId);public override bool Equals(object? o)=>o is ContractTargetBinding x&&Equals(x);public override int GetHashCode()=>SlotId.GetHashCode();private static string Need(bool valid,string value){if(!valid)throw new ArgumentException("Typed target ID is invalid.");return value;}}
    public readonly struct ContractIssuerRef:IEquatable<ContractIssuerRef>
    {private ContractIssuerRef(ContractIssuerKind kind,string id){if(!Enum.IsDefined(typeof(ContractIssuerKind),kind)||string.IsNullOrWhiteSpace(id))throw new ArgumentException("Contract issuer is invalid.");Kind=kind;Id=id;}public ContractIssuerKind Kind{get;}public string Id{get;}public static ContractIssuerRef Character(CharacterId id)=>new ContractIssuerRef(ContractIssuerKind.Character,Need(id.IsValid,id.Value));public static ContractIssuerRef City(CityId id)=>new ContractIssuerRef(ContractIssuerKind.City,Need(id.IsValid,id.Value));public static ContractIssuerRef Faction(FactionId id)=>new ContractIssuerRef(ContractIssuerKind.Faction,Need(id.IsValid,id.Value));public static ContractIssuerRef Clique(CliqueId id)=>new ContractIssuerRef(ContractIssuerKind.Clique,Need(id.IsValid,id.Value));public static ContractIssuerRef Organization(OrganizationId id)=>new ContractIssuerRef(ContractIssuerKind.Organization,Need(id.IsValid,id.Value));internal static ContractIssuerRef Restore(ContractIssuerKind k,string id)=>new ContractIssuerRef(k,id);public bool Equals(ContractIssuerRef o)=>Kind==o.Kind&&StringComparer.Ordinal.Equals(Id,o.Id);public override bool Equals(object? o)=>o is ContractIssuerRef x&&Equals(x);public override int GetHashCode()=>((int)Kind*397)^StringComparer.Ordinal.GetHashCode(Id);private static string Need(bool valid,string value){if(!valid)throw new ArgumentException("Typed issuer ID is invalid.");return value;}}

    public sealed class ContractObjectiveDefinition{public ContractObjectiveDefinition(ContractObjectiveId id,ContractEvidenceKind evidenceKind,ContractTargetSlotId? targetSlot=null,int requiredEvidenceCount=1){if(!id.IsValid||!Enum.IsDefined(typeof(ContractEvidenceKind),evidenceKind)||requiredEvidenceCount<=0)throw new ArgumentException("Contract objective definition is invalid.");Id=id;EvidenceKind=evidenceKind;TargetSlotId=targetSlot;RequiredEvidenceCount=requiredEvidenceCount;}public ContractObjectiveId Id{get;}public ContractEvidenceKind EvidenceKind{get;}public ContractTargetSlotId? TargetSlotId{get;}public int RequiredEvidenceCount{get;}}
    public sealed class ContractDefinition
    {private readonly SortedDictionary<ContractTargetSlotId,ContractTargetSlotDefinition> _slots=new SortedDictionary<ContractTargetSlotId,ContractTargetSlotDefinition>();private readonly SortedDictionary<ContractObjectiveId,ContractObjectiveDefinition> _objectives=new SortedDictionary<ContractObjectiveId,ContractObjectiveDefinition>();public ContractDefinition(ContractDefinitionId id,ContractCategory category,IEnumerable<ContractTargetSlotDefinition> slots,IEnumerable<ContractObjectiveDefinition> objectives,string contentKey,ContractResolutionProfileId? profileId=null){if(!id.IsValid||!Enum.IsDefined(typeof(ContractCategory),category)||string.IsNullOrWhiteSpace(contentKey))throw new ArgumentException("Contract definition is invalid.");Id=id;Category=category;ContentKey=contentKey;ResolutionProfileId=profileId;foreach(var x in slots??throw new ArgumentNullException(nameof(slots)))if(x==null||_slots.ContainsKey(x.Id))throw new InvalidOperationException("Contract target slot is duplicated.");else _slots.Add(x.Id,x);foreach(var x in objectives??throw new ArgumentNullException(nameof(objectives))){if(x==null||_objectives.ContainsKey(x.Id)||(x.TargetSlotId.HasValue&&!_slots.ContainsKey(x.TargetSlotId.Value)))throw new InvalidOperationException("Contract objective is invalid or duplicated.");_objectives.Add(x.Id,x);}if(_objectives.Count==0)throw new ArgumentException("Contract definition requires objectives.");}public ContractDefinitionId Id{get;}public ContractCategory Category{get;}public string ContentKey{get;}public ContractResolutionProfileId? ResolutionProfileId{get;}public IReadOnlyCollection<ContractTargetSlotDefinition> OrderedTargetSlots=>_slots.Values;public IReadOnlyCollection<ContractObjectiveDefinition> OrderedObjectives=>_objectives.Values;public ContractTargetSlotDefinition GetRequiredSlot(ContractTargetSlotId id){if(!_slots.TryGetValue(id,out var x))throw new KeyNotFoundException("Contract target slot was not found.");return x;}}
    public sealed class ContractDefinitionCatalog{private readonly SortedDictionary<ContractDefinitionId,ContractDefinition> _items=new SortedDictionary<ContractDefinitionId,ContractDefinition>();public IReadOnlyCollection<ContractDefinition> OrderedDefinitions=>_items.Values;public void Add(ContractDefinition x){if(x==null||_items.ContainsKey(x.Id))throw new InvalidOperationException("Contract definition is null or duplicated.");_items.Add(x.Id,x);}public ContractDefinition GetRequired(ContractDefinitionId id){if(!_items.TryGetValue(id,out var x))throw new KeyNotFoundException("Contract definition was not found.");return x;}public bool Contains(ContractDefinitionId id)=>_items.ContainsKey(id);}
    public sealed class ContractEvidence{private ContractEvidence(ContractEvidenceId id,ContractEvidenceKind kind,ContractTargetKind targetKind,string targetId,WorldTimestamp occurredAt){if(!id.IsValid||!Enum.IsDefined(typeof(ContractEvidenceKind),kind)||!Enum.IsDefined(typeof(ContractTargetKind),targetKind)||string.IsNullOrWhiteSpace(targetId))throw new ArgumentException("Contract evidence is invalid.");Id=id;Kind=kind;TargetKind=targetKind;TargetId=targetId;OccurredAt=occurredAt;}public ContractEvidenceId Id{get;}public ContractEvidenceKind Kind{get;}public ContractTargetKind TargetKind{get;}public string TargetId{get;}public WorldTimestamp OccurredAt{get;}public static ContractEvidence BattleCompleted(ContractEvidenceId id,BattleId target,WorldTimestamp at)=>new ContractEvidence(id,ContractEvidenceKind.BattleCompleted,ContractTargetKind.Battle,target.Value,at);public static ContractEvidence EncounterResolved(ContractEvidenceId id,EncounterId target,WorldTimestamp at)=>new ContractEvidence(id,ContractEvidenceKind.EncounterResolved,ContractTargetKind.Encounter,target.Value,at);public static ContractEvidence CaravanArrived(ContractEvidenceId id,CaravanId target,WorldTimestamp at)=>new ContractEvidence(id,ContractEvidenceKind.CaravanArrived,ContractTargetKind.Caravan,target.Value,at);public static ContractEvidence ReportDelivered(ContractEvidenceId id,FactionId target,WorldTimestamp at)=>new ContractEvidence(id,ContractEvidenceKind.DiplomaticReportDelivered,ContractTargetKind.Faction,target.Value,at);public static ContractEvidence TradeCompleted(ContractEvidenceId id,CaravanId target,WorldTimestamp at)=>new ContractEvidence(id,ContractEvidenceKind.TradeCompleted,ContractTargetKind.Caravan,target.Value,at);public static ContractEvidence CityChanged(ContractEvidenceId id,CityId target,WorldTimestamp at)=>new ContractEvidence(id,ContractEvidenceKind.CityStateChanged,ContractTargetKind.City,target.Value,at);public static ContractEvidence CharacterAssigned(ContractEvidenceId id,CharacterId target,WorldTimestamp at)=>new ContractEvidence(id,ContractEvidenceKind.CharacterAssignmentChanged,ContractTargetKind.Character,target.Value,at);internal static ContractEvidence Restore(ContractEvidenceId id,ContractEvidenceKind kind,ContractTargetKind targetKind,string targetId,WorldTimestamp at)=>new ContractEvidence(id,kind,targetKind,targetId,at);}
    public sealed class ContractObjectiveState
    {private readonly SortedDictionary<ContractEvidenceId,ContractEvidence> _evidence=new SortedDictionary<ContractEvidenceId,ContractEvidence>();public ContractObjectiveState(ContractObjectiveId id,ContractEvidenceKind kind,ContractTargetSlotId? targetSlot,int requiredEvidenceCount,IEnumerable<ContractEvidence>? evidence=null){if(!id.IsValid||!Enum.IsDefined(typeof(ContractEvidenceKind),kind)||requiredEvidenceCount<=0)throw new ArgumentException("Contract objective state is invalid.");Id=id;EvidenceKind=kind;TargetSlotId=targetSlot;RequiredEvidenceCount=requiredEvidenceCount;foreach(var x in evidence??Array.Empty<ContractEvidence>())AddEvidence(x);}public ContractObjectiveId Id{get;}public ContractEvidenceKind EvidenceKind{get;}public ContractTargetSlotId? TargetSlotId{get;}public int RequiredEvidenceCount{get;}public bool IsSatisfied=>_evidence.Count>=RequiredEvidenceCount;public IReadOnlyCollection<ContractEvidence> OrderedEvidence=>_evidence.Values;public void AddEvidence(ContractEvidence x){if(x==null||x.Kind!=EvidenceKind||_evidence.ContainsKey(x.Id))throw new InvalidOperationException("Contract evidence is incompatible or duplicated.");_evidence.Add(x.Id,x);}}
    public sealed class ContractState
    {
        private readonly SortedDictionary<ContractTargetSlotId,ContractTargetBinding> _targets=new SortedDictionary<ContractTargetSlotId,ContractTargetBinding>();private readonly SortedDictionary<ContractObjectiveId,ContractObjectiveState> _objectives=new SortedDictionary<ContractObjectiveId,ContractObjectiveState>();
        public ContractState(ContractId id,ContractDefinitionId definitionId,ContractCategory category,ContractIssuerRef issuer,IEnumerable<ContractTargetBinding> targets,IEnumerable<ContractObjectiveState> objectives,WorldTimestamp offeredAt,CharacterId? assignee=null,WorldTimestamp? deadline=null,EncounterId? linkedEncounter=null,BattleId? linkedBattle=null,ContractLifecycle lifecycle=ContractLifecycle.Offered,WorldTimestamp? acceptedAt=null,WorldTimestamp? terminalAt=null,bool outcomeApplied=false){if(!id.IsValid||!definitionId.IsValid||!Enum.IsDefined(typeof(ContractCategory),category)||(deadline.HasValue&&deadline.Value.Ticks<=offeredAt.Ticks))throw new ArgumentException("Contract state is invalid.");Id=id;DefinitionId=definitionId;Category=category;Issuer=issuer;OfferedAt=offeredAt;AssigneeId=assignee;Deadline=deadline;LinkedEncounterId=linkedEncounter;LinkedBattleId=linkedBattle;Lifecycle=lifecycle;AcceptedAt=acceptedAt;TerminalAt=terminalAt;IsOutcomeApplied=outcomeApplied;foreach(var x in targets??throw new ArgumentNullException(nameof(targets)))if(_targets.ContainsKey(x.SlotId))throw new InvalidOperationException("Contract target binding is duplicated.");else _targets.Add(x.SlotId,x);foreach(var x in objectives??throw new ArgumentNullException(nameof(objectives)))if(x==null||_objectives.ContainsKey(x.Id))throw new InvalidOperationException("Contract objective is duplicated.");else _objectives.Add(x.Id,x);if(_objectives.Count==0)throw new ArgumentException("Contract requires objectives.");ValidateLifecycle();}
        public ContractId Id{get;}public ContractDefinitionId DefinitionId{get;}public ContractCategory Category{get;}public ContractIssuerRef Issuer{get;}public CharacterId? AssigneeId{get;}public WorldTimestamp OfferedAt{get;}public WorldTimestamp? AcceptedAt{get;private set;}public WorldTimestamp? Deadline{get;}public WorldTimestamp? TerminalAt{get;private set;}public EncounterId? LinkedEncounterId{get;}public BattleId? LinkedBattleId{get;}public ContractLifecycle Lifecycle{get;private set;}public bool IsOutcomeApplied{get;private set;}public IReadOnlyCollection<ContractTargetBinding> OrderedTargets=>_targets.Values;public IReadOnlyCollection<ContractObjectiveState> OrderedObjectives=>_objectives.Values;public bool AllObjectivesSatisfied=>_objectives.Values.All(x=>x.IsSatisfied);
        public ContractTargetBinding GetRequiredTarget(ContractTargetSlotId id){if(!_targets.TryGetValue(id,out var x))throw new KeyNotFoundException("Contract target binding was not found.");return x;}public ContractObjectiveState GetRequiredObjective(ContractObjectiveId id){if(!_objectives.TryGetValue(id,out var x))throw new KeyNotFoundException("Contract objective was not found.");return x;}public void Accept(WorldTimestamp at){if(Lifecycle!=ContractLifecycle.Offered||at.Ticks<OfferedAt.Ticks)throw new InvalidOperationException("Contract cannot be accepted.");AcceptedAt=at;Lifecycle=ContractLifecycle.Active;}public void Complete(WorldTimestamp at){if(Lifecycle!=ContractLifecycle.Active||!AllObjectivesSatisfied||at.Ticks<AcceptedAt!.Value.Ticks)throw new InvalidOperationException("Contract cannot complete.");TerminalAt=at;Lifecycle=ContractLifecycle.Completed;}public void Fail(WorldTimestamp at){if(Lifecycle!=ContractLifecycle.Active||at.Ticks<AcceptedAt!.Value.Ticks)throw new InvalidOperationException("Contract cannot fail.");TerminalAt=at;Lifecycle=ContractLifecycle.Failed;}public void Cancel(WorldTimestamp at){if((Lifecycle!=ContractLifecycle.Offered&&Lifecycle!=ContractLifecycle.Active)||at.Ticks<OfferedAt.Ticks)throw new InvalidOperationException("Contract cannot be cancelled.");TerminalAt=at;Lifecycle=ContractLifecycle.Cancelled;}public void MarkOutcomeApplied(){if((Lifecycle!=ContractLifecycle.Completed&&Lifecycle!=ContractLifecycle.Failed)||IsOutcomeApplied)throw new InvalidOperationException("Contract outcome is unavailable or already applied.");IsOutcomeApplied=true;}
        private void ValidateLifecycle(){if(Lifecycle==ContractLifecycle.Offered&&(AcceptedAt.HasValue||TerminalAt.HasValue||IsOutcomeApplied)||Lifecycle==ContractLifecycle.Active&&(!AcceptedAt.HasValue||TerminalAt.HasValue||IsOutcomeApplied)||(Lifecycle==ContractLifecycle.Completed||Lifecycle==ContractLifecycle.Failed)&&(!AcceptedAt.HasValue||!TerminalAt.HasValue)||(Lifecycle==ContractLifecycle.Cancelled&&(!TerminalAt.HasValue||IsOutcomeApplied)))throw new ArgumentException("Contract lifecycle and timestamps disagree.");if(Lifecycle==ContractLifecycle.Completed&&!AllObjectivesSatisfied)throw new ArgumentException("Completed Contract has unsatisfied objectives.");}
    }
    public sealed class ContractRegistry{private readonly SortedDictionary<ContractId,ContractState> _items=new SortedDictionary<ContractId,ContractState>();public IReadOnlyCollection<ContractState> OrderedContracts=>_items.Values;public void Add(ContractState x){if(x==null||_items.ContainsKey(x.Id))throw new InvalidOperationException("Contract is null or duplicated.");_items.Add(x.Id,x);}public ContractState GetRequired(ContractId id){if(!_items.TryGetValue(id,out var x))throw new KeyNotFoundException("Contract was not found.");return x;}public bool Contains(ContractId id)=>_items.ContainsKey(id);}
    public sealed class ContractStatWeight{public ContractStatWeight(CharacterStatKind stat,int weight){if(!Enum.IsDefined(typeof(CharacterStatKind),stat)||weight==0)throw new ArgumentException("Contract stat weight is invalid.");Stat=stat;Weight=weight;}public CharacterStatKind Stat{get;}public int Weight{get;}}
    public sealed class ContractResolutionProfile{private readonly SortedDictionary<CharacterStatKind,int> _weights=new SortedDictionary<CharacterStatKind,int>();public ContractResolutionProfile(ContractResolutionProfileId id,IEnumerable<ContractStatWeight> weights){if(!id.IsValid)throw new ArgumentException(nameof(id));Id=id;foreach(var x in weights??throw new ArgumentNullException(nameof(weights)))if(x==null||_weights.ContainsKey(x.Stat))throw new InvalidOperationException("Contract profile weight is duplicated.");else _weights.Add(x.Stat,x.Weight);if(_weights.Count==0)throw new ArgumentException("Contract profile requires explicit weights.");}public ContractResolutionProfileId Id{get;}public IReadOnlyDictionary<CharacterStatKind,int> OrderedWeights=>_weights;public long Evaluate(CharacterStats stats){if(stats==null)throw new ArgumentNullException(nameof(stats));long value=0;checked{foreach(var x in _weights)value+=x.Value*Read(stats,x.Key);}return value;}private static int Read(CharacterStats s,CharacterStatKind k){switch(k){case CharacterStatKind.Intelligence:return s.Intelligence.Value;case CharacterStatKind.Observation:return s.Observation.Value;case CharacterStatKind.Persuasion:return s.Persuasion.Value;case CharacterStatKind.Leadership:return s.Leadership.Value;case CharacterStatKind.Command:return s.Command.Value;case CharacterStatKind.Trade:return s.Trade.Value;case CharacterStatKind.Administration:return s.Administration.Value;case CharacterStatKind.Courage:return s.Courage.Value;case CharacterStatKind.Experience:return s.Experience.Value;default:throw new ArgumentOutOfRangeException(nameof(k));}}}
    public sealed class EncounterContractCampaignState{public EncounterContractCampaignState(EncounterRegistry? encounters=null,ContractRegistry? contracts=null){Encounters=encounters??new EncounterRegistry();Contracts=contracts??new ContractRegistry();}public EncounterRegistry Encounters{get;}public ContractRegistry Contracts{get;}}
}
