using System;
using FOC.Domain.Campaign;
using FOC.Domain.Characters;
using FOC.Domain.Cities;
using FOC.Domain.Common;
using FOC.Domain.Diplomacy;
using FOC.Domain.Organizations;

namespace FOC.Domain.Validation
{
    public sealed class DiplomacyInvariantValidator:IInvariantValidator<CampaignRuntimeState>
    {
        public ValidationResult Validate(CampaignRuntimeState campaign){var r=new ValidationResult();if(campaign==null){r.AddError("CAMPAIGN_NULL","Campaign required.");return r;}foreach(var x in campaign.Diplomacy.Relations.OrderedRelations)Try(r,"DIPLOMATIC_RELATION_INVALID",()=>{RequireActor(campaign,x.Pair.First);RequireActor(campaign,x.Pair.Second);});foreach(var x in campaign.Diplomacy.Missions.OrderedMissions)Try(r,"ENVOY_MISSION_INVALID",()=>ValidateMission(campaign,x));foreach(var x in campaign.Diplomacy.Messages.OrderedMessages)Try(r,"DIPLOMATIC_MESSAGE_INVALID",()=>ValidateMessage(campaign,x));foreach(var x in campaign.Diplomacy.Actions.OrderedActions)Try(r,"DIPLOMATIC_ACTION_INVALID",()=>ValidateAction(campaign,x));foreach(var x in campaign.Diplomacy.Reports.OrderedReports)Try(r,"REPORT_INVALID",()=>ValidateReport(campaign,x));foreach(var x in campaign.Diplomacy.Information.OrderedInformation)Try(r,"INFORMATION_INVALID",()=>{RequireActor(campaign,x.ActorId);foreach(var report in x.OrderedAvailableReports)if(report.Status!=CommunicationStatus.Delivered||!report.RecipientActorId.Equals(x.ActorId))throw new InvalidOperationException();});foreach(var x in campaign.Diplomacy.Agreements.OrderedAgreements)Try(r,"AGREEMENT_INVALID",()=>{RequireActor(campaign,x.Parties.First);RequireActor(campaign,x.Parties.Second);});return r;}
        private static void ValidateMission(CampaignRuntimeState c,EnvoyMissionState x){RequireActor(c,x.SourceActorId);RequireActor(c,x.TargetActorId);var character=c.Characters.GetRequired(x.CharacterId);if(character.IsDead||character.Location.Kind==CharacterLocationKind.Captivity)throw new InvalidOperationException();var org=c.Organizations.GetRequired(x.OrganizationId);AssignmentState? found=null;foreach(var a in org.OrderedAssignments)if(a.Id.Equals(x.AssignmentId)){found=a;break;}if(found==null||!found.IsActive||found.Branch!=OrganizationBranch.Diplomacy||!found.CharacterId.Equals(x.CharacterId)||!AuthorityEnough(found.Authority,x.Mandate.Scope))throw new InvalidOperationException();}
        private static bool AuthorityEnough(AssignmentAuthority a,DiplomaticAuthorityScope s)=>s==DiplomaticAuthorityScope.DeliverOnly||s==DiplomaticAuthorityScope.Negotiate&&(a==AssignmentAuthority.Responsible||a==AssignmentAuthority.Manager||a==AssignmentAuthority.Deputy||a==AssignmentAuthority.FullAuthority)||s==DiplomaticAuthorityScope.Conclude&&a==AssignmentAuthority.FullAuthority;
        private static void ValidateMessage(CampaignRuntimeState c,DiplomaticMessageState x){RequireActor(c,x.SenderActorId);RequireActor(c,x.RecipientActorId);var carrier=c.Characters.GetRequired(x.CarrierCharacterId);if(carrier.IsDead||carrier.Location.Kind==CharacterLocationKind.Captivity)throw new InvalidOperationException();if(x.CarrierKind==MessageCarrierKind.EnvoyMission){var mission=c.Diplomacy.Missions.GetRequired(x.EnvoyMissionId!.Value);if(!mission.CharacterId.Equals(x.CarrierCharacterId)||!mission.SourceActorId.Equals(x.SenderActorId)||!mission.TargetActorId.Equals(x.RecipientActorId))throw new InvalidOperationException();}}
        private static void ValidateAction(CampaignRuntimeState c,DiplomaticActionState x){RequireActor(c,x.SourceActorId);RequireActor(c,x.TargetActorId);var mission=c.Diplomacy.Missions.GetRequired(x.MissionId);var message=c.Diplomacy.Messages.GetRequired(x.MessageId);if(!mission.SourceActorId.Equals(x.SourceActorId)||!mission.TargetActorId.Equals(x.TargetActorId)||!mission.Mandate.Allows(x.Kind)||!message.SenderActorId.Equals(x.SourceActorId)||!message.RecipientActorId.Equals(x.TargetActorId))throw new InvalidOperationException();}
        private static void ValidateReport(CampaignRuntimeState c,ReportState x){RequireActor(c,x.RecipientActorId);switch(x.Source.Kind){case ReportSourceKind.Caravan:c.Economy.Caravans.GetRequired(CaravanId.Create(x.Source.Id));break;case ReportSourceKind.CityInstitution:var city=c.Cities.GetRequired(x.Source.CityId!.Value);var active=false;foreach(var area in city.OrderedAreas)foreach(var b in area.OrderedActiveBuildings)if(b.Id.Equals(x.Source.BuildingId!.Value)){foreach(var tag in b.EffectTags)if(tag==CityInstitutionEffectTag.ReportQuality||tag==CityInstitutionEffectTag.RecordOrder||tag==CityInstitutionEffectTag.DiplomacyOptions||tag==CityInstitutionEffectTag.ExternalInformation)active=true;}if(!active)throw new InvalidOperationException();break;default:c.Characters.GetRequired(CharacterId.Create(x.Source.Id));break;}foreach(var o in x.OrderedObservations)ValidateSubject(c,o.Subject);}
        private static void ValidateSubject(CampaignRuntimeState c,ReportSubjectRef x){switch(x.Kind){case ReportSubjectKind.Faction:RequireActor(c,FactionId.Create(x.Id));break;case ReportSubjectKind.City:case ReportSubjectKind.Market:c.Cities.GetRequired(CityId.Create(x.Id));break;case ReportSubjectKind.Caravan:c.Economy.Caravans.GetRequired(CaravanId.Create(x.Id));break;case ReportSubjectKind.Character:c.Characters.GetRequired(CharacterId.Create(x.Id));break;case ReportSubjectKind.Diplomacy:var found=false;foreach(var relation in c.Diplomacy.Relations.OrderedRelations)if(relation.Id.Value==x.Id)found=true;if(!found)throw new InvalidOperationException();break;}}
        private static DiplomaticActorState RequireActor(CampaignRuntimeState c,FactionId id){var x=c.Diplomacy.Actors.GetRequired(id);if(!x.IsActive)throw new InvalidOperationException();return x;}
        private static void Try(ValidationResult r,string code,Action a){try{a();}catch(Exception){r.AddError(code,"Diplomacy invariant is invalid.");}}
    }
}
