using System;
using FOC.Domain.Campaign;
using FOC.Domain.Characters;
using FOC.Domain.Cities;
using FOC.Domain.Common;
using FOC.Domain.Military;
using FOC.Domain.Organizations;

namespace FOC.Domain.Validation
{
    public sealed class MilitaryInvariantValidator:IInvariantValidator<CampaignRuntimeState>
    {
        public ValidationResult Validate(CampaignRuntimeState subject)
        {
            var result=new ValidationResult();if(subject==null){result.AddError("CAMPAIGN_NULL","Campaign is required.");return result;}foreach(var source in subject.Military.RecruitmentSources.OrderedSources)Try(result,"RECRUITMENT_SOURCE_INVALID",()=>ValidateSource(subject,source));foreach(var army in subject.Military.Armies.OrderedArmies)Try(result,"ARMY_INVALID",()=>ValidateArmy(subject,army));foreach(var record in subject.Military.RecruitmentRecords.OrderedRecords)Try(result,"RECRUITMENT_RECORD_INVALID",()=>{subject.Military.RecruitmentSources.GetRequired(record.SourceId);var army=subject.Military.Armies.GetRequired(record.ArmyId);var unit=army.GetRequiredUnit(record.UnitGroupId);if(record.Headcount<=0||!unit.SourceId.Equals(record.SourceId))throw new InvalidOperationException();});return result;
        }
        private static void ValidateSource(CampaignRuntimeState campaign,RecruitmentSourceState source){ValidateArmyAssignment(campaign,source.Authority.CharacterId,source.Authority.OrganizationId,source.Authority.AssignmentId,null);if(source.CityId.HasValue)campaign.Cities.GetRequired(source.CityId.Value);if(source.InstitutionId.HasValue){var city=campaign.Cities.GetRequired(source.CityId!.Value);var found=false;foreach(var b in city.GetRequiredArea(CityAreaType.Military).OrderedActiveBuildings)if(b.Id.Equals(source.InstitutionId.Value))found=true;if(!found)throw new InvalidOperationException();}}
        private static void ValidateArmy(CampaignRuntimeState campaign,ArmyState army){ValidateOwner(campaign,army.Owner);ValidateOwner(campaign,army.Controller);if(army.Location.Kind==ArmyLocationKind.City)campaign.Cities.GetRequired(army.Location.CityId!.Value);if(army.Commander!=null){var c=campaign.Characters.GetRequired(army.Commander.CharacterId);if(c.IsDead||c.Captivity!=null)throw new InvalidOperationException();ValidateArmyAssignment(campaign,c.Id,army.Commander.OrganizationId,army.Commander.AssignmentId,army.Id);}foreach(var u in army.OrderedUnits){campaign.Military.RecruitmentSources.GetRequired(u.SourceId);if(u.Headcount<0)throw new InvalidOperationException();if(u.CommanderId.HasValue){var c=campaign.Characters.GetRequired(u.CommanderId.Value);if(c.IsDead||c.Captivity!=null)throw new InvalidOperationException();}}foreach(var relationship in army.Command.OrderedRelationships){if(relationship.Parent.Kind==CommandNodeKind.Army){if(relationship.Parent.Id!=army.Id.Value)throw new InvalidOperationException();}else army.GetRequiredUnit(UnitGroupId.Create(relationship.Parent.Id));army.GetRequiredUnit(UnitGroupId.Create(relationship.Child.Id));}foreach(var q in army.Supply.OrderedGoods)campaign.Economy.Goods.GetRequired(q.GoodId);foreach(var q in army.OrderedSupplyRequirements){var good=campaign.Economy.Goods.GetRequired(q.GoodId);if(q.Purpose==SupplyPurpose.Food&&!good.IsFood||q.Purpose==SupplyPurpose.Ammunition&&!good.IsMilitaryGood)throw new InvalidOperationException();}foreach(var o in army.Payroll.OrderedObligations){if(o.FundingSource.Kind==PayrollFundingSourceKind.CityMarket)campaign.Economy.GetRequiredMarket(CityId.Create(o.FundingSource.Id));else campaign.Economy.Caravans.GetRequired(CaravanId.Create(o.FundingSource.Id));}}
        private static void ValidateOwner(CampaignRuntimeState c,ArmyOwnerRef o){switch(o.Kind){case ArmyOwnerKind.Character:c.Characters.GetRequired(CharacterId.Create(o.Id));break;case ArmyOwnerKind.Faction:c.Diplomacy.Actors.GetRequired(FactionId.Create(o.Id));break;case ArmyOwnerKind.Organization:c.Organizations.GetRequired(OrganizationId.Create(o.Id));break;case ArmyOwnerKind.CityGarrison:c.Cities.GetRequired(CityId.Create(o.Id));break;case ArmyOwnerKind.Institution:var found=false;foreach(var city in c.Cities.OrderedCities)foreach(var b in city.GetRequiredArea(CityAreaType.Military).OrderedActiveBuildings)if(b.Id.Value==o.Id)found=true;if(!found)throw new InvalidOperationException();break;case ArmyOwnerKind.MercenaryCompany:if(string.IsNullOrWhiteSpace(o.Id))throw new InvalidOperationException();break;case ArmyOwnerKind.CaravanSecurity:c.Economy.Caravans.GetRequired(CaravanId.Create(o.Id));break;default:throw new InvalidOperationException();}}
        private static void ValidateArmyAssignment(CampaignRuntimeState c,CharacterId characterId,OrganizationId organizationId,AssignmentId assignmentId,ArmyId? armyId){var character=c.Characters.GetRequired(characterId);if(character.IsDead||character.Captivity!=null)throw new InvalidOperationException();var o=c.Organizations.GetRequired(organizationId);foreach(var a in o.OrderedAssignments)if(a.Id.Equals(assignmentId)&&a.CharacterId.Equals(characterId)&&a.IsActive&&a.Branch==OrganizationBranch.Army&&(!armyId.HasValue||(a.Target.Kind==AssignmentTargetKind.Army&&a.Target.TargetId==armyId.Value.Value)))return;throw new InvalidOperationException();}
        private static void Try(ValidationResult result,string code,Action action){try{action();}catch(Exception){result.AddError(code,"Military invariant is invalid.");}}
    }
}
