using System;
using System.Collections.Generic;
using System.Linq;
using FOC.Domain.Campaign;
using FOC.Domain.Common;
using FOC.Domain.Military;
using FOC.Domain.Soldiers;

namespace FOC.Domain.Validation
{
    public sealed class SoldierInvariantValidator:IInvariantValidator<CampaignRuntimeState>
    {
        public ValidationResult Validate(CampaignRuntimeState state)
        {
            var result=new ValidationResult();if(state==null){result.AddError("SOLDIER_CAMPAIGN_NULL","Campaign is required.");return result;}var units=new Dictionary<UnitGroupId,UnitGroupState>();foreach(var army in state.Military.Armies.OrderedArmies)foreach(var unit in army.OrderedUnits)units[unit.Id]=unit;var counts=new Dictionary<UnitGroupId,long>();
            foreach(var soldier in state.Soldiers.Soldiers.OrderedSoldiers){if(!units.TryGetValue(soldier.UnitGroupId,out var unit)){result.AddError("SOLDIER_UNIT_DANGLING","Soldier Unit Group is missing.");continue;}var hasTroop=state.Soldiers.Definitions.Contains(soldier.TroopDefinitionId);if(!hasTroop||!StringComparer.Ordinal.Equals(unit.TroopDefinitionId,soldier.TroopDefinitionId.Value))result.AddError("SOLDIER_TROOP_INVALID","Soldier troop definition conflicts with Unit Group.");counts[soldier.UnitGroupId]=(counts.TryGetValue(soldier.UnitGroupId,out var n)?n:0)+1;var record=state.Military.RecruitmentRecords.OrderedRecords.FirstOrDefault(x=>x.Id.Equals(soldier.Recruitment.RecordId));if(record==null||!record.SourceId.Equals(soldier.Recruitment.SourceId)||!record.UnitGroupId.Equals(soldier.UnitGroupId))result.AddError("SOLDIER_RECRUITMENT_INVALID","Soldier recruitment provenance is invalid.");if(hasTroop)ValidateLoadout(state,soldier,result);}
            foreach(var pair in counts)if(pair.Value>units[pair.Key].Headcount)result.AddError("SOLDIER_HEADCOUNT_EXCEEDED","Instantiated Soldiers exceed Unit Group headcount.");foreach(var equipment in state.Soldiers.Equipment.OrderedEquipment){if(!DefinitionExists(state,equipment.Definition)||equipment.Owner.Kind==EquipmentOwnerKind.Soldier&&!state.Soldiers.Soldiers.Contains(SoldierId.Create(equipment.Owner.Id)))result.AddError("EQUIPMENT_INVALID","Equipment definition or owner is invalid.");if(!state.Economy.Goods.OrderedGoods.Any(x=>x.Id.Equals(equipment.Provenance.EconomicGoodId)))result.AddError("EQUIPMENT_GOOD_DANGLING","Equipment economic source Good is missing.");}
            return result;
        }
        private static void ValidateLoadout(CampaignRuntimeState state,SoldierInstance soldier,ValidationResult r){var ids=new HashSet<EquipmentInstanceId>();var mounted=soldier.Loadout.Mount.HasValue;var troop=state.Soldiers.Definitions.GetRequired(soldier.TroopDefinitionId);if(!troop.AllowsArmor&&soldier.Loadout.OrderedArmor.Count>0)r.AddError("SOLDIER_ARMOR_FORBIDDEN","Troop definition does not allow armor.");if(!troop.AllowsShield&&soldier.Loadout.Shield.HasValue)r.AddError("SOLDIER_SHIELD_FORBIDDEN","Troop definition does not allow a shield.");if(troop.MountContext==MountContext.MountedOnly&&!mounted||troop.MountContext==MountContext.InfantryOnly&&mounted)r.AddError("SOLDIER_MOUNT_INCOMPATIBLE","Soldier mount conflicts with troop definition.");foreach(var x in soldier.Loadout.OrderedWeapons){if(!ids.Add(x.EquipmentId)){r.AddError("LOADOUT_DUPLICATE_EQUIPMENT","Equipment occupies multiple slots.");continue;}EquipmentInstance e;try{e=state.Soldiers.Equipment.GetRequired(x.EquipmentId);}catch(KeyNotFoundException){r.AddError("LOADOUT_EQUIPMENT_DANGLING","Loadout equipment is missing.");continue;}if(!e.Owner.Equals(EquipmentOwnerRef.Soldier(soldier.Id))||!TroopAllowsWeapon(state,troop,e)||!WeaponFits(state,e,x.Slot,soldier.Loadout))r.AddError("LOADOUT_WEAPON_INVALID","Weapon slot or owner is invalid.");}foreach(var x in soldier.Loadout.OrderedArmor){if(!ids.Add(x.EquipmentId)){r.AddError("LOADOUT_DUPLICATE_EQUIPMENT","Equipment occupies multiple slots.");continue;}try{var e=state.Soldiers.Equipment.GetRequired(x.EquipmentId);if(!e.Owner.Equals(EquipmentOwnerRef.Soldier(soldier.Id))||e.Definition.Kind!=EquipmentKind.Armor||state.Soldiers.Definitions.GetRequired(ArmorDefinitionId.Create(e.Definition.Id)).Slot!=x.Slot||(x.Slot==ArmorSlot.MountArmor&&!mounted))r.AddError("LOADOUT_ARMOR_INVALID","Armor slot or owner is invalid.");}catch(KeyNotFoundException){r.AddError("LOADOUT_EQUIPMENT_DANGLING","Loadout equipment is missing.");}}ValidateSpecial(state,soldier,soldier.Loadout.Shield,EquipmentKind.Shield,ids,r);ValidateSpecial(state,soldier,soldier.Loadout.Mount,EquipmentKind.Mount,ids,r);}
        private static void ValidateSpecial(CampaignRuntimeState state,SoldierInstance soldier,EquipmentInstanceId? id,EquipmentKind kind,HashSet<EquipmentInstanceId> ids,ValidationResult r){if(!id.HasValue)return;if(!ids.Add(id.Value)){r.AddError("LOADOUT_DUPLICATE_EQUIPMENT","Equipment occupies multiple slots.");return;}try{var e=state.Soldiers.Equipment.GetRequired(id.Value);if(e.Definition.Kind!=kind||!e.Owner.Equals(EquipmentOwnerRef.Soldier(soldier.Id)))r.AddError("LOADOUT_SPECIAL_INVALID","Shield or mount slot is invalid.");}catch(KeyNotFoundException){r.AddError("LOADOUT_EQUIPMENT_DANGLING","Loadout equipment is missing.");}}
        private static bool WeaponFits(CampaignRuntimeState state,EquipmentInstance e,WeaponSlot slot,SoldierLoadout loadout){if(e.Definition.Kind==EquipmentKind.Weapon){var d=state.Soldiers.Definitions.GetRequired(WeaponDefinitionId.Create(e.Definition.Id));if(!d.AllowedSlots.Contains(slot))return false;if(d.MountContext==MountContext.MountedOnly&&!loadout.Mount.HasValue||d.MountContext==MountContext.InfantryOnly&&loadout.Mount.HasValue)return false;if(d.IsRanged){var ammo=loadout.WeaponAt(WeaponSlot.Ammo);if(!ammo.HasValue)return false;var a=state.Soldiers.Equipment.GetRequired(ammo.Value);return a.Definition.Kind==EquipmentKind.Auxiliary&&Nullable.Equals(state.Soldiers.Definitions.GetRequired(AuxiliaryEquipmentDefinitionId.Create(a.Definition.Id)).AmmoFamilyId,d.AmmoFamilyId);}return true;}if(e.Definition.Kind!=EquipmentKind.Auxiliary)return false;var aux=state.Soldiers.Definitions.GetRequired(AuxiliaryEquipmentDefinitionId.Create(e.Definition.Id));return aux.Kind==AuxiliaryEquipmentKind.Ammunition?slot==WeaponSlot.Ammo:slot==WeaponSlot.Special;}
        private static bool TroopAllowsWeapon(CampaignRuntimeState state,TroopDefinition troop,EquipmentInstance equipment){if(equipment.Definition.Kind!=EquipmentKind.Weapon||troop.AllowedWeaponFamilies.Count==0)return true;return troop.AllowedWeaponFamilies.Contains(state.Soldiers.Definitions.GetRequired(WeaponDefinitionId.Create(equipment.Definition.Id)).Family);}
        private static bool DefinitionExists(CampaignRuntimeState state,EquipmentDefinitionRef d){switch(d.Kind){case EquipmentKind.Weapon:return state.Soldiers.Definitions.Contains(WeaponDefinitionId.Create(d.Id));case EquipmentKind.Armor:return state.Soldiers.Definitions.Contains(ArmorDefinitionId.Create(d.Id));case EquipmentKind.Shield:return state.Soldiers.Definitions.Contains(ShieldDefinitionId.Create(d.Id));case EquipmentKind.Mount:return state.Soldiers.Definitions.Contains(MountDefinitionId.Create(d.Id));case EquipmentKind.Auxiliary:return state.Soldiers.Definitions.Contains(AuxiliaryEquipmentDefinitionId.Create(d.Id));default:return false;}}
    }
}
