using System;
using System.Collections.Generic;
using System.Linq;
using FOC.Domain.Campaign;
using FOC.Domain.Characters;
using FOC.Domain.Common;
using FOC.Domain.Economy;
using FOC.Domain.Military;
using FOC.Domain.Soldiers;
using FOC.Domain.Time;

namespace FOC.Application.Soldiers
{
    public enum EquipmentPlacementKind { Weapon, Armor, Shield, Mount }

    public sealed class EquipmentIssueLine
    {
        private EquipmentIssueLine(EquipmentInstanceId instanceId,EquipmentDefinitionRef definition,EquipmentPlacementKind placement,WeaponSlot weaponSlot,ArmorSlot armorSlot,string qualityCode){if(!instanceId.IsValid||string.IsNullOrWhiteSpace(definition.Id)||string.IsNullOrWhiteSpace(qualityCode))throw new ArgumentException("Equipment issue line is invalid.");InstanceId=instanceId;Definition=definition;Placement=placement;WeaponSlot=weaponSlot;ArmorSlot=armorSlot;QualityCode=qualityCode;}
        public EquipmentInstanceId InstanceId{get;}public EquipmentDefinitionRef Definition{get;}public EquipmentPlacementKind Placement{get;}public WeaponSlot WeaponSlot{get;}public ArmorSlot ArmorSlot{get;}public string QualityCode{get;}
        public static EquipmentIssueLine Weapon(EquipmentInstanceId id,WeaponDefinitionId definition,WeaponSlot slot,string quality="unspecified")=>new EquipmentIssueLine(id,EquipmentDefinitionRef.Weapon(definition),EquipmentPlacementKind.Weapon,slot,default,quality);
        public static EquipmentIssueLine Auxiliary(EquipmentInstanceId id,AuxiliaryEquipmentDefinitionId definition,WeaponSlot slot,string quality="unspecified")=>new EquipmentIssueLine(id,EquipmentDefinitionRef.Auxiliary(definition),EquipmentPlacementKind.Weapon,slot,default,quality);
        public static EquipmentIssueLine Armor(EquipmentInstanceId id,ArmorDefinitionId definition,ArmorSlot slot,string quality="unspecified")=>new EquipmentIssueLine(id,EquipmentDefinitionRef.Armor(definition),EquipmentPlacementKind.Armor,default,slot,quality);
        public static EquipmentIssueLine Shield(EquipmentInstanceId id,ShieldDefinitionId definition,string quality="unspecified")=>new EquipmentIssueLine(id,EquipmentDefinitionRef.Shield(definition),EquipmentPlacementKind.Shield,default,default,quality);
        public static EquipmentIssueLine Mount(EquipmentInstanceId id,MountDefinitionId definition,string quality="unspecified")=>new EquipmentIssueLine(id,EquipmentDefinitionRef.Mount(definition),EquipmentPlacementKind.Mount,default,default,quality);
    }

    public sealed class SoldierAcquisitionRequest
    {
        private readonly List<EquipmentIssueLine> _equipment;
        public SoldierAcquisitionRequest(SoldierId soldierId,UnitGroupId unitGroupId,TroopDefinitionId troopDefinitionId,RecruitmentRecordId recruitmentRecordId,CityId issueCityId,IEnumerable<EquipmentIssueLine> equipment)
        {if(!soldierId.IsValid||!unitGroupId.IsValid||!troopDefinitionId.IsValid||!recruitmentRecordId.IsValid||!issueCityId.IsValid)throw new ArgumentException("Soldier acquisition references are invalid.");_equipment=(equipment??throw new ArgumentNullException(nameof(equipment))).ToList();if(_equipment.Any(x=>x==null)||_equipment.Select(x=>x.InstanceId).Distinct().Count()!=_equipment.Count)throw new InvalidOperationException("Equipment issue IDs must be unique.");SoldierId=soldierId;UnitGroupId=unitGroupId;TroopDefinitionId=troopDefinitionId;RecruitmentRecordId=recruitmentRecordId;IssueCityId=issueCityId;}
        public SoldierId SoldierId{get;}public UnitGroupId UnitGroupId{get;}public TroopDefinitionId TroopDefinitionId{get;}public RecruitmentRecordId RecruitmentRecordId{get;}public CityId IssueCityId{get;}public IReadOnlyList<EquipmentIssueLine> Equipment=>_equipment;
    }

    public sealed class SoldierEquipmentService
    {
        private readonly CampaignRuntimeState _campaign;
        public SoldierEquipmentService(CampaignRuntimeState campaign){_campaign=campaign??throw new ArgumentNullException(nameof(campaign));}

        public SoldierInstance AcquireFromCity(SoldierAcquisitionRequest request,WorldTimestamp acquiredAt)
        {
            if(request==null)throw new ArgumentNullException(nameof(request));if(_campaign.Soldiers.Soldiers.Contains(request.SoldierId))throw new InvalidOperationException("Duplicate SoldierId.");var unit=FindUnit(request.UnitGroupId);var troop=_campaign.Soldiers.Definitions.GetRequired(request.TroopDefinitionId);if(!StringComparer.Ordinal.Equals(unit.TroopDefinitionId,troop.Id.Value))throw new InvalidOperationException("Soldier troop definition conflicts with Unit Group.");if(_campaign.Soldiers.Soldiers.CountFor(unit.Id)>=unit.Headcount)throw new InvalidOperationException("Instantiated Soldier roster cannot exceed Unit Group headcount.");var record=FindRecruitmentRecord(request.RecruitmentRecordId);if(!record.UnitGroupId.Equals(unit.Id)||!record.SourceId.Equals(unit.SourceId))throw new InvalidOperationException("Soldier recruitment provenance conflicts with Unit Group.");var source=_campaign.Military.RecruitmentSources.GetRequired(record.SourceId);if(source.Type==RecruitmentType.TimarService||source.Type==RecruitmentType.Mercenary){if(string.IsNullOrWhiteSpace(source.ObligationOrContractId))throw new InvalidOperationException("Recruitment obligation or contract is missing.");}var market=_campaign.Economy.GetRequiredMarket(request.IssueCityId);_campaign.Cities.GetRequired(request.IssueCityId);
            var loadout=BuildAndValidateLoadout(request.Equipment,troop,out var goods);foreach(var line in request.Equipment)if(_campaign.Soldiers.Equipment.Contains(line.InstanceId))throw new InvalidOperationException("Duplicate EquipmentInstanceId.");foreach(var pair in goods)if(market.Stock.QuantityOf(pair.Key)<pair.Value)throw new InvalidOperationException("Insufficient City equipment stock.");
            foreach(var pair in goods)market.Stock.Remove(pair.Key,pair.Value);foreach(var line in request.Equipment){var good=EconomicGood(line.Definition);_campaign.Soldiers.Equipment.Add(new EquipmentInstance(line.InstanceId,line.Definition,EquipmentOwnerRef.Soldier(request.SoldierId),EquipmentAcquisitionProvenance.CityMarket(request.IssueCityId,good,acquiredAt),line.QualityCode));}var soldier=new SoldierInstance(request.SoldierId,unit.Id,troop.Id,new SoldierRecruitmentProvenance(record.SourceId,record.Id),loadout,troop.DefaultCombatRoleId);_campaign.Soldiers.Soldiers.Add(soldier);return soldier;
        }

        public SoldierLoadout ReadPersistentLoadout(SoldierId soldierId)=>_campaign.Soldiers.Soldiers.GetRequired(soldierId).Loadout;

        public void ReplaceLoadout(SoldierId soldierId,SoldierLoadout replacement)
        {var soldier=_campaign.Soldiers.Soldiers.GetRequired(soldierId);ValidateLoadout(soldierId,replacement,_campaign.Soldiers.Definitions.GetRequired(soldier.TroopDefinitionId));soldier.ReplaceLoadout(replacement);}

        private SoldierLoadout BuildAndValidateLoadout(IReadOnlyList<EquipmentIssueLine> lines,TroopDefinition troop,out SortedDictionary<TradeGoodId,long> goods)
        {var weapons=new List<WeaponSlotAssignment>();var armor=new List<ArmorSlotAssignment>();EquipmentInstanceId? shield=null;EquipmentInstanceId? mount=null;goods=new SortedDictionary<TradeGoodId,long>();foreach(var line in lines){if(!Enum.IsDefined(typeof(EquipmentPlacementKind),line.Placement))throw new InvalidOperationException("Equipment placement is invalid.");var good=EconomicGood(line.Definition);goods[good]=checked((goods.TryGetValue(good,out var n)?n:0)+1);switch(line.Placement){case EquipmentPlacementKind.Weapon:weapons.Add(new WeaponSlotAssignment(line.WeaponSlot,line.InstanceId));ValidateWeaponPlacement(line);break;case EquipmentPlacementKind.Armor:armor.Add(new ArmorSlotAssignment(line.ArmorSlot,line.InstanceId));ValidateArmorPlacement(line);break;case EquipmentPlacementKind.Shield:if(shield.HasValue||line.Definition.Kind!=EquipmentKind.Shield)throw new InvalidOperationException("Shield placement is incompatible.");_campaign.Soldiers.Definitions.GetRequired(ShieldDefinitionId.Create(line.Definition.Id));shield=line.InstanceId;break;case EquipmentPlacementKind.Mount:if(mount.HasValue||line.Definition.Kind!=EquipmentKind.Mount)throw new InvalidOperationException("Mount placement is incompatible.");_campaign.Soldiers.Definitions.GetRequired(MountDefinitionId.Create(line.Definition.Id));mount=line.InstanceId;break;default:throw new InvalidOperationException("Equipment placement is invalid.");}}var result=new SoldierLoadout(weapons,armor,shield,mount);ValidatePlannedLoadout(result,lines,troop);return result;}
        private void ValidateWeaponPlacement(EquipmentIssueLine line){if(line.Definition.Kind==EquipmentKind.Weapon){var d=_campaign.Soldiers.Definitions.GetRequired(WeaponDefinitionId.Create(line.Definition.Id));if(!d.AllowedSlots.Contains(line.WeaponSlot))throw new InvalidOperationException("Weapon is incompatible with slot.");}else if(line.Definition.Kind==EquipmentKind.Auxiliary){var d=_campaign.Soldiers.Definitions.GetRequired(AuxiliaryEquipmentDefinitionId.Create(line.Definition.Id));if((d.Kind==AuxiliaryEquipmentKind.Ammunition&&line.WeaponSlot!=WeaponSlot.Ammo)||(d.Kind==AuxiliaryEquipmentKind.Special&&line.WeaponSlot!=WeaponSlot.Special))throw new InvalidOperationException("Auxiliary equipment is incompatible with slot.");}else throw new InvalidOperationException("Non-weapon equipment cannot occupy a weapon slot.");}
        private void ValidateArmorPlacement(EquipmentIssueLine line){if(line.Definition.Kind!=EquipmentKind.Armor)throw new InvalidOperationException("Non-armor equipment cannot occupy an armor slot.");var d=_campaign.Soldiers.Definitions.GetRequired(ArmorDefinitionId.Create(line.Definition.Id));if(d.Slot!=line.ArmorSlot)throw new InvalidOperationException("Armor is incompatible with slot.");}
        private void ValidatePlannedLoadout(SoldierLoadout loadout,IReadOnlyList<EquipmentIssueLine> lines,TroopDefinition troop){var mounted=loadout.Mount.HasValue;if(troop.MountContext==MountContext.MountedOnly&&!mounted||troop.MountContext==MountContext.InfantryOnly&&mounted)throw new InvalidOperationException("Troop and mount are incompatible.");if(loadout.ArmorAt(ArmorSlot.MountArmor).HasValue&&!mounted)throw new InvalidOperationException("Mount armor requires a mount.");if(!troop.AllowsArmor&&lines.Any(x=>x.Placement==EquipmentPlacementKind.Armor))throw new InvalidOperationException("Troop definition does not allow armor.");if(!troop.AllowsShield&&loadout.Shield.HasValue)throw new InvalidOperationException("Troop definition does not allow a shield.");foreach(var line in lines)if(line.Definition.Kind==EquipmentKind.Weapon){var d=_campaign.Soldiers.Definitions.GetRequired(WeaponDefinitionId.Create(line.Definition.Id));if(troop.AllowedWeaponFamilies.Count>0&&!troop.AllowedWeaponFamilies.Contains(d.Family))throw new InvalidOperationException("Weapon family is incompatible with troop definition.");if(d.MountContext==MountContext.MountedOnly&&!mounted||d.MountContext==MountContext.InfantryOnly&&mounted)throw new InvalidOperationException("Weapon and mount context are incompatible.");if(d.IsRanged){var ammo=lines.FirstOrDefault(x=>x.WeaponSlot==WeaponSlot.Ammo&&x.Definition.Kind==EquipmentKind.Auxiliary);if(ammo==null||!Nullable.Equals(_campaign.Soldiers.Definitions.GetRequired(AuxiliaryEquipmentDefinitionId.Create(ammo.Definition.Id)).AmmoFamilyId,d.AmmoFamilyId))throw new InvalidOperationException("Ranged weapon ammunition is incompatible.");}}}
        private void ValidateLoadout(SoldierId soldierId,SoldierLoadout loadout,TroopDefinition troop){if(loadout==null)throw new ArgumentNullException(nameof(loadout));var lines=new List<EquipmentIssueLine>();foreach(var x in loadout.OrderedWeapons){var e=_campaign.Soldiers.Equipment.GetRequired(x.EquipmentId);lines.Add(ToExistingLine(e,x.Slot));}foreach(var x in loadout.OrderedArmor){var e=_campaign.Soldiers.Equipment.GetRequired(x.EquipmentId);lines.Add(EquipmentIssueLine.Armor(e.Id,ArmorDefinitionId.Create(e.Definition.Id),x.Slot,e.QualityCode));}if(loadout.Shield.HasValue){var e=_campaign.Soldiers.Equipment.GetRequired(loadout.Shield.Value);lines.Add(EquipmentIssueLine.Shield(e.Id,ShieldDefinitionId.Create(e.Definition.Id),e.QualityCode));}if(loadout.Mount.HasValue){var e=_campaign.Soldiers.Equipment.GetRequired(loadout.Mount.Value);lines.Add(EquipmentIssueLine.Mount(e.Id,MountDefinitionId.Create(e.Definition.Id),e.QualityCode));}if(lines.Any(x=>!_campaign.Soldiers.Equipment.GetRequired(x.InstanceId).Owner.Equals(EquipmentOwnerRef.Soldier(soldierId))))throw new InvalidOperationException("Equipment owner and Soldier conflict.");ValidatePlannedLoadout(loadout,lines,troop);}
        private static EquipmentIssueLine ToExistingLine(EquipmentInstance e,WeaponSlot slot)=>e.Definition.Kind==EquipmentKind.Weapon?EquipmentIssueLine.Weapon(e.Id,WeaponDefinitionId.Create(e.Definition.Id),slot,e.QualityCode):EquipmentIssueLine.Auxiliary(e.Id,AuxiliaryEquipmentDefinitionId.Create(e.Definition.Id),slot,e.QualityCode);
        private TradeGoodId EconomicGood(EquipmentDefinitionRef definition){TradeGoodId good;switch(definition.Kind){case EquipmentKind.Weapon:good=_campaign.Soldiers.Definitions.GetRequired(WeaponDefinitionId.Create(definition.Id)).EconomicGoodId;break;case EquipmentKind.Armor:good=_campaign.Soldiers.Definitions.GetRequired(ArmorDefinitionId.Create(definition.Id)).EconomicGoodId;break;case EquipmentKind.Shield:good=_campaign.Soldiers.Definitions.GetRequired(ShieldDefinitionId.Create(definition.Id)).EconomicGoodId;break;case EquipmentKind.Mount:good=_campaign.Soldiers.Definitions.GetRequired(MountDefinitionId.Create(definition.Id)).EconomicGoodId;break;case EquipmentKind.Auxiliary:good=_campaign.Soldiers.Definitions.GetRequired(AuxiliaryEquipmentDefinitionId.Create(definition.Id)).EconomicGoodId;break;default:throw new InvalidOperationException("Equipment definition kind is invalid.");}_campaign.Economy.Goods.GetRequired(good);return good;}
        private UnitGroupState FindUnit(UnitGroupId id){foreach(var army in _campaign.Military.Armies.OrderedArmies)foreach(var unit in army.OrderedUnits)if(unit.Id.Equals(id))return unit;throw new KeyNotFoundException("Unit Group was not found.");}
        private RecruitmentRecord FindRecruitmentRecord(RecruitmentRecordId id){foreach(var x in _campaign.Military.RecruitmentRecords.OrderedRecords)if(x.Id.Equals(id))return x;throw new KeyNotFoundException("Recruitment record was not found.");}
    }

    public sealed class SoldierCombatSnapshot
    {public SoldierCombatSnapshot(SoldierInstance soldier){if(soldier==null)throw new ArgumentNullException(nameof(soldier));SoldierId=soldier.Id;UnitGroupId=soldier.UnitGroupId;TroopDefinitionId=soldier.TroopDefinitionId;Loadout=soldier.Loadout;}public SoldierId SoldierId{get;}public UnitGroupId UnitGroupId{get;}public TroopDefinitionId TroopDefinitionId{get;}public SoldierLoadout Loadout{get;}}
}
